throneteki/throneteki

server/game/cards/locations.js

Introduces a new class, `FactionCostReduction`, that reduces the cost of the next marshaled card for the faction specified in the constructor. `FactionCostReduction` replaces `DragonstonePort`, `BloodOrangeGrove` and `HeartTreeGrove` which were all identical minus the faction code used. 
It also introduces a function `factionCostReductionLocation` which takes a faction code and returns a card implementation that uses `FactionCostReduction` for that faction code. This function is now used to generate both the replaced reducer locations as well as implement the remaining reducer locations.

Implement faction-based cost reduction locations

---

server/game/game.js

Some small things I noticed while reading through the code, now since my node.js is currently quite rusty these fixes might ruin intended behavior and in that case feel free to ignore this pull request. But I'd thought it good to point them out. :)
Power comparison fix: All winner.getTotalPower() check for "> 15", wouldn't this lead to a player needing 16 power to win?
Power claim fix: When applying power claim to a losing player the code currently only checks to see if that player has any power (ie. loser.power > 0) and then subtracts the claim from that players power and adds it to the winner. This could lead to a player having negative power/a player getting power that didn't exist. An example would be that the losing player has 1 power and has just lost a power challenge with claim 2. …

Small power comparison fixes and power claim fix

---

client/GameBoard.jsx
server/game/player.js

Updated plot decks to now be able to click on Active Plot to view either player's used plots. Also fixed logic where current plot was being added to used pile too soon (creates an invalid games state). Plots should only be added (as per rules) to used pile when a new plot is revealed. As well this fixes the logic when users get to the 7th plot where used pile should recycle into the unused pile (making used pile 0 again).

plot deck/phase updates

---

server/game/cards/characters.js
server/game/cards/reducer.js

Character-based faction cost reducers (such as Dragonstone Faithful for
Baratheon) only reduces the cost of the next character. This is in
contrast with the location-based reducers, which reduces the cost of any
type of card for the faction.

Enforce card restriction for character reducers

---

server/game/cards/plots.js
server/game/game.js
server/game/player.js
server/index.js
test/server/plots/02039-pentoshi.spec.js

Adding the ability for first player to resolve plot effect (even if there is only 1) in the order of their choosing. As well adding a formal draw phase and emitter for that phase's beginning due to some things that may take effect during draw phase (such as Time of Plenty). Note that now there is also a distinction between a static ability that is turned on as soon as a plot is flipped (plotRevealed emission event) and the "When Revealed" ability (whenRevealed emission event). This is to avoid conflicts between cards (for example Blood of the Dragon with a 5 strength character that has Crown of Gold and Confiscation).

Plot phase enhancements

---

server/game/cards/plots.js
server/game/game.js
test/server/game.power.spec.js

Previously power was being modified directly in multiple places and the win condition wasn't being checked in all of them. Additionally, the win condition was duplicated in multiple spots. This should make things a bit more consistent.
In the future this could also emit a 'powerGained' event, which may be needed for cards like [Edmure Tully](https://thronesdb.com/card/04041) and [Eddard Stark (WotN)](https://thronesdb.com/card/03003).

Always check win condition when power is gained.

---

server/game/cards/characters.js
server/game/cards/locations.js
server/game/player.js
test/server/player.plotstats.spec.js

Introduces all of the simple reserve modifying cards.
I also changed the test for `Player.getTotalIncome` to be a general test for `Player.getTotalPlotStat`. It seemed needless to introduce a separate test for `getTotalReserve` (or `getTotalInitiative` for tha matter) when they all use the same method.

Introduce reserve modifier cards

---

server/game/cards/plots.js
server/game/player.js
test/server/player/player.moveFromDrawDeckToHand.spec.js
test/server/player/player.searchDrawDeck.spec.js

Saw some minor repetition that would get worse as more cards are implemented. Minor refactor that introduces methods to:
* Search the top or bottom X cards of the draw deck - [Summons](https://thronesdb.com/card/01022), [Building Orders](https://thronesdb.com/card/01006), [I Never Bet Against My Family](https://thronesdb.com/card/02050), etc
* Search the entire deck for a certain type of card - [Wolf Dreams](https://thronesdb.com/card/02042), [Ser Hobber Redwyne](https://thronesdb.com/card/02043), etc
* Move a specific card from the draw deck to the player's hand.

Draw deck improvements

---

client/GameBoard.jsx
client/GameComponents/Messages.jsx
server/game/cards/locations.js
server/game/cards/plots.js
server/game/cards/reducer.js
server/game/game.js
server/index.js
test/server/game/game.chat.spec.js
test/server/game/game.formatMessage.spec.js

Reworks `Game.addMessage` to work as a general-purpose formatter when constructing messages for chat. It may now take a list of optional arguments that are interpolated into the message. 
```
// server side
this.addMessage('{0} discards {1}', player.name, card);
// what appears client side
Player 1 discard Tyrion Lannister
```
* In general, the usage of addMessage going forward should favor argument replacement over concating strings together. This provides consistency, allows other rich data to be interpolated into the message (player data, challenge type + icon, etc), and allows a way forward in the future should translation ever be desired.
* Arguments can be either strings or JSON data. Currently no enforcement of what type of JSON data, is left up to the client to interpret. 
* On …

Implement card preview in chat

---

server/game/drawcard.js
server/game/game.js
server/game/player.js
test/server/card/drawcard.usestealthtobypass.spec.js

* A character with stealth may no longer be chosen as a target for stealth. 
* Removes the requirement that the targeted character has the icon for the current challenge. Per the rules, the only requirement is that it be a character the opposing player controls.
* This is useful for cards that have an ability triggered when they bypass a character by stealth (such as [Wolves of the North](https://thronesdb.com/card/03006)).
* Resets all stealth targeting / bypass effect at the start of each challenge.
Fixes #54.

Update stealth targeting requirements

---

server/game/basecard.js
server/game/drawcard.js
test/server/card/drawcard.canAttach.spec.js
test/server/card/drawcard.hasKeyword.spec.js

* Parses out a list of keywords when a card is constructed based on the first line of the card text. Only exact matches are considered.
* No longer considers 'no attachment' to be a keyword. Instead, it's tracked separately and allows characters to exclude attachments that don't match a certain trait - [most notably weapon](https://thronesdb.com/find?q=x%3A%22no+attachments+except%22&view=card&sort=name&page=1).
* It provides a place that 'ambush' can be parsed in the future.
This PR makes me sad.
Fixes #76 .

Fix keyword related issues

---

server/game/game.js
test/server/game/getplayers.spec.js

Previously, if Player.firstPlayer was explicitly set to false instead of
being undefined, the player order would list the first player as being
last.

Fix first player ordering

---

server/game/game.js
server/game/gamesteps/playerorderprompt.js
server/game/gamesteps/taxation/discardtoreserveprompt.js
server/game/gamesteps/taxation/endroundprompt.js
server/game/gamesteps/taxationphase.js
server/game/player.js
server/index.js
test/server/game/getplayers.spec.js
test/server/gamesteps/playerorderprompt.spec.js
test/server/gamesteps/taxation/discardtoreserveprompt.spec.js
test/server/plots/02039-pentoshi.spec.js

You should merge #83 first.
* Introduces `PlayerOrderPrompt` class to implement prompts that are given to each player in first-player order (contrast w/ `AllPlayerPrompt` which prompts simultaneously)
* Converts the taxation phase into steps and prompts.
* Implements a prompt when players need to discard down to their reserve value. If players already are below reserve they're skipped.
Fixes #68.

Convert taxation phase to new game flow.

---

server/game/game.js
server/game/gamesteps/attachmentprompt.js
server/game/gamesteps/challenge/fulfillmilitaryclaim.js
server/game/gamesteps/killcharacterprompt.js
server/game/gamesteps/uiprompt.js
server/game/player.js
server/index.js
test/server/gamesteps/killcharacterprompt.spec.js

* Slightly reworks UiPrompt to save and restore the original prompt. This should centralize such logic and make it easier to remove once the entire game is converted.
* Implements a reusable kill character prompt. The prompted player must choose a character that matches the passed condition, or cancel the prompt. Should make it easier to implement cards that have "[choose and kill](https://thronesdb.com/find?q=x%3A%22choose+and+kill%22&sort=name&view=card)" or similar kill abilities.
* Implements military claim using the kill character prompt.

Implement a kill character prompt

---

server/game/gamepipeline.js
server/game/gamesteps/phase.js
test/server/gamepipeline/cancelStep.spec.js
test/server/gamepipeline/continue.spec.js
test/server/gamepipeline/queuestep.spec.js

* Allows a factory method to be passed into the pipeline instead of just a game step.
* When queuing steps, if the current step itself is a pipeline, then pass it to the current step instead of adding it to the top-level queue. This fixes a bug where a step queued by the second-to-last step of a phase was being executed after the last step of the phase instead of before.

Gamepipeline improvements

---

client/GameBoard.jsx
server/game/game.js
server/game/gamesteps/plot/firstplayerprompt.js
server/game/gamesteps/plot/plotrevealprompt.js
server/game/gamesteps/plot/revealplotorderprompt.js
server/game/gamesteps/plot/selectplotprompt.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/setupphase.js
server/game/gamesteps/taxationphase.js
server/game/player.js
server/index.js
test/server/cards/plots/02/02039-pentoshi.spec.js

* Converts the 'choose plot' and 'choose first player' prompts into the new game flow.
* Ensures that at the end of the taxation phase the plot phase is triggered again.
* Continues to use the old flow for plot resolution (converted in separate PR) to make it safer to merge this.

Convert plot phase up until plot resolution

---

server/game/game.js

The pipeline click handler added to Game.playCard was returning if it
couldn't find the card within the player's hand. This method is also
called when a card is dragged into the play area. By returning early,
cards dragged from the dead and discard piles would disappear instead of
be put into play.

Fix dragging cards from dead/discard to play.

---

server/game/drawcard.js
server/game/gamesteps/setupphase.js
server/game/player.js
test/server/player/find.spec.js
test/server/player/getduplicateinplay.spec.js
test/server/player/playcard.spec.js
test/server/player/removeattachment.spec.js

* Marshaling a unique attachment that is already in play is treated like marshaling any other duplicate.
* Duplicate attachments are automatically placed rather than asking the player to choose where to attach it.
* Discarding the attachment via an ability (e.g. Confiscation) will discard from duplicates first, if any.
* Manually dragging an attachment with duplicates to the discard pile will not lose the duplicates.
* Minor change to the setup phase - cards are flipped and dupes consolidated prior to choosing attachment placement (per rules about setup phase).
* Minor cleanup of the find card methods on player.
Currently it isn't possible to tell in the UI whether an attachment has duplicates. I didn't want to interfere with your ongoing refactor of the client card rendering.
Fixes #63

Allow dupes for unique attachments

---

server/game/game.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/challenge/fulfillmilitaryclaim.js
server/game/player.js
server/index.js

* Converts selecting defenders to a select card prompt.
* Moves determining winner, awarding unopposed, applying claim and applying keywords into the challenge flow.
I moved keywords after claim per the rules, which may introduce a bug based on your previous "needs reworking" comment, but I couldn't immediately identify why it was done in that order.

Convert defenders + DUCK to new flow

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/challengephase.js
server/game/player.js
test/server/challenge/determinewinner.spec.js
test/server/challenge/removefromchallenge.spec.js

* Moves most of the challenge logic to the Challenge class.
* Sets the challenge object as currentChallenge on Game (note: this is being used by Superior Claim on master but isn't implemented there)
* Removes Player.currentChallenge
* Works toward removing Player.challengeStrength and Player.cardsInChallenge (not quite there yet)
* Removes characters that are discarded or killed from the current challenge (needed to make challenge action windows useful).

Challenge refactor

---

client/GameComponents/Card.jsx

The parent card should just pass along the external handler it was given rather than try to call it's own internal handler.
Fixes #112.

Fix click handler for attachments.

---

server/game/cards/characters/01/rattleshirtsraiders.js
server/game/cards/plots/01/powerbehindthethrone.js
server/game/game.js
server/game/gamesteps/uiprompt.js
server/index.js
test/server/game/chat.spec.js

* Converts the remaining usages of the deprecated select card prompt to the new prompt.
* Removes the deprecated methods and the associated callback mechanism.
* Removes saving and restoring of old prompts (should no longer be needed now that everything uses the pipeline)
* Slight fix to Rattleshirt's ability.
Fixes #103.

Remove deprecated select card prompt

---

server/game/gamesteps/actionwindow.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/playerorderprompt.js
test/server/gamesteps/actionwindow.spec.js

* Prompts players in first player order for actions.
* If a player clicks a card (best approximation currently for using an ability or playing a card), then any players that have passed will be prompted again.
* The window ends once both players have passed.
This is implemented according to the rules text as much as possible. Let me know if it's too much clicking for you. It could also be implemented as a simultaneous prompt instead, where if any player plays something then the other player has to reconfirm they are done. That may be better for game flow but is less in accordance with the rules.

Add action windows in challenges phase

---

server/game/cards/reducer.js

Reducer wasn't called its parent version of leavesPlay, so power,
strength and kneeling were not being reset on reducer cards.

Fix Kingsroad kneel in discard pile.

---

server/game/cards/plots/01/wildfireassault.js
server/game/player.js

Previously, Wildfire Assault just moved the non-selected characters into
the player's deadpile. However, doing so did not fire the
onCharacterKilled event, which can trigger reactions (e.g. Catelyn Stark
gaining power).

Wildfire Assault should explicitly kill.

---

server/game/game.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js
test/server/gamesteps/selectcardprompt.spec.js

The cause of the crash was when people were in the middle of selecting either attackers or defenders, clicked to select their characters, then decided to set the strength of one of those characters. Clicking on the character in the set strength prompt would unselect it (since it was already selected in the previous prompt) and fire the select handler with no card.
The select card prompt now clears all previous selections when it activates. As a nicety, it restores the old selections once complete.

Fix strength prompt crash

---

server/game/player.js
test/server/player/setupdone.spec.js

Per the rules, cards placed in set up do not trigger abilities or
reactions that they normally trigger when marshalled or entering play.

Cards placed in setup do not trigger 'enters play'

---

less/site.less
server/game/cards/agendas/fealty.js
server/game/cards/agendas/therainsofcastamere.js
server/game/game.js
server/game/gamesteps/plot/resolveplots.js
server/game/player.js
test/server/agendas/05045 - therainsofcastamere.spec.js
test/server/gamesteps/plot/resolveplots.spec.js

* Removes schemes from the normal plot deck when the player has Rains of Castamere agenda.
* Prompts to trigger a scheme plot when winning an intrigue challenge by 5 or more.
* Move standing of faction card into the stand phase instead of handled case-by-case as it was with Fealty.
There is probably some weirdness around reserve if the opponent has a Kings of Summer/Winter agenda. They're persistent effects but currently only modify reserve when the plot phase starts. It should be whenever a plot enters play, but that will require serious reworking of those agendas.
Completes #32.
_"A coat of gold, a coat of red, a lion still has claws"_

Implement Rains of Castamere

---

client/GameComponents/Card.jsx
client/GameComponents/PlayerRow.jsx
less/site.less

* Previously when a card had multiple attachments, the attachments could overlap with a location card below it. Now the row grows as more attachments are added.
* Previously card menus would pop up underneath cards next to then. Now the menu properly appears above cards and other UI elements.
* Removes a few of the special case CSS classes such as `.horizontal-card` and `.plot-card` in favor of using `.card` and adding modifiers (`.horizontal`, `.vertical`)
* Pulls out z-indexes into constants so that it's easier to see what the hierarchy is (not full proof due to how stacking contexts work but should make things more understandable)
* Removes manual style positioning of attachments and facedown duplicates in favor of CSS classes. Currently the classes are limited to 5 attachments on the …

Fix attachment overlap and menus under cards.

---

server/game/cards/attachments/04/redgodsblessing.js
server/game/cards/characters/01/direwolfpup.js
server/game/cards/locations/01/greatkraken.js
server/game/cards/locations/01/thewall.js
server/game/cards/locations/03/winterfell.js
server/game/cards/plots/01/marchingorders.js
server/game/cards/plots/01/reinforcement.js
server/game/cards/plots/02/heretoserve.js
server/game/cards/plots/03/asongofsummer.js
server/game/cards/plots/03/atimeforwolves.js
server/game/game.js
server/game/player.js
test/server/player/canplaycard.spec.js
test/server/player/playcard.spec.js

Slight improvements to playCard and related events.
* Passes a card object directly into Player.playCard
* Gets rid of sourceList on Player.playCard
* Sends full card in the onCardPlayed event and removes all of the card lookups in those implementations.
* Removes (for now) checking with opponent cards on whether or not the player can play a card. There currently aren't any opponent cards that restrict what you can marshal / play.
Should result in no functionality changes, just slight refactoring.

Pass cards to play-related methods and events instead of IDs

---

client/GameBoard.jsx
client/GameComponents/Card.jsx
server/game/cards/plots/01/powerbehindthethrone.js
server/game/game.js

* Allows the card menu to be triggered for the active plot.
* Automatically close menus once you've clicked a menu item.
* Fix bug with Power Behind the Throne that allowed it to be used multiple times.

Handle plot menu for current player

---

client/GameComponents/Card.jsx
less/cards.less

* Changes the orientation of the token list to be horizontal for horizontal cards.
* When there are 4 or more tokens, it bunches them up as best as possible.
* Moved duplicated styling into the `.counter` class.

Fix token styling on horizontal cards + more than 3 tokens.

---

server/game/drawcard.js
test/server/card/drawcard.getsummary.spec.js

Previously, characters with 0 base strength (e.g. Lancel Lannister)
would not display their strength if it were increased via abilities,
attachments or using the /strength command. This was due to the strength
not being sent if the base strength was a falsy value. Now it explicitly
sends it unless the base strength is explicitly null, which is the case
on non-character cards.

Send strength stats for 0 strength characters.

---

server/game/game.js
server/index.js

Previously, `pipeline.continue()` was being called at the end of each
command handler, but a few pathways weren't properly calling it. To make
sure the pipeline is continued consistently, the call is now made in the
server level when a game command comes in.

Ensure pipeline is executed after each command.

---

server/game/cards/characters/02/bronn.js
server/game/cards/locations/01/thewall.js

Both the Wall and Bronn were missing the event param in their event handlers, meaning neither were working as intended. Also added an in-play check for the Wall to ensure it only kneels when in the play area.
Fixes #158

Fix the Wall + Bronn

---

client/GameBoard.jsx
client/GameComponents/Card.jsx
client/GameComponents/CardCollection.jsx
client/GameComponents/PlayerRow.jsx
less/cards.less
less/gameboard.less
server/game/player.js

Faction card should now kneeled centered in its card pile rather than aligned with the top left of the pile, and no longer overlaps with the agenda card. Also makes card collection styling classes more consistent with the new card classes.

Faction kneeling / card collection improvements.

---

server/game/cards/agendas/thelordofthecrossing.js
server/game/cards/attachments/01/ice.js
server/game/cards/characters/01/rattleshirtsraiders.js
server/game/cards/characters/01/serjaimelannister.js
server/game/cards/characters/01/wildlinghorde.js
server/game/cards/characters/03/eddardstark.js
server/game/cards/characters/05/cerseilannister.js
server/game/cards/locations/01/theredkeep.js
server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/cards/characters/01/01087 - serjaimelannister.spec.js
test/server/cards/characters/02/02070 - redcloaks.spec.js

* Removes `Player.cardsInChallenge` and updates remaining usages to reference the challenge object.
* Removes `Player.challengeStrength` which was not being used when determining winner but was being used for UI and modified for cards that don't participate but do contribute strength (The Red Keep).

Remove duplicated responsibility from Player to Challenge

---

server/game/game.js
server/game/gamesteps/setupphase.js
server/index.js

Previously the server would accept 'game' commands as long as the game
exists. Now it explicitly prevents these commands from being processed
unless the game has started. Additionally, the pipeline is now created
in the constructor instead of waiting until when the game starts.

Guard against game commands when not started.

---

server/game/player.js
test/server/player/flipplotfaceup.spec.js

Player.plotDeck is already an underscore wrapped array, so the use of
each was causing a crash.
Resolves https://sentry.io/throneteki/throneteki/issues/198219459/

Fix plot replenishing loop

---

server/game/player.js
test/server/player/playcard.spec.js

Previously, if a card with the Ambush keyword was played normally during
the setup phase, it would play it as an ambushed card at its non-ambush
price, including a message saying that they ambushed it. This would
reveal information about the player's setup to the opponent before the
cards were revealed.

Only play cards as ambush during challenge phase

---

server/game/player.js

Previously, cards were listening to their appropriate events at all
times. Commit a1e39969e0d90f93968978f72211e1758fd9a462 changed this so
that they would only listen to events while in play. Due to the order
things were done in the Player.playCard method, this introduced a bug
where cards that had reactions when they entered play (such as Arya
Stark) would not fire correctly. This changes the order to fire the
onCardEntersPlay event after the event listeners have been turned on.

Fix cards that react to themselves entering play

---

server/game/basecard.js
server/game/cardaction.js
server/game/cards/agendas/fealty.js
server/game/cards/attachments/01/sealofthehand.js
server/game/cards/characters/01/wildlinghorde.js
server/game/cards/characters/02/bronn.js
server/game/cards/characters/02/redcloaks.js
server/game/cards/characters/03/jonsnow.js
server/game/cards/characters/04/shae.js
server/game/cards/plots/01/powerbehindthethrone.js
server/game/gamesteps/taxationphase.js
test/server/card/cardaction.spec.js
test/server/cards/characters/02/02070 - redcloaks.spec.js

Wraps card actions in a class that manages the following:
* Ensures the action can be executed in the current phase.
* Ensures the action is being executed by the appropriate player (the card controller by default, any player if the anyPlayer flag is set)
* Ensures the card is not blank before executing the action
* Allows an optional limit that is enforced. Limits can be per 'challenge', per 'phase' or per 'round'. (the format of this option will likely change once a similar class is introduced for reactions)

Introduce class to manage card actions

---

server/game/cards/characters/01/edricdayne.js
server/game/cards/characters/01/selysebaratheon.js
server/game/cards/characters/01/serjaimelannister.js
server/game/cards/characters/01/wildlinghorde.js
server/game/cards/characters/02/bronn.js
server/game/cards/characters/02/nymeriasand.js
server/game/cards/characters/02/redcloaks.js
server/game/cards/characters/02/wildlingscout.js
server/game/cards/characters/03/oldnan.js
server/game/cards/events/01/tearsoflys.js
server/game/cards/locations/01/ironfleetscout.js
server/game/cards/locations/04/pyke.js
test/server/cards/characters/01/01087 - serjaimelannister.spec.js
test/server/cards/characters/02/02070 - redcloaks.spec.js

Previously, cards listened to end of phase and end of challenge events
to remove any lasting effects they may have applied. However, since
cards only listen to events while in play now, cards that left play
before the end of challenge / phase would not properly clean up after
themselves.
This change attaches a one-time event listener each time a lasting
effect is applied. Because the event is registered through game directly
and not the underlying event registrar, it won't be unregistered should
the card leave play prematurely.

Use once events to clean up lasting effects

---

server/game/player.js
test/server/player/drop.spec.js

Some cards need to react to being killed, sacrificed or discarded.
Because event listeners are removed when a card leaves play, these
events must be fired prior to the card being moved to an out-of-play
game location.
This change ensures that the onCharacterKilled and onSacrificed events
are raised prior to the onCardLeftPlay event.

Allow event self handlers when leaving play

---

server/game/cards/characters/01/drownedmen.js

Previously the Drowned Men was recalculating its strength as cards
entered and left play. This meant that if its strength should be
modified via another card, such as Priest of the Drowned God, that
modification would be lost when strength when Drowned Men strength was
recalculated.
Fixes #190

Modify Drowned Men strength instead of recalculate

---

test/server/cards/locations/01/01137 - thewall.spec.js

Adds a test for the bug fixed in commit
43ec92f2d33ad63744781996b8475b4e26fcafb4 that caused cards like the Wall
to apply their effects twice if a dupe of the card was played during the
setup phase.

Integration test for the Wall dupe setup bug.

---

server/game/abilitydsl.js
server/game/basecard.js
server/game/cards/attachments/01/drogosarakh.js
server/game/cards/attachments/01/littlebird.js
server/game/cards/attachments/01/milkofthepoppy.js
server/game/cards/attachments/01/noblelineage.js
server/game/cards/attachments/01/syriostraining.js
server/game/cards/attachments/01/widowswail.js
server/game/cards/attachments/02/knighted.js
server/game/cards/attachments/02/practiceblade.js
server/game/cards/characters/01/direwolfpup.js
server/game/cards/characters/01/drogon.js
server/game/cards/characters/01/drownedmen.js
server/game/cards/characters/01/robertbaratheon.js
server/game/cards/characters/01/unsullied.js
server/game/cards/characters/01/viserion.js
server/game/cards/characters/01/wardensofthereach.js
server/game/cards/characters/02/priestofthedrownedgod.js
server/game/cards/characters/03/sansastark.js
server/game/cards/locations/01/thewall.js
server/game/cards/locations/03/winterfell.js
server/game/drawcard.js
server/game/effect.js
server/game/effectengine.js
server/game/effects.js
server/game/game.js
test/server/effect.spec.js
test/server/effectengine.spec.js

* Adds an Effect class that manages applying and unapplying effects to targeted cards.
* Adds an EffectEngine class that manages lifecycle for effects (adding targets as they come into play, removing them as they leave play, removing effects as their source leave play, etc)
* Adds BaseCard.persistentEffect for defining any given effect that continues while a card is in play, and BaseCard.whileAttached which reduces some of the boilerplate for attachment effects.
* Converts several cards to use the new declaration syntax.
There's probably some problems around timing of when conditional effects are refreshed (e.g. Unsullied applies its -1 correctly but the game announces the defense strength incorrectly initially), but want to keep things rolling forward.

Introduce effects wrapper + persistent effects

---

server/game/cards/plots/01/powerbehindthethrone.js
server/game/player.js
server/game/plotcard.js
test/server/gamesteps/plot/resolveplots.spec.js

Previously, PlotCard.onReveal was used to implement 'when revealed'
abilities. These abilities are now defined using BaseCard.whenRevealed
instead.

Remove unused PlotCard.onReveal method.

---

server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/selectcardprompt.spec.js

Previously, the previous card selection was being recalculated based on
the current prompt's player. However, the selection for the prior prompt
may have been for a different player. This led to a bug where when
returning to the original prompt, the card selected property would be
false, but the card would be in the internal list, allowing the player
to add the character to the selection multiple times.
This change saves the exact values for card.selected and
card.opponentSelected and restores them directly rather than attempt to
recalculate which type of selection was used.

Fix restore of card selection on prompt completion

---

server/game/basecard.js
server/game/effects.js
test/server/card/drawcard.hasKeyword.spec.js
test/server/card/drawcard.usestealthtobypass.spec.js

Previously, if a card was blanked it would lose all of its keywords,
even those provided by non-blanked cards. This change makes keywords in
the card text into a persistent effect, which means it will only lose
those keywords when blanked instead of all keywords.
Fixes #214.

Treat printed keywords like a persistent effect

---

server/game/cards/characters/02/nymeriasand.js

Previously, when the player used Nymeria's ability it would not remove
the icon from the opponents card. This is because the effect wasn't
specifically targetting opponent controlled cards. This change makes it
target a specific card, which skips the controller checks.
Additionally, Nymeria should now be able to remove an icon even if the
target card does not have that icon. This should be more in line with
the card text.

Fix Nymeria Sand

---

server/game/cards/attachments/02/thesilversteed.js
server/game/cards/characters/01/khaldrogo.js
server/game/cards/characters/01/olennasinformant.js
server/game/cards/locations/01/casterlyrock.js
server/game/cards/plots/01/astormofswords.js
server/game/cards/plots/01/sneakattack.js
server/game/cards/plots/02/wraithsintheirmidst.js
server/game/challengetracker.js
server/game/effect.js
server/game/effectengine.js
server/game/effects.js
server/game/game.js
server/game/gamesteps/challengephase.js
server/game/player.js
test/server/effect.spec.js
test/server/effectengine.spec.js

* Converts the "additional challenge" and "only X challenge" cards to use effects targeting the appropriate player.
* Extracts the tracking of challenge limits, initiation, win and lose counts into a separate class as it was necessary to change how the maximum challenge limits were reset.
* Implements the reserve limit for Wraiths in their Midst.

Effects that target the player instead of cards

---

server/game/drawcard.js

In order to make searching all cards safer for effects being applied,
duplicates are no longer considering to have a location of 'play area'.
Previously, this caused the Shadow Tower Mason to grant its ability by
counting duplicated location cards as in play.
Fixes #231.

Duplicates shouldn't be considering in play area.

---

server/game/cards/attachments/04/beggarking.js
server/game/cards/locations/04/bitterbridgeencampment.js
server/game/gamesteps/plotphase.js
test/server/cards/agendas/05045 - therainsofcastamere.spec.js
test/server/gamesteps/plot/resolveplots.spec.js

Previously, card abilities that had a reaction to "after a X plot card
is revealed" were executing right when the plot was revealed but before
the "when revealed" text was resolved. Per the rules, these reactions
should happen after all of the "when revealed" abilities have resolved.
Fixes #219.

Fix timing of "after plot revealed" reactions.

---

server/game/basecard.js
server/game/drawcard.js

Previously, keywords were converted to persistent effects to make them
blankable if their card was blanked. However, since those effects only
are applied once the card enters play, cards with the limited keyword
were not reading as having the keyword. To fix this, the isLimited
method now specifically looks at the list of printed keywords instead of
keywords that have been applied.

Fix Limited keyword by looking at printed keywords

---

server/game/cards/characters/02/hodor.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js

Cards can now be prevented from being declared as attackers or defenders using an effect now. It should be possible to implement these cards now: https://thronesdb.com/find?q=x%3Acannot+x%3Adeclared&sort=set&view=card
Hodor has been converted to use the effect. Doing so removed the need for the onAttackerSelected event.

Prevent challenge participation as an effect

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js

Previously, if the "cannot win a challenge" effect was in play, the
challenge would still declare a winner but skip over applying claim. Now
when the effect is in play, the attacking player is not named the
winner. If the defending player wins, they are still declared the
winner.
Fixes #247.

Do not declare a winner if cannot be won.

---

server/game/cards/plots/01/joustingcontest.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/selectcardprompt.js

* Makes select card prompt always pass an array instead of a single card when selecting attackers / defenders in a challenge. It was passing a single card when Jousting Contest was out since the limit was 1.
* Adds the challenger limit to the attacker/defender prompts (if there is a limit in effect).
* Converts Jousting Contest to use a persistent effect.
Resolves https://sentry.io/throneteki/throneteki/issues/203294158/

Fix Jousting Contest crash

---

server/game/game.js

The previous change introducing event ordering did so by queuing an
event resolver onto the game pipeline. Therefore the order of queuing
the onBeginRound event and the rest of the game steps matters now.
Previous to this change, reducers were no longer reseting because the
onBeginRound event was being queued after all of the round steps,
thereby never executing.

Ensure onBeginRound event is fired.

---

server/game/cards/agendas/kingsofsummer.js
server/game/cards/agendas/kingsofwinter.js
server/game/cards/agendas/thelordofthecrossing.js
server/game/game.js
server/game/gamesteps/setupphase.js

* Fixes Rains of Castamere by ensuring the onDecksPrepared event is properly fired.
* Adds support for persistent effects on agendas.
* Converts Kings of Winter, Kings of Summer and Lord of the Crossing to use persistent effects.
Note: because Lord of the Crossing now uses a dynamic effect, the strength announced for a challenge will be incorrect. The strength used to determine winners should be fine. Same issue as #236.

Fix and convert agendas

---

server/game/basecard.js
server/game/cards/plots/02/pullingthestrings.js
server/game/cards/plots/04/varyssriddle.js

Varys' Riddle and Pulling the Strings could put the players in an
infinite loop because events are pipeline-based and no longer 100%
synchronous.

Prevent infinite loop on plot duplicators

---

server/game/cards/attachments/01/throwingaxe.js
server/game/cards/characters/01/ariannemartell.js
server/game/cards/characters/01/direwolfpup.js
server/game/cards/characters/01/drogon.js
server/game/cards/characters/01/drownedmen.js
server/game/cards/characters/01/magisterillyrio.js
server/game/cards/characters/01/oldforesthunter.js
server/game/cards/characters/01/robertbaratheon.js
server/game/cards/characters/01/tyrionlannister.js
server/game/cards/characters/01/unsullied.js
server/game/cards/characters/01/viserion.js
server/game/cards/characters/01/wardensofthereach.js
server/game/cards/characters/02/arborknight.js
server/game/cards/characters/02/priestofthedrownedgod.js
server/game/cards/characters/03/jonsnow.js
server/game/cards/characters/03/sansastark.js
server/game/cards/characters/04/shae.js
server/game/cards/locations/01/greatkraken.js
server/game/cards/locations/01/thewall.js
server/game/cards/locations/03/winterfell.js
server/game/cards/plots/02/wardensofthenorth.js

* Replaces old references to `dsl` to the now standard `ability`.
* Uses `ability.limit` for ability limits instead of explicitly requiring `AbilityLimit` each time.

Cleanup old ability code

---

docs/implementing-cards.md
server/game/cards/agendas/thelordofthecrossing.js
server/game/cards/characters/01/robertbaratheon.js
server/game/cards/characters/01/unsullied.js
server/game/effect.js
server/game/effectengine.js
server/game/gamesteps/challenge/challengeflow.js
test/server/effectengine.spec.js

* Fixes display bugs when an effect needs to be calculated immediately after challenge participants are declared including: Lord of the Crossing, Robert Baratheon, and Unsullied.
Fixes #236.

Allow event-based recalculation of effects

---

server/game/effects.js
test/server/effects/dynamicstrength.spec.js

Previously, effects that were dynamicly calculated or restored original
state upon being unapplied were using the card object as the key on the
context object. Javascript silently converts these to strings using
`toString`, meaning if such an effect were applied to multiple cards,
they would all use the same key and overwrite each others state.
As a result, cards like Lord of the Crossing which apply their effect to
multiple cards were setting the strength properly, then when unapplied
would correctly reduce the strength of the first card, delete the state
from the context object, and then apply an undefined strength modifier to
the remainder of the cards. Since the remaining cards had `NaN` as a
strength, the resulting challenge strength would be 0.

Fix dynamic and state restoring effects.

---

docs/implementing-cards.md
server/game/cards/characters/02/raiderfrompyke.js
server/game/cards/characters/03/mancerayder.js
server/game/cards/characters/04/harmenuller.js
server/game/cards/locations/01/thewolfswood.js
server/game/effect.js
server/game/effectengine.js
server/game/effects.js
server/game/player.js
test/server/effect.spec.js
test/server/effectengine.spec.js
test/server/player/movecard.spec.js

* Adds the ability for an effect to target cards in hand (reducers can be converted to this next)
* Implements all the "Each X card in your hand gains ambush" persistent effects. Does not implement [Shagga Son of Dolf](https://thronesdb.com/card/05009) which requires cards in hand to provide effects while they are in hand.

Implement card ambushers

---

server/game/effect.js
test/server/effect.spec.js

Previously the ability to match cards in hand was implemented. This
introduced a bug where cards that did not use a matching function (i.e.
they targetted themselves or another specific card) could have their
effect applied multiple times because the target location was not
enforced. In the case of Robert Baratheon, the effect was applied just
before he entered play (while still in hand), then again when the
onCardEnterPlay event was fired. Then when strength was recalculated for
the card, it was unapplied twice, leading to a NaN strength modifier.

Fix cards with self-matching persistent effects

---

server/game/cards/characters/01/maestercaleotte.js

The match property should have been targeting a specific card.
Because it was a matching function, it was searching only cards in the
targetController - your own cards by default - and not matching on
opponent cards.

Fix Maester Caleotte

---

server/game/player.js

Previously, the onCardStood and onCardKneeled events were being fired
even if the card was already standing or kneeling. This lead to a
problem where Stinking Drunk would activate during the stand phase
even if the card was already standing.

Only fire kneel/stand events when state changes.

---

server/game/gamesteps/eventwindow.js
test/server/gamesteps/eventwindow.spec.js

Previously, if an interrupt ended up cancelling an event, any events
that may have been triggered during that cancellation would be skipped
because they are queued onto the EventWindow's pipeline.
For example, if Jory Cassel's ability activated when a character would
be killed, the sacrifice and left play events for Jory would not be
emitted. Thus, any cards that react to Jory's sacrifice (e.g. WotN
Catelyn) would not trigger.

Ensure nested events are not cancelled

---

server/game/cards/plots/02/forthewatch.js
server/game/challenge.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js

* Converts For the Watch! to use an effect so that it can be blanked by Forgotten Plans in the future.
* Nests the onAttackersDeclared event inside of the onChallenge event to ensure proper resolution order.
* Misc: adds a message when a player does not defend against a challenge.
Fixes #301.

Fix For the Watch!

---

server/game/gamesteps/playerorderprompt.js
test/server/gamesteps/playerorderprompt.spec.js

* Action windows such as those at the start of challenges phase and in the dominance phase were prompting in the order for the previous round because they're queued before the new first player is chosen. Action windows queued after first player was chosen were in the correct order.
* Any other prompts derived from `PlayerOrderPrompt` were potentially affected but less noticeable.
* Converts the `PlayerOrderPrompt` tests and makes them less integrationy. First commit is the real change, remaining 2 are conversion if that makes review easier.

Fix action window ordering

---

server/game/cards/plots/01/marchingorders.js
server/game/effects.js
server/game/player.js

* Adds effects for 'cannot play' and 'cannot marshal' and updates Marching Orders to use them. This has the side effect of allowing Marching Orders to be blankable through Forgotten Plans (previously would have ignored the blank).
* Since Marching Orders was the only non-event card using the `canPlay` method, it was possible to stop asking all other cards in play for permission when playing a card. `canPlay` will only be called for events under the current scenario, and player will always be `this.controller` and card will always be `this`, rendering the parameters useless. I would have gone through and updated all usages but this was a first baby step towards experimenting w/ what I mentioned in #296, so usage may change more.

Convert Marching Orders to an effect

---

server/game/cards/characters/02/bastarddaughter.js

Per the rules if a card refers to itself by name, its ability should
only trigger for that specific card. Previously, Bastard Daughter would
react to any other Bastard Daughter being killed, when it should only do
so for itself.
Fixes #314.

Bastard Daughter should self-react, not by name.

---

server/game/cards/characters/01/euroncrowseye.js
server/game/cards/characters/01/yoren.js
server/game/cards/locations/04/houseoftheundying.js
server/game/effectengine.js
server/game/game.js
server/game/player.js
test/server/player/movecard.spec.js

* Adds a /take-control command (useful for debugging purposes + cards that haven't been implemented yet)
* Recalculates effects once a card changes controller to ensure the new controller receives the benefits of the effect (and the old controller loses it).
Fixes #317.
Fixes #319.

Reapply effects upon take control.

---

server/game/drawcard.js
test/server/card/drawcard.canAttach.spec.js
test/server/card/drawcard.clearblank.spec.js

Previously, cards with 'No attachments' and 'No attachments except' in
their card text were ignoring blanking. Per the rules, if the card is
blanked through various means (e.g. Fortified Position) then the
attachment restriction goes away. If the card later becomes unblanked,
then any invalid attachments on it are discarded.

Allow invalid attachments while card is blank.

---

test/server/cards/cancreatecards.spec.js

Adds tests to make sure you can at least create each card and therefore call setupCardAbilities on it without error. It should help prevent bugs like Left in the future (making sure every deck is at least loadable). Feel free to reject if you think it's low value.

Add canary test to make sure all cards can be created.

---

server/game/cards/characters/02/croneofvaesdothrak.js
server/game/player.js

[ reopening after inadvertent close due to branch reorganization on my fork ]
A few points worth noting:
I had to had a new game event "onCardDiscardedFromDraw", because apparently there isn't an event raised upon pillage and similar effects. I guess a better long-term solution for this situations would be a generic "onCardMove(source, target)" event, but I didn't feel like starting that journey. If I'm missing a better way to do this, please let me know.
I'm not sure how much automation should go into verifying the starting condition of this card. I've decided to be minimal for now, so for instance the player will be prompted to trigger Crone even if they have no standing Dothraki character. If you think that part should be automated, just let me know.

implement Crone of Vaes Dothrak

---

server/game/cards/events/03/evenhandedjustice.js

The implementation requires the user to *separately* choose standing characters controlled by each player. This is due to the fact that, AFAICT, there is no way to pass separate cardCondition functions to promptForSelect, when asking to select multiple cards. Without that we cannot enforce the fact that the 2 selected characters must belong to different players. Hence the awkward workflow. Let me know if there are better ways to do this right now.
Additionally, the message emitted after the event is completed shows card names, but they are not "hyperlinks" that allow hovering, as I didn't find a way to do that. If you can point me in the right direction, I'll be happy to improve that.

implement Even-Handed Justice

---

server/game/cards/characters/05/cerseilannister.js
server/game/player.js
test/server/player/drop.spec.js

* LoCR Cersei will react again when cards are discarded from hand. Note: This brings back bug #184 which only stopped because the event got wiped out somehow. So Cersei will again react to every single card discarded and thus trigger inappropriately on 2 claim intrigue and reserve discard. That will need to be fixed separately.
* Makes drag-drop handling more consistent by using the discardCard and killCharacter methods. Previously it was trying to simulate those methods by raising events but it didn't quite match up with what those methods do.

Get LoCR Cersei's reaction working again

---

client/GameBoard.jsx
client/GameComponents/AdditionalCardPile.jsx
client/GameComponents/Card.jsx
client/GameComponents/CardCollection.jsx
client/GameComponents/PlayerRow.jsx
less/gameboard.less
server/game/cards/agendas/therainsofcastamere.js
server/game/cards/characters/01/varys.js
server/game/cards/locations/04/houseoftheundying.js
server/game/player.js
test/server/cards/agendas/05045 - therainsofcastamere.spec.js
test/server/player/flipplotfaceup.spec.js
test/server/player/movecard.spec.js

* Internally changes how plot cards are managed - they can now be placed like any other card using `Player.moveCard`.
* Adds support for additional card piles - including 'out of game' and the scheme plots for Rains of Castamere. 
* Castamere schemes are displayed in a pile below the normal plot piles. As with the normal plot pile, opponents / spectators can't view the cards. 
* Cards that have been removed from the game show up knelt next to the dead pile. If there are no cards in the pile, it won't be displayed. Like other face up piles, 'out of game' is open information and the opponent can view the cards. 
Resolves #253.

UI for Castamere schemes and 'out of game' cards.

---

server/game/player.js

Previously, if a card was played during set up, but then dragged back to
hand, any effects applied by the card would remain in place. The
reported example was The Arbor granting its +3 gold even though the
player moved it back to hand. This was because the onCardLeftPlay event
is relied upon by the effects engine and was explicitly not being fired
during the setup phase.
(during my brief testing this didn't seem to break anything but I can't really remember why it was written this way in the first place. No tests broke when removing the if, so whatever the reason it was apparently not important enough to test).

Always fire onCardLeftPlay when leaving play area.

---

README.md

Note: the instructions on how to run eslint singles out the client/ and server/
dir. This is because we cannot simply tell people to run 'eslint .' from the
root dir, as some built bundles will make eslint barf.

document ESLint usage in README.md

---

server/game/cards/plots/04/summerharvest.js
server/game/plotcard.js
test/server/cards/plots/04/04039 - summerharvest.spec.js

Previously, if you went through all of your plots and played Summer
Harvest a second time, it would retain its income value from the first
time in addition to how much it would normally gain this round. Now
instead of setting a gold modifier, it sets the base income value which
is overwritten each time. This prevents the previous bug and should
allow interactions with Varys' Riddle to be correct.
Fixes #261.

Fix Summer Harvest from granting too much gold

---

docs/implementing-cards.md
server/game/abilitydsl.js
server/game/baseability.js
server/game/cardaction.js
server/game/cards/attachments/01/sealofthehand.js
server/game/cards/characters/01/wildlinghorde.js
server/game/cards/characters/02/halder.js
server/game/cards/locations/01/ghastongrey.js
server/game/cards/locations/01/thewall.js
server/game/costs.js
server/game/gamesteps/abilityresolver.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/card/baseability.spec.js
test/server/card/cardaction.spec.js
test/server/card/cardreaction.spec.js
test/server/gamesteps/abilityresolver.spec.js

* Introduces an optional `condition` property on actions. This should be used to check non-cost requirements for an action prior to allowing it to execute. For example - if the action is supposed to stand the parent card, the condition should make sure the parent card is currently kneeling.
* Converts actions to take a `handler` property more similar to reactions / interrupts. Instead of taking the separate player and arg arguments, it takes a context object that has those objects as properties. The context object will also contain the card knelt to pay costs and will (later) contain card targets chosen by the player.
* Introduces an optional `cost` property on actions, reactions and interrupts. This is used to specify the cost of the ability, such as kneeling the card, kneeling the …

Cost API for abilities + general action improvements.

---

client/NewGame.jsx
less/gamelist.less

Added a 140 character limit for the game name with a character counter located to the top right of the text input.
(As ystros suggested, we want to prevent full texts of War & Peace as game titles)
Also added CSS adjustments to keep the text within its container, wrapping accordingly

Limit game name to 140 characters, inspired by twitter char count (#405)

---

client/GameComponents/Card.jsx

Previously, if the effects engine caused a card to gain icons during the
setup phase, the icons would appear on the facedown card, potentially
revealing information to the opponent. For example, if the Shadow Tower
Mason was placed along with 3 Night's Watch locations, the intrigue and
military icons gained would be visible to the opponent even if the card
was face down.

Don't display counters / tokens when facedown

---

server/fetchdata.js

Previously, if the card.imagesrc property returned by ThronesDB was
null to indicate they don't have an image for the card, the fetch data
script would create a zero byte file locally. This prevented the image
from being fetched after the image had been uploaded, because there was
a local file (even though it was empty).

Only fetch images if one exists.

---

client/GameComponents/Card.jsx
less/cards.less
server/game/basecard.js
server/game/gamesteps/selectcardprompt.js

Adds a glow around cards that can be selected during a card selection
prompt.
I've made the color a bit closer to white (though still green tinted) so that it's more distinct from the selection color itself. Here's a preview (excuse the GIF artifacts, Github apparently won't let me embed a video directly):
I figure this is a good starting point and those with more design savvy can improve it.
Resolves #422.

Highlight cards that can be selected by prompt

---

client/GameComponents/Messages.jsx
server/game/cards/attachments/02/kingrobertswarhammer.js
server/game/cards/characters/01/stannisbaratheon.js
server/game/cards/characters/04/roosebolton.js
server/game/cards/events/01/consolidationofpower.js
server/game/cards/events/02/agiftofarborred.js
server/game/cards/events/02/ineverbetagainstmyfamily.js
server/game/cards/events/03/evenhandedjustice.js
server/game/cards/events/04/thereismyclaim.js
server/game/cards/locations/04/houseoftheundying.js
server/game/cards/plots/01/rebuilding.js
server/game/cards/plots/01/wildfireassault.js
server/game/cards/plots/02/politicaldisaster.js
server/game/cards/plots/02/wardensofthewest.js
server/game/gamechat.js
server/game/gamesteps/challenge/fulfillmilitaryclaim.js
test/server/game/gamechat.formatMessage.spec.js

You can now pass arrays directly into `addMessage` and have them be formatted for you automatically instead of manually building up the format message manually in your card implementations. The formatting output is based on the number of items in the array - either 1, 2 or 3+ items. Examples:
[cardA] = 'card A'
[cardA, cardB] = 'card A and card B'
[cardA, cardB, cardC, cardD] = 'card A, card B, card C, and card D'
Also adds an announcement message to Wildfire upon a player choosing which characters to save, since the choices should be public info and could modify the second player's decision making.

Add support for formatting arrays in messages

---

server/game/effect.js
server/game/effectengine.js
test/server/effect.spec.js
test/server/effectengine.spec.js

Previously, if an effect was state dependent (dynamic strength, kill on
0 strength, etc) OR an effect was conditional, the recalculation
mechanism would always remove all targets and go through all cards for
eligible targets. This lead to a bug with Dracarys which is state
dependent, not conditional, and not persistent. The effect of Dracarys
would be re-applied if the card killed by its effect was manually
dragged back into play - the target was removed when it left play, but
the matching function would allow it to be reapplied after entering play
again.
Now, only conditional effects will update their target lists upon
recalculation. Effects that are solely state dependent will unapply and
reapply their effect to existing targets, but will not add any
additional targets.
Fixes #454.

Only recalc targets for conditional effects.

---

server/game/cards/characters/02/newly-madelord.js

the requirement of target location being standing is not part of the card
behavior

make Newly Made Lord activable on kneeled location

---

README.md

Rationale: it's duplicate information w.r.t. the About page that is a pain to
maintain up-to-date. Plus, README is mostly geared towards developers rather
than players anyway.

remove command cheatsheet from README, pointing to About page instead

---

server/game/abilitylimit.js
test/server/abilitylimit.spec.js

Can be used for per-game limits and the upcoming changes for cost reducing effects.

Add support for non-repeating ability limits

---

server/game/costreducer.js
server/game/effects.js
server/game/player.js
test/server/costreducer.spec.js
test/server/player/costreduction.spec.js

Introduces the CostReducer class that represents an active cost
reduction effect. These reducer objects can be added to the player
object, which are then used to calculate reductions on matching cards.
This change does not replace the current cost calculations yet.

Implement framework for cost reducing effects.

---

server/game/cards/characters/04/seredmuretully.js

This is an implementation of Edmure. But there is a BUT (that is also noted as
a TODO in the card code). It will trigger even when power is *moved* between
cards, rather than only when it is *gained*. To achieve the proper semantics
however we need to:
- introduce a new event (!= onCardPowerChanged) that is raised when power is
moved between cards
- add a new function to move power, so that cards that need to do so have a
high-level way of implementing it, rather than using two distinct power
modifications on two cards
- review all current uses of power modifications to check whether they should
be ported to the new high level effect
Do we want to do the above as a condition for having Edmure implemented, or do
we prefer to have a suboptimal implementation of Edmure in right now, and …

implement Ser Edmure Tully

---

server/game/basecard.js
server/game/cardaction.js
server/game/cards/locations/01/thekingsroad.js
server/game/cards/locations/05/oceanroad.js
server/game/cards/reducer.js

This converts all reducers to use the standard action syntax. An
additional property, `clickToActivate`, can be passed into actions now
indicating they can be executed by clicking the card instead of using
the menu.

Convert reducers to normal actions.

---

server/game/cards/plots/02/forgottenplans.js

The .phase attribute is not defined on Game objects, but as the condition was
negated in this plot, it always succeeded. The proper way to do this is
checking .phase on Player objects.
We now check it on both player at once, which is OK as phases are always
updated simultaneously.

fix Forgotten Plans condition check to verify current phase on players

---

test/helpers/gameflowwrapper.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/locations/01/01137 - thewall.spec.js
test/server/cards/plots/04/04039 - summerharvest.spec.js

Adds an `integration` method as a spec helper. Using this method instead
of a normal `describe` block will create a set of integration objects
that allow you to simulate game flow in tests without having to manually
manipulate the game, player and pipeline objects.

Introduce integration testing helpers

---

server/game/cards/characters/04/seredmuretully.js

Adds a title for the prompt for Edmure to make it clear which character
is moving power away from, do not allow Edmure to move power to and from
the same character, and return true from select card to ensure that the
prompt completes.

Make Edmure Tully clearer.

---

server/game/cards/events/02/agiftofarborred.js

before this change the card made it seems that opponents choose themselves to
active the tutoring effect, while it is always the card controller who does so

fix A Gift of Arbor Red log message to always state controller's name

---

.gitmodules
README.md
circle.yml
test/helpers/cardutil.js
test/helpers/deckbuilder.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/locations/01/01137 - thewall.spec.js
test/server/cards/plots/04/04039 - summerharvest.spec.js

* Adds a submodule to pull in card data from https://github.com/Alsciende/thronesdb-json-data for use in tests. **Important:** you'll need to run `git submodule init` and `git submodule update` initially if you intend on running tests.
* Adds a `buildDeck` method during integration tests. It takes the faction name and then an array of cards that are in the deck. This array can either be the unique card codes, the name of the card if it is unambiguous, or the card name + pack combination, e.g. "Tyrion Lannister (Core)". Cards are looked up and automatically placed in the correct structure for loading it in the game.

Introduce deck builder for integration tests

---

server/game/basecard.js
test/server/card/basecard.spec.js

Previous PR #477 broke all non-click-to-activate actions by updating a
usage of CardAction.execute to pass a context object while not updating
the definition. This reverts the usage to match the method signature
again.

Fix card actions

---

server/game/cards/characters/02/winterfellkennelmaster.js
server/game/cards/plots/02/wardensofthenorth.js
server/game/costs.js

* Fixes a problem with `Costs.kneel` which allowed you to select cards that were already knelt or not in the play area.
* Fixes Wardens of the North plot to disallow kneeling an opponent's Stark character (since the kneel is part of the cost and you can only use your own cards to pay costs)
* Implements Winterfell Kennel Master since it's almost identical to Wardens of the North.

Fix kneel cost + Wardens of the North + Winterfell Kennel Master

---

server/game/cards/characters/04/renlybaratheon.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js

To that end, raise a new onInsight event, carrying the list of cards drawn
using the Insight keyword.
Passing note: I find super annoying that the "drawn" parameter of the new event
is either a singleton element (a card) or an array of cards. But I've done it
that way for consistency with what we do for onPillage/discardFromDraw. IMHO
it'd be nice to uniform all of those to always return an array of cards.

implement Renly Baratheon (For Family Honor)

---

server/game/drawcard.js
server/game/player.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/integration/setup.spec.js
test/server/player/canplaycard.spec.js

* Prevents more than 1 limited card from being setup, even if they're dupes.
* Fixes a bug where dupes dragged back to hand during setup would end up both places and face up.
* Prevents events from being played during setup.

Fix setup problems

---

server/game/cards/characters/04/salladhorsaan.js
server/game/cards/characters/05/serkevanlannister.js
server/game/cards/events/01/hearmeroar.js
server/game/cards/events/02/ineverbetagainstmyfamily.js
server/game/cards/events/04/bloodofmyblood.js
server/game/cards/locations/04/bitterbridgeencampment.js
server/game/cards/locations/05/oldwyk.js
server/game/cards/plots/01/reinforcement.js
server/game/cards/plots/02/heretoserve.js
server/game/cards/plots/03/atimeforwolves.js
server/game/player.js
test/server/player/playcard.spec.js
test/server/player/putintoplay.spec.js

* Replaces usages of `playCard(card, true)` a.k.a force-play with a new `putIntoPlay` method.
* I'll fix usages introduced in #515 once it's merged (force play will continue to work even with this change, putIntoPlay is just simpler / reads better)
* `putIntoPlay` will ultimately be used by the forthcoming marshaling refactor

Introduce a 'put into play' method

---

server/game/costs.js

Don't see discarding more than 1 gold as a cost or discarding different types of tokens as a cost happening soon, so I kept it simple.
Edit: Hmm, probably better to do it right the first time, have it take type and amount arguments...

Add "discard 1 gold"-cost to the cost framework

---

test/helpers/gameflowwrapper.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/characters/01/01088-thetickler.spec.js
test/server/cards/characters/02/02053-croneofvaesdothrak.spec.js
test/server/cards/plots/01/01013-headsonspikes.spec.js

Prep work for refactoring how discarding cards work.
* Adds tests for The Tickler, Crone of Vaes Dothrak, and Heads on Spikes.
* Adds support for menus in integration tests, helpers for skipping an action window, and for doing compact unopposed challenges.

Add tests for various discarding abilities

---

server/game/baseability.js
server/game/cardaction.js
server/game/costs.js
server/game/drawcard.js
server/game/game.js
server/game/player.js
server/game/promptedtriggeredability.js
server/game/setupcardaction.js
server/game/triggeredability.js
test/server/card/baseability.spec.js
test/server/card/cardaction.spec.js
test/server/card/cardreaction.spec.js
test/server/player/playcard.spec.js
test/server/setupcardaction.spec.js

* Introduces the concept of 'play actions' for cards. These are game actions / abilities that can occur when clicking on cards in hand. This includes playing a card during setup, marshaling, ambushing, in-hand actions, or other special in-hand abilities (e.g. marshal Lady in Waiting as a duplicate on a lady).
* This converts the setup phase to use these actions.
Later changes will prompt the player if multiple actions are valid at any one time (e.g. marshal LiW directly or marshal her as a dupe, ambush a card or use their in-hand action, etc).

Introduce play actions for cards

---

server/game/cards/locations/01/castleblack.js

In particular, it is possible (although probably never what you want to do) to
use Castle Black on opponents' characters, as long as they are Night's Watch
and defending.  While at it, drop redundant (and maybe incorrect in the future)
checks, such as play area positioning.

fix Castle Black to properly implement card semantics

---

server/game/cards/characters/01/aerondamphair.js
server/game/cards/characters/01/ariannemartell.js
server/game/cards/characters/01/oldbearmormont.js
server/game/cards/characters/01/thequeenofthorns.js
server/game/cards/events/01/fireandblood.js
server/game/cards/plots/04/ghostsofharrenhal.js
server/game/game.js
server/game/player.js
test/server/player/drop.spec.js

Replaces all usages of `Player.playCard(card, true)` with
`Player.putIntoPlay(card)`. This simplified the way drag and drop works,
so the extra parameters on `Game.playCard` could be removed.

Convert all usages of force play to put into play

---

server/game/cards/characters/04/robbstark.js

Previously, King Robb's action was able to be used during any challenge
he participated in. Now it will only properly trigger for military
challenges.
Fixes #544.

Fix King Robb and convert to new syntax

---

server/game/cards/locations/01/greatkraken.js

Giving Balon stealth is now a persistent effect, getting rid of the
usage for the weird onCardPlayed event.

Convert Great Kraken to use persistent effect.

---

server/game/cards/characters/02/ladyinwaiting.js

This should make the temporary implementation work in more cases. Only case in which this won't be "perfect" is if you want to play her as a dupe while having less than 2 gold. Manually adding gold to be able to marshal her, then substracting the gold you got from the handler should solve that.

Remove gold check from Lady In Waiting

---

server/gamerouter.js
server/lobby.js

Previously, if a game server worker timed out, the games would remain in
the lobby view even though they were no longer running / accessible.
Additionally, if a worker was restarted, any games that were on that
worker would also remain stuck in the lobby.

Clear games when worker is restarted or times out

---

server/game/cards/characters/02/sergregorclegane.js

Previously, the prompt to kill a character for Ser Gregor Clegane would
not be dismissed after selecting a character, allowing him to kill
multiple characters.

Close prompt for Ser Gregor Clegane.

---

server/game/cards/characters/01/euroncrowseye.js
server/game/cards/characters/01/yoren.js
server/game/cards/events/04/nightgathers.js
server/game/cards/locations/04/houseoftheundying.js
server/game/player.js
test/server/cards/events/04/04046-nightgathers.spec.js
test/server/player/flipplotfaceup.spec.js
test/server/player/playcard.spec.js
test/server/player/putintoplay.spec.js

Previously, the `takeControl` method was being used for putting
opponents non-play area cards into play for the current player. This has
been changed to use the `putIntoPlay` method directly, which more
closely matches the card text.
Additionally, this fixes Night Gathers as it uses the `playCard` method,
which uses `putIntoPlay` internally.
Fixes #366.

Allow putIntoPlay to transfer control of cards.

---

server/game/deck.js

Previously, it was possible to end up with agendas in the draw deck.
These and other non-draw cards are now filtered out when the deck is
constructed at the start of a game.
Resolves https://sentry.io/throneteki/throneteki/issues/232365876/

Filter out invalid cards when building deck.

---

server/game/game.js

Currently the list of public places is hard coded in the Game.drop() method, as
they are just strings throughout the code. If/when they become abstract
objects (e.g., Pile, Places, or something such), we should make sure they have
isPublic() properties to make this and similar checks more clean.

log details of moved cards when they move from/to public places

---

server/game/drawcard.js
server/game/game.js
server/game/playcardaction.js
server/game/player.js
test/server/playcardaction.spec.js

Converts playing event cards from hand to play actions. Also moves the onCardPlayed event to only apply to playing events, which should make #553 easier.

Convert event cards to use play actions.

---

server/game/cards/plots/02/wraithsintheirmidst.js
test/helpers/deckbuilder.js
test/server/cards/plots/02/02080-wraithsintheirmidst.spec.js

Previously, Wraiths in their Midst was not being applied to plots
revealed by The Rains of Castamere. This has been resolved by converting
it into a persistent effect.
Fixes #590.

Apply Wraiths in their Midst to Rains plots.

---

server/game/basecard.js
server/game/cards/characters/02/ladyinwaiting.js
server/game/customplayaction.js
server/game/drawcard.js
test/server/cards/characters/02/02023-ladyinwaiting.spec.js

* Adds a `playAction` method to the ability API that allows you to define custom behavior when a player tries to play the card.
* Converts Lady-in-Waiting to use a play action for her marshal-as-a-dupe ability. Clicking on LiW during the marshal phase will now allow the player to choose whether to marshal her as normal or play her as a dupe. This prompt will only appear if both actions are eligible - if the player doesn't have enough gold to marshal, it will default to playing as a dupe. If the player doesn't have a Lady character out, it defaults to normal marshaling. If neither is possible, nothing happens.
Fixes #593.

Convert Lady-in-Waiting to use custom play action

---

server/lobby.js
server/pendinggame.js

Previously, if a player left the game after it had been started, they
could still be considered active in the game from the perspective of the
lobby. This would leave their name listed in the game and could also
potentially cause reconnect issues. Now, once they leave an active game,
they are marked as 'left' in the lobby listing.

Hide users that have left in lobby listings.

---

docs/implementing-cards.md
server/game/basecard.js
server/game/cardaction.js
server/game/cards/characters/04/dolorousedd.js
server/game/drawcard.js
test/server/card/cardaction.spec.js
test/server/cards/characters/04/04025-dolorousedd.spec.js
test/server/playcardaction.spec.js

* Allows an optional `location` property to be specified on actions. This indicates where the action may be activated from. For 'hand' actions, clicking the card will activate the ability (or prompt the player if multiple play actions are eligible).
* Implements Dolorous Edd.

Allow in-hand actions and implement Dolorous Edd

---

server/game/cards/events/01/seeninflames.js
server/game/cards/events/03/hisvipereyes.js

Until cancels are implemented, these allow the target player to cancel these events before irreversible information is revealed to the opponent.

Add cancel prompts to hand reveal events

---

server/game/effect.js
test/server/cards/plots/04/04020-varyssriddle.spec.js
test/server/effect.spec.js

Previously, there were scenarios in which a plot with persistent effects
could end up being applied to the same card twice. Wraiths in their
Midst, for instance, would get applied twice when it was revealed as the
second plot during a round. Now the effect engine checks whether the
target is already in the current targets list for an effect before
adding it again.
Fixes #615.

Ensure persistent plot effects apply only once.

---

docs/implementing-cards.md
server/game/baseability.js
server/game/cardaction.js
server/game/cards/attachments/01/ice.js
server/game/cards/characters/01/greywind.js
server/game/cards/characters/03/aggo.js
server/game/cards/characters/03/eddardstark.js
server/game/cards/locations/04/renlyspavilion.js
server/game/gamesteps/abilityresolver.js
server/game/player.js
server/game/triggeredability.js
test/server/card/baseability.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/player/playcard.spec.js

* Simplifies and automates card selection prompts by providing a `target` property. If an ability requires multiple targets to be chosen (somewhat rare), they can be specified and named using `targets` property instead.
* If an ability has no valid targets, it will no longer be allowed to trigger (similar to if costs couldn't be paid).
* Converts a few cards over as examples.

Add card targeting to ability API

---

server/game/gamesteps/challenge/challengeflow.js
test/server/integration/pillage.spec.js

Previously, if multiple instances of pillage would trigger at once, only
the first card would actually be discarded. This was because pillage
determined which card would be discarded synchronously, but executed
asynchronously. Now the entire pillage step is asynchronous.
Fixes #641.

Properly handle multiple pillages.

---

server/game/cards/characters/01/selysebaratheon.js
server/game/costs.js
test/helpers/playerinteractionwrapper.js
test/server/cards/characters/01/01049-selysebaratheon.spec.js

Previously, Selyse's action was not working at all because the `addIcon`
method had been overridden to handle the action. When the effect was
attempted to be applied, it would call the prompt again instead of
actually adding the icon.
Fixes #639.

Fix Selyse Baratheon

---

server/game/basecard.js
server/game/cardaction.js
test/server/card/cardaction.spec.js
test/server/cards/agendas/01027-fealty.spec.js

The introduction of `location` onto actions broke Fealty because it's
location is 'agenda' but by default the action assumes it should be
'play area'.
Now cards with type 'agenda' are defaulted to have their actions in that
location.
Fixes #647.

Fix Fealty reduction

---

server/lobby.js

Previously, sockets that belonged to a user that was logged in but was
not in a game were not being removed from the socket list.
Additionally, it isn't possible to send game state to a socket that has
been disconnected, and rooms are left automatically upon disconnection.

Always delete disconnected sockets.

---

server/game/basecard.js
server/game/cardaction.js
test/server/card/cardaction.spec.js
test/server/cards/plots/01/01018-powerbehindthethrone.spec.js

The previous introduction of non-menu in-hand actions that broke agenda
menus also broke plot menus.
Fixes #656.

Fix plots with action menus.

---

server/game/baseability.js
server/game/basecard.js
server/game/cardaction.js
server/game/cards/locations/03/tourneygrounds.js
server/game/cards/locations/05/oceanroad.js
server/game/cards/reducer.js
server/game/costs.js
test/server/card/cardaction.spec.js
test/server/integration/reducers.spec.js

After converting reducer cards to the effects API, it was no longer
possible to cancel the ability by standing the card. Now, for any click
to activate action, clicking the card again will cancel the ability and
unpay the costs associated with the action. Currently this is only
implemented on the kneelSelf cost but can be extended to other costs in
the future should the need arise.
Fixes #648.

Allow click to activate actions to be undone.

---

server/game/basecard.js
server/game/cardaction.js
server/game/drawcard.js
test/server/card/basecard.spec.js
test/server/card/cardaction.spec.js

Previously, the ability API assumed that cards would only have a
single action. With the upcoming card The New Gift, cards must now
support multiple actions. The API now supports this and distinguishes
between actions using their index as the argument for the card menu.

Add support for multiple actions per card.

---

server/game/cards/events/02/funeralpyre.js

As is, the event is always playable rather than only when a Lord/Lady character
dies, because we don't have yet in place the scaffolding for in-hand reactions.

implement Funeral Pyre (partial)

---

server/game/cards/events/01/ameagercontribution.js

As is, the event is playable as long as opponent has at least 1 gold in their
gold pool, rather than only as a reaction to them collecting income. This will
be properly addressable once we have the in-hand reaction mechanism.
Fixes #383

implement A Meager Contribution (partial)

---

server/game/cards/characters/03/houseflorentknight.js
server/game/cards/plots/01/confiscation.js
server/game/forcedtriggeredability.js
test/server/card/cardforcedreaction.spec.js

The target API is now supported on forced interrupts, forced
reactions, and when revealed abilities.

Add target API support to forced abilities.

---

server/game/ambushcardaction.js
server/game/cards/characters/01/euroncrowseye.js
server/game/marshalcardaction.js
server/game/player.js
test/server/ambushcardaction.spec.js
test/server/cards/characters/01/01069-euroncrowseye.spec.js
test/server/marshalcardaction.spec.js
test/server/player/putintoplay.spec.js

Previously, the checks when putting into play cards from the opponent that:
1. Neither player already had the card in play if unique
2. Neither player had the card in their dead pile if unique (unless that card was the only copy)
were only being enforced when marshaling. Now `Player.canPutIntoPlay` is provided and is automatically checked when `Player.putIntoPlay` is called. Each card can also use it when searching for valid put-into-play targets.
Fixes #669.

Enforce in-play and dead checks for put into play

---

less/cards.less
server/game/cards/attachments/07/lingeringvenom.js
server/game/chatcommands.js

<strike>I'm putting the tokens on the parent card for now. This causes issues when: 
1. The attachment is discarded, which leaves the now redundant tokens. This could further impact gamestate whenever a new Lingering Venom is attached to the same character later. 
2. Lingering Venom gets moved to a different character, which should move the venom tokens with it (but doesn't now).
Both cases are easily solvable with the /token command until we deal putting tokens/markers on attachment cards.</strike>
Put the tokens back on the attachment.

Implement Lingering Venom

---

client/GameBoard.jsx
client/GameComponents/MenuPane.jsx
less/gameboard.less
server/game/gamesteps/menuprompt.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js

Now when a character ability triggers a prompt, the name of the card
will be displayed in the menu prompt. This should help reduce confusion
during nested ability windows where a new window is opened and resolved
and then it returns to the original window.

Add card name to ability prompts.

---

server/game/baseability.js
server/game/cards/characters/03/houseflorentknight.js
test/server/card/baseability.spec.js
test/server/cards/characters/03/03037-houseflorentknight.spec.js

Previously the targeting API was checking all cards, including plots,
agendas and factions, for whether they were valid targets. This made it
incredibly easy to generate an error by providing a card condition that
needed a method only found on `DrawCard`
Fixes #690.
Fixes #691.

Only allow targeting API to target draw cards.

---

server/game/effects.js
test/server/effects/killbystrength.spec.js

Previously, burn effects could end up killing a character twice as
effects are reapplied. This could end up triggering reactions multiple
times innapropriately. Now the `killByStrength` guards against this
condition.
Fixes #678.

Protect against double kill through burn effects.

---

server/game/cards/characters/01/aerondamphair.js

Previously, Core Aeron was able to put characters into play from the
opponent's dead pile. Now it is properly restricted to the dead pile
owned by Aeron's current controller. Additionally, it will no longer
trigger if there are no characters to put into play.
Fixes #660.

Restrict Aeron's resurrection to current player.

---

server/game/effect.js
server/game/effectengine.js
server/game/effects.js
test/server/effect.spec.js
test/server/effects/dynamicstrength.spec.js

* Allows effects to implement a `reapply` method to directly update their effect rather than unapplying and then reapplying it from scratch.
* Conditional effects are now only recalculated when the result of the `condition` method changes. If a condition goes from `true` to `false`, it is unapplied. If it goes from `false` to `true`, it's applied to all matching targets.
This should get rid of all effect churn I'm aware of and allows Randyll Tarly to be implemented without false positive triggers.

Improve recalculation of effects

---

server/game/effect.js
test/server/cards/agendas/02060-thelordofthecrossing.spec.js
test/server/effect.spec.js

The previous change to how conditional effects are recalculated broke
effects such as Lords of the Crossing, whose targets can change while
the condition value remains the same. Now the target list is updated as
new targets come in, and targets that are no longer matching are
removed.

Fix challenge-related conditional effects.

---

server/game/effect.js
test/server/cards/plots/03/03050-asongofsummer.spec.js
test/server/effect.spec.js

When a condition changed from another card entering play (e.g. A Song of
Summer applying its effect, then a Winter plot being revealed), the
effect was no longer being cancelled. This was due to the change in the
reapply method as the condition was already false when reaching it. Now
reapply looks at the condition whether or not the result changed from
the last check.

Fix effects when condition changes on enter play.

---

server/game/effects.js
test/server/effects/canmarshalfrom.spec.js

Previously, cards that used the `canMarshalFrom` effect such as Night
Gathers would improperly clear the valid marshal locations for a player
when the effect ended. This resulted in not being able to marshal cards
from the players hand after the effect was unapplied.

Fix canMarshalFrom effect + Night Gathers.

---

server/game/cards/characters/01/ashagreyjoy.js
server/game/cards/characters/01/theongreyjoy.js
server/game/cards/characters/02/thereader.js
server/game/cards/characters/02/will.js
server/game/cards/locations/01/greatkraken.js
server/game/cards/locations/01/thewall.js
test/server/cards/characters/05/05006-tywinlannister.spec.js

Reactions and interrupts for winning or losing unopposed challenges
should have the same window as winning or losing normal challenges. Thus
they should use the `afterChallenge` event instead of `onUnopposedWin`.

Use correct event for unopposed win/loss

---

server/game/cards/plots/02/pullingthestrings.js
server/game/cards/plots/04/varyssriddle.js
server/game/forcedtriggeredability.js
server/game/game.js
server/game/gamesteps/eventwindow.js
server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/gamesteps/triggeredabilitywindowtitles.js
test/server/card/cardforcedreaction.spec.js
test/server/gamesteps/eventwindow.spec.js
test/server/gamesteps/forcedtriggeredabilitywindow.spec.js
test/server/integration/forcedreactionorder.spec.js

Per the rules, when there are more than one forced reactions /
interrupts in the same window, the first player gets to choose the order
that they are resolved.

Allow first player to choose forced ability order.

---

server/game/cardaction.js
server/game/cards/events/01/hearmeroar.js
server/game/costs.js
server/game/playcardaction.js
test/server/card/cardaction.spec.js
test/server/integration/marshalphase.spec.js
test/server/playcardaction.spec.js

It is now possible to define actions for event cards through the ability
API. By default, each event card with an action is playable from hand
(assuming requirements and costs are met) and they will automatically
have the standard event costs specified.
Hear Me Roar has been converted as an example.

Default location and cost for event card actions.

---

server/game/gamesteps/challenge/applyclaim.js
server/game/gamesteps/challenge/challengeflow.js

In order to support cards that apply claim outside of challenges (e.g.
WotW Maester Aemon), applying claim has been extracted into its own game
step class.

Extract claim into its own game step.

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js
test/server/integration/challengesphase.spec.js

Per the rules, if either the attacker or defender has higher strength,
but has no participating characters, then neither player wins or loses
the challenge. This is most applicable when something like The Haunted
Forest ends up with higher strength than the attacking player.
Fixes #730.

Require participating characters to win challenges

---

docs/implementing-cards.md
server/game/basecard.js
server/game/cardaction.js
server/game/cards/events/06/theprincesplan.js
server/game/forcedtriggeredability.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js

Allows reactions to be defined for locations other than 'play area' and implements The Prince's Plan.
**Note:** It is now technically possible to define in-hand reactions for event cards. However, the cost is not currently defaulted like it is for in-hand event card actions, and (more importantly), such reactions are still blocking prompts, which could reveal information about the player's hand. So while you could start defining event card reactions using the API, I wouldn't recommend it yet.

Implement The Prince's Plan.

---

server/game/cards/attachments/07/sworntothewatch.js

Fixes the immediate crashes related to Sworn to the Watch, but there are a myriad of other problems with it currently (see #756).

Fix Sworn to the Watch crash on setup.

---

server/game/cards/locations/04/houseoftheundying.js

Before this fix House of the Undying always worked for its owner, because
removing it from the game (which happens before the effect) reset the
controller to the owner.
Fixes #750

make House of the Undying work for the current controller

---

server/game/gamesteps/challenge/applyclaim.js
server/game/gamesteps/challenge/challengeflow.js

While a claim value of 0 means that no characters will be killed, cards
discarded, or power stolen, it still counts as applying claim. This
allows cards such as The Seastone Chair to replace the effects of that
claim.
Fixes #738.

Apply claim even if the claim value is 0.

---

server/game/cards/attachments/05/shieldoflannisport.js
test/server/cards/attachments/05020-shieldoflannisport.spec.js

Shield of Lannisport was checking that there weren't any lords or ladies
of cost below 4 instead of 4 or higher like the card text says.
Fixes #745.

Fix Shield of Lannisport.

---

server/game/cards/locations/01/thekingsroad.js
test/server/integration/takecontrol.spec.js

Previously, the Kingsroad was always giving its reduction to the player
set in the `controller` property. However, because the Kingsroad was
sacrificed prior to applying the reduction, the controller was always
the original owner. This lead to a bug where the Kingsroad would apply
its reduction improperly to the owner even when it had been taken
control using cards like Euron Crow's Eye.
Fixes #569.

Give reduction to player that activated Kingsroad.

---

server/game/gamesteps/challenge/challengeflow.js
test/server/integration/challengesphase.spec.js

Per the rules, stealth targets must be chosen prior to any reactions or
interrupts firing for the challenge initiation.
Fixes #450.

Choose stealth targets before challenge initiated.

---

server/game/triggeredability.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/cards/locations/04/04082-harrenhal.spec.js

Previously, if an interrupt or reaction ended up removing another card
from play (e.g. Harrenhal kills Littlefinger when he enters play), then
the player would still be prompted to trigger the removed card's
abilities. Now reactions check that the card is still in the proper area
to be eligible to activate.
Fixes #640.

Prevent reactions from firing from wrong location.

---

server/game/cards/events/04/offerofapeach.js

Got a little too overzealous deleting code when converting event cards
to use `action`.

Undelete target condition for Offer a Peach.

---

server/game/gamesteps/plotphase.js
server/game/player.js
test/server/player/flipplotfaceup.spec.js

Previously, plots were being recycled immediately upon the 7th plot
becoming active. This prevented Pulling the Strings from replicating the
ability of the 6th plot played by the opponent. Per the rules, plots
should be recycled after all active plots have been resolved.

Recycle plots after "when revealed" has resolved.

---

server/game/cards/events/01/taketheblack.js
test/server/cards/characters/01/01139-taketheblack.spec.js

Previously, Take the Black was only allowing unique cards to be selected
instead of non-unique cards per the card text.
Fixes #759.

Fix Take the Black to control non-uniques.

---

server/game/cards/plots/02/pullingthestrings.js
server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/selectcardprompt.spec.js

Select card prompts can now filter cards by their type. Most card
conditions written have assumed they're operating on draw cards, leading
to errors if the player happens to click a non-draw card. Prompts are
now limited to draw card types unless explicitly specified using the
`cardType` property (e.g. Pulling the Strings for plot cards).
Fixes #770.

Add `cardType` property to select card prompts.

---

server/game/basecard.js
server/game/cards/agendas/therainsofcastamere.js
server/game/cards/plots/02/pullingthestrings.js
server/game/cards/plots/04/varyssriddle.js
server/game/gamesteps/plot/resolveplots.js
server/game/gamesteps/plotphase.js
test/server/cards/agendas/05045-therainsofcastamere.spec.js
test/server/cards/plots/04/04020-varyssriddle.spec.js
test/server/gamesteps/plot/resolveplots.spec.js

Previously, the onPlotRevealed event used to trigger "When Revealed"
abilities was only passing the player object. This made it necessary to
set controller to null on Varys's Riddle and Pulling the Strings because
they fire the onPlotRevealed event to replicate the opponent plot. This
would lead to them triggering themselves and prompting the player to
choose order of resolution. However, by setting the controller to null,
any cards that modified the current plot (including simple ones like the
+1 gold from Roseroad) would start to produce errors.
By sending the plot card that is firing with the onPlotRevealed event,
it is now possible to trigger only that specific card's "When Revealed"
ability and is no longer necessary to disown cards that replicate other
plots.
Fixes #769.

"When Revealed" should fire per card not player.

---

server/game/cards/events/02/ineverbetagainstmyfamily.js
test/server/cards/characters/05/05014-serlancellannister.spec.js

Tries to reproduce #771 but fails. Still worthwhile to have some tests around Lancel though. Plus misc fix to a unusable prompt for Never Bet Against My Family when the player's deck is empty (edge case but came up in the tests).

Add tests for Ser Lancel Lannister.

---

server/game/cards/characters/02/serhobberredwyne.js
server/game/cards/characters/04/pyatpree.js
server/game/cards/characters/05/alerietyrell.js
server/game/cards/characters/06/margaerytyrell.js
server/game/cards/events/01/olennascunning.js
server/game/cards/events/04/bloodofmyblood.js
server/game/cards/locations/02/shadowblacklane.js
server/game/cards/locations/02/streetofsilk.js
server/game/cards/locations/02/streetofsteel.js
server/game/cards/plots/01/buildingorders.js
server/game/cards/plots/01/summons.js
server/game/cards/plots/02/heretoserve.js
server/game/cards/plots/03/atimeforwolves.js
server/game/game.js
server/game/gamesteps/decksearchprompt.js
test/server/gamesteps/decksearchprompt.spec.js

Implements a `promptForDeckSearch` method on `Game` to simplify the deck
searching process. The new prompt asks the player to choose a card based
on the number of cards and card condition matcher, then calls an
onSelect callback when they've chosen. Whether they choose a card or
cancel the prompt, the player's draw deck is automatically shuffled.
Converts all existing "search" cards to use the new prompt. "Look at X top/bottom cards" should NOT use this prompt and will need their own version.

Add a deck search prompt.

---

server/game/basecard.js
server/game/cards/agendas/therainsofcastamere.js
server/game/cards/attachments/03/greendreams.js
server/game/cards/characters/01/greenbloodtrader.js
server/game/cards/characters/05/tywinlannister.js
server/game/cards/characters/06/melisandre.js
server/game/cards/events/01/seeninflames.js
server/game/cards/events/01/thebearandthemaidenfair.js
server/game/cards/events/02/agiftofarborred.js
server/game/cards/events/02/ineverbetagainstmyfamily.js
server/game/cards/events/03/hisvipereyes.js
server/game/cards/events/05/aroseofgold.js
server/game/cards/locations/04/caswellskeep.js
server/game/cards/locations/07/queenscrown.js
server/game/cards/plots/05/summonedtocourt.js
server/game/gamesteps/decksearchprompt.js
server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/player.js
test/server/gamesteps/decksearchprompt.spec.js

Previously, when a menu prompt button was associated with a card, there
was a lot of repetition in that the text, argument and card summary were
almost always the same. Now, it is possible to just specify the card and
the other arguments are automatically filled in. If the `text` or `arg`
properties are specified, they will override the default card-generated
values.
Additionally, instead of sending the full card summary, only the
information used for card previews is sent to the client.

Simplify prompt buttons representing cards.

---

server/game/cards/attachments/02/kingrobertswarhammer.js
server/game/cards/characters/04/roosebolton.js
server/game/cards/events/01/consolidationofpower.js
server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/selectcardprompt.spec.js

Previously, cards that had a mechanism to select cards up to a combined
strength or cost (e.g. King Robert's Warhammer) were manually tracking
the sum by monitoring card selection being toggled. Now the select card
prompt supports this natively, allowing a `maxStat` function to be
passed to indicate what the maximum stat value is, and a `cardStat`
function to take a card and get the appropriate stat value for it (e.g.
strength).

Add support for "up to X stat" selection prompts.

---

server/game/basecard.js
server/game/drawcard.js
server/game/game.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js
server/game/spectator.js
test/server/card/basecard.spec.js
test/server/gamesteps/selectcardprompt.spec.js

Previously, the `selected` and `selectable` state for cards was stored directly on the card. This made it difficult to hide selection state from the opponent when their cards were selected or selectable (hence the `opponentSelected` flag). In the case of `selectable`, it was impossible to show the selecting player which opponent cards were selectable without also showing the opponent.
Now, the list of selected and selectable cards is stored directly on the player object doing the selection. This made it easy to only show selection state to that player, though it did require passing the full player object in the serializers instead of a boolean flag indicating 'active' player.

Fix selectable card state when selecting opponent cards.

---

server/game/cards/plots/04/battleoftheblackwater.js
server/game/player.js
test/server/player/removeattachment.spec.js

Battle of the Blackwater could trigger an infinite loop if the character
that has the dupe had been taken control from the opponent.
When removing attachments, if the dupe's owner is not the same as the
attachment's owner an infinite loop could occur. There's no scenario
under the current rules where this should be able to happen but we
should still protect against it.

Protect against loops when removing duplicates.

---

server/game/triggeredability.js
test/server/cards/events/06/06016-theprincesplan.spec.js

Non-hand event card abilities were broken when implementing the Annals
of Castle Black, as it was always checking that the event card was in a
playable locations. This prevented cards like The Prince's Plan from
triggering properly from discard pile.

Fix return to hand ability for The Prince's Plan.

---

client/Application.jsx
client/actions.js
client/reducers/games.js
server/game/anonymousspectator.js
server/game/basecard.js
server/game/game.js
server/gamenode/gameserver.js
server/lobby.js

* Ensures a player object is always sent to serializers, opening up the possibility of anonymous spectators in the future.
* No longer sends full game state when leaving a game - instead, sends a more targeted 'clear game state' command to that specific socket.

Ensure player object always sent to serializers

---

server/game/baseability.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/actionwindow.js
server/game/triggeredability.js
test/server/cards/characters/01/01183-randylltarly.spec.js
test/server/cards/characters/04/04025-dolorousedd.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/gamesteps/actionwindow.spec.js

Action windows will now automatically pass to the next player after the
current player has taken an action, as per the rules. Additionally, the
game now properly detects when an action is taken. Previously it only
understood when an event was played or a card was ambushed.

Implement proper action window flow.

---

server/game/basecard.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/player.js
test/server/card/basecard.spec.js
test/server/challenge/determinewinner.spec.js
test/server/challenge/removefromchallenge.spec.js
test/server/game/applygameaction.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/player/discardcards.spec.js

Provides infrastructure for #414 but does not implement immunity.
It is now possible to restrict an action from being taken on a card
based on restrictions placed on the card. As abilities are activated,
they are placed on a stack on `Game` to keep track of the current
ability's source card. When a game action is applied to a card (e.g.
being killed, discarded, knelt, etc), the card checks through the list
of restrictions to see if that particular action coming from the source
card is allowed. This provides the necessary infrastructure to implement
both immunity abilities as well as conditional 'cannot' effects (e.g.
Ygritte).
To make checking these restrictions more convenient, a `applyGameAction`
method is provided on `Game` that will only apply an action to eligible
cards.

Allow actions to be restricted per card.

---

server/game/cannotrestriction.js
server/game/cards/attachments/02/fishingnet.js
server/game/cards/attachments/04/craven.js
server/game/cards/characters/01/ghost.js
server/game/cards/characters/02/hodor.js
server/game/cards/characters/02/ladyinwaiting.js
server/game/cards/characters/02/winterfellkennelmaster.js
server/game/cards/characters/04/kingrenlyshost.js
server/game/cards/characters/05/trystanemartell.js
server/game/cards/characters/06/wexpyke.js
server/game/cards/characters/06/ygritte.js
server/game/cards/characters/07/rattleshirt.js
server/game/cards/characters/07/saltwife.js
server/game/cards/locations/03/theshadowtower.js
server/game/cards/plots/02/wardensofthenorth.js
server/game/cards/plots/04/battleofoxcross.js
server/game/costs.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/marshalcardaction.js
server/game/playcardaction.js
test/server/card/drawcard.usestealthtobypass.spec.js
test/server/cards/characters/06/06017-ygritte.spec.js
test/server/marshalcardaction.spec.js
test/server/playcardaction.spec.js

Continuing on #414, adding the ability to have conditional 'cannot's (e.g. Ygritte)
Reworks the rest of the card-level cannot effects to use restrictions instead of boolean flags.
Also renames the poorly named allowAsAttacker/Defender effects to cannotDeclareAsAttacker/Defender.

Add conditional 'cannot' restrictions + Ygritte's ability

---

server/game/basecard.js
server/game/cards/attachments/04/dragonglassdagger.js
server/game/cards/characters/02/maesterluwin.js
server/game/cards/characters/02/septamordane.js
server/game/cards/characters/03/bearislandloyalist.js
server/game/cards/characters/04/craster.js
server/game/cards/locations/02/pleasurebarge.js
server/game/cards/locations/02/smallcouncilchamber.js
server/game/cards/locations/03/winterfellheartree.js
server/game/cards/plots/02/atourneyfortheking.js
server/game/effect.js
server/game/effects.js
server/game/immunityrestriction.js
test/server/effect.spec.js
test/server/integration/immunity.spec.js

* Finishes implementations for cards that were just missing immunity.
* Adds full implementations of Winterfell Heart Tree, Bear Island
Loyalist, A Tourney for the King.
* Adds a partial implementation of Craster for his immunity effect.
Completes #414.

Implement immunity restriction and cards.

---

server/game/cards/locations/01/theredkeep.js
server/game/cards/locations/04/thehauntedforest.js
server/game/challenge.js
server/game/effects.js
test/server/cards/locations/01/01061-theredkeep.spec.js

* Adds a `contributeChallengeStrength` effect.
* Converts The Red Keep and Haunted Forest to use the new effect to ensure blanking / removing characters from a challenge removes the effect where appropriate.
Fixes #858.
Fixes #697.

Implement Red Keep and Haunted Forest using effects

---

server/game/baseability.js
server/game/cardaction.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/eventwindow.js
server/game/playcardaction.js
server/game/triggeredability.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/playingevents.spec.js
test/server/playcardaction.spec.js

* Ensures the onCardPlayed event is raised for events implemented via the legacy `play` method and through the ability API (including actions and reactions/interrupts).
* Ensures that additional event card abilities such as return-to-hand-from-discard do not count as playing an event.
* Removes the now unused onCanceled handler from the event window.

Make the onCardPlayed event more consistent.

---

server/game/effect.js
server/game/effectengine.js
test/server/effect.spec.js
test/server/effectengine.spec.js
test/server/integration/effects.spec.js

Previously, blanked effects continued to track the targets they were
applied to. However, it did not check the condition for the effect when
it was unblanked. This lead to crashes when unblanked while the
condition was no longer valid and the effect was dynamically calculated.
For example, it would try to apply Jhogo's strength bonus outside a
challenge if blanked during a challenge, leading to a crash.
Now, blanking is handled similar to conditional effects in that all
targets are removed when blanked, then targets are added back from
scratch when unblanked.
Fixes #771 
Fixes #689

Fix unblanking conditional dynamic effects.

---

server/game/baseability.js
server/game/cardaction.js
server/game/cards/characters/01/branstark.js
server/game/cards/events/01/thehandsjudgment.js
server/game/gamesteps/abilityresolver.js
server/game/marshalcardaction.js
server/game/playcardaction.js
test/server/gamesteps/abilityresolver.spec.js

Previously, only Action abilities and event cards implemented using the
legacy `play` method raised the event to indicate an ability effects
were being applied. Now, this event is raised for all card abilities
(pretty much everything except marshaling) when they are executed by the
AbilityResolver class. The event has been renamed from
onBeforeCardPlayed to onCardAbilityInitiated to better reflect what it
represents.

Make ability initiation event more consistent.

---

server/game/gamekeywords.js
server/game/gamesteps/challenge/challengeflow.js
server/game/insightkeyword.js
server/game/intimidatekeyword.js
server/game/pillagekeyword.js
server/game/renownkeyword.js

Separates out post-challenge keywords into ability classes. This will
allow more consistent handling of immunity to keywords (e.g. Dragonglass
Dagger vs intimidate) and clears the way for choosing the order of
keyword resolution and optional keywords.

Implement challenge keywords as abilities.

---

test/server/integration/effects.spec.js

The until end of phase vs at end of phase test is explicitly checking
the winner, but did not have enough cards in the deck to prevent the
draw deck from becoming empty. When it became empty, the wrong winner
was being declared. Now the test has enough cards in it to prevent from
being decked, they're just not used in the test for any other purpose.

Prevent being decked in test checking winner.

---

server/game/cards/locations/07/plazaofpride.js

Due to a typo in the used attribute name, before this change the message of
Plaza of Pride did not log the name of the card that was discarded to pay its
cost.

bug fix: avoid null discarded card in Plaza of Pride message

---

server/game/anonymousspectator.js
server/game/basecard.js
server/game/player.js
server/game/playerpromptstate.js
server/game/spectator.js
test/server/card/basecard.spec.js

Consolidates selection state to a single `getCardSelectionState` method
instead of individual methods checking for pieces of selection state.
Also extracts player prompt state logic to its own class.
(This is prep work for ordering prompts, which is going to add another property - `order` - to selection state)

Separate player prompt state to another class.

---

client/GameComponents/Card.jsx
less/cards.less
server/game/game.js
server/game/gamesteps/killcharacters.js
server/game/gamesteps/selectcardprompt.js
server/game/gamesteps/simultaneouseventwindow.js
server/game/playerpromptstate.js
test/server/cards/plots/04/04080-valarmorghulis.spec.js
test/server/gamesteps/simultaneouseventwindow.spec.js

* Adds an `ordered` property to selection prompts that will display numbers above the cards selected to indicate the selection order.
* When two or more characters are killed, the player is prompted to select the order to place the characters in the dead pile (top-most card first). If only one card is killed, the player will not receive the prompt. If the player clicks 'Done' after selecting the order for some cards but not all of them, it won't continue. If the player clicks 'Done' without selecting any of the cards, it will place them in the dead pile from left to right automatically (right card being top-most).
* Because killing characters was getting more complicated, it has been moved to its own game step class and off of `Game`.

Prompt for dead pile order when multiple characters killed.

---

server/game/playcardaction.js
test/server/playcardaction.spec.js

Previously, legacy event cards were being placed in discard as part of
their handler. However, if the effects of the event were cancelled, the
event would not be placed in discard. Now, placing in discard is
considered part of the cost as it is with events defined using the
ability API.

Ensure legacy events placed in discard.

---

server/game/gamesteps/triggeredabilitywindowtitles.js

Previously, the prompts for cards like Hand's Judgment and Treachery
were not clear on which card they were interrupting. Now, the name of
the card whose effects are being applied is displayed in the prompt.

Add prompt title for effect cancels.

---

server/game/gamesteps/simultaneouseventwindow.js
test/server/gamesteps/simultaneouseventwindow.spec.js

Previously, if a kill was canceled during a simultaneous kill window, it
would continue to try to fire events for that card. However, the card's
event had already been removed from the window, leading it to try and
open an ability window for an undefined / null event object.
Fixes THRONETEKI-SX
Fixes THRONETEKI-T0
Fixes THRONETEKI-SV
Fixes THRONETEKI-T2

Fix simultaneous event window crash

---

less/cards.less

With the addition of greying out unselectable cards, the pulse effect on
selectable cards is less necessary. The animation is not very
performant, so dropping it should help client side rendering
performance. The glowing shadow effect for selectable cards is still
retained to make select prompts clear in IE versions that do not support
the grey scale effect.

Remove pulse effect from selectable cards.

---

server/game/player.js
test/server/integration/setup.spec.js

Attachments placed during setup were having their effects doubled in at
least some cases, because the effects were registered with the engine
twice - once when placed facedown, then again when attached. Now,
effects are only registered once for attachments when they're actually
attached.
Fixes #833.

Fix doubling of effects from setup attachments.

---

server/game/basecard.js
server/game/cards/locations/01/theironthrone.js
server/game/drawcard.js
server/game/effects.js
server/game/player.js

Removes the legacy `modifyDominance` reducer method in favor of an
effect that modifies how much strength a card provides towards
dominance. Also moves the logic of how dominance strength is calculated
onto the DrawCard class.

Convert Iron Throne to effect API.

---

server/game/cards/characters/02/brothelmadame.js

The doNotPay method, called by the "No" dialog button was simply missing.
This change adds it, together with a suitable game log message.

fix Brothel Madame to not hang upon refused payment

---

server/game/basecard.js
test/server/card/basecard.spec.js

Per the rules, cards that "are not affiliated with any faction" are
considered neutral. Thus, a neutral card that has gained an affiliation
via cards like Ward or Sworn to the Watch are no longer considered
neutral. This distinction is mildly important for cards like Tithe which
require kneeling a neutral card as a cost.

Gaining faction affiliation loses neutrality.

---

server/game/cards/attachments/01/bodyguard.js
server/game/cards/attachments/01/drogosarakh.js
server/game/cards/attachments/01/heartsbane.js
server/game/cards/attachments/01/sealofthehand.js
server/game/cards/attachments/02/lady.js
server/game/cards/attachments/02/mareinheat.js
server/game/cards/attachments/03/motley.js
server/game/cards/attachments/03/nymeria.js
server/game/cards/attachments/04/beggarking.js
server/game/cards/attachments/04/crownofgoldenroses.js
server/game/cards/attachments/04/dragonglassdagger.js
server/game/cards/attachments/04/kingbeyondthewall.js
server/game/cards/attachments/04/kingofsaltandrock.js
server/game/cards/attachments/04/motherofdragons.js
server/game/cards/attachments/04/theboyking.js
server/game/cards/attachments/04/thewolfking.js
server/game/cards/attachments/04/venomousblade.js
server/game/cards/attachments/05/disputedclaim.js
server/game/cards/attachments/06/lightofthelord.js
server/game/cards/attachments/07/ghost.js
server/game/cards/attachments/07/weirwoodbow.js

As part of this, also uniform the canAttach() test so that checking for card
type comes first in the test.
Fixes #830

make sure non-location attachments can only be placed on characters

---

server/game/baseability.js
server/game/cardaction.js
server/game/cards/events/01/ameagercontribution.js
server/game/cards/events/01/likewarmrain.js
server/game/cards/events/01/puttothesword.js
server/game/cards/events/01/puttothetorch.js
server/game/cards/events/01/superiorclaim.js
server/game/cards/events/01/taketheblack.js
server/game/cards/events/01/winteriscoming.js
server/game/cards/events/04/thereismyclaim.js
server/game/costs.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/player.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/cards/cancreatecards.spec.js
test/server/gamesteps/triggeredabilitywindow.spec.js
test/server/integration/eventmaximums.spec.js

* Adds `max` property to implement maximums per card title. Uses the same objects as the `limit` property.
* Uses the new property on all event cards that have been implemented via the ability API.
* Does NOT add the restriction to event cards implemented via the legacy `canPlay` / `play` mechanism. This should be done when those cards are converted.
* As a UI nicety, if the player has multiple max-restricted cards in hand, the prompt they see will only have one button.

Implement 'Max X per period' ability restrictions.

---

server/game/cards/locations/01/dothrakisea.js

`context.card` is not a thing.
Fixes THRONETEKI-TH

Fix Dothraki Sea

---

server/game/cards/events/02/vengeanceforelia.js
test/server/cards/events/02/02096-vengeanceforelia.spec.js

Vengeance for Elia changes who claim is applied to but not who is
considered to win the challenge. Thus, if it is played on a power
challenge, Vengeance will cause power to be transfered from the winner
of the challenge to themself, thus no power is gained or lost by either
player.
Fixes #940.

Vengeance for Elia shouldn't transfer power

---

server/game/cards/events/06/adragonisnoslave.js

... even we do not have 3 golds (i.e., event cost + reaction cost). One gold
should be enough to trigger, so we have to ignore *event* cost.

fix A Dragon Is No Slave so that it triggers from the discard pile

---

server/game/cards/locations/03/winterfell.js

Previously, Winterfell was not kneeling because the `cost` property was
typoed as `costs` (plural). However, in the case of Winterfell, kneeling
is not a cost for the ability; it is a pre-then effect. Thus, if
Winterfell is canceled through cards like Treachery, it will not kneel.
The implementation now reflects this.
Fixes #950.

Kneeling Winterfell is an effect, not a cost.

---

server/game/basecard.js
server/game/forcedtriggeredability.js
server/game/game.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/cards/agendas/05045-therainsofcastamere.spec.js
test/server/integration/nestedabilitysequences.spec.js

Previously, if an ability triggering brought a card into play or into
hand that should be playable, the new card wouldn't trigger because the
appropriate event listeners weren't bound when the original event
occurred. Now, when a card is moved to a location it would listen to
events, it registers its abilities with the Game object, which will add
the abilities to any prompts that are already open. This allows
interactions such as triggering Rains of Castamere to play Wardens of
the West, or allowing an event card drawn mid-reaction to be playable if
that ability window is still open.
Fixes #245.

Allow abilities to trigger when they enter play.

---

server/game/cards/events/06/thedornishmanswife.js

Instead of building up a long string, pushing "hits" to an array allows existing methods to take care of proper punctuation

Improve messaging for The Dornishman's Wife

---

server/game/player.js
test/server/integration/marshalphase.spec.js
test/server/player/getduplicateinplay.spec.js

Previously, if the opponent placed a unique attachment on one of your
cards and you attempted to play the same attachment, it would improperly
be placed as a duplicate on top of the opponent's copy. Additionally,
the opponent could place multiple copies of that attachment instead of
it automatically duplicating the original.
Fixes #967.

Properly handle unique attachments on opponents.

---

server/game/cards/characters/06/melisandre.js
server/game/cards/events/01/seeninflames.js
server/game/cards/events/03/hisvipereyes.js
test/server/integration/playingevents.spec.js

Now that cancel abilities are implemented, it is no longer necessary to
ask the opponent whether to reveal their hand or not - the cancel will
prompt before the reveal happens.

Remove permission prompts from reveal hand cards.

---

server/game/challenge.js

Great Kraken and other abilities were triggering inappropriately when a
challenge was won with the attacker at 0 strength. Only challenges
ending with 0 defending strength count as unopposed, so the attacker
must be the winner.
Fixes #906.

Only attackers can win unopposed.

---

server/game/effectengine.js
server/game/player.js
test/server/integration/takecontrol.spec.js

Previously, if a card was put into play under another player's control
(e.g. through Euron's ability), effects were being applied before the
control change occurred. Thus, the effects would be applied to the
opponent and not the player taking control.
Fixes #711 
Fixes #845 
Fixes #906 
Fixes #924

Apply effects after the controller is set.

---

server/game/cards/attachments/01/dawn.js
server/game/cards/attachments/01/littlebird.js
server/game/cards/attachments/01/longclaw.js
server/game/cards/attachments/01/milkofthepoppy.js
server/game/cards/attachments/01/noblelineage.js
server/game/cards/attachments/01/syriostraining.js
server/game/cards/attachments/01/widowswail.js
server/game/cards/attachments/02/attainted.js
server/game/cards/attachments/02/condemned.js
server/game/cards/attachments/02/drownedgodsblessing.js
server/game/cards/attachments/02/imprisoned.js
server/game/cards/attachments/02/kingrobertswarhammer.js
server/game/cards/attachments/02/knighted.js
server/game/cards/attachments/03/greendreams.js
server/game/cards/attachments/04/craven.js
server/game/cards/attachments/04/redgodsblessing.js
server/game/cards/attachments/05/shieldoflannisport.js
server/game/cards/attachments/06/marriagepact.js
server/game/cards/attachments/07/sworntothewatch.js

This change should fix all other (current) instances of bugs like #970.

make all (non-location) attachments check target card is a character

---

server/game/cards/characters/01/stannisbaratheon.js
server/game/effects.js
server/game/gamesteps/standingphase.js
server/game/player.js
test/server/cards/characters/01/01052-stannisbaratheon.spec.js

Moves the logic for the stand phase off of player and into the
StandingPhase class. Core Stannis is now implemented by adding a
'standing phase restriction' to each player that filters out character
cards from automatically standing.
Additionally, the player is now required to select 2 cards to stand if
they have more than 2 cards. Previously it was implemented as 'up to 2
cards' but standing during the standing phase is mandatory.
Finally, if the player has less than the stand maximum, all cards will
be stood automatically with no player selection.

Convert Core Stannis to an effect.

---

server/game/basecard.js
server/game/cards/characters/06/recruiterforthewatch.js
server/game/effect.js
server/game/effectengine.js
server/game/effects.js
server/game/gamesteps/standingphase.js
test/server/cards/agendas/01027-fealty.spec.js
test/server/cards/characters/01/01052-stannisbaratheon.spec.js
test/server/cards/characters/06/06045-recruiterforthewatch.spec.js
test/server/effectengine.spec.js

* Adds an 'optional stand' effect that allows the player to choose whether or not to stand affected cards during the standing phase.
* Ensures that if a card is explicitly selected in the standing phase (e.g. through Core Stannis) that the player will not be prompted to stand the character.
* Adds the ability to do lasting effects with custom durations using the `lastingEffect` method. An `until` property is specified with event listeners, similar to the way `when` works for reactions / interrupts.
* Putting it all together, implements Recruiter for the Watch.

Implement Recruiter for the Watch

---

server/game/cards/events/02/funeralpyre.js

Funeral Pyre should trigger when any Lord/Lady is killed, not just controlled by yourself

Fix Funeral Pyre

---

server/game/cards/attachments/07/catapultonthewall.js
server/game/costs.js

As noted (at least as far as I could figure out), there's not really a clean way to include kneeling the attached character as part of the cost of using the attachment action.  `ability.costs` needs another / updated kneel method to allow for this.  Certainly something I could do / we might consider, as I'm sure more costs like this are coming, but as I'm probably the least familiar with the code and gameflow, I figured I would just do the quick and dirty implementation.

Implement Catapult on the Wall.

---

server/game/cards/events/03/thepacksurvives.js
server/game/costs.js
server/game/costs/choosecost.js

Implements a choose cost that allows the player to choose which cost
they want to pay on a card. Useful for cards like The Pack Survives and
I Shall Win No Glory which give players an 'or' choice. If only one cost
is able to be paid, it will pick that cost automatically. If multiple
costs are payable, the player will be prompted to choose which they wish
to pay.

Implement `choose` cost.

---

server/game/gamesteps/challenge/challengeflow.js

Previously, using /cancel-prompt during a challenge would not just
cancel the current prompt as intended but cancel the entire challenge.
This lead to situations where cleanup of reaction / interrupt windows
was inappropriately canceled, causing crashes when a card with that
event handler came into hand or into play.
Example: a "when you win/lose a challenge" ability would be prompted.
The player uses /cancel-prompt instead of clicking on 'Pass.' The player
later draws an event card that triggers when winning/losing a challenge.
The game potentially crashes if that card expects there to be an active
challenge.
Now, /cancel-prompt will appropriately only cancel the current prompt,
not the entire challenge.
Fixes THRONETEKI-VN
Fixes THRONETEKI-V7
Fixes THRONETEKI-V6

Fix /cancel-prompt during challenge.

---

server/game/cards/plots/06/wheelswithinwheels.js

Took a stab at this weird card, couple of notes:
* Cards are dumped in the discard pile before being "officially" revealed through a chat message. This is not ideal, though to get the ever-decreasing prompt we want for effects like these I needed to move them somewhere, and discard pile makes the most sense here to me.
* The prompt does not show duplicates. That is preferable for a card like Summons, a bit less so for this one. If you hit a duplicate, you won't know it at first, though you find out after selecting them (since the card will just keep showing in the prompt until all duplicates have been moved to the discard pile). Not a huge deal though.
* I'm quite sure that if you would manage to hit 10 events, it won't resolve correctly since you won't get the chance to choose Done. …

Implement Wheels Within Wheels

---

server/game/cards/locations/04/thegodseye.js
server/game/effects.js

Note that this assumes that all possibilities of discarding The God's Eye from
play are via the engine effect. As far as I understand this should be the case
right now, but @ystros might want to double-check that.

add effect cannotBeDiscarded and use it to immunize The God's Eye

---

server/game/cards/characters/02/serhobberredwyne.js
server/game/cards/characters/04/pyatpree.js
server/game/cards/characters/05/alerietyrell.js
server/game/cards/characters/06/margaerytyrell.js
server/game/cards/characters/07/castleblackmason.js
server/game/cards/events/01/olennascunning.js
server/game/cards/events/02/supportofthepeople.js
server/game/cards/events/02/thewatchhasneed.js
server/game/cards/events/02/wolfdreams.js
server/game/cards/events/04/bloodofmyblood.js
server/game/cards/locations/02/shadowblacklane.js
server/game/cards/locations/02/streetofsilk.js
server/game/cards/locations/02/streetofsteel.js
server/game/cards/plots/01/buildingorders.js
server/game/cards/plots/01/summons.js
server/game/cards/plots/02/heretoserve.js
server/game/cards/plots/03/atimeforwolves.js
server/game/cards/plots/06/wheelswithinwheels.js

Before this change, when no card was found (or chosen) by the user, tutoring
completed with messages "FOO does not use BAR to ...", which is misleading
given the player did use the card, but did not find (or choose) any card. With
this change this is replaced by message like "FOO uses BAR, but does not ...".
Also, this change uniform tutoring so that there is a single message about
tutoring outcome, rather than more than once for some weird cards.
Finally, this change also drops the explicit use of the verb "reveal", which
was redundant given that tutoring success messages always name cards,
"revealing" them to the opponent already.

improve and uniform game messages for all tutoring cards

---

server/game/cards/attachments/07/summer.js
server/game/player.js

The 'attach to a different character' handler is a little bit awkward, but I didn't want to just invoke player.attach() since that raises onCardEntersPlay, or player.putIntoPlay(), which would prompt for a parent where the old parent would be made a legal choice (and invokes player.attach() itself anyway).

Implement Summer (WotW)

---

server/game/gamesteps/challenge/fulfillmilitaryclaim.js

Previously, when no characters where forced to be chosen for claim, a "is automatically chosen for claim"-message would be displayed. Checking if there's any cards in forcedClaim before displaying the message fixes that.

Fix forced claim messaging

---

server/game/cards/events/04/burningonthesand.js
server/game/effects.js
server/game/game.js
server/game/plotcard.js

* Fixes #1062 
* This has some wonky interactions with the claim modification buttons in the client, as illustrated by the pasted game chat below. Nothing game-breaking though.
```
user1 is initiating a  challenge
user1 has initiated a  challenge with strength 2
DukeTax does not defend the challenge
user1 uses Winter Is Coming to raise the claim value on their revealed plot card by 1 until the end of the challenge
user1 won a  challenge 2 vs 0
DukeTax plays Burning on the Sand to set the claim value on user1's revealed plot card to 0 until the end of the challenge
//Here I press the + Claim button three times. Claim remains 0 on the indicator, though chat messages don't correspond
user1 sets claim to 2 (+1)
user1 sets claim to 3 (+1)
user1 sets claim to 4 (+1)
user1 has gained 1 power …
```

Implement Burning on the Sand

---

server/game/cards/characters/04/dolorousedd.js
server/game/cards/characters/04/spearmaiden.js
server/game/cards/locations/05/oldwyk.js
server/game/effects.js

* Previously, Old Wyk made use of a lasting effect until the end of the challenge to resolve its effect. This was incorrect as its ability should resolve after the winner is determined, but before any reactions, similar to Dolorous Edd or Spearmaiden.
* Checking if there's any Drowned God characters in the dead pile before prompting to trigger the reaction prevents triggering it without any change in game state.

Fix Old Wyk

---

client/GameBoard.jsx
client/GameComponents/AdditionalCardPile.jsx
client/GameComponents/PlayerRow.jsx
server/game/cards/agendas/therainsofcastamere.js
server/game/player.js
test/client/GameBoard.spec.jsx
test/server/cards/agendas/05045-therainsofcastamere.spec.js

Removes the presentational concerns of 'area' and 'title' for Scheme and
Out of Game piles from the backend and moves them to the client side.

Handle layout for additional piles client side.

---

server/game/cards/characters/05/redkeepspy.js
server/game/cards/characters/06/orphanofthegreenblood.js
server/game/cards/events/01/thethingsidoforlove.js
server/game/cards/events/05/daringrescue.js

This propagates the fix done in 7c37a0d8e62ea05ca4cda5cc7669959c164ed0ae for
Scaling the Wall to other cards that should behave similarly with respect to
save by duplicates.

allow saves for all (savable) "return to hand" effects

---

server/game/effect.js
server/game/effectengine.js
server/game/effects.js
test/server/integration/burneffects.spec.js

Previously, the order burn effects were applied was determined by the
order of players joining the game plus the order that the burn effect
came into play. This lead to bugs where a card both buffed by one card
and burned by another was killed because the burn effect happened first.
Now, the `killByStrength` effect is explicitly ordered to be applied
after other effects so that cards aren't killed inappropriately.
Fixes #868.
Fixes #966.
Fixes #543.

Prevent premature kills from burn effects.

---

server/game/basecard.js
server/game/cards/events/03/aryasgift.js
server/game/effectengine.js
server/game/player.js
test/server/cards/events/03/03024-aryasgift.spec.js
test/server/player/removeattachment.spec.js

Previously, when an attachment was re-attached from one card to another,
it would leave its effect on the original parent in addition to applying
it to the new parent. Now, effects are removed immediately when the
parent changes, and effects are applied to the new parent asynchronously
after the move has completed.
Fixes #1097

Properly remove / apply effects during reattach.

---

server/game/player.js
test/server/cards/attachments/06022-marriagepact.spec.js

Previously, when a card would leave play it would remove attachments and
dupes from the card prior to interrupts firing. This caused a bug where
Marriage Pact's forced interrupt would not fire because it was detached
from the parent before the parent started to leave play.
Now, all interrupts fire for the card leaving play, then attachments and
dupes on the card leave play, then reactions to the card leaving play
fire.
Fixes #1052

Fix ordering of leaves play events / effects.

---

server/game/game.js
server/game/gamesteps/phase.js

Previously, effects were only recalculated when user input was required.
This could lead to bugs with effect recalculation during long periods
that may not have any user input - e.g. from the end of the challenges
phase to the beginning of the taxation phase if both players had those
windows off. The biggest example being lasting effects that only applied
during the standing phase (Stannis TIMC, etc). Now effects are
explicitly recalculated at the beginning of each phase.

Explicitly recalculate effects at phase start.

---

server/game/cards/attachments/07/catapultonthewall.js
server/game/cards/characters/04/stannisbaratheon.js
server/game/cards/events/06/savingthekingdom.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/standingphase.js

Previously, effects that made cards unable to stand during the standing phase were implemented by setting and checking a flag during the mandatory standing in the standing phase. This worked fine for the majority of use cases, but it still wrongly allowed cards to be stood during the standing phase by for example a card like Magister Illyrio. This PR fixes that by porting these implementations to true cannot effects.
Needs #1109

Convert 'cannot stand during standing' to true cannot effect

---

server/game/drawcard.js

Per this change to the JSON data format, cards that have X strength like
Dacey Mormont and Beric Dondarrian are represented with a NULL strength.
https://github.com/Alsciende/thronesdb-json-data/pull/160/commits/b5982faf8126c4f030af26dc71d28150f235983b
Such cards were not displaying their strength at all because the
serializer was always sending strength 0 even if the strength was
boosted through effects. Now, the printed strength and current strength
are fully calculated regardless of whether the JSON field is null. This
should ensure strength is always displayed properly. It should not
affect location and attachment cards, as their strength was already
being sent as 0 and `DrawCard.getStrength` now always returns 0 if
strength is not defined.
Fixes #1131.

Handle characters with null strength.

---

server/game/game.js
test/server/cards/agendas/05045-therainsofcastamere.spec.js

Previously, if a card with an interrupt ability entered play during the
window for reactions (e.g. reveal The Red Wedding with Rains of
Castamere), the player would be inappropriately prompted. Now, the
ability type for abilities are checked against the ability type for any
open windows.
Fixes #1118

Do not let abilities trigger in the wrong window.

---

server/game/player.js
test/server/integration/takecontrol.spec.js

Previously, cards that were taken control by putting them directly into
play under the new controller (e.g. marshalling via Night Gathers) did
not add the card to the `allCards` array for that player. This lead to
bugs where the card was clearly in play, but checks that used
`filterCardsInPlay` would fail. Now, the `putIntoPlay` method moves the
card to the `allCards` array the same way that the `takeControl` method
previously did.
Fixes #795.

Ensure take control adds card to `allCards` array.

---

server/game/cards/characters/06/eastwatchcarpenter.js

Previously, Eastwatch Carpenter would prompt even when triggering it would result in no extra gold. This PR fixes that, and also checks for the number of locations in a more desired way.

Only prompt Eastwatch Carpenter when there is gold to gain

---

server/game/triggeredability.js
test/server/cards/plots/06/06040-theannalsofcastleblack.spec.js

Previously, Annals of Castle Black would not allow event interrupts /
reactions to trigger from discard. This is because event listeners were
only ever bound if the card was in the expected location - in the case
of event cards, in hand.
Now, interrupts / reactions listen to events in all open information
locations plus while in hand. Since the `location` property restricts
whether the ability actually fires, abilities should not activate while
in inappropriate locations even if it listens to events.
Fixes #1048.

Trigger reaction events for Annals of Castle Black.

---

client/GameComponents/ActionWindowsMenu.jsx
client/Profile.jsx
server/game/gamesteps/challengephase.js

Previously, there was a "Challenge phase begins" window that
corresponded to the action window in the challenge phase before the
first challenge. This option has been renamed to "Before challenge" to
better match up with the rules and will now prompt before / after each
challenge in accordance with the RRG.
Fixes #1149.

Implement pre-challenge windows.

---

server/game/cards/attachments/02/lady.js
server/game/cards/attachments/03/nymeria.js
server/game/cards/attachments/07/summer.js
server/game/cards/events/01/risenfromthesea.js
server/game/cards/events/02/bloodmagicritual.js
server/game/cards/events/03/aryasgift.js
server/game/drawcard.js
server/game/gamesteps/attachmentprompt.js
server/game/player.js
test/server/cards/events/03/03024-aryasgift.spec.js
test/server/player/removeattachment.spec.js

Also stops passing around UUIDs when attaching cards, instead passing the object directly.
Fixes #1138.

Remove attachments from previous parent on reattach.

---

server/game/cards/plots/02/wardensofthewest.js

Previously, Wardens of the West was manually moving cards into discard,
which should only be done when an ability says "place" the cards in
discard. It now uses the proper `discardCards` method to ensure LoCR
Cersei can gain power off the ability.

Use proper discard for Wardens of the West.

---

server/game/cards/locations/01/ghastongrey.js

* Similar to #1156, a taken control of Ghaston Grey asked its owner to return an attacking character to its owner's hand (caused by the card being in its owner's discard pile after sacrificing). Converting this card to the target API should fix that.
* Invoking the correct method for returning a character to hand makes sure the game action is allowed.

Prompt proper player for resolution of Ghaston Grey

---

server/game/drawcard.js

Before this change locations could --- in corner cases where challenge icones
are ignored, e.g., when Ours Is The Fury is triggered --- be allowed to be
selected as cards that can participate in challenge.

make sure that canPartecipateInChallenge() succeeds only on characters

---

server/game/cards/locations/02/ironmines.js
test/server/integration/takecontrol.spec.js

Because Iron Mines sacrifices itself as a cost to activate, it is placed
in its owner's discard pile before the target for the save is prompted.
This means that the controller has reverted to the original owner by the
time targeting happens. This caused a bug where a taken-control-of Iron
Mines would trigger if any of your characters were killed, but then
would only allow you to use it to save your opponent's characters.
Now, Iron Mines explicitly compares the target's controller with the
player that activated the ability.

Save cards for ability activator for Iron Mines.

---

server/game/effects.js
test/server/cards/plots/06/06040-theannalsofcastleblack.spec.js

Because each player gets applied with the effect from Annals of Castle
Black, the playable location must be associated with a specific player.
Previously it was using the same variable for all players, which caused
the effect to not be removed from the first player during two player
games.

Properly remove Annals of Castle Black effect.

---

server/game/cards/characters/01/oldforesthunter.js
server/game/cards/characters/01/tyrionlannister.js
server/game/cards/characters/05/devoutfreerider.js
server/game/cards/events/02/indoransname.js
server/game/cards/events/06/plunder.js
server/game/cards/plots/05/lionsoftherock.js
server/game/effects.js
server/game/game.js
server/game/player.js

Not entirely sure if this is the desired way, but..... it works I guess. I don't really like the additional checks on other cards to prevent trigger prompts, but it's only a handful (and even then it's 95% Tyrion Lannister (Core)).
Other slight issue: there are a bunch of cards that transfer gold implemented by invoking game.addGold() twice, instead of just game.transferGold(), which could be prevented from resolving correctly by Devout Freerider. It's on the list for when I go through the entire cardpool.

Implement Devout Freerider

---

server/game/cards/characters/07/maryaseaworth.js
server/game/challenge.js
server/game/game.js
server/game/gamesteps/atomiceventwindow.js
server/game/gamesteps/baseabilitywindow.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/challenge/choosestealthtargets.js
server/game/gamesteps/forcedtriggeredabilitywindow.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/triggeredability.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/cards/agendas/05045-therainsofcastamere.spec.js
test/server/gamesteps/forcedtriggeredabilitywindow.spec.js
test/server/gamesteps/triggeredabilitywindow.spec.js
test/server/integration/challengesphase.spec.js

Combines the interrupt / reaction windows for challenge initiation, attackers declared and bypasses by stealth into a single window per the timing note under RRG 4.2. This is done by introducing an 'atomic' event type, which takes multiple events and raises them within the same window.
Fixes #1047.

Combine windows during challenge initiation

---

client/ReduxActions/deck.js
server/game/game.js
server/game/player.js

Pass the deck name when saving it as stats use it.  Patch existing decks which don't have a faction name with value - will require fixing in stats too later

Pass the deck name when saving it

---

client/Application.jsx
client/GameBoard.jsx
client/ReduxActions/socket.js
client/reducers/socket.js

That way the next time a game is played there isn't a socket hanging around listening to events eg if the game node restarts or connection is lost.  Should fix the issue where games seem to 'hang'

C;ose the game socket after a game is played

---

server/game/cards/characters/07/jonsnow.js

The previous implementation of Jon Snow was a little bit confusing. This one removes the choice and prevents accidental misclicks, at the cost of not being able to stand your opponent's characters, with which I'm completely fine.

Remove choices from Jon Snow (Watchers on the Wall)

---

client/GameBoard.jsx
less/gameboard.less
server/game/deck.js
server/game/player.js

Adds a popup when clicking the Alliance agenda that will display the
banner cards selected for the deck.

Show Alliance banner cards under agenda card

---

server/game/gamesteps/triggeredabilitywindow.js
test/server/gamesteps/triggeredabilitywindow.spec.js
test/server/integration/eventmaximums.spec.js

Previously, if a copy of a card with a maximum limit was in the discard
pile, the player would not be prompted to trigger that card if they had
another copy in hand. This was because the copy in discard would
register with the prompt first, preventing any other copies from being
registered. Then, when the prompt activated it saw that the registered
copy was in discard and therefore couldn't be triggered.
Instead of preventing multiple copies from being registered, it is now
filtered when the prompt is generated and presented to the player.
Fixes #1172.

Fix prompts for cards with maximum limits.

---

server/game/game.js
server/game/player.js
test/helpers/integrationhelper.js
test/server/integration/takecontrol.spec.js
test/server/player/putintoplay.spec.js

The checks applied to putting unique cards into play were not being
checked on take control. Thus, players were able to take control of
cards in their dead pile. Additionally, checks were not being made that
an opponent had taken control of your card, allowing players to put out
a new copy of a unique card already stolen by the opponent.
Fixes #1170.

Fix uniqueness checks for take control.

---

server/game/cards/agendas/therainsofcastamere.js
server/game/gamesteps/plotphase.js
server/game/player.js
test/helpers/playerinteractionwrapper.js
test/server/cards/agendas/05045-therainsofcastamere.spec.js
test/server/cards/plots/07/07047-retaliation.spec.js
test/server/integration/takecontrol.spec.js
test/server/player/flipplotfaceup.spec.js

Because plots were being removed and revealed in the same game step, the unapply of effects from the active plot could occur after the effects of the new plot. Thus in cases where the same plot was revealed twice, it could end up unapplying the effect of the new plot as well (e.g. Retaliation not working when revealed twice).
Fixes #1165

Remove plots before revealing new ones

---

server/game/cards/attachments/02/lady.js
server/game/cards/attachments/03/nymeria.js
server/game/cards/attachments/07/summer.js
server/game/cards/events/01/risenfromthesea.js
server/game/cards/events/02/bloodmagicritual.js
server/game/cards/events/03/aryasgift.js
server/game/drawcard.js
server/game/gamesteps/attachmentprompt.js
server/game/player.js
test/server/card/drawcard.canAttach.spec.js
test/server/cards/events/01/01081-risenfromthesea.spec.js
test/server/player/canattach.spec.js
test/server/player/removeattachment.spec.js

* Introduces better separation between `canAttach` and `allowAttachment` in `DrawCard` to make inheritance less error prone.
* Checks both methods when calling `Player.attach`, which fixes the problem of Risen from the Sea and Blood Magic Ritual inappropriately attaching to 'No attachments' cards.
Fixes #953.

Enforce attachment restrictions when attaching cards

---

server/game/triggeredability.js

Listening to events for all open information areas for all cards caused
problems with attachments such as Paid Off whose listeners expected to
be attached to another card. Thus, only reaction / interrupts for event
cards should listen in multiple locations. Right now that's hand and
discard as they are the only playable locations for events.
Fixes THRONETEKI-Z3
Fixes THRONETEKI-Z5
Fixes THRONETEKI-Z7

Only event cards should listen in many locations

---

server/game/cards/locations/03/towerofthehand.js
server/game/triggeredability.js

The 'returnedToHand' cost card currently cannot be resolved before
target eligibility is checked, causing a crash when trying to get the
printed cost for that card.
Fixes THRONETEKI-114
Fixes THRONETEKI-115

Fix targeting crash for Tower of the Hand

---

server/game/cards/characters/08/queensmen.js

@ystros: As we talked about in chat, showing the hand through a prompt instead of a chat message would help with an eventual melee implementation. Not sure if I like how this turned out though. Clicking a character card has the same effect as clicking Done, which seems weird but I don't know a way around this. And if you decide to trigger then then-effect, the cost-effect flow is reversed from the usual. On the other hand, this way does take relatively few clicks.
Another possibility: reveal the hand via chat message. Then, if you have a standing non-Bara character, prompt whether to kneel one, and if so, only prompt non-character cards from the opponents hand to be discarded. Showing the hand through a chat message can't be used in melee obviously, unless we would implement player …

Implement Queen's Men

---

server/game/gamesteps/challenge/applyclaim.js

Previously, when winning a power challenge while having higher claim than the amount of power on the defending player's house card, chatmessages would indicate the full claim amount was moved to the attacking player's house card. Even though the transferPower method already guards against this, players who were unaware of the exact power totals before claim was applied could still wonder whether or not too much power was gained by the attacker. This PR should fix that by differentiating in the chatmessage between the claim value and the amount of power moved.

Clarify amount of power moved when claim exceeds power

---

server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/keywordwindow.js
test/server/integration/pillage.spec.js

* Processes keywords in sequence instead of processing all keywords for a given card before moving to the next card.
* If there is a single card with keyword Pillage, pillage will automatically occur as before.
* If there are multiple cards with keyword Pillage, the player will be prompted to select the order to process pillage. If they click 'Done' without selecting the order, then pillage will occur in the default order (the order the characters were declared as attackers). Otherwise, pillage will be processed in the order they select.
Fixes #909.

Allow player to choose pillage order

---

server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/triggeredabilitywindow.js
test/server/gamesteps/abilityresolver.spec.js

* When the resolution of ability throws an exception anywhere (paying costs, targeting, in the handler, in prompts nested under the handler, etc), the error will be reported and the ability will be cancelled.
* When a prompt checks an ability for eligibility and the eligibility check throws an exception, the prompt will report the error and remove that ability from the prompt.
There may be cleanup paths I'm missing, particularly around ability resolution, but having the game in a slightly weird state but playable is preferable to total crash, which can happen currently.

Better crash recovery

---

server/game/cards/plots/01/marchedtothewall.js
server/game/cards/plots/01/wildfireassault.js
server/game/cards/plots/02/politicaldisaster.js

* Skips the prompt for Marched to the Wall, Wildfire Assault and Political Disaster if there's nothing to select.
* Fixes Political Disaster not displaying the FP's choices before prompting the second player to choose.
* Improves messaging. Most notably, while the word 'save' informally covers such effects, it also has a specific meaning in the game making it unsuitable here.

Update plot resets

---

client/GameComponents/ActionWindowsMenu.jsx
client/Profile.jsx
server/api/account.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
server/server.js
test/helpers/gameflowwrapper.js
test/server/cards/agendas/02060-thelordofthecrossing.spec.js
test/server/cards/characters/01/01183-randylltarly.spec.js
test/server/cards/characters/05/05006-tywinlannister.spec.js
test/server/cards/locations/04/04066-thehauntedforest.spec.js
test/server/cards/plots/01/01008-calmoverwesteros.spec.js
test/server/cards/plots/02/02080-wraithsintheirmidst.spec.js
test/server/cards/plots/04/04020-varyssriddle.spec.js
test/server/cards/plots/06/06040-theannalsofcastleblack.spec.js
test/server/cards/plots/06/06080-theredwedding.spec.js
test/server/integration/effects.spec.js
test/server/integration/intimidate.spec.js
test/server/integration/nestedabilitysequences.spec.js
test/server/integration/pillage.spec.js
test/server/integration/takecontrol.spec.js

The "winner determined" action window was put into place to allow a
pause to play in-hand event cards. Now that nearly all events in hand
prompt the player directly, the window is no longer needed.
Additionally, the presence of the window leads newer players to believe
they can ambush cards or play Action events in this pause, which is not
allowed by the rules.

Remove "winner determined" action window

---

server/game/cards/characters/04/aerondamphair.js
server/game/event.js
server/game/player.js

to that end, introduce a new onCardSaved event, raised when a card (of any
kind) is saved (for any reason: kill, discard, etc.)

implement Aeron Damphair (TIMC)

---

server/game/cards/locations/02/pleasurebarge.js
server/game/player.js

* Pleasure Barge should only trigger when the player has not drawn any cards yet that phase.

Restrict Pleasure Barge draw

---

server/game/gamesteps/actionwindow.js
test/helpers/gameflowwrapper.js
test/server/cards/characters/01/01183-randylltarly.spec.js
test/server/cards/characters/04/04025-dolorousedd.spec.js
test/server/cards/characters/04/04085-craster.spec.js
test/server/cards/locations/01/01061-theredkeep.spec.js
test/server/cards/plots/01/01013-headsonspikes.spec.js
test/server/integration/effects.spec.js

* Remove reactions from the title and use singular 'action' to better match their use.
* Pass instead of Done in the button matches the implementation of the reaction and interrupt windows and mirrors the language used in the RRG.

Reword action window prompts

---

server/game/cards/agendas/thelordofthecrossing.js
server/game/cards/characters/06/blackwalder.js
server/game/cards/events/06/freyhospitality.js
server/game/cards/locations/06/thetwins.js
server/game/cards/plots/02/forthewatch.js
server/game/cards/plots/04/battleofoxcross.js
server/game/challenge.js
server/game/gamesteps/challengephase.js
test/server/cards/agendas/02060-thelordofthecrossing.spec.js
test/server/challenge/determinewinner.spec.js
test/server/challenge/removefromchallenge.spec.js

Previously, Lord of the Crossing's STR bonuses were calculated based on
the number of challenges initiated by the player. This lead to a bug
where after attackers were picked but before the challenge was
initiated, the attackers would get the -1 STR penalty. If the opponent
had Blood of the Dragon at the time, this could kill the attackers.
Now, the challenge number is calculated up front and remains constant for
the entire challenge, preventing such bugs.
Fixes #1169

Calculate Crossing STR based on challenge number

---

server/game/basecard.js
server/game/effectengine.js
test/server/card/drawcard.canAttach.spec.js
test/server/integration/traitchange.spec.js

Previously, if an effect were already in play that was limited to cards
with a certain trait, and a card already in play gained or lost that
trait, the effect would not be applied or removed from that card. For
example, characters that gained the 'Knight' trait while Tourney for the
King was revealed did not gain the renown keyword.
Now, when a card gains or loses a trait, effects for that card are
recalculated in a similar manner to the way they are recalculated for
faction changes.
Fixes #1027.

Recalculate effects when traits change

---

server/game/player.js
test/server/integration/takecontrol.spec.js

Previously, if a card that had been taken control of was sacrificed or
returned to hand, it would properly update the `controller` property.
However, the card would not be removed from the list of cards controlled
by the opponent nor added back to the list of cards controlled by the
player. This caused bugs where a controlled character leaving play could
not be controlled again if they re-entered play somehow.
Fixes #1223

Revert controlled cards when they move

---

server/game/cards/attachments/01/bodyguard.js
server/game/cards/attachments/01/heartsbane.js
server/game/cards/attachments/01/throwingaxe.js
server/game/cards/attachments/02/drownedgodsblessing.js
server/game/cards/attachments/02/kingrobertswarhammer.js
server/game/cards/attachments/02/maesterschain.js
server/game/cards/attachments/02/mareinheat.js
server/game/cards/attachments/02/paidoff.js
server/game/cards/attachments/02/stinkingdrunk.js
server/game/cards/attachments/02/thesilversteed.js
server/game/cards/attachments/03/greendreams.js
server/game/cards/attachments/03/needle.js
server/game/cards/attachments/04/beggarking.js
server/game/cards/attachments/04/crownofgoldenroses.js
server/game/cards/attachments/04/kingbeyondthewall.js
server/game/cards/attachments/04/motherofdragons.js
server/game/cards/attachments/04/venomousblade.js
server/game/cards/attachments/05/disputedclaim.js
server/game/cards/attachments/05/shieldoflannisport.js
server/game/cards/attachments/06/corsairsdirk.js
server/game/cards/attachments/07/catapultonthewall.js
server/game/cards/attachments/07/weirwoodbow.js
server/game/cards/attachments/08/oathkeeper.js

* Updates all currently implemented attachments
* Converts implementations to use the cost and/or target API.
* Makes sure the ability can only trigger or initiate if it would change the game state
* Standardises action labels, prompt titles and chat messages.
* Changes actions to use a handler instead of method, where needed.
* Fixes canAttach() methods to match the card limitations.
* Changes var into let where possible.
* Invokes game.transferGold() instead of two times invoking game.addGold().

Update attachment card implementations

---

server/game/cards/plots/01/calmoverwesteros.js

* Previously, Calm Over Westeros' effect lasted until the end of the round instead of until a new plot was revealed. This lead to the effect still being active even when a new plot had been revealed in the challenges phase through Rains of Castamere. This PR fixes that by implementing the effect as a custom lasting effect.
* Also remove the cancel option. Cancelling When Revealed effects is not a legal play.
* Fixes #1267.

Make Calm Over Westeros last until a new plot is revealed

---

server/game/player.js

* Checking whether a card by title is allowed to be put into play/marshalled, should happen before the unique check.
* Makes sure you can't marshal or put into play a non-unique character after returning it with "The Iron Bank Will Have Its Due".

Rearrange canPutIntoPlay check

---

server/game/cards/events/01/oursisthefury.js
server/game/challenge.js

* Previously, when Ours is the Fury was played on a character that was already participating in the challenge, that character's strength would be added again. This PR fixes that by adding a check to challenge.addDefender.
* Fixes #1273.

Prevent Ours is the Fury double adding characters to challenge

---

server/game/cards/plots/02/thelongplan.js
server/game/effects.js
server/game/gamesteps/taxationphase.js
server/game/player.js

* Previously, Long Plan's ability to keep unspent gold during taxation was implemented as a hacky interrupt, causing it to trigger the timed interrupt window. This PR fixes that by converting this ability to a persistent effect.
* Fixes #1279.

Convert Long Plan to a persistent effect

---

server/game/cards/characters/04/dolorousedd.js

Previously, when Dolorous Edd couldn't be put into play for whatever reason, his ability could still trigger, causing him to remain in hand but still added as defender. This PR fixes that by having the canPutIntoPlay check as a play condition.

Only allow triggering of D. Edd when he can be put into play

---

server/game/baseability.js
server/game/cards/characters/01/thequeensassassin.js
server/game/cards/characters/01/thetickler.js
server/game/cards/characters/06/melisandre.js
server/game/cards/characters/07/maesteraemon.js
server/game/cards/characters/08/queensmen.js
server/game/cards/events/01/seeninflames.js
server/game/cards/events/02/vengeanceforelia.js
server/game/cards/events/04/nightgathers.js
server/game/cards/events/04/thedragonstail.js
server/game/cards/events/05/alannisteralwayspayshisdebts.js
server/game/cards/events/06/plunder.js
server/game/cards/events/06/thedornishmanswife.js
server/game/cards/locations/04/houseoftheundying.js
server/game/cards/locations/04/thefrostfangs.js
server/game/cards/locations/05/bridgeofskulls.js
server/game/cards/locations/07/queenscrown.js
server/game/cards/plots/01/callingthebanners.js
server/game/cards/plots/01/headsonspikes.js
server/game/cards/plots/04/battleoftheblackwater.js
server/game/cards/plots/04/summerharvest.js
server/game/cards/plots/06/duel.js
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/chooseopponentprompt.js
server/game/gamesteps/selectopponentprompt.js
server/game/triggeredability.js
test/helpers/gameflowwrapper.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/takecontrol.spec.js

Cards that require the player to choose an opponent can now add a `chooseOpponent` property. This can either be `true` if there are no restrictions on which opponent can be chosen, or a function that returns true for opponents that can be chosen. Once chosen, the opponent's player object is available via `context.opponent`.
In single player games, such abilities cannot be triggered because there are no opponents.
In two player games, the opponent will automatically be selected if there are any eligible, maintaining existing behavior.
In future Melee games, the player will be prompted to choose the opponent they want to target with the ability.
Partial for #1237

Add `chooseOpponent` option for abilities

---

server/game/gamesteps/challenge/challengeflow.js

* Previously, it was possible to use Dolorous Edd's ability to put him into play defending, stand him with Castle Black, and then select him again to essentially have him defend twice. This PR fixes that by disallowing characters that are already defending to be selected as defenders.
* Fixes #1285.

Prevent double adding defenders

---

client/GameBoard.jsx
client/GameComponents/AdditionalCardPile.jsx
client/GameComponents/PlayerRow.jsx
server/game/game.js
server/game/player.js
test/server/player/drop.spec.js

* Passes card directly into Player.drop to better match current style practices.
* Reworks drag-drop validity to be based on type instead of source location. This is because the out of game pile can contain both draw and plot cards, so dragging them out from there needs to check the type vs target location.
* Adds proper source and drag handler to the piles client side.
Fixes #1216 
Edit: Also fixes #1303 by renaming the pile source to 'conclave' for the Conclave pile.

Allow drag-drop from additional card piles

---

server/game/cards/characters/02/gendry.js
server/game/cards/characters/02/thehound.js
server/game/cards/characters/06/secondsons.js

Previously, the "less bad" choice for forced reactions such as these could still be chosen, leaving the possibility of illegal plays. This PR fixes that by only prompting such choices if both options are a possibility.

Only prompt choices for forced reactions if real choice

---

server/game/game.js

Previously, if a minimum reserve was set by something like Wraiths in
their Midst, it was impossible to go below that reserve even when
setting it manually. Now, any adjustment to reserve will get rid of the
minimum requirement. This behavior is more in line with other overrides
and should help players get past the NaN reserve bug while we track it
down.

Override min reserve when manually setting reserve

---

server/game/effectengine.js
test/server/effectengine.spec.js
test/server/integration/leavingplay.spec.js

Previously, only persistent effects were removed when a card left the
play area. This lead to bugs where a card that left play but entered
play again during the period for a lasting effect would continue to have
that effect. With burn effects, this would lead to the card re-entering
play with the strength penalty still in place.
Fixes #844 
Fixes #1321

Reset lasting effects when card leaves play

---

client/About.jsx
server/game/chatcommands.js

This chatcommand makes sure you can move a card to the bottom of your deck when for example a character was automatically saved against your will.

Implement /move-bottom chatcommand

---

server/game/cards/characters/04/roosebolton.js

Previously, because costs are paid before resolution, any strength buffs on Roose had worn off by the time targets were chosen. This PR fixes that by recording his strength at the point of initiation of his ability.

Record Roose Bolton's strength before sacrificing

---

server/game/player.js
test/helpers/integrationhelper.js
test/helpers/objectformatters.js
test/server/cards/characters/01/01142-branstark.spec.js
test/server/cards/events/03/03024-aryasgift.spec.js
test/server/integration/leavingplay.spec.js
test/server/integration/reducers.spec.js

Previously, when a card was moved, it would immediately be moved to the
target pile. In the case of abilities like dupes and Improved
Fortifications, this would move the card before the interrupt prompted,
preventing the save from working properly.
Necessary to consolidate dupe logic properly for #1231 
Also adds test-only `toString` methods for cards, players and game to make test output less awful.

Do not remove card from play until interrupts

---

server/game/challenge.js
test/server/cards/characters/02/02093-mirrimazduur.spec.js

Previously when a card left play during a challenge, if the winner had
already been determined then the card would still be considered
participating. This caused bugs where if the participants were checked
after winner had been determined, the phantom card could effect the
outcome. For example, if the Hound and Mirri Maz Duur were in a
challenge and the Hound leaves plays during the D of DUCK due to his
forced reaction, then Mirri should be considered attacking alone at the
C step, allowing her ability to trigger.
Fixes #1341

Always remove card leaving play from challenge

---

server/game/cards/locations/06/scorchingdeserts.js

Depending on the event that triggered the reaction.

Allow Scorching Deserts to only target attackers OR defenders

---

client/GameComponents/ActivePlayerPrompt.jsx

Previously, the ActivePlayerPrompt component was not checking buttons
when deciding whether to update. This lead to bugs where if two prompts
had the same titles but different buttons (or the same button names with
different arguments), the prompt would not refresh client side and the
buttons wouldn't work. The most common cases for this were multiple
Bastard Daughters being killed and prompts where multiple abilities were
available (e.g. Stark reactions to sacrifices)

Check buttons when updating prompt client side

---

server/game/event.js
server/game/game.js
server/game/gamesteps/eventwindow.js
server/game/gamesteps/killcharacters.js
server/game/gamesteps/simultaneouseventwindow.js
server/game/player.js
test/server/player/discardcards.spec.js
test/server/player/removeattachment.spec.js

* Ensures that automatic saves with dupes happens after cancellation interrupts have fired but before the normal interrupts (previously was done inside the handler, allowing onCharacterKilled interrupts to fire even though the card was later saved)
* Cleans up logic by making cards leaving play cancellable using dupes directly.
Fixes #1231

Fix timing of automatic dupe saves

---

server/game/basecard.js
server/game/challenge.js
server/game/player.js

Modifying claim has been entirely converted to effects. There's no
longer a need for the method you used to have to override to implement
claim modification.
Fixes THRONETEKI-1A1

Remove old override style modifyClaim

---

server/game/cards/attachments/04/motherofdragons.js
server/game/cards/attachments/07/summer.js
server/game/cards/characters/04/dolorousedd.js
server/game/cards/characters/05/moonbrothers.js
server/game/cards/characters/09/margaerytyrell.js
server/game/cards/locations/05/oldwyk.js
server/game/cards/plots/02/wardensofthenorth.js
server/game/challenge.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js

Previously, the onCardKneeled event for kneeling an attacker/defender was raised before any of the other challenge initiation/declare defenders events. This made it for example impossible to prevent a Satin trigger with Winterfell. This PR fixes that by raising onCardKneeled simultaneously with the other associated challenge events.

Simultaneously raise kneel event during challenges

---

server/game/cards/characters/06/ficklebannerman.js

Previously, if the Fickle Bannerman had no gold tokens on the card, the
player would still be prompted and if they selected to discard a
non-existent gold token, they would keep control.

Do not prompt when Fickle Bannerman has no gold

---

server/game/basecard.js
server/game/cards/events/01/risenfromthesea.js
server/game/cards/events/02/bloodmagicritual.js
server/game/cards/plots/03/weaponsatthedoor.js

Previously, after playing and attaching a Risen from the Sea/Blood Magic Ritual to a character, these cards still retained their event cardtype. This made it for example impossible to discard these cards with Confiscation. This PR fixes that by setting the correct cardtype as long as these cards remain in play.

Set correct cardtype for event+attach saves

---

server/game/chatcommands.js
server/game/game.js

Adds a flag to debug data about whether the /cancel-prompt command has
been used. This should allow a better understanding of which errors are
caused because the user canceled something and which are general errors.

Track whether /cancel-prompt used

---

server/game/gamesteps/abilityresolver.js

Set the resolution of an ability to be cancelled when cancel-prompt is used, so that the prompt does not continue or try to invoke a handler with no targets selected
@ystros this almost certainly has consequences I haven't thought about, but it does work in the one tiny circumstance I managed to reproduce and doesn't break any tests...

Fix /cancel-prompt

---

server/game/abilitylimit.js
test/server/abilitylimit.spec.js
test/server/integration/leavingplay.spec.js

Cards leaving play unregister the event listeners for their ability
limits, so whenever an ability is unregistered, the limit is now reset.
Fixes #1098

Reset ability limits when cards leave play

---

client/deck-validator.js

Per the RRG, you can only have a single plot by title that contains
multiple copies. All other plots can only contain a single copy by
title.

Validate number of different plots

---

server/game/gamesteps/triggeredabilitywindow.js
test/server/gamesteps/triggeredabilitywindow.spec.js
test/server/integration/challengesphase.spec.js

Previously, it was assumed that if a prompt had multiple choices from
the same card in a single window that it was because the card offered
multiple choices (e.g. The Reader, LoCR Tyrion). Thus, if the player
clicked one of the options, the others were removed.
However, now that the challenge initiation window contains choices for
multiple events, it's possible to have the same card produce multiple
independent choices. For example, Marya Seaworth can trigger separately
for each card bypassed by stealth. The previous implementation only
allowed one instance of her ability to be triggered. The prompt now
treats them as separate abilities instead of separate choices for the
same ability, and allows all of them to be triggered.

Allow multiple reactions from a card in a window

---

client/Profile.jsx
server/game/challenge.js
server/game/gamesteps/keywordwindow.js
server/game/player.js
server/settings.js
test/helpers/gameflowwrapper.js
test/helpers/playerinteractionwrapper.js
test/server/gamesteps/actionwindow.spec.js
test/server/integration/challengesphase.spec.js

* Adds profile options for choosing the order keywords are resolved as well as making keywords optional.
* When keywords are set as optional, the challenge winner are prompted to select which cards they want to trigger the individual keywords on. Clicking 'Done' without selecting any cards will skip that keyword.
* When the first player has the option on to choose order, they get a prompt allowing to choose which keyword to resolve next. Choosing 'automatic' resolves all keywords without further prompting.
* Does not add the keyword settings to the in-game options yet (which is where it would be most useful), because significant restyling would be required to fit it at lower screen resolutions and that would conflict with the gameboard UI redo.
Resolves #526

Allow optional keywords + choosing order

---

server/game/chatcommands.js

Communicating the amount the token was set to, instead of the difference, brings it in line with the other similar chatcommands.

Fix token command message

---

server/game/cards/characters/01/benjenstark.js
server/game/effects.js
server/game/player.js

because it's not always synchronous and modify card effects to use the callback when shuffling cards into deck from the play area
Fixes cards like benjen stark who liked to put himself to the top of the deck instead of shuffling.  Could be extended to every use of shuffle but only really matters for cards in play

Add a callback for moveCard 

---

client/GameBoard.jsx
client/GameComponents/PlayerRow.jsx
server/game/cards/agendas/theconclave.js
server/game/cards/agendas/therainsofcastamere.js
server/game/player.js
test/client/GameBoard.spec.jsx
test/server/cards/agendas/05045-therainsofcastamere.spec.js
test/server/cards/cancreatecards.spec.js

Removes the ability to create additional piles and nests all agenda
specific piles at the same level as the other piles under the
`Player` object.

Remove additional pile mechanism

---

server/game/cards/04.3 FFH/RenlyBaratheon.js
server/game/costs.js
server/game/insightkeyword.js
test/server/integration/challengesphase.spec.js

* Solves the issue where a cancel (Treachery, Begging Brothers) could be baited when there was nothing to trigger in the first place.
* Makes sure that when it does get cancelled, the right card was revealed as it is a cost (previously, the revealing of the card got cancelled as well).

Implement cost function for Renly Baratheon's (FFH) reaction

---

server/game/cards/03 WotN/JonSnow.js

This often happens when there are kneeling characters at the time Jon Snow is
triggered, but not at the time it resolves, e.g., because Robb Stark (core) was
used.

Jon Snow (WotN): do not prompt if there are no kneeling targets

---

server/game/gamesteps/challenge/challengeflow.js
test/server/cards/characters/05/05007-ChellaDaughterOfCheyk.spec.js

Certain effects, such as Chella's 3 ear token ability, can activate
after claim has been applied but before keywords are resolved. Thus, an
explicit recalculation is needed between those two steps.
Fixes #1305

Explicitly recalculate state after claim

---

server/game/effect.js
server/game/effectengine.js
server/game/game.js
server/game/gamesteps/setupphase.js
test/server/integration/setup.spec.js

Previously, effects of cards placed during setup were immediately
active, even if not immediately visible to the player. This led to bugs
such as Elinor Tyrell allowing an extra limited card to be played during
setup.
Now, when an effect is created, its `active` property is determined by
whether or not the source of the effect is facedown. Thus, cards placed
in setup will not be active immediately. At the end of setup, all
persistent effects are explicitly activated.
Fixes #1174 
More general fix than #1375

Activate effects at the end of setup phase

---

client/GameBoard.jsx
client/GameComponents/PlayerRow.jsx
client/NewGame.jsx
server/game/TitleCard.js
server/game/TitlePool.js
server/game/basecard.js
server/game/cards/titles/CrownRegent.js
server/game/cards/titles/HandOfTheKing.js
server/game/cards/titles/MasterOfCoin.js
server/game/cards/titles/MasterOfLaws.js
server/game/cards/titles/MasterOfShips.js
server/game/cards/titles/MasterOfWhispers.js
server/game/game.js
server/game/gamesteps/plot/ChooseTitlePrompt.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/taxationphase.js
server/game/player.js
server/gamenode/gameserver.js
server/pendinggame.js
server/services/CardService.js

* Melee can be accessed by giving the user that creates the game an `allowMelee` permission.
* Implements the persistent effects for each title card in Melee games.
* Players select their title during the plot phase, return it during the taxation phase.
* Joust games remain unaffected.
Not currently implemented:
* Challenge restrictions for titles that support another title
* Challenge bonuses for titles that rival another title
* Challenge redirect ability for Crown Regent
* Hand of the King allowing an additional power challenge against a different opponent (need to track which opponents they've initiated against)
* Master of Whispers applying intrigue claim to players of their choice (this is just going to be super weird so probably should be done separately)
Progress toward #1237

Implement basic title cards for Melee

---

server/game/cards/05-LoCR/ALannisterAlwaysPaysHisDebts.js
server/game/cards/07-WotW/MaesterAemon.js
server/game/challenge.js
server/game/challengetracker.js
server/game/player.js
test/server/challenge/determinewinner.spec.js
test/server/challenge/removefromchallenge.spec.js

Updates the challenge tracker to simply keep records of challenges that the player has participated in.  The performed / won / lost stats are then calculated based on the list of challenges.
This allows proper implementations for WotW Aemon and A Lannister Always Pays Their Debts that will work in Melee, as well as provides some infrastructure necessary to implement the Hand of the King title additional power challenge ability (not implemented here).
Progress toward #1237

Track challenges directly for Melee

---

docs/implementing-cards.md
server/game/cards/01-Core/BenjenStark.js
server/game/cards/01-Core/SerDavosSeaworth.js
server/game/cards/02.1-TtB/TheSeastoneChair.js
server/game/cards/02.5-COW/MirriMazDuur.js
server/game/cards/02.5-COW/TrialByCombat.js
server/game/cards/02.5-COW/VengeanceForElia.js
server/game/cards/02.6-TS/DagmerCleftjaw.js
server/game/cards/03-WotN/Needle.js
server/game/cards/04.5-GoH/Craster.js
server/game/cards/06.3-TFoA/SpearsOfTheMerlingKing.js
server/game/event.js
server/game/gamesteps/atomiceventwindow.js
server/game/gamesteps/eventwindow.js
server/game/gamesteps/killcharacters.js
server/game/gamesteps/simultaneouseventwindow.js
server/game/triggeredability.js
test/server/gamesteps/eventwindow.spec.js
test/server/gamesteps/simultaneouseventwindow.spec.js
test/server/integration/ReplacementEffects.spec.js

* Replacement effects now execute when the thing they're supposed to replace would execute instead of immediately after triggering.
* Because replacement effects no longer trigger immediately, when multiple replacements are triggered only the last will actually be applied, as per the rules.
* Fixing the timing revealed a bug w/ Craster where he could return Benjen Stark from the draw deck into play.
* Fixing the timing revealed a bug where dead pile order was being asked before it was determined which cards may be placed somewhere other than the dead pile (e.g. Benjen, Davos)
* Fixing the timing revealed a bug where if a replacement effect occurred, reactions to that event would not fire (e.g. Benjen dying vs Chella gaining ears). (Not sure why this bug was happening, but this PR fixes it …

Implement proper behavior for replacement effects

---

client/GameBoard.jsx
client/GameComponents/AbilityTargeting.jsx
client/GameComponents/ActivePlayerPrompt.jsx
less/gameboard.less
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/playerpromptstate.js
test/server/gamesteps/abilityresolver.spec.js
test/server/gamesteps/triggeredabilitywindow.spec.js

* Adds a `controls` property to prompts to add on additional display / form elements.
* When a user is prompted for an ability / event cancel and the ability has at least one target, it will display the card that generated the ability as well as all of the targets chosen for the ability. If there are multiple targets, the cards shrink to fit on a single line. Hovering over these cards displays a card preview as normal:
Major progress toward #1249 but the targeting improvements from #1389 needed to fully resolve it.

Display targets on cancel prompts

---

server/game/cards/01-Core/BenjenStark.js
server/game/cards/01-Core/SerDavosSeaworth.js
server/game/cards/03-WotN/Needle.js
server/game/cards/06.3-TFoA/SpearsOfTheMerlingKing.js

Because card snapshots for kill / sacrifice events are done within the
normal handler, any replacement effects like Benjen Stark must
explicitly also create a snapshot. Otherwise, cards that react to other
cards being killed (Starks, Funeral Pyre, etc) will encounter an
undefined object when looking for card state.
Fixes THRONETEKI-1E5
Fixes THRONETEKI-1EF
Fixes THRONETEKI-1EA
Fixes THRONETEKI-1EK
Fixes THRONETEKI-1E0
Fixes THRONETEKI-1E7
Fixes THRONETEKI-1EE

Record card snapshots in replacement handlers

---

client/GameBoard.jsx
client/GameComponents/PlayerRow.jsx
server/game/cards/01-Core/VanguardLancer.js
server/game/cards/03-WotN/TheLongWinter.js
server/game/chatcommands.js
server/game/game.js

* Removes special client and server side handling for clicking on a faction card, allowing faction card to be clicked during card select prompts.
* Removes the 'Faction Card' button during prompts for Vanguard Lancer and Long Winter in favor of allowing the faction card to be clicked directly (makes Melee possible for Lancer)
* As a bonus, /power command now works consistently for either cards in play or the faction card.

Treat faction card like a normal card

---

server/game/cards/01-Core/ArianneMartell.js
server/game/cards/01-Core/DothrakiSea.js
server/game/cards/01-Core/FireAndBlood.js
server/game/cards/01-Core/HearMeRoar.js
server/game/cards/01-Core/OldBearMormont.js
server/game/cards/01-Core/Reinforcement.js
server/game/cards/01-Core/TheQueenOfThorns.js
server/game/cards/01-Core/Yoren.js
server/game/cards/02.3-TKP/SerAlliserThorne.js
server/game/cards/03-WotN/ATimeForWolves.js
server/game/cards/03-WotN/AsHardAsWinter.js
server/game/cards/04.1-AtSK/BitterbridgeEncampment.js
server/game/cards/04.3-FFH/Harrenhal.js
server/game/cards/05-LoCR/MoonBrothers.js
server/game/cards/06.1-AMAF/AttackFromTheMountains.js
server/game/cards/06.2-GtR/GuardingTheRealm.js
server/game/cards/06.4-TRW/BreakerOfChains.js
server/game/cards/06.4-TRW/SerOsmundKettleblack.js
server/game/cards/06.5-OR/ATaskForEveryTool.js
server/game/cards/06.5-OR/FleaBottom.js
server/game/cards/07-WotW/NowMyWatchBegins.js
server/game/cards/07-WotW/OldBearMormont.js
server/game/cards/07-WotW/TheLastOfTheGiants.js

Previously, when a character that could not be put into play was chosen as a target for such an effect, even though the card would not be put into play, costs were paid and messages for said abilities were printed anyway. This PR fixes that by adding canPutIntoPlay checks as a targeting restriction or play condition on all cards that put characters into play.

Add canPutIntoPlay check to abilities

---

server/game/cards/01-Core/ChamberOfThePaintedTable.js
server/game/cards/02.4-NMG/Loot.js
server/game/cards/02.6-TS/AGiftOfArborRed.js
server/game/cards/04.1-AtSK/VaryssRiddle.js
server/game/cards/04.4-TIMC/JojenReed.js
server/game/costs.js

Removes the remaining card usages of `getOtherPlayer` in favor of `getOpponents`. 
Progress toward #1237.

Remove `getOtherPlayer` from more complex melee cards

---

server/game/baseability.js
server/game/cards/02.2-TRtW/LadyInWaiting.js
server/game/cards/06.6-TBWB/BericDondarrion.js
server/game/gamesteps/abilityresolver.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/cards/characters/02/02023-ladyinwaiting.spec.js
test/server/gamesteps/abilityresolver.spec.js

Adds a flag to indicate whether an ability being resolved can be
canceled. This flag is automatically checked for cancel interrupts so
that it isn't necessary to check it in individual card implementations.
Fixes #1239

Add cannotBeCanceled flag to abilities

---

server/game/baseability.js

Fixes a bug where Vanguard Lancer would not trigger if the opponent's faction card was the only card with power.

Include faction card in target eligibility check

---

server/game/cards/01-Core/CalmOverWesteros.js
test/server/cards/plots/04/04020-varyssriddle.spec.js

Varys' Riddle initiates Calm Over Westeros' "When Revealed" ability as
if that player had revealed it. The lasting effect of Calm lasts until
the revealing player (the Riddle player) reveals a new plot, not until
the current controller reveals a new plot. Thus, the Calm player
revealing a new plot via Rains of Castamere should not cancel Riddle's
copy of the lasting effect.
Fixes #1493.

Fix Rains + Calm + Riddle interaction

---

server/game/cards/03-WotN/AsHardAsWinter.js
server/game/cards/03-WotN/WeaponsAtTheDoor.js
server/game/cards/04.4-TIMC/ShadowTowerMason.js
server/game/cards/04.6-TC/TyrionsChain.js
server/game/cards/05-LoCR/OldWyk.js
server/game/cards/05-LoCR/SummonedToCourt.js
server/game/cards/06.4-TRW/Plunder.js
server/game/cards/agendas/ThePowerOfWealth.js
server/game/cards/agendas/Treaty.js
server/game/costs.js
server/game/game.js
server/game/player.js
test/helpers/playerinteractionwrapper.js
test/server/player/getduplicateinplay.spec.js
test/server/player/putintoplay.spec.js

Replaces usages of Player.allCards with Game.allCards and relevant methods. This simplifies take control because you no longer have to keep Player.allCards in sync with cards that the player controls. Instead, you just query Game.allCards which never changes even when control of a card changes (it's fixed upon game start).

Remove Player.allCards

---

server/game/basecard.js
server/game/effectengine.js
server/game/game.js
server/game/gamesteps/revealplots.js
server/game/player.js
test/server/integration/plotphase.spec.js
test/server/player/flipplotfaceup.spec.js

Instead of applying plot effects one at a time as they are flipped (in
player-join order), they are now applied simultaneously per the rules.
This fixes a bug where if the player that created the game revealed
Blood of the Dragon and the opponent revealed A Song of Summer, the
opponent's 1 STR characters would improperly die.
Fixes #1247

Apply plot persistent effects simultaneously

---

client/BlockList.jsx
client/reducers/auth.js
server/api/account.js

In order to update the blocklist on both the client side JWT and server
side user objects, a new token is sent back with the updated blocklist,
similar to what is done on profile updates. Then, the client reauths
with the server using the token, which updates the user object on the
corresponding socket on the server side.
Fixes #1505 (once #1507 is merged)

Refresh user auth when blocklist is modified

---

server/game/CardSelector.js
server/game/CardSelectors/BaseCardSelector.js
server/game/CardSelectors/ExactlyXCardSelector.js
server/game/cards/04.5-GoH/RitualOfRhllor.js
server/game/cards/06.3-TFoA/Duel.js
server/game/cards/06.4-TRW/FreyHospitality.js
server/game/cards/06.4-TRW/OldtownInformer.js
server/game/cards/08.1-TAK/ValarDohaeris.js
server/game/cards/09-HoT/MeleeAtBitterbridge.js
server/game/costs.js
server/game/gamesteps/keywordwindow.js
server/game/gamesteps/killcharacters.js
server/game/gamesteps/selectcardprompt.js
server/game/gamesteps/standingphase.js
server/game/gamesteps/taxation/discardtoreserveprompt.js

Natively supports prompts that require the player to select the exact amount of cards (e.g. selecting exactly 2 cards for Duel, selecting all killed cards for dead pile order, etc).
Progress toward #1389.

Implement a "select exactly X cards" prompt

---

server/game/cards/02.1-TtB/RiseOfTheKraken.js
server/game/gamesteps/challenge/challengeflow.js

Fixes a bug where Rise of the Kraken could still be triggered even if the player was unable to gain challenge bonuses

Convert Rise of the Kraken to a replacement effect

---

server/game/effect.js

Trying to track down the NaN reserve bug cause
Progress toward #1506

Add temporary logging for duplicated targets

---

server/game/cards/01-Core/Sunspear.js

Sunspear's claim modification should apply to the currently revealed
plot, not just the plot that was active at the time Sunspear triggered.
This is because "your revealed plot" refers to a game area, not the
specific plot revealed.
See ruling:
http://www.cardgamedb.com/forums/index.php?/topic/33992-calm-over-westeros-rains-of-castamere/?p=298061

Apply Sunspear effect to "revealed plot"

---

server/pendinggame.js

Bug description:
When user click on "watch" on a game still pending nothing happen, nevertheless he could no watch nor join any other game in list. Page refresh was needed or wait until game starts.
Ps. 
I hope I have not make any mess 'cause these are my very first steps with "git".

Minor bug fix that resolve user being stuck on game list.

---

server/game/costs.js
server/game/gamesteps/abilityresolver.js
server/game/player.js
test/server/cards/01-Core/RisenFromTheSea.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/marshalphase.spec.js

When an event card is played, it goes into a temporary "being played"
pile to indicate that it is currently resolving. Once the resolution of
the ability has completed, it is then placed in discard.
From a UI perspective, cards that are currently being played are
displayed as if they are already in the discard pile.

Do not place events in discard immediately

---

server/game/effectengine.js
server/game/effects.js
server/game/player.js
test/server/cards/09-HoT/MaceTyrell.spec.js

Previously, when using Mace Tyrell's ability to remove a card from the
game, the card would leave then immediately re-enter play. This is
because the effects engine was fixed to remove effects from cards that
leave play.
Now, 'custom' duration lasting effects are not removed from cards when
they leave play. This change should have no effect on other cards using
custom lasting effects as they explicitly listen to onCardLeftPlay
already where appropriate.
Additionally, Barring the Gates will no longer prevent the card from
re-entering play.

Fix Mace Tyrell's remove from game ability

---

server/game/costreducer.js

Previously, CostReducer expected that a `match` function was passed into
the constructor to determine which cards the reduction could be applied
to. The Bastard of Godsgrace, however, matches all cards either being
played or ambush, so the match function was omitted, causing crashes.
Fixes THRONETEKI-1K4
Fixes THRONETEKI-1K5
Fixes THRONETEKI-1KF

Default to match any card for cost reducers

---

server/game/basecard.js
test/server/card/basecard.spec.js

Previously, if an ability attempted to remove a token from a card that
didn't have that token, it would set the token value to NaN. This
displayed the token in the UI but did not count as having the token for
the purpose of the `hasToken` method. The main scenario involved is
Jaqen places a Valar token on a character. That character leaves and
re-enters play. Then Jaqen leaves play and tries to remove the original
token placed, which was already removed when the targeted character left
play.
Fixes #1550

Do not allow removal of non-existent tokens

---

server/game/cards/01-Core/BalonGreyjoy.js
server/game/cards/01-Core/DornishParamour.js
server/game/cards/01-Core/EuronCrowsEye.js
server/game/cards/01-Core/Ice.js
server/game/cards/01-Core/PutToTheSword.js
server/game/cards/01-Core/PutToTheTorch.js
server/game/cards/01-Core/TearsOfLys.js
server/game/cards/01-Core/TheQueensAssassin.js
server/game/cards/02.1-TtB/TheSeastoneChair.js
server/game/cards/02.2-TRtW/WardensOfTheWest.js
server/game/cards/02.5-COW/MirriMazDuur.js
server/game/cards/02.6-TS/DagmerCleftjaw.js
server/game/cards/03-WotN/EvenHandedJustice.js
server/game/cards/03-WotN/TheShadowTower.js
server/game/cards/03-WotN/TowerOfTheHand.js
server/game/cards/04.3-FFH/Spearmaiden.js
server/game/cards/04.5-GoH/RooseBolton.js
server/game/cards/04.6-TC/QhorinHalfhand.js
server/game/cards/06.4-TRW/FreyHospitality.js
server/game/cards/06.4-TRW/TywinsStratagem.js
server/game/cards/06.5-OR/DornishRevenge.js
server/game/cards/07-WotW/RaidingTheBayOfIce.js
server/game/cards/09-HoT/MargaeryTyrell.js

Previously, cards that were supposed to target a specific player during
a challenge (the defending player, the losing opponent, etc) were simply
targeting any opponent. For Melee games this would allow targets to be
chosen inappropriately outside the players in the challenge.
Progress toward #1237

Fix targeting for challenge-related abilities

---

server/game/AbilityContext.js
server/game/costs/FactionCardCost.js
server/game/costs/ParentCost.js
server/game/costs/SelectCardCost.js
server/game/costs/SelfCost.js
server/game/costs/SpecificCardCost.js

The previous cost refactor introduced a bug where if a card used the
same cost action on two different cards (e.g. Joffrey (GoH) kneeling the
loyal card and the faction card), only one of the cards would get the
cost action applied. This was due to the entry in the costs object being
overwritten, whereas previously each cost was written manually and
didn't always store an entry on the costs object.
Now, when a cost choice is made, its recorded to a separate parallel
object that always stores the costs as an array. The previous mechanism
is left in place for compatibility with abilities that need to look up
the exact card (typically for the message in chat).
Fixes #1571

Record costs in array to prevent overwriting

---

README.md

Take the chance to make the list of commands to run locally more uniform.
(In particolar, they are all shell commands now, allowing copy-paste.)

README: document the need of running build-vendor

---

server/game/cards/06.5-OR/WheelsWithinWheels.js

rationale: it wasn't clear before if the prompt was asking which card to draw
or which card(s) to discard, especially when exactly two events were revealed
to resolve the first part of the plot

Wheels within Wheels: clarify that last selection is for drawing

---

server/game/gamesteps/challenge/challengeflow.js

Previously, the onDeclaredAsDefender event was being fired for all
defenders within a challenge. However, it should only fire for cards
specifically chosen / forced to be chosen by the player. This lead to a
bug where cards added to the challenge by an ability (e.g. HoT Margaery)
would be declared as a defender even though they weren't actually
declared.
Fixes #1569

Only fire onDeclaredAsDefender for chosen cards

---

server/game/cards/05-LoCR/OldWyk.js

The bug was most likely due to copy-pasting from Edd, where the trigger and the
character entering play were the same card, which is not the case for Old Wyk.
Fixes #1599

Old Wyk: kneel character that enters play

---

server/game/gamesteps/challenge/challengeflow.js

Rationale: now that there are both max (e.g., Knight of Flowers) and min (e.g.,
Beseiged) defender limits, having messages that specify a "limit", without
clarifying if it's min or max, is confusing.

uniform messages for defender limits to use min/max as needed

---

server/scripts/fetchdata/CardgameDbImageSource.js
test/server/cards/01-Core/SelyseBaratheon.spec.js
test/server/cards/02.5-COW/MirriMazDuur.spec.js
test/server/cards/agendas/TheLordOfTheCrossing.spec.js
test/server/integration/challengesphase.spec.js
test/server/integration/forcedreactionorder.spec.js

Adds an error message when the image fetch script can't find the appropriate pack code for a card instead of crashing. Also updates the submodule to the latest data.

Make image fetch more forgiving of missing packs

---

server/game/gamesteps/plotphase.js

As per the RRG, plots should cycle right after When Revealeds have been resolved, and before Melee title selection or plot phase action window.
https://thronesdb.com/rulesreference#1.3_Reveal_plots

Cycle plots right after When Revealeds have been resolved

---

README.md
package.json
webpack.config.js
webpack.config.vendor.js

Adds a `build-vendor:dev` script for local development. This fixes the
issue where building the vendor scripts in production mode but running
the server in development mode caused ReactDOMServer.renderToString to
crash.
Removes the `-p` option from the build scripts. This was conflicting
with the usage of UglifyJsPlugin, basically uglifying Javascript code
twice. See:
https://github.com/webpack/webpack/issues/1385#issuecomment-160553651
Removes the unnecessary passing of environment variables to Webpack.
Environment is now controlled completely using the `--env` option.

Fix webpack build scripts

---

server/game/MinMaxProperty.js
server/game/cards/01-Core/JoustingContest.js
server/game/cards/01-Core/TheKnightOfFlowers.js
server/game/cards/09-HoT/Besieged.js
server/game/cards/09-HoT/TourneyLance.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/cards/09-HoT/Besieged.spec.js

Previously, if two copies of Besieged were revealed at the same time,
the defender minimum would not reset properly after the next set of
plots were revealed. This was due to the second copy of Besieged seeing
the value set by the first one, and reseting it to that value. The bug
did not occur with double Jousting Contest because the maximum was being
explicitly reset at the start of the plot phase.
Now, both mins and maxs are stored on an array. Once all values are
unset, the default value will be returned again instead of overwriting
values.
~~Needs #1607 to be merged first~~
Fixes #1602

Handle setting multiple challenge limits at once

---

server/game/ambushcardaction.js
server/game/baseability.js
server/game/cardaction.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/marshalcardaction.js
server/game/triggeredability.js

To make it more clear that players are not following the rules, Action
abilities used outside an explicit action window now add a danger alert
in the game log.

Add alert when using actions outside of window

---

server/game/GroupedCardEvent.js
server/game/cards/05-LoCR/TywinLannister.js
server/game/player.js
test/server/cards/01-Core/Bodyguard.spec.js
test/server/player/discardcards.spec.js

After refactoring the event system and introducing the GroupedCardEvent,
Bodyguard was crashing when saving against discarding the card from
play. Now, the discard events are all in the same reaction window and
it's possible to save properly.
Fixes THRONETEKI-1P8

Use simultaneous event for discarding cards

---

less/cards.less

Positioning for dupes on Core Arya at card sizes other than "normal" did
not fully pull themselves above the parent card, thus pushing down any
additional cards attached.

Fix positioning of Core Arya dupes

---

client/GameComponents/Card.jsx
client/GameComponents/CardCounters.jsx

Previously, if a card had duplicates and one of its attachments was
unique and had duplicates, only the indicator for the duplicate was
displayed. Now both dupes are represented.
Fixes #1601

Display dupe indicator for card and attachments

---

server/game/cards/02.3-TKP/CroneOfVaesDothrak.js
server/game/cards/02.3-TKP/SerGregorClegane.js
server/game/cards/04.6-TC/BattleOfTheBlackwater.js
server/game/cards/07-WotW/NowMyWatchBegins.js
server/game/cards/08.1-TAK/NaggasRibs.js
server/game/drawcard.js
server/game/game.js
server/game/player.js
test/server/cards/08.1-TAK/NaggasRibs.spec.js
test/server/player/movecard.spec.js

Previously, duplicates were manually removed and placed in the discard pile without generating the events normally associated with discard. Now, when they're attached they record their parent card, allowing them to be discarded directly using the normal `discardCards` method.
Also fixes related card abilities that interact / move cards that are placed in discard - if the card is moved out discard before the ability is triggered (e.g. Now My Watch Begins vs Nagga's Ribs), the prompt for that ability will go away.
Fixes #1610 
Fixes #1623
Fixes #1639
Provides the groundwork for #1521 but additional effect engine changes seem to be required (effects applied to cards with location 'duplicate' instead of 'play area').

Allow dupes to be moved / discarded

---

server/game/cards/08.1-TAK/MagTheMighty.js

Have already seen this go wrong a couple of times, so a reminder seems appriopriate.

Clarify second Mag kill to resolve only when first was not saved

---

server/game/gamesteps/triggeredabilitywindow.js
server/game/triggeredability.js
test/server/card/cardreaction.spec.js
test/server/integration/playingevents.spec.js

* Removes prompt choices for already cancelled events (e.g. two copies of a cancel in hand)
* Remove timed prompt for already cancelled event (e.g. use a cancel, should not get a blank timed prompt afterward)
Fixes #1636

Fix double prompt for cancels

---

server/game/cards/08.2-JtO/ArianneMartell.js
server/game/cards/08.2-JtO/ChangeOfPlans.js
server/game/cards/agendas/TheRainsOfCastamere.js
server/game/game.js
server/game/player.js
test/server/cards/agendas/TheRainsOfCastamere.spec.js

Mostly this fixes the problem w/ Change of Plans inappropriately wiping out the schemes pile after plots got recycled.
I'm inclined to leave the ugliness on Arianne (setting the strength in a condition) w/ a TODO as-is in the interest of getting a working implementation out. 
The proper fix (taking a snapshot the moment the `AbilityContext` object is created for the ability) currently generates a somewhat hard to diagnose infinite loop in the effects engine related to the `onCardTraitChanged` and `onCardFactionChanged` events being raised when constructing a brand new `DrawCard` for the snapshot. 
The alternative suggestion of checking to see if the snapshot exists and using the current strength otherwise isn't a pattern I'd like to encourage. (Neither is this TBH but this looks obviously …

Implement Martell cards for Journey to Oldtown

---

server/game/cards/02.2-TRtW/PoliticalDisaster.js

The Political Disaster prompt selects locations to preclude from discarding, so the gameAction property preventing selection of cards that are immune/cannot be discarded doesn't fit here.

Remove gameAction property from Political Disaster prompt

---

client/reducers/cards.js

Previously, if a single deck in the deck list contained a card whose
code was not in the list of available cards, the entire deck list would
refuse to load. This situation likely only occurred in development mode,
after creating a deck with a card then reseting card data to a data set
that did not include that card. Now, such cards are simply filtered out
of the deck prior to validation.
Fixes #1576

Filter out cards missing card data from decks

---

client/reducers/cards.js

The client-side deck processing that occurs now assumes the deck data
already has arrays for `plotCards` and `drawCards`. This caused crashes
when creating a new deck because it was missing these fields.
Fixes THRONETEKI-1QX
Fixes THRONETEKI-1QW

Fix data format for new decks

---

server/game/cards/06.3-TFoA/SpearsOfTheMerlingKing.js

Fixes a bug where when multiple characters were dying at the same time, players had to guess which button corresponded to which character.

Show character being returned on button prompt for SpearsOTMK

---

less/cards.less
less/gameboard.less
less/variables.less
server/game/gamesteps/plotphase.js
server/game/player.js

* Increases the display offset for attachments when the card size is above the default
* Fixes spacing issues for kneeled attachments when the card size is not the default
* Increases the styling limit for attachments up to 10 attachments on a single card (previously 5)
* Properly clear "new" status from attachments.
Also offsets attachments to the right as suggested in lobby chat. This should make clicking on attachments a bit easier overall. 
If we don't want the offset (or want to think about it more), it's easy enough to drop the specific commit.

Fixes to attachment styling

---

server/game/plotcard.js

Fixes a bug where for example Calm over Westeros vs. Valar Morghulis could result in a -1 claim value.

Set claim minimum to 0

---

server/game/CardSelector.js
server/game/CardSelectors/BaseCardSelector.js
server/game/cards/01-Core/ConsolidationOfPower.js
server/game/gamesteps/selectcardprompt.js

This flag restricts SelectCardPrompt targets to a single controller. Fixes a bug where Consolidation of Power could be used to select characters from either player.
Fixes #1669.

Add a 'singleController'-flag to the target API

---

server/game/drawcard.js
server/game/player.js
test/server/integration/Bestow.spec.js
test/server/player/putintoplay.spec.js

Previously, if a character with Bestow came out during Fortified
Position, the player would be prompted for the bestow amount even though
Bestow keyword would be blanked. Now the prompt is delayed until after
the effects engine has a chance to apply effects to the card.
Fixes #1462

Allow effects to be applied before Bestow prompt

---

server/game/cardaction.js
server/game/gamesteps/abilityresolver.js
server/game/triggeredability.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/playingevents.spec.js

Previously, playing Risen from the Sea and Blood Magic Ritual did not
properly count as playing events because they change their card type to
'attachment' after resolving. Now, this check looks at the printed card
type and makes sure the event is still "being played" before placing in
discard.
Fixes #1675

Raise onCardPlayed event for attaching events

---

server/game/gamesteps/challenge/choosestealthtargets.js

Previously, the game step that prompted for stealth targets during a
challenge would check each character individually and pause the step if
they had no valid targets. This lead to a bug where if two or more
stealth characters were declared and the defender had no valid targets,
the pipeline would pause indefinitely.
Now, stealth characters that don't have valid targets are immediately
filtered out, allowing the game step to prompt without improperly
pausing.

Filter out stealth characters without targets

---

server/game/gamesteps/challenge/challengeflow.js
test/server/effects/doesNotKneelAsAttacker.spec.js
test/server/effects/doesNotKneelAsDefender.spec.js

The previous change to the effects engine where effects are recalculated
only after a game event has occurred caused the "does not kneel when
declared as an attacker" cards to stop working. This is because the
event for attackers being declared and being knelt happens
simultaneously, so the engine had no opportunity to see that the cards
shouldn't be knelt until after kneeling them.

Fix "does not kneel when declared as attacker"

---

server/game/AttachmentValidityCheck.js
server/game/player.js
test/server/integration/Attachments.spec.js

The addition of the attachment validity check lead to a bug where
non-terminal attachments did not return to hand properly. This was due
to the fact that by the time the asynchronous return to hand call
occurs, the parent of the attachment is already out of the play area,
which then triggers the attachment validity check to discard it instead.
Fixes #1719

Do not discard attachments that are being removed

---

server/game/effectengine.js
test/server/integration/plotphase.spec.js

With the previous change to the effects engine, conditional and state
dependent effects are queued up to be recalculated after each event.
However, certain events around revealing new plots cause those effects
to be removed. Since the effects were already queued, though, the engine
ended up reapplying the effect after it expired.
Now, the engine makes sure the effect is still in the list of active
effects before reapplying it.
Fixes #1722 
Fixes #1724

Do not recalculate effects that have expired

---

server/game/cards/05-LoCR/TommenBaratheon.js
server/game/cards/08.4-FotOG/TheKingInTheNorth.js
server/game/effect.js
test/server/cards/01-Core/AGameOfThrones.spec.js

Previously, when an effect was applied only to players that met a
matching condition (e.g. Tommen, The King in the North, A Game of
Thrones), an explicit recalculate was needed. The change to the way
effects are recalculated didn't take this into account, requiring an
always-true condition be added to such effects to ensure they were
recalculated. If that condition was missing, the effect would never be
reapplied properly.
This led to a bug where A Game of Thrones would not allow players
initiate military or power challenges, even after winning intrigue
challenges, because the effect wasn't removed from the player.
Now, all effects that target a player that also have a matching function
will automatically be considered a conditional effect and be
recalculated at the proper interval.
Fixes …

Automatically recalculate player-matched effects

---

server/game/cards/01-Core/SansaStark.js
server/game/cards/04.2-CtA/DolorousEdd.js
server/game/cards/05-LoCR/OldWyk.js
server/game/cards/10-SoD/Val.js
server/game/effectengine.js
server/game/effects.js
server/game/player.js
test/server/effectengine.spec.js

Now cards that enter play knelt (such as Core Sansa or Dolorous Edd's
ability) can be done directly by either applying an effect to the card,
or by passing a `kneeled` option into the `Player.putIntoPlay` method.
Note that the effect must be applied no matter where the card is
currently, because the act of entering play knelt completes before any
effects for in-play cards can be applied. For example, Sansa comes into
play knelt before the effects of Fortified Position can blank her card
text.

Convert "enters play knelt" to effect + option

---

server/game/cards/04.1-AtSK/BitterbridgeEncampment.js

Fixes a bug where a (non-triggering) player would not be allowed to put a unique character into play if that character would be in the triggering player's dead pile. Also standardizes a message and makes sure the card does not prompt to trigger when it's knelt.
Fixes #1746.

Check canPutIntoPlay() on correct player for Bitterbridge Encampment

---

server/game/cards/09-HoT/NothingBurnsLikeTheCold.js
server/game/drawcard.js

Previously, the target prompt for Nothing Burns Like the Cold precluded selecting locations that can't be discarded, but the hasValidLocations() check did not. This could lead to players being presented with a prompt with all targets greyed out, but after cancelling getting a message warning players they did have valid targets. This PR fixes that.

Don't show warning message for Nothing Burns when no valid locations

---

server/game/CardSelector.js
server/game/CardSelectors/BaseCardSelector.js
server/game/CardSelectors/EachPlayerCardSelector.js
server/game/cards/03-WotN/EvenHandedJustice.js
server/game/cards/06.4-TRW/TywinsStratagem.js
server/game/cards/08.5-TFM/Coldhands.js
server/game/game.js
server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/selectcardprompt.spec.js

- Adds a target mode that satisfies a target for each player, making such cards compatible with upcoming melee functionality and single-player.
- Instead of sequentially prompting for each separate player, all targets are selected in a single prompt.

Implement 'Each Player' targeting mode

---

server/game/AbilityContext.js
server/game/baseability.js
server/game/basecard.js
server/game/cards/06.1-AMAF/Ygritte.js
server/game/cards/agendas/TheHouseWithTheRedDoor.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/immunityrestriction.js
test/server/card/baseability.spec.js
test/server/card/cardaction.spec.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/gamesteps/abilityresolver.spec.js

Previously, immunity / cannot restrictions looked at an object that
contained the card and the current stage of resolution for the ability.
This was referred to as a "ability context" which overlapped with the
name given to the context that tracks the player using the ability and
cost / target resolution.
To reduce confusion and gain access to this additional information, the
actual AbilityContext object is tracked directly and used within the
immunity system.

Use ability contexts directly for immunity

---

server/game/GoldSource.js
server/game/cards/01-Core/TheThingsIDoForLove.js
server/game/cards/02.2-TRtW/BrothelMadame.js
server/game/cards/02.4-NMG/PaidOff.js
server/game/cards/02.4-NMG/RedCloaks.js
server/game/cards/04.6-TC/PodrickPayne.js
server/game/cards/05-LoCR/LannisportTreasury.js
server/game/cards/06.2-GtR/WexPyke.js
server/game/cards/06.5-OR/StannissCavalry.js
server/game/cards/08.1-TAK/TheIronBank.js
server/game/cards/08.2-JtO/TheHouseOfBlackAndWhite.js
server/game/cards/08.4-FotOG/SweetCersei.js
server/game/chatcommands.js
server/game/costs.js
server/game/effects.js
server/game/game.js
server/game/gamesteps/ChooseGoldSourceAmounts.js
server/game/gamesteps/bestowprompt.js
server/game/player.js
test/server/cards/08.1-TAK/TheIronBank.spec.js
test/server/costs/payreduceablegoldcost.spec.js

~**DO NOT MERGE until #1806 and #1807 are merged**~
For review purposes until the other 2 PRs are merged, you can look at https://github.com/ystros/throneteki/compare/b630c5f...ystros:iron-bank-final?expand=1
This works by explicitly prompting the user when they want to spend gold during the eligible phase. If there aren't multiple ways to combine the gold in their pool and the gold on the card, then the gold will be spent automatically without prompting. Examples:
* 4 gold in pool, 1 on Iron Bank. Marshal a 5 cost character. All gold spent automatically, no prompting.
* 1 gold in pool, 4 on Iron Bank. Marshal a 5 cost character. All gold spent automatically, no prompting.
* 4 gold in pool, 2 on Iron Bank. Marshal a 5 cost character. Player is prompted whether they want to spend 1 or 2 …

Fully implement Iron Bank and Sweet Cersei

---

server/game/drawcard.js
test/server/card/drawcard.modifyPower.spec.js

Previously, `DrawCard.modifyPower` always applied a 'gain power' action
to the card, regardless of whether power was being gained or lost. This
lead to a bug where Your King Commands It would prevent not only power
from being gained but also power being discarded from cards.

Distinguish between gaining and discarding power

---

server/game/basecard.js
server/game/challenge.js
server/game/effectengine.js
server/game/game.js
test/server/cards/04.5-GoH/DragonglassDagger.spec.js
test/server/cards/agendas/TheLordOfTheCrossing.spec.js

Adds an `isDirty` flag to cards whose state has changed that might require recalculation of existing effects that target them. Examples:
* [Theon (TFoA)](https://thronesdb.com/card/06051) is attacking alone. No one with STR greater than him can contribute strength to defense. A character with greater STR that has [Dragonglass Dagger](https://thronesdb.com/card/04086) attached is declared as a defender. As soon as they become a defender, the ability for Dragonglass Dagger kicks in, making them immune to opponent abilities. Thus, the "does not contribute strength" effect from Theon needs to be deactivated for that character.
* A player with [Lord of the Crossing](https://thronesdb.com/card/02060) initiates their first challenge with a Night's Watch character while [Jon Snow …

Reliably recalculate effects after state change

---

client/GameBoard.jsx
client/GameComponents/PlayerHand.jsx
client/GameComponents/PlayerRow.jsx
server/game/CardSelector.js
server/game/CardSelectors/BaseCardSelector.js
server/game/cards/01-Core/SeenInFlames.js
server/game/cards/03-WotN/HisViperEyes.js
server/game/cards/06.2-GtR/Melisandre.js
server/game/cards/08.1-TAK/QueensMen.js
server/game/cards/10-SoD/FalseSpring.js
server/game/drawcard.js
server/game/gamesteps/selectcardprompt.js
server/game/playerpromptstate.js
test/server/card/drawcard.getsummary.spec.js
test/server/integration/playingevents.spec.js

- Adds a flag to select card prompts that reveals selectable cards that are otherwise facedown, for example cards in an opponent's hand.
- Allows cards like Seen in Flames and His Viper Eyes to use a select card prompt, instead of menu buttons.
- This mirrors earlier changes that converted cards targeting the faction card to switch from menu buttons to target prompts.

Allow select card prompts to reveal facedown targets & Implement False Spring

---

server/game/cardaction.js

Fixes a bug where Seen in Flames could be played when no opponents had cards in hand to trigger Melisandre.
Fixes #1497.
Fixes #1791.

Disallow triggering action abilities when no valid opponents

---

client/reducers/cards.js

The deck validator relies on the restricted list having been loaded, so
validation needs to be delayed until after. Once the list has been
loaded, any loaded decks are reprocessed.
Fixes THRONETEKI-1ZQ

Delay validation until restricted list loads

---

server/game/gamesteps/plotphase.js
server/game/player.js

Previously, if a player used /cancel-prompt to skip the plot selection
step, the game would enter an unplayable state that continually threw
errors. Now if they have no plot card selected and cancel the prompt,
the game will continue as best it can with the other players that have
selected their plot.
Fixes THRONETEKI-1J9
Fixes THRONETEKI-1M9

Handle players without plot cards

---

server/game/cardaction.js
server/game/triggeredability.js
test/server/cards/10-SoD/ObaraSand.spec.js

Previously, if an ability had both a cost that caused the card to leave
and a limit, the limit would be improperly incremented after the card
left play. This could cause cards like Obara Sand (SoD) to only be
usable once per phase, despite the rules saying the limit should reset
when they leave / re-enter play.
Fixes #1850

Fix ability limit when card leaves play as cost

---

server/game/drawcard.js
test/server/card/drawcard.getsummary.spec.js

Returning information about a card's strength and the icons while it's
facedown can make it guessable what card it may be. This is a potential
problem during setup, for cards in hand, and cards in the upcoming
Shadow zone.

Do not reveal strength / icons for facedown cards

---

client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/CardTiledList.jsx
client/Components/GameBoard/PlayerRow.jsx
less/gameboard.less

* Scales the size of the popup based on the card size selected (previously stuck on normal sized calculations, so you'd get more wrapping if you set card size to large or extra large)
* Updated styling for grouped cards in the popup.
Normal:
Select plot:
Select Rains:

Update styling for pile popup groups

---

client/Components/GameBoard/Card.jsx

Make sure the card component is using the wrapped version of itself for attachments so that they have the drag related functions
Fixes attachments crashing the client

Fix client crash when attachments are marshalled

---

client/ReduxActions/socket.js
server/lobby.js

send the game id with the handoff message
use this game id on the client to not hand off to a game socket that it's already connected to

Fix reconnecting to games when the lobby socket bounces

---

client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/CardTiledList.jsx

Cards in a card list should be oriented by the type of card they are -
horizontal for plot cards, vertical for everything else.
Before:
After:

Fix kneeling cards in dead pile popup

---

client/Components/GameBoard/Card.jsx

Fixes bug introduced in #1858 
Before:
After:

Plots should not be displayed as "kneeled" in UI

---

server/game/player.js

Fixes a bug where Hotah's Axe through its ability could be attached in multiples to a character even though it is unique.
Fixes #1877.

Check for dupes in player.attach

---

server/game/gamesteps/challengephase.js

- Pre-challenge action window
- Player1 is prompted to initiate a challenge
- Player1 completes challenges
- Player2 is prompted for challenges
- Pre-challenge action window
- Player1 is prompted to initiate a challenge
- Player1 completes challenges
- Pre-challenge action window
- Player2 is prompted for challenges

Add pre-challenge action window after first player completes challenges

---

.babelrc
client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/MovablePanel.jsx
client/Components/GameBoard/PlayerPlots.jsx
client/Components/GameBoard/PlayerRow.jsx
client/Components/GameBoard/PopupDefaults.js
client/constants.js
client/index.dev.jsx
less/gameboard.less

Allow dragging of window titles to move the windows
save the positions the windows are in in the browser
fix hot reloading
repurpose PopupLocation property to refer to the board side, rather than the popup location

Implement movable card windows

---

server/game/basecard.js
server/game/cardaction.js
server/game/cards/02.3-TKP/TheLordOfTheCrossing.js
server/game/cards/03-WotN/SansaStark.js
server/game/cards/07-WotW/DothrakiHonorGuard.js
server/game/cards/08.5-TFM/DaenerysTargaryen.js
server/game/costs.js
server/game/effect.js
server/game/effects.js
server/game/game.js
server/game/triggeredability.js
test/server/card/cardaction.spec.js
test/server/cards/08.5-TFM/DaenerysTargaryen.spec.js
test/server/effect.spec.js

Allows specific game actions (such as `'decreaseStrength'`) be specified at the effect level, allowing the effect engine to check immunity to specific types of effects prior to targeting / applying the effect to a card.

Check game actions on effect targets / fix TFM Dany

---

server/game/AbilityTarget.js
test/server/AbilityTarget.spec.js
test/server/card/baseability.spec.js

Currently, costs are paid and no message is shown so it can be confusing for opponents

Add an alert when a targetting prompt was cancelled

---

server/game/cards/08.6-SAT/MyaStone.js

Character, Neutral, Bastard
Cost: 4
STR: 2
Icons: Power
Interruption: when the claim for a military or an intrigue challenge where you are the defending player should apply, kneel Mya Stone to apply a power claim instead.

Implement Mya Stone

---

README.md
client/Components/Games/PendingGame.jsx
client/Components/Games/SelectDeckModal.jsx
client/ReduxActions/cards.js
client/reducers/cards.js
less/common.less
server/api/decks.js
server/lobby.js
server/scripts/importstandalonedecks.js
server/services/DeckService.js

Adds the ability for people to play with the standalone decks such as the 2016 and 2017 World Championship decks, and the upcoming individual House Intro decks. This should make things a bit more friendly for new users, allowing them to immediately start playing without having to create or upload a deck of their own.
Need to make sure submodules are updated and run `node server/scripts/importstandalonedecks.js` to import the decks.
New user:
User with a few decks:
User with a lot of decks:

Add standalone, pre-made decks

---

server/game/basecard.js
server/game/cards/05-LoCR/SweetDonnelHill.js
server/game/cards/08.5-TFM/IAmNoOne.js
server/game/drawcard.js
server/game/effects.js
test/server/effects/LosesAll.spec.js

Per a new ruling, a card that "loses all" of something, such as
keywords, faction affiliation, or traits, loses all instances of that
thing instead losing one instance of each.
http://www.cardgamedb.com/forums/index.php?/topic/39647-ruling-i-am-no-one/?p=328947.

Fix "loses all" effects

---

server/game/drawcard.js

Previously, Randyll Tarly with Strangler could stand after modifying his strength through for example Wardens of the South. This PR fixes that by only raising the event if the character's strength is not set.

Only raise onCardStrengthChanged if strength is not set

---

client/Components/GameBoard/AbilityTimer.jsx
client/Components/GameBoard/ActivePlayerPrompt.jsx
client/Components/GameBoard/GameBoard.jsx
client/ReduxActions/game.js
client/ReduxActions/prompt.js
client/actions.js
client/reducers/index.js
client/reducers/prompt.js

Converts the ability timer on prompts to store state in redux, in order to allow cancellation of the timer where cards are clicked or menu items triggered.
Prep work for converting ability window prompts to use clicking cards to trigger their abilities instead of menu buttons.

Convert ability timer to use redux

---

server/game/AtomicEvent.js
server/game/SimultaneousEvents.js
server/game/cards/02.5-COW/PullingTheStrings.js
server/game/cards/04.1-AtSK/VaryssRiddle.js
server/game/cards/04.6-TC/TyrionsChain.js
server/game/cards/10-SoD/AtPrinceDoransBehest.js
server/game/event.js
server/game/game.js
server/game/gamesteps/BaseAbilityWindow.js
server/game/gamesteps/ForcedTriggeredAbilityWindow.js
server/game/gamesteps/InterruptWindow.js
server/game/gamesteps/TriggeredAbilityWindow.js
server/game/gamesteps/eventwindow.js
server/game/gamesteps/revealplots.js
server/game/plotcard.js
test/server/cards/04.2-CtA/SummerHarvest.spec.js
test/server/cards/10-SoD/AtPrinceDoransBehest.spec.js
test/server/gamesteps/BaseAbilityWindow.spec.js
test/server/gamesteps/ForcedTriggeredAbilityWindow.spec.js
test/server/gamesteps/TriggeredAbilityWindow.spec.js
test/server/gamesteps/eventwindow.spec.js

* Ensures that first player gets to choose plot order after a new plot has been revealed by Behest
* Adds the capability to have a separate interrupt window with combined reactions, allowing proper interrupt / reaction timing after a new plot has been revealed by Behest.
* Fixes timing on ability copiers like Varys's Riddle to resolve the copied ability in the context of their own "When Revealed" event (necessary w/ Behest, otherwise it generates a nested sequence)
Fixes #1864

Fix timing for At Prince Doran's Behest

---

client/Components/GameBoard/ActivePlayerPrompt.jsx
client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardPile.jsx
client/ReduxActions/game.js
client/ReduxActions/prompt.js
server/game/forcedtriggeredability.js
server/game/gamesteps/AbilityChoicePrompt.js
server/game/gamesteps/BaseAbilityWindow.js
server/game/gamesteps/TriggeredAbilityWindow.js
server/game/gamesteps/selectcardprompt.js
server/game/playerpromptstate.js
server/game/promptedtriggeredability.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/card/cardreaction.spec.js
test/server/cards/05-LoCR/TywinLannister.spec.js
test/server/cards/06.2-GtR/TheAnnalsOfCastleBlack.spec.js
test/server/cards/09-HoT/EmissaryOfTheHightower.spec.js
test/server/cards/10-SoD/Missandei.spec.js
test/server/gamesteps/BaseAbilityWindow.spec.js
test/server/gamesteps/TriggeredAbilityWindow.spec.js
test/server/integration/challengesphase.spec.js

* When prompted for an interrupt or reaction window, players now click on the card they want to trigger directly instead of clicking menu buttons.
* If the same card can trigger on multiple simultaneous events (e.g. Marya Seaworth when multiple characters are bypassed from stealth), the player is then prompted to click on the card associated with the event.
* If the card has multiple choices (e.g. LoCR Tyrion), the choice is presented in a button menu after the card is chosen.
* Action abilities continue to be triggered through card-level menus during the appropriate action window.
* When revealed and forced interrupt / reaction order continues to be chosen by button prompts for now.
I highly recommend pulling this locally to try it out rather than reviewing solely based on code changes.

Click cards to trigger interrupt / reaction abilities

---

server/game/CardSelector.js
server/game/CardSelectors/BaseCardSelector.js
server/game/gamesteps/TriggeredAbilityWindow.js
test/server/integration/immunity.spec.js

Fixes an issue where Pleasure Barge could not be triggered after
marshalling it because the ability trigger prompt thought Pleasure Barge
was immune.

Allow abilities of immune cards to be triggered

---

server/game/gamesteps/ForcedTriggeredAbilityWindow.js
test/server/cards/10-SoD/AtPrinceDoransBehest.spec.js
test/server/gamesteps/ForcedTriggeredAbilityWindow.spec.js

When At Prince Doran's Behest was revealed as the only plot with a 'when
revealed' ability, the ability window was closing immediately after
executing Behest. This lead to the plot revealed by Behest not
executing, because the window it would be executed in was already
closed.
Now, the 'when revealed' ability window will stay open until it has done
one final cycle and verified there are no more abilities needing to be
executed.

Ensure plot revealed by Behest triggers

---

server/game/game.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js

Previously, triggering an action ability outside of an action window
would print a warning in chat except during the marshal phase. Because
the marshal phase was excluded, actions could be used without warning
even when they were outside the normal marshal phase window. For
example, actions used while another ability was being resolved or
while a player was being prompted for interrupts / reactions did not
properly give the warning.
Fixes #1966

Add warning for actions during marshal phase

---

server/game/cards/08.6-SAT/HostOfTheRiverlands.js

`Game.addPower` works exclusively on players, `Card.modifyPower` should
be used on cards.
Fixes THRONETEKI-26V

Use correct method for Host of the Riverlands

---

server/lobby.js

The server side validation was marking decks with rookery cards as
invalid even though client-side they were fine. This was because the
card data for the rookery cards was incomplete on the server.

Fix rookery validation when selecting a deck

---

server/game/basecard.js
server/game/cards/08.6-SAT/SaltcliffeSailor.js
test/server/cards/08.6-SAT/SaltcliffeSailor.spec.js

Some effects like Saltcliffe Sailor depend on the state of tokens on
cards, so cards should be marked as dirty after tokens are modified to
ensure proper recalculation.
Fixes #1974

Recalculate effects after tokens have changed

---

server/game/cards/05-LoCR/HighSepton.js
server/game/gamesteps/TriggeredAbilityWindow.js
server/game/gamesteps/TriggeredAbilityWindowTitles.js

Limits High Septon to triggering on and choosing characters, and updates the prompt to display the same targeting indicator used for cancel abilities:
Fixes #1980 
Fixes #1981

Fix High Septon triggers + add better UI

---

server/api/cards.js
server/game/Factions.js
server/game/deck.js

Faction data for decks is inconsistently stored in the database -
sometimes it has the name / label for the faction, sometimes it doesn't.
This will ensure that the faction name is always associated with the
card data for the faction card.

Always look up faction name

---

server/game/basecard.js
test/server/integration/effects.spec.js

Previously, attachment related `whileAttached` effects were always
active, using a matching function to limit its targets to only the
parent card (if there was one). This led to crashes when the effect was
dependent on a parent card being present, such as Tokar. Now, the
attachment must have a parent before the effect is applied, and losing
the parent will immediately unapply the effect entirely instead of
recalculating.
Fixes THRONETEKI-26R

Only apply attachment effects if there's a parent

---

server/game/costs/KillCost.js

Currently Given to the Drowned God allows to use in-hand cards to pay its
cost. While that could be fixed in the card, as per the rules killed characters
"leave play", so they have to be in play to be killed. Hence this change, which
enforces the fact that kill costs can be played only using in-play cards.

kill costs can be payed only using in-play characters

---

package-lock.json
package.json
server/game/cards/11.1-TSC/BeneathTheBridgeOfDream.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/revealplots.js

Currently the timing is implemented as before either player chooses their plot card. This may not be correct but I'd rather wait for a full ruling on timing before putting more time into it.

Implement Beneath the Bridge of Dream

---

server/game/game.js
server/game/gamesteps/killcharacters.js
server/game/player.js
test/server/integration/ManualActions.spec.js
test/server/player/drop.spec.js

Dragging and clicking cards should always work now, even if they have an associated "cannot" effect applied to them.
Fixes #1104

Allow manual actions to override effects

---

server/game/drawcard.js
test/server/integration/Attachments.spec.js

Previously, blanking an attachment did not blank the attachment
requirements imposed by the card text (e.g. only certain factions, only
opponent cards, etc). Normally this doesn't make a difference, but if an
attachment specifies that it goes on a location, blanking should cause
it to revert to an attachment for characters, which should cause the
attachment to be discarded as invalid.
Fixes #2014

Remove restrictions when blanking an attachment

---

server/game/game.js
server/gamenode/gameserver.js

since failed connect notices trigger whenever anything bad happens on the socket, even after connecting, don't let those received after initial connect is made allow the game to be considered 'finished'

Fix games being killed off when a player reconnects

---

server/game/cards/01-Core/BodyGuard.js
server/game/cards/01-Core/MaesterAemon.js
server/game/cards/01-Core/RisenFromTheSea.js
server/game/cards/02.5-COW/BloodMagicRitual.js
server/game/cards/02.5-COW/IronMines.js
server/game/cards/02.6-TS/SerBarristanSelmy.js
server/game/cards/03-WotN/HealingExpertise.js
server/game/cards/03-WotN/JoryCassel.js
server/game/cards/04.6-TC/PodrickPayne.js
server/game/cards/05-LoCR/VictarionGreyjoy.js
server/game/cards/06.4-TRW/StrongBelwas.js
server/game/cards/06.6-TBWB/BericDondarrion.js
server/game/cards/07-WotW/Ghost.js
server/game/cards/08.2-JtO/ThorosOfMyr.js
server/game/cards/09-HoT/SerDontosHollard.js
server/game/event.js
server/game/game.js
test/server/cards/04.4-TIMC/ValarMorghulis.spec.js
test/server/integration/takecontrol.spec.js

Previously, we used fake plural events such as onCharactersKilled to
simulate simultaneous resolution. Since then, support has been added for
simultaneous events as well as better UI for choosing which event you
want to match when triggering an ability. It is now possible to
implement saves directly on the singular onCharacterKilled event.

Implement saves using singular events

---

server/game/effect.js
server/game/effects.js
test/server/cards/08.5-TFM/DaenerysTargaryen.spec.js

Setting a card value to a lower value than it currently has should be
considered "reducing" the value, not just when manually subtracting from
the value. Thus, Daenerys (TFM) should be immune to the strength setting
effect applied by Strangler.
Ruling: http://www.cardgamedb.com/forums/index.php?/topic/39646-ruling-daenerys-targaryen-tfm-strangler/

Setting STR to lower value is considered reducing

---

server/game/AtomicEvent.js
server/game/event.js
server/game/game.js
server/game/gamesteps/BaseAbilityWindow.js
server/game/gamesteps/InterruptWindow.js
test/server/AtomicEvent.spec.js
test/server/game/openInterruptWindowForAttachedEvents.spec.js
test/server/gamesteps/BaseAbilityWindow.spec.js
test/server/gamesteps/eventwindow.spec.js

* Adds the ability to chain post-handlers onto an event using `thenExecute`. This is useful for generalizing callbacks within the event system (e.g. shuffling the deck after moving Benjen into it) rather than relying on every method needing a callback parameter.
* Updates atomic events so that they aggregate all of the event properties of their children. This is mostly so that the `card` property is available on the parent atomic event but may be useful in other scenarios as well. e.g. you should be able to access the `card` property of the atomic combination of a kill event and a leaves play event.
* Fixes the way attached events are executed. Previously it was executing the handler for the events twice if the event was attached in a handler - once inside the handler (because it was …

Event system enhancements

---

server/game/ChallengeTypes.js
server/game/cards/01-Core/CalmOverWesteros.js
server/game/cards/01-Core/OlennasInformant.js
server/game/cards/01-Core/UnbowedUnbentUnbroken.js
server/game/gamesteps/challengephase.js
server/game/gamesteps/iconprompt.js
server/game/playerpromptstate.js
test/helpers/integrationhelper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/01-Core/AGameOfThrones.spec.js
test/server/cards/02.2-TRtW/BrothelMadame.spec.js
test/server/integration/challengesphase.spec.js

If a player cannot initiate another challenge of a certain type (met their limit for that type of challenge already, restricted by something like Game of Thrones, etc), the button for that challenge type will be disabled.
Using the `/reset-challenges-count` command will live-update an existing challenge prompt.

Disable challenge buttons for invalid challenges

---

server/game/TitlePool.js
server/game/basecard.js
server/game/cards/02.5-COW/PullingTheStrings.js
server/game/cards/04.1-AtSK/VaryssRiddle.js
server/game/cards/04.6-TC/TyrionsChain.js
server/game/drawcard.js
server/game/effects.js
server/game/game.js
server/game/player.js
test/server/card/basecard.takeControl.spec.js
test/server/integration/takecontrol.spec.js
test/server/player/putintoplay.spec.js

In order to properly revert control back to the most recent control
effect, take control effects are now tracked on a stack.
Lasting effects that take control pass along the source card so that
when they expire, just their controller can be reverted. This prevents
newer controllers from being overwritten when older effects are expired.
Permanent, source-less take control simply clears the stack and adds the
new controller directly.
Fixes #1904

Track controller changes by card source

---

server/game/cards/01-Core/ThrowingAxe.js
server/game/cards/02.5-COW/StinkingDrunk.js
server/game/cards/02.5-COW/WinterfellCrypt.js
server/game/cards/03-WotN/JoryCassel.js
server/game/cards/03-WotN/Needle.js
server/game/cards/03-WotN/RickonStark.js
server/game/cards/03-WotN/WinterfellHeartTree.js
server/game/cards/04.1-AtSK/CaptainsDaughter.js
server/game/cards/04.5-GoH/Craster.js
server/game/cards/04.5-GoH/Harrenhal.js
server/game/cards/04.5-GoH/RooseBolton.js
server/game/cards/06.2-GtR/ScorchingDeserts.js
server/game/cards/06.3-TFoA/SpearsOfTheMerlingKing.js
server/game/cards/06.4-TRW/ImprovedFortifications.js
server/game/cards/07-WotW/JeynePoole.js
server/game/cards/08.1-TAK/Ashemark.js
server/game/cards/08.1-TAK/DreadfortMaester.js
server/game/cards/08.1-TAK/Oathkeeper.js
server/game/cards/09-HoT/LionsTooth.js

Cards that sacrifice themselves as cost need to refer to
`context.player` instead of `this.controller` because if they were
controlled by an opponent, the controller reverts back to its owner
after the sacrifice completes and before targeting / handler for the
ability executes.
Fixes #1790

Use ability's player instead of controller

---

server/game/cards/08.6-SAT/TheCrowIsATricksyBird.js
server/game/cards/11.1-TSC/BeneathTheBridgeOfDream.js
server/game/player.js

Beneath the Bridge of Dream should only randomly select non-Scheme plots
in a Rains deck because the Scheme plots are not considered part of the
plot deck during the plot phase.
Fixes #2064

Fix Bridge of Dream + Rains interaction

---

server/game/cards/08.4-FotOG/Nymeria.js
server/game/cards/11.2-TMoW/SteelRain.js
server/game/costs.js
server/game/costs/CostBuilder.js

Fixes a bug where "Steel Rain" could be played without sacrificing any locations.

Differentiate kneel/sacrifice *any* costs by whether 0 is allowed

---

server/game/cards/03-WotN/AryasGift.js

Fixes a bug where, after having moved an opponent's attachment with Aryas Gift, the opponent was unable to use that attachment to trigger Trading with Qohor.

Don't change attachment controller after moving with Aryas Gift

---

server/gamenode/gameserver.js
server/util.js
test/helpers/gameflowwrapper.js
test/helpers/playerinteractionwrapper.js

Since integration tests do not run an actual game server + socket.io,
the tests would not detect changes that added unserializable data to
either game messages or as properties on player or card state. Now the
integration tests check that there is no unserializable data in the game
state that would be sent to the client after every player input in the
tests.

Check for unserializable data in integration tests

---

server/game/cards/11.2-TMoW/TradingWithQohor.js

Also make sure only attachments with equal or lower printed cost can be searched.

Limit Qohor to search different cards by name

---

server/game/gamesteps/taxation/DiscardToReservePrompt.js
server/game/gamesteps/taxationphase.js

Previously, the prompt to discard down to reserve was being created at
the beginning of each round. Because of this, the `remainingPlayers`
array was always in first player order for the previous round, which may
not match the first player order for the current round after plots are
revealed.
Now the prompt is created on demand when the proper step in the pipeline
has been reached.
Additionally, a message has been added when a player does not have to
discard to meet reserve to make it more clear for both players and
spectators on what's happening.

Ensure first player order for reserve prompt

---

server/game/gamesteps/challenge/challengeflow.js

Fixes a bug where this effect was executed incorrectly after challengeOptions was converted to a reference counted set property.

Fix mustBeDeclaredAsDefender effect

---

server/game/basecard.js

The carddata does not include loyalty data for neutral cards anymore, which caused a bug where Turncloak could not be attached to neutral characters as the attachment check was trying to match undefined to false.
Fixes #2122.

Force boolean on card loyalty check

---

docs/implementing-cards.md
server/game/cards/06.2-GtR/ScorchingDeserts.js
server/game/cards/06.3-TFoA/SpearsOfTheMerlingKing.js
server/game/cards/07-WotW/MaryaSeaworth.js
server/game/cards/09-HoT/WardensOfTheSouth.js

Since reactions/interrupts are triggered by clicking cards instead of buttons, this property serves no function anymore.

Remove unused title property from reactions/interrupts

---

server/game/gamesteps/TriggeredAbilityWindowTitles.js

* This makes it clearer which card is triggering for example Harrenhal (GoH).
* Fixes #2129.

Add triggered ability window title for onCardEntersPlay event

---

server/game/cards/01-Core/MarchedToTheWall.js
server/game/cards/01-Core/Varys.js
server/game/cards/02.2-TRtW/PoliticalDisaster.js
server/game/cards/09-HoT/NothingBurnsLikeTheCold.js
server/game/game.js
server/game/player.js
test/server/cards/01-Core/Varys.spec.js
test/server/player/discardcards.spec.js

Previously, abilities that discarded cards from play controlled by
multiple players were implemented using for loops to either discard each
card individually, or discard each set of cards per player. Because it
was done sequentially, this could lead to bugs where a card leaving play
earlier than the others could change the outcome of the discard (e.g. if
TFM Arya leaves play before other characters with potential saves).
Now all cards are grouped into a single bundle and discarded at once.
This can only be applied to cards that are in play currently - cards
discarded simultaneously from hand (Bastard Daughter) or deck
(Greensight) still need individual events in order to properly trigger
cards like LoCR Tywin. Another solution will be needed for such
abilities.
Fixes #2128

Allow simultaneous discard across multiple players

---

server/game/CardSelectors/BaseCardSelector.js
server/game/CardVisibility.js
server/game/basecard.js
server/game/drawcard.js
server/game/game.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js
server/game/playerpromptstate.js
test/server/CardVisibility.spec.js
test/server/card/basecard.spec.js
test/server/card/drawcard.getsummary.spec.js

Previously, the logic about who could see which cards was spread across
multiple classes - Player class controlled the visibility of cards
within individual piles, the Card classes controlled it via properties
passed into their getSummary methods, and logic for revealed in-hand
cards appeared in multiple spots related to card selection prompts.
By centralizing it, the overall logic should be more clear.
Additionally, adding the ability to add new visibility rules should make
it easier to implement upcoming cards like Stolen Message, which reveal
cards publicly instead of only to a specific player.

Centralize how card visibility is handled

---

server/game/effects.js

Fixes an issue where House with the Red Door was giving players 8 gold
during setup instead of 4 gold like it should.

Setup gold effect should be applied to players

---

server/game/cards/11.3-SoKL/GrowingAmbition.js

Growing Ambition requires the player pay at least 1 gold for X. However,
if the player does not choose their card in the deck search prompt, the
ability would crash.
Fixes THRONETEKI-2A6

Handle choosing no cards w/ Growing Ambition

---

server/game/basecard.js

Previously, it was assumed that the Player.playCard method would only be
called with draw card objects. However, as we've generalized click
behavior it can now be reached with both plot and agenda card objects,
which was crashing. Adding a default implementation in BaseCard that
returns no possible play actions prevents this crash.
Fixes THRONETEKI-2A3

Add getPlayActions to base card class

---

server/game/PlayActions/OutOfShadowsAction.js
server/game/player.js
test/server/integration/ShadowKeyword.spec.js

Recently, card IDs were added to the data for facedown cards in order to
support cards like Hired Assassin and Valyrian's Crew. However, this
revealed an existing bug where a player could bring out opponent's cards
from shadow under their own control. It simply never could occur before
because the client was not sent the IDs for in-shadow cards.
Now, the out-of-shadows action uses the same "playable location"
mechanism that is used for marshalling, ambushing, and playing in-hand
cards, preventing opponents from using them by default. The playable
location mechanism should also automatically support any cards in the
future that do allow you to bring opponent cards out-of-shadow (similar
to Night Gathers allowing marshalling from opponent discard pile).
Fixes #2171

Limit out-of-shadows action to controlling player

---

server/game/CardVisibility.js

If a duplicate is not facedown, an opponent should be able to see the
card used.

Fix duplicate visibility

---

server/game/costreducer.js

Reducers such as Hizdahr zo Loraq that have no characteristic
requirement for the reduction (e.g. being a certain faction, being a
character, etc) should also reduce any card marshalled into shadows.
http://www.cardgamedb.com/forums/index.php?/topic/39948-ruling-hizdahr-zo-loraq/

Hizdahr zo Loraq reduces marshalling into shadow

---

server/game/cards/11.3-SoKL/GrowingAmbition.js

Cleans up language of the prompt for Growing Ambition after converting
it to a card select prompt, as well as adding messages for cancellation
cases and removing the call to a cleanup method that was removed.
Fixes THRONETEKI-2AJ

Fix crash + language on Growing Ambition

---

server/game/PlayActions/MarshalCardAction.js
server/game/PlayActions/MarshalIntoShadowsAction.js
server/game/PlayActions/SetupCardAction.js
server/game/PlayActions/SetupInShadowsAction.js
server/game/baseability.js
server/game/cardaction.js
server/game/drawcard.js
server/game/triggeredability.js
test/helpers/playerinteractionwrapper.js
test/server/integration/Duplicates.spec.js

Using a dupe to save is considered a "game ability" instead of a "card
ability." Since manual dupes are set up as using the ability system,
they were improperly considered a "card ability" when cards like
Winterfell, Core Catelyn, or King in the North were in play.
Now, abilities can be defined as a game ability and thus skip the checks
involved with effects preventing card abilities.

Allow dupes when card abilities prevented

---

server/game/basecard.js
server/game/cardaction.js
server/game/game.js
test/helpers/playerinteractionwrapper.js
test/server/card/cardaction.spec.js

Also remove menus entirely for actions opponents can't trigger (i.e. every existing Action ability except Bronn).
Requires front end from throneteki/throneteki-client#41
Progress toward #2212

Disable menu items for unusable actions

---

server/game/drawcard.js
test/server/integration/Duplicates.spec.js
test/server/integration/takecontrol.spec.js

Prior to implementing manual dupes, there was no way for a player to use
the dupes on a character that was stolen from them. After manual dupes
was implemented, they could save stolen character if they had the manual
dupe option turned on. However, using automatic dupes still left no
option to save stolen characters.
Now, players will be prompted whether they want to use the dupe or pass
on a stolen character, regardless of whether they have the manual dupe
option turned on.
Fixes #2214

Always prompt for dupes on stolen characters

---

server/game/player.js

Reverses the order of the out-of-game pile so that the last card added
to the pile displays first, as with the discard and dead piles.
Fixes #2230

Display newest out-of-game card first

---

server/game/drawcard.js

Previously, if an X strength character reached 0 STR (e.g. a Stark-less
Dacey Mormonet or Beric Dondarrion with no kiss tokens), their strength
wouldn't be displayed by the client. This is because the client was
checking the numerical printed value of strength against the current
strength. For X STR characters, that's 0.
By sending 'X' STR to the client directly instead of 0, the client can
decide whether it should display a 0 STR value.
Suggested in #2216

Send 'X' strength to client

---

server/game/gamechat.js

The Free Folk agenda was displaying the player receiving claim using
their avatar, like a chat message from that player. This is because the
`Claim.recipients` field is an array in case of Master of Whispers in
melee, and player objects in arrays used the avatar. Now, only chat
messages are explicitly formatted to display with avatars.
Fixes #2226

Format arrays of players without using avatars

---

server/game/anonymousspectator.js

When an error occurs, the current game state is serialized for the error
report as if an anonymous spectator were watching the game. However, the
spectator detection changed in #2228 was not applied to the
AnonymousSpectator class, causing a crash when an error report would
occur.
Fixes THRONETEKI-2BB
Fixes THRONETEKI-2BC

Anonymous spectators are spectators

---

server/game/gamesteps/actionwindow.js
test/server/cards/04.5-GoH/Craster.spec.js
test/server/gamesteps/actionwindow.spec.js
test/server/gamesteps/dominancephase.spec.js

Previously, when a single player had an action window setting turned on,
only the player with the setting turned on would be prompted. Any player
without the setting turned on would auto-pass when it was their turn in
the action window, unless another player had actually taken an action.
This could lead to confusion for players that do not understand that
they will auto-pass without the option turned on. A typical scenario
would be first player has the window off, and thus auto-passes. Then,
the second player has the window on, and uses an action. Then, the first
player, not realizing they auto-passed, complains that they should have
had the first opportunity to use an action.
To alleviate this confusion, auto-pass has been removed unless all
players have the action window turned off. If …

Prompt all players for actions when setting is on

---

server/game/cards/11.6-DitD/StarfallSpy.js

Rationale: "to choose *another* card you control in shadows"

Starfall Spy: do not allow to select itself

---

server/game/EventTrackers/CardEntersPlayTracker.js
server/game/cards/01-Core/GoldCloaks.js
server/game/cards/05-LoCR/ShaggaSonOfDolf.js
server/game/cards/11.4-MoD/GreyGhost.js
server/game/drawcard.js
server/game/player.js
test/server/cards/01-Core/GoldCloaks.spec.js
test/server/player/putintoplay.spec.js

* Only discards Gold Cloaks during the phase it was ambushed. The previous `wasAmbush` flag never got reset, so it would cause Gold Cloaks to be discarded in subsequent phases if it were blanked previously.
* Ensures that the discard cannot be saved per card text
* Generalizes tracking of cards coming into play with `CardEntersPlayTracker`, which can be extended for different durations (challenge, round, etc) or actions (was marshalled, general was put into play) as needed.
Fixes #2321

Various fixes to Gold Cloaks

---

server/game/effectengine.js
test/server/integration/burneffects.spec.js

Previously, lasting effects that buffed and then burned a character
could end up killing the character if they expired simultaneously. The
STR buff would expire first, putting the character at 0 STR and thus
killing the character before even attempting to expire the burn effect.
Now, just as effects are applied in a specific order, they are expired
in reverse order from which they were applied. This should ensure that
negative effects are expired first, preventing STR from improperly
reaching 0 and thus killing the character.
Fixes #2328 
Fixes #1706

Expire effects in reverse order

---

server/game/cards/01-Core/Heartsbane.js
server/game/cards/04.3-FFH/CrownOfGoldenRoses.js

Previously, Heartbane and Crown of Golden Roses were generating a
lasting effect that applied to any card it was attached on, instead of
only the card it was attach on when the ability triggered. This led to a
bug where if the attachment was moved to another character, the new
character would improperly gain the effect applied to its original
parent.
Fixes #2325

Apply attachment lasting effect to specific parent

---

server/game/cards/12-KotI/Reckless.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/challenge/ChooseParticipantsPrompt.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/challenge/ChooseParticipantsPrompt.spec.js
test/server/gamesteps/selectcardprompt.spec.js

Also:
* Shows auto-declared attackers / defenders within the select prompt instead of adding them after selection. Future improvement could be to highlight these unselectable cards in a different color.
* Extracts the "must be declared" and minimum participant logic into its own class, so that it can be used for both attackers and defenders.

Implement Reckless

---

server/game/Constants.js
server/game/PlayActions/MarshalCardAction.js
server/game/PlayActions/MarshalIntoShadowsAction.js
server/game/challenge.js
server/game/gamesteps/drawphase.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/setup/keepormulliganprompt.js
server/game/gamesteps/setupphase.js
server/game/player.js
test/server/PlayActions/MarshalCardAction.spec.js
test/server/gamesteps/setup/keepormulliganprompt.spec.js
test/server/integration/marshalphase.spec.js
test/server/player/revealsetupcards.spec.js

Moves game flow rules off of the `Player` class so that it can concentrate on methods that directly mutate the player or return info about it.
Bonus: fixes the long standing bug that allowed players to marshal outside of their turn.
Theoretically fixes #1851 by blocking double clicks earlier in the keep or mulligan prompt.

Move phase logic off player

---

server/game/gamesteps/DeckSearchPrompt.js

Previously, full deck searches would reveal all cards in all draw decks,
regardless of owner. This was hidden by the fact that the top of
opponent draw decks always displayed as a facedown card. However, the
implementation of Stolen Message changed this behavior to display the
card if it was visible, revealing the bug.
Now, card visibility for full deck searches is explicitly limited to
cards in your own draw deck.

Only reveal your own draw deck on searches

---

server/game/cards/10-SoD/SpareBoot.js
test/helpers/integrationhelper.js
test/server/cards/10-SoD/SpareBoot.spec.js

Spare Boot's ability is worded such that he can stand an attachment that
could not be moved to him (e.g. Seal of the Hand) or one that is already
attachment to him.

Allow Spare Boot to stand unusable attachments

---

docs/implementing-cards.md
server/game/AbilityMessage.js
server/game/baseability.js
server/game/cards/01-Core/SealOfTheHand.js
server/game/cards/12-KotI/BalonGreyjoy.js
server/game/cards/12-KotI/CitadelArchivist.js
server/game/cards/12-KotI/Cohollo.js
server/game/cards/12-KotI/DanceOfTheDragons.js
server/game/cards/12-KotI/EagerDeckhand.js
server/game/cards/12-KotI/Fury.js
server/game/cards/12-KotI/MaesterMurenmure.js
server/game/cards/12-KotI/MaidensBane.js
server/game/cards/12-KotI/MyMindIsMyWeapon.js
server/game/cards/12-KotI/OldGreyGull.js
server/game/gamesteps/abilityresolver.js
test/server/AbilityMessage.spec.js
test/server/gamesteps/abilityresolver.spec.js

Adds a `message` property to triggered abilities in order to allow
messages to be output before the handler for the ability executes. This
will allow messages to be output to the game log before players are
prompted for cancel abilities (Treachery, Hand's Judgment, etc). It will
also enable the game action mechanism in the future, which will require
removing / replacing the existing `handler` property for abilities.

Allow ability messages defined outside of handler

---

server/game/effectengine.js
test/server/cards/11.6-DitD/AssaultFromTheShadows.spec.js

PR #2361 changed the way lasting effects get applied to cards within the
effect engine, causing Assault from the Shadows and Banished from the
Light no longer allowing the card to be brought out of shadows. Now
effects can explicitly be applied to cards in shadow.
Fixes #2382

Allow effects on cards in shadow

---

server/scripts/implementation-status.js

This is a fuller version of the script I used to generate #2376 and #2377. Can be used to regenerate those lists once more card data has been entered while keeping the checkboxes checked for implemented cards.

Add script to generate implementation status list

---

server/game/cards/10-SoD/GrandMelee.js
server/game/effects.js
test/server/cards/10-SoD/GrandMelee.spec.js

Recalculates Grand Melee's effect after every game step in order to
ensure that its "does not contribute STR" effect is added or removed
when the number of participants change. Additionally, challenge strength
is now recalculated when the "does not contribute STR" effect is applied
to a card.
Fixes #2231

Fix Grand Melee when adding/removing participants

---

server/game/cards/12-KotI/MaesterMurenmure.js

For card abilities from taken-control cards that have a sacrifice cost
(e.g. Iron Mines, Sea Bitch, etc), `event.source.controller` will refer
to the wrong player by the time Murenmure triggers. Thus, his triggering
condition should be based on `event.player` instead, which is the player
that initially triggered the ability.
Fixes #2418

Trigger Murenmure based on triggering player

---

server/game/costs/XValuePrompt.js
test/helpers/playerinteractionwrapper.js
test/server/cards/11.6-DitD/GiftsForTheWidow.spec.js

Previously, if a card that had an X cost whose value could only be 0,
the prompt would be skipped without setting the `xValue` on the context
object. This lead to the player's gold becoming `NaN` for the rest of
the game with no way to recover. The most common scenario was playing
Gifts for the Widow while having no gold - you'd want to search for a 0
cost attachment but it would trigger the bug.
Now, the XValuePrompt will properly ask the player to choose the number,
even if it's only 0. As a safety measure, if the prompt is called with
an invalid range, it automatically resolve for the lower end of the
range to ensure an `xValue` is always set. While this would still be a
bug, it would be less catastrophic than rendering gold useless the rest
of the game.
Fixes #2419

Allow "pay X gold" prompts to have a 0 maximum

---

server/game/cards/01-Core/RisenFromTheSea.js
server/game/drawcard.js
test/server/integration/burneffects.spec.js

Before October 2017, it was ruled that characters killed by burn would
die at their STR before the burn was applied. For example, Quentyn
Martell killed by Dracarys! would be able to trigger his ability to
target a character with less than 4 STR.
Then it was re-ruled in FAQ 1.2 that they should die at STR 0 after all,
as would be common sense. I guess it's about time we changed it back?
Fixes #1643

The Sordid Tale of Quentyn Martell continued

---

server/game/chatcommands.js

Previously, persistent effects for a card that are normally activated
during the setup phase were not being activated when adding a new card
mid-game via `/add-card`. This made cards like Sansa Stark (Core)
created via `/add-card` not enter play knelt properly.
Fixes #2388

Activate non-play-area effects for /add-card

---

server/game/cards/01-Core/RisenFromTheSea.js
server/game/cards/02.5-COW/BloodMagicRitual.js
test/helpers/playerinteractionwrapper.js
test/server/cards/01-Core/RisenFromTheSea.spec.js

Previously, the +1 STR effect on Risen from the Sea and the blanking
effect on Blood Magic Ritual were implemented as persistence effects.
This resulted in losing the effect when blanked by Brother's Robes,
which should only blank printed text and not gained text.
Now these effects are implemented as lasting effects that are active
while the cards remain in play.
Fixes #2433

Change Risen / BMR text to lasting effect

---

server/game/cards/08.2-JtO/DevanSeaworth.js

Previously, we looked through the deck for the minimum cost location
that could be put into play using Devan Seaworth's ability. This does
not reflect real games where you need to remember whether you still have
locations with the specified cost remaining in your deck. Now, player's
will be prompted with 1 up to the bestow amount, regardless of whether
there are valid locations with those costs.

Remove minimum from Devan Seaworth's cost

---

server/game/cards/02.1-TtB/TheWatchHasNeed.js

Previously, triggering The Watch Has Need while you had 0 reserve would
allow you to search your entire deck for NW characters. This is because
the select prompt views `numCards: 0` as being able to select unlimited
cards. Now, Watch Has Need cannot be triggered because it isn't possible
to search through the top 0 cards of your deck.

Prevent Watch Has Need when player has 0 reserve

---

server/game/cards/13.1-AtG/AtTheGates.js

Parenthetical "instead" clauses are not optional, so the chosen card
should always be put into play for At the Gates when there are no City
plots in the used pile.

Do not allow player choice for At the Gates

---

server/game/cardaction.js
server/game/cards/13.1-AtG/DragonGate.js
server/game/cards/13.1-AtG/FleaBottomAlley.js
server/game/cards/13.1-AtG/GateOfTheGods.js
server/game/cards/13.1-AtG/IronGate.js
server/game/cards/13.1-AtG/KingsGate.js
server/game/cards/13.1-AtG/LionGate.js
server/game/cards/13.1-AtG/OldGate.js
server/game/cards/13.1-AtG/RiverGate.js

Because the Gate cards from At the Gates sacrifice themselves as a cost,
they *must* refer to `context.player` instead of `this.controller`
because the controller does not reflect the player that controlled the
card before sacrifice.
Also pass `context` to `condition` methods to further reduce the usages
of `this.controller`.
Fixes #2468

Use `context.player` on Gate locations

---

server/gamenode/gameserver.js

The plain text log is easier to read than the rich-object array the
messages are actually represented with.

Send plain text log to Sentry

---

server/game/gamesteps/ForcedTriggeredAbilityWindow.js
server/game/gamesteps/revealplots.js

* Adds a message announcing which plot each player has revealed to make
it easier to follow the game within the log
* Simplifies the message when first player chooses the order of
resolution for plots

Improve messages for the plot phase

---

server/game/gamesteps/ResolvedTargets.js
test/server/ResolvedTargets.spec.js

In order to support "if able" and "each player" target selections, the
value of the selection now has to allow null. The ability cancellation
UI tries to display a list of chosen cards, but was crashing due to null
values being in the array.
Now, null selections and unresolved selections are filtered out of that
array.
Fixes THRONETEKI-2EV
Fixes THRONETEKI-2EZ

Filter out null target selections

---

server/game/cards/02.5-COW/PullingTheStrings.js
server/game/cards/04.1-AtSK/VaryssRiddle.js
server/game/cards/04.6-TC/TyrionsChain.js
test/server/cards/13.1-AtG/AtTheGates.spec.js

Because Varys's Riddle is implemented to temporarily "take control" of
the plot, when At the Gates is copied and brings out a card that applies
an effect to opponent plot card (such as Gates of the Moon), the current
controller is incorrect and the effect isn't applied. Since Riddle
wasn't raising the `onCardTakenControl` event, the effect engine never
knew to recalculate the effect.
Fixes #2503

Fix Gates of the Moon w/ Riddle + AtG

---

server/game/cards/13.2-CoS/BlackMarketMerchant.js

Fixes the Issue #2511
The problem was that the card was just put into play with no restrictions. This made it so you could target any card. I used the card 'Gifts for the Widow' as a reference as that seemed to work without the bug. To keep everything the same i changed a bit of the naming, so that it is in line with the other card.

Fixed Black Market Merchant Bug #2511

---

server/game/game.js

After converting kneel/stand to use game actions that totally wrap the
state change in an event, the message generation for manual kneel/stand
was backwards because it depended on the state changing immediately

Fix message for manual kneel/stand clicks

---

server/game/cards/14-FotS/CapeWrath.js
server/game/cards/14-FotS/DesperateAttack.js

Both Cape Wrath and Desperate Attack need to be explicitly applied to
any controller and not just the current one.
Fixes #2601

Fix claim increase effects for FotS

---

server/game/SimultaneousEvents.js
test/server/SimultaneousEvents.spec.js

This should fix the issue with dupes not properly saving vs Poltical
Disaster, Varys (Core), and other simultaneous discards.
The SimultaneousEvents class groups together a series of events for
simultaneous execution. However, if one of those events is cancelled, it
should not be executed. The Event class itself achieves this by marking
a `parent` event object and notifying the parent to remove the event
upon cancellation. This mechanism is not directly possible with
simultaneous events because each event may have its own parent already.
Now, the SimultaneousEvents class will manually filter through cancelled
child events to ensure that they are properly excluded.
Progress towards #2600

Do not execute cancelled simultaneous events

---

server/game/ServerCommands/DropCommand.js
test/server/ServerCommands/DropCommand.spec.js

The DiscardCard game action enforces the fact that you can't "discard"
from your dead pile. Thus, dragging cards from the dead pile to the
discard pile should now do a general move instead of "discarding" it.
Fixes #2600

Fix dragging from dead pile to discard pile

---

server/game/cards/14-FotS/DothrakiSteed.js

It should only be active while the attached character is attacking.
Fixes #2609

Limit STR boost for Dothraki Steed

---

server/game/challenge.js
server/game/drawcard.js
server/game/gamesteps/challenge/challengeflow.js
test/server/cards/14-FotS/AzorAhaiReborn.spec.js

Limits stealth character to those declared as attackers, and adds a test around removing the only other R'hllor character to ensure Azor Ahai gets kicked out of the challenge.
Fixes #2644 
Fixes #2594

Fixes for Azor Ahai Reborn

---

server/game/cards/04.1-AtSK/RubyOfRhllor.js

The card was missing the attachmentRestriction so it can only be attached to R'hllor characters
Closes #2659

add attachmentRestriction for Ruby of R'hllor

---

server/game/triggeredability.js
test/server/cards/13.3-PoS/MaesterGormon.spec.js

Maester Gormon requires that event cards listen to game events even
while in the draw deck. The ability system should already prevent event
card abilities from triggering while the card is not in a playable
location - Maester Gormon simply makes the top of the deck a playable
location.
Fixes #2664

Allow event abilities to trigger from draw deck

---

server/game/AbilityContext.js
server/game/AbilityTarget.js
server/game/ThenClauseAbility.js
server/game/cardaction.js
server/game/cards/10-SoD/ForcedMarch.js
server/game/game.js
server/game/triggeredability.js
test/server/cards/10-SoD/ForcedMarch.spec.js

* Prevents Forced March from allowing the player to kneel a character to re-initiate the effect unless the opponent has valid targets.
* Allows the re-initiated effect to be cancelled separately from the initial effect.
Fixes #2663

Fix targeting and cancellation of Forced March

---

server/game/cards/13.4-BtRK/DoubtingSepta.js

not 100% sure about the target restriction "card.canGainPower()". The card reads "After you win an INT challenge, sacrifice Doubting Septa to choose a character or location you control. That card gains 1 power". I would say the card to choose must be able to gain power else the effect couldn´t resolve fully. Appreciate any feedback!

implement Doubting Septa

---

server/game/cards/14-FotS/DaleSeaworth.js

* Fixes typo that prevented his reaction from firing
* Properly restricts the ability to Baratheon locations
Fixes #2677

Fix Dale Seaworth

---

server/game/cards/13.5-TB/ShadowOfTheRose.js

not 100% sure if the order of actions happening is correctly implemented this way. the card reads that first you choose the card to put into shadows, then shuffle your deck and then optionally return shadow of the rose to shadows. I do not know if the shuffling of the deck executed by the promptForDeckSearch happens after the complete resolution of the onSelect and onCancel handler functions or not. In any case, i do not think it matters that much if you first return the card to shadows and then shuffle or do it the other way around.
Appreciate any feedback!

implement shadow of the rose

---

server/game/cards/13.4-BtRK/TunnelsOfTheRedKeep.js
test/server/cards/13.4-BTRK/TunnelsOfTheRedKeep.spec.js

Per rules on lasting effects, the value should be fixed at the time of
initiation. So cards leaving or entering shadows should not affect the
STR bonus.

Make Tunnels of Red Keep STR bonus fixed

---

server/game/cards/05-LoCR/UnexpectedDelay.js
test/server/cards/05-LoCR/UnexpectedDelay.spec.js

When two or more players choose the same character to be returned to
hand for Unexpected Delay, it should only return that character a single
time. This means if the owner has a single duplicate on the card, it can
be saved.
Fixes #2724

Handle same character chosen for Unexpected Delay

---

server/game/basecard.js
server/game/drawcard.js
test/server/card/basecard.spec.js

Previously, we were only looking at the very first line for keywords.
However, Forest Patrol has keywords on two separate lines.
Now, keyword parsing looks at all lines that don't have a triggered
ability (anything wrapped in \<b\> element). Additionally, initial card
set up based on the card text has been moved to a new
setupCardTextProperties method for slightly better organization.
Fixes #2732

Handle keywords on multiple lines

---

server/game/AtomicEvent.js
server/game/Constants/Tokens.js
server/game/GameActions/DrawCards.js
server/game/GameActions/ReturnGoldToTreasury.js
server/game/GameActions/SimultaneousAction.js
server/game/GameActions/ThenAbilityAction.js
server/game/GameActions/index.js
server/game/NullEvent.js
server/game/SimultaneousEvents.js
server/game/cards/04.3-FFH/RenlyBaratheon.js
server/game/cards/13.5-TB/HighgardenJester.js
server/game/cards/13.6-LMHR/AryaStark.js
server/game/event.js
server/game/insightkeyword.js
server/game/player.js
test/server/AtomicEvent.spec.js
test/server/Event.spec.js
test/server/GameActions/DrawCards.spec.js
test/server/GameActions/ReturnGoldToTreasury.spec.js
test/server/GameActions/SimultaneousAction.spec.js
test/server/GameActions/ThenAbilityAction.spec.js
test/server/SimultaneousEvents.spec.js
test/server/player/movecard.spec.js

* Converts drawing cards into a game action.
* Removes explicit Insight event in favor of a `reason` on the draw cards event.
* Updates events and game actions to allow the concept of fully resolving. E.g. when drawing 2 cards, if you're only able to draw 1 card then the action did not fully resolve. Thus any subsequent "Then" actions should not resolve.
Progress towards #2641

Implement Arya Stark (LMHR)

---

server/game/GameActions/LookAtDeck.js
server/game/GameActions/PlaceToken.js
test/server/GameActions/LookAtDeck.spec.js
test/server/GameActions/PlaceToken.spec.js
test/server/cards/07-WotW/LingeringVenom.spec.js

Any event that has an `amount` property needs a corresponding
`desiredAmount` property if used with "Then" abilities. The lack of
`desiredAmount` was preventing Lingering Venom from killing characters
after placing a token.
Fixes #2770

Ensure PlaceToken and LookAtDeck events resolve

---

server/game/cards/13.3-PoS/TheFaithsDecree.js

observing a game i noticed that the message parameters were in the wrong order

fix the order of the message parameters on the faiths decree

---

server/game/cards/13.5-TB/TheBloodyCup.js

moveCard doesn't generate an event covered by dupes, but
moveCardToTopOfDeck does.
Fixes #2757

Allow Bloody Cup to be saved

---

server/game/player.js

A check was added when searching for a duplicate that the in-play card
isn't facedown, to ensure facedown attachments under Dothraki Handmaiden
aren't counted. However, all cards in setup are facedown, so it
prevented placing duplicates during setup.

Allow dupes of facedown card during setup

---

server/game/cards/15-DotE/SerMerynTrant.js

Because Ser Meryn Trant's ability is an interrupt and not a reaction,
and because it uses the word "instead", the ability needs to use a
replacement handler. Otherwise, the card will be moved out of the game
immediately, and then placed in the discard pile from the normal
onCardDiscarded event handler.
Fixes #2850

Use replacement handler for Meryn Trant

---

server/game/CardMatcher.js
server/game/CardSelectors/BaseCardSelector.js
server/game/cards/15-DotE/BlueGraces.js

Since Blue Graces removes itself from the game as a cost,
`this.controller` will always refer to the card's owner, not the player
that initiated the ability.

Refer to current player for Blue Graces

---

server/game/gamesteps/abilityresolver.js

Previously, if /cancel-prompt was used during a cost-related prompt for
an ability, the immediate prompt would be cancelled, but then
AbilityResolver.cancelled would be overridden afterwards. This then
forced the player to continue resolving the ability in a bad state.
Fixes #2866

Fully cancel ability during cost resolution

---

server/game/cards/04.1-AtSK/RubyOfRhllor.js
server/game/cards/13.3-PoS/TheFaithsDecree.js
server/game/cards/13.6-LMHR/TheIronThrone.js
server/game/cards/14-FotS/ThePrinceThatWasPromised.js
server/game/cards/15-DotE/DragonstoneConvert.js
server/game/game.js
server/game/gamesteps/CardNamePrompt.js

Previously, card abilities that required you to name a card used basic
menu prompts and did checks on the cards manually. This introduces a
special prompt that makes it easier to limit the card named to given
`match` criteria, and better handles if the player does not name a card.
Fixes #2867 
Closes #2848

Add a prompt to handle naming cards

---

server/game/cards/15-DotE/ChampionsChallenge.js

Fix Champion's Challenge can be triggered multiple times per phase if the character strength condition has been met. The plot says "Limit once per phase" so this restriction should be applied as well.

Fix Champion's Challenge can be triggered multiple times per phase

---

server/game/cards/11.3-SoKL/ValyriansCrew.js
server/game/cards/15-DotE/ArchmaesterMarwyn.js
server/game/cards/15-DotE/DothrakiHandmaiden.js
server/game/effects.js

According to my search, this affects the following three cards:
* Archmaester Marwyn
* Valyrian Crew
* Dothraki Handmaiden
Note that the rules are a bit complex here: Similar effects that
have *any* limitation to the card e.g. Maester Gormon do not allow
marshalling into shadows.
This fixes #2932

Allow cards to be marshalled into shadows through card effects

---

server/game/cards/16-TTWDFL/BenjensCache.js

Benjen's Cache searches for any card with no conditions, so the player is
not required to reveal the card to prove it matches the search.
Fixes #2946

Prevent Benjen's Cache from revealing card

---

server/game/cards/03-WotN/Motley.js
server/game/cards/06.4-TRW/BreakerOfChains.js
server/game/gamesteps/challenge/challengeflow.js

Previously, there were aggregate events for when attackers
and defenders were declared in a challenge. This was causing
cards that used the events like Motley and Breaker of Chains
to trigger for characters that were added to the challenge
via an effect (e.g. Azor Ahai).
These cards have been reimplemented to use the singular
events for declaring an attacker or defender (which will not
fire if added by an effect), and the aggregate event has
been removed.
Fixes #2954

Remove attackers / defenders declared event

---

server/game/costs/KneelCost.js
server/game/costs/StandCost.js

The cost system was put into place before there was an effect
that prevented either kneeling or standing. This updates the
corresponding costs to use game actions to ensure that it
checks that the card can be knelt / stood.
Fixes #2955

Ensure Black Cells is respected for costs

---

server/game/cards/15-DotE/WyllaManderly.js

For any kill or sacrifice events, they should look at the card
state when the event initiated instead of the current card so
that take control doesn't cause the ability to trigger for the
wrong player.
Fixes #2965

Trigger Wylla based on original card state

---

server/game/drawcard.js

Previously, the logic to check if a card had a printed
STR value returned false for 0 STR characters due to
it coercing the STR value into a boolean. However, unlike
printed costs, all characters have a printed STR.
Fixes #2964

Allow Water Dancer's Sword on 0 STR chars

---

server/game/cards/02.4-NMG/Halder.js

currently halders ability targets characters that are in out of play areas which leads to the deck, discard and dead pile to pop up and highlight the valid cards. This is a problem and could potentially be abused because now you see your deck and can derive information from this, for example how many characters are in the next 10 cards of your deck.

fix so halder can´t target out of play characters

---

server/game/cards/14-FotS/ShyraErrol.js

currently she moves only 1 power as that is the default amount value of the movePower Gameaction

fix amount of power moved by shyra errol

---

server/game/cards/15-DotE/TheLostMessage.js
test/server/cards/15-DotE/TheLostMessage.spec.js

It has been ruled for The Lost Message that if one of the players
has 0 cards in hand, the pre-then condition is still considered to
be successful. Therefore, the players with cards in hand should be
able to add cards back to their hand.
Fixes #2983

Fix The Lost Message interaction w/ 0 cards

---

server/game/CardMatcher.js
server/game/cards/13.1-AtG/CityOfSecrets.js

Previously, City of Secrets immediately checked whether the
player had 2 cards in hand after calling the draw method.
However, this method is now asynchronous, so if a player had
fewer than 2 cards in hand before the draw, they would not
be required to discard 2 cards.
Similarly, since the card did not use a proper Then check,
if either player was unable to draw 2 cards, the discard
would still trigger.
Fixes #2971

Fix City of Secrets then clause

---

server/game/cards/13.4-BtRK/DoubtingSepta.js

Because Doubting Septa sacrifices itself to activate its ability, the
controller may change if it is taken from another player. Thus, the
card chosen to gain power should be the initiating player, not the
controller after Doubting Septa is in the discard pile.
Fixes #2994

Use initiating player for Doubting Septa

---

server/game/player.js

fix so that the player with knights of the hollow hill can´t setup cards in shadows. I had a look at the stuff for the cannotSetup effect and why that didn´t work for setting up in shadows.

knights of the hollow hill shadows setup

---

server/game/CardMatcher.js
server/game/cards/01-Core/BuildingOrders.js
server/game/cards/01-Core/CallingTheBanners.js
server/game/cards/01-Core/CountingCoppers.js
server/game/cards/01-Core/FilthyAccusations.js
server/game/cards/01-Core/HeadsOnSpikes.js
server/game/cards/01-Core/Rebuilding.js
server/game/cards/01-Core/Reinforcement.js
server/game/cards/01-Core/Summons.js
server/game/cards/02.1-TtB/HereToServe.js
server/game/cards/02.2-TRtW/TradingWithThePentoshi.js
server/game/cards/02.5-COW/PullingTheStrings.js
server/game/cards/06.5-OR/WheelsWithinWheels.js
server/game/cards/07-WotW/CalledIntoService.js
server/game/cards/08.6-SAT/YouWinOrYouDie.js
server/game/cards/10-SoD/AtPrinceDoransBehest.js
server/game/cards/11.1-TSC/ExchangeOfInformation.js
server/game/cards/12-KotI/HeirToTheIronThrone.js
server/game/cards/12-KotI/ReturnToTheFields.js
server/game/cards/13.1-AtG/AtTheGates.js
server/game/cards/13.2-CoS/ACityBesieged.js
server/game/cards/13.4-BtRK/CityOfSpiders.js
server/game/cards/13.6-LMHR/ExposeDuplicity.js
test/server/cards/13.1-AtG/AtTheGates.spec.js

Gets rid of `this.controller` within each plot that Pulling the Strings can interact with, so we no longer need to do a fake take-control to initiate the ability. This means that the At The Gates plot being initiated no longer counts as a City plot in your own used pile.

Fix Pulling the Strings + At the Gates interaction

---

server/game/cards/13.2-CoS/KnightsOfHollowHill.js
server/game/effects.js
server/game/player.js

… so it doesn´t prevent a player from marshalling into shadows while barring the gates or similar effects are active

fix canPutIntoShadows 

---

server/game/ChessClock.js
server/game/chatcommands.js
server/game/game.js
server/game/gamesteps/attachmentprompt.js
server/game/gamesteps/marshaling/marshalcardsprompt.js
server/game/gamesteps/menuprompt.js
server/game/gamesteps/plot/firstplayerprompt.js
server/game/gamesteps/selectcardprompt.js
server/game/gamesteps/uiprompt.js
server/game/player.js
server/lobby.js
server/pendinggame.js
test/server/gamesteps/playerorderprompt.spec.js
test/server/gamesteps/selectcardprompt.spec.js
test/server/gamesteps/uiprompt.spec.js

Players can now choose to use a chess clock to time their games.
Chess clocks provide a time limit per player. The time will start running if a player has an active prompt and after an initial delay of 5 seconds.
There are also two new chat commands:
- /pause-clock to pause the chess clocks (other time limit not yet implemented) so both clocks will stop running until /pause-clock is called a second time.
- /add-chess-clock-time to add time to the calling players clock (in case someone disconnects and the clock keeps running and players agree to add the lost time)

Chessclocks

---

server/game/Deck.js
server/game/cards/index.js

Adds the ability to override stats by defining a `cardData` object on the card implementation class. This object will be merged into the existing card data JSON and only override the pieces of data defined. For example, if you wanted to override Arya Stark's cost, you could define the following:
```javascript
const DrawCard = require('../../drawcard.js');
class AryaStark extends DrawCard {
// full ability definition here
}
AryaStark.code = '01141';
AryaStark.cardData = {
"cost": 8
};
module.exports = AryaStark;
```
This PR also limits the files loaded as card definitions to only JS files. This will allow server operators to clone a Git repository with just card definitions into the `/server/game/cards/` directory. Because cards are loaded in order by directory name, you can name the …

Add basic support towards overriding cards for playtesting

---

server/game/cards/13.3-PoS/UnexpectedGuile.js

resolves #3025 
found out that the difference between moveCard(card, shadows) and putIntoShadows(card) is the way which event gets fired after the card is moved. For the saving of the moved card to work correctly and still work if the user has "prompt before using dupes to save" active, a putIntoShadowsEvent needs to be fired, which currently is fired by the putIntoShadows function before moving the card. moveCard on the other hand does not fire this event and only works with auto-saving the card with dupes

fix unexpected guile so the character can be saved

---

server/api/events.js
server/game/game.js
server/pendinggame.js

I made some extensions to the event functionality:
1. I added game options to be set for every game of the event. These options will be set when a user chooses an event in the event dropdown of a new game and will be fixed so the user can´t change these.
2. I added the option to have a list of valid spectators for an event so that judges/streamers can be put on that list and join any game of that event but no regular users not on that list can´t.
(also have a look at the corresponding client PR)

Add event game options and list of valid spectators

---

server/game/cards/17.1-R/DesertRaider.js
server/game/player.js

remove unnecessary putIntoPlay in DesertRaider´s handler
prevent cards from entering play when they already are in the play area

Fix Desert Raider (R) and Prized interaction when entering play from the dead pile

---

server/game/GameActions/InitiateChallenge.js
server/game/challenge.js
test/server/cards/02.3-TKP/TheLordOfTheCrossing.spec.js
test/server/challenge/removefromchallenge.spec.js

this let´s Randyll Tarly trigger to the STR increase from the third crossing challenge again.
characters are now considered to be attacking/defending only when the challenge´s isInitiated flag is true, which is now set after the call to initiateChallenge has been performed. Before, characters were attacking after the promptForAttackers step, which broke a (some?) card interaction like Randyll Tarly and the lord of the crossing

Fix Randyll Tarly+The Lord of the Crossing interaction

---

server/api/events.js
server/lobby.js

An event was able to choose to use it´s custom RL or the default RL. Now that there are two default RL´s to choose from, original and redesigns, an event needs to be able to choose which one of the default RL´s to use. This PR adds this option to an event.
This PR also changes the way the restricted list for a game is determined when creating a new game. It now looks up the default or custom restricted list of the chosen event.
resolves #3048 (via the [client PR](https://github.com/throneteki/throneteki-client/pull/120) )
resolves #3049

Add default restricted list to events

---

test/server/cards/11.3-SoKL/KingsLanding.spec.js

specify which King´s Landing to use in KingsLanding.spec.js to remove the multiple cards match name warning

specify which King´s Landing to use in KingsLanding.spec.js

---

server/game/cards/17.1-R/BoundForTheWall.js

This limit disappeared in the reimplementation. I added exactly the
code that the original implementation is using.

[bugfix] Add limit of once per challenge to redesignbound for the wall

---

server/game/cards/16-TTWDFL/AloofAndApart.js
test/server/integration/Prized.spec.js

so that characters that were placed in the setup also gain the prized keyword
resolves #3014

add a condition to the Prized giving effect of Aloof and Apart

---

server/api/cards.js
server/services/CardService.js

this leads to the redesigned RL coming first and being the default selection for client side dropdowns

sort the restrictedList array by release date

---

server/game/ChallengeMatcher.js
server/game/cards/02.3-TKP/TheLordOfTheCrossing.js
server/game/challenge.js
test/server/cards/12-KotI/TheKnight.spec.js

A previous fix aimed at Randyl Tarly and Lord of the Crossing
changed when a character was considered attacking. This broke
The Knight's ability to gain stealth before the challenge was
officially initiated.
The attacking / defending check has been reverted, and instead
Lord of the Crossing has been modified to only apply the
strength buff after the challenge has been initiated.
Fixes #3059

Fix the Knight gaining stealth

---

server/game/EventTrackers/GenericTracker.js
server/game/cards/13.4-BtRK/CastleGuard.js

Check for the onCardOutOfShadows event instead of whether a card
was put into play with the 'outOfShadows' meta-action.
Fixes #3000

Fix Castle Guard target condition

---

server/game/cards/12-KotI/Karhold.js

The cards that Karhold is applied to needs to change as new plots are
revealed. Adding an explicit condition to the effect ensures the effect
is continuously recalculated.
Fixes #2783

Ensure Karhold persistent effect gets recalculated

---

server/game/challenge.js
server/game/gamesteps/menuprompt.js
server/game/gamesteps/selectcardprompt.js

In single player games, we create a fake defending player during challenges
to avoid special casing every ability to handle a missing defending player.
This leads to a problem on abilities that prompt the defending player, such
as Late Summer Feast, since there's no player to respond to the prompt.
Now the menu and card select prompts will immediately complete themselves
if the player being prompted is the fake player. This may not cover every
case, but it should fix many of the existing hanging prompts.
Fixes #3027

Automatically complete prompts for fake players

---

server/game/cards/19-JS/TyrionLannister.js

fix tyrion lannister JS targetLocation so that dupes will be moved to the bottom of the deck

fix tyrion lannister JS targetLocation so that dupes will be moved

---

server/game/costs/XValuePrompt.js
test/helpers/playerinteractionwrapper.js
test/server/cards/09-HoT/MeleeAtBitterbridge.spec.js
test/server/cards/11.6-DitD/GiftsForTheWidow.spec.js
test/server/cards/17.1-R/GiftsForTheWidow.spec.js

currently only XValuePrompt is affected
fixes #3082 
and probably fixes some of the upcoming cards that may prompt the player to select a token type
also take a look at the related client PR here: https://github.com/throneteki/throneteki-client/pull/132

add new prompt for selecting a value from an array of values 

---

server/game/cards/09-HoT/JoustingPavilion.js
test/server/cards/09-HoT/JoustingPavilion.spec.js

fix the jousting pavilion + knighted + randyll tarly interaction so that the str buff reaction of randyll works
we fixed randyll + lord of the crossing some time ago, but jousting pavilion´s usage of hasSingleParticipant is not enough because without checking for initiated it is already true before randyll gets knelt as an attacker

fix the jousting pavilion + knighted + randyll tarly interaction 

---

server/game/GameActions/SacrificeCard.js
test/server/GameActions/SacrificeCard.spec.js

Replaces #3128 
Also switches to using the `snapshotName` event mechanism to record card state.

Make sacrifice and leave play simultaneous

---

server/game/costs/XValuePrompt.js

fix the XValuePrompt so that an invalid value chosen in the prompt doesn´t break the gold of the player anymore.
before this fix, an invalid value would set player.gold to undefined and the player wasn´t able to gain any gold anymore

fix the XValuePrompt

---

server/game/PlayActions/MarshalIntoShadowsAction.js
server/game/baseability.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
test/server/gamesteps/abilityresolver.spec.js

hides the source of an MarshalIntoShadowsAction in the alert when doing the action outside of your action window
when marshaling a card into shadows during your opponents reaction window by accident, the marshaling action is outside of your action window and it puts an alert in the game log, stating which card you marshal into shadows and thus spoiling secret information to your opponent

hides the source of an MarshalIntoShadowsAction in the alert 

---

server/game/cards/12-KotI/HeirToTheIronThrone.js

new players get confused by this rule. you have to know about it and then cancel the sacrifice manually which in turn leads to a warning in the game log.
fixes #2417

only prompt for sacrifice on heir to the iron throne if the card put into play was not a duplicate

---

server/game/gamesteps/TriggeredAbilityWindowTitles.js

add a titleFunc for the onCardReturnedToHand trigger so that the prompt displays which card is being returned to hand when a triggered ability interacts with it
relevant for Golden Company and things like First snow of winter

add a titleFunc for the onCardReturnedToHand trigger 

---

server/game/cards/11.4-MoD/MeereeneseMarket.js
server/game/cards/12-KotI/StolenMessage.js
server/game/cards/14-FotS/AcolyteOfTheFlame.js
server/game/effects.js
server/game/player.js

Returning a card to the deck assumes that the card is already outside of
the deck. For cards that take the top card of the deck and place it on
bottom, PlaceCard should be used instead.
Fixes #3160

Fix "place on bottom of deck" effects

---

server/services/CardService.js

* Uses the newer code and name fields that have been added to
the RL data instead of calculating it.

Update to G.O.T. restricted lists

---

server/game/cards/20-HMW/TheFather.js

the father (https://thronesdb.com/card/20054) uses a wrong triggered ability handler at the moment. this leads to timing issues with other reactions/interrupts

fix the father to be a forced interrupt instead of reaction

---

server/Array.js
server/game/cards/11.1-TSC/FreshRecruits.js
server/game/cards/20-HMW/BraveCompanions.js

Fixes a bug with Brave Companions (and Fresh Recruits) by updating its logic. It will now correctly highlight the valid cards based on the remaining _**Traits**_ when looking in the deck, even if a card with multiple of those _**Traits**_ is selected. For example, if you find a character with _**Commander. Mercenary.**_, they could be selected as the _**Commander**_ card or the _**Mercenary**_ card, meaning both traits are still available for selection.
This update uses permutation to find all valid combinations of the selected cards against the given traits, and returns the list of remaining traits that can still be selected.
Discord: Deathlysteve#4587 for any queries.

Updated BraveCompanions & FreshRecruits logic

---

server/game/player.js

currently, the game log message uses the wrong player when you attach an attachment to an opponent´s card

fix the "player attaches x to y" game message to use the controller

---

server/game/cards/06.4-TRW/ImprovedFortifications.js

previously, improved fortification reacted to late for a "would leave play" interrupt. I now used the same triggering condition as dupes (minus the killing part).
furthermore, using context.event.saveCard() should be called, just like for dupes, which in turn calls cancel()

Fix improved fortification triggering condition and saving

---

server/api/draftCubes.js
server/api/events.js
server/api/index.js
server/services/DraftCubeService.js
server/services/ServiceFactory.js

Adds API endpoint to manage draft cubes, and allows events to be
configured with a format and draft options.
Progress toward #3206

Add API endpoint for draft cubes

---

server/game/cards/13.4-BtRK/CityOfSpiders.js

this leads to city of spiders being able to be executed multiple times during a single game
fixes #3113

fix city of spiders by resetting the resolving flag

---

server/game/gamesteps/plot/selectplotprompt.js

call clearSelectableCards after forced plot selection so the plot selection works correctly after the plots get recycled

---

server/game/gamesteps/killcharacters.js

rename gameaction in killcharacters.js to "kill" instead of "killed" so cannot be killed effects are properly checked
before this fix you were able to trigger cards like shireen baratheon (core) or jinglebell on a The crone vs Valar Morghulis turn, even though shireen/jinglebell had the cannot be killed effect active

rename gameaction in killcharacters.js to "kill" instead of "killed"

---

server/game/cards/01-Core/ArianneMartell.js

Currently, Arianne can be (incorrectly) saved by a dupe when she returns to hand via the "then" portion of her ability. This should fix that bug.

Fix core Arianne ability with cannot be saved

---

server/Array.js
server/game/PropertyTypes/KeywordsProperty.js
server/game/cards/20-HMW/Shagwell.js
test/server/cards/20-HMW/Shagwell.spec.js

Situation specified in 3rd point of the Rules FAQ for Shagwell (https://thronesdb.com/card/20045):
`If a character that was giving two or more Fools a keyword via Shagwell's constant effect leaves play or loses that keyword, those characters will lose that keyword too, unless there is another "source". They cannot continue to be each other's only source of that keyword if none of them are gaining it from anywhere else.`
This fix prevents Shagwells ability from adding instances of keywords which were originally obtained from Shagwells ability:
- Gets the current counts of each keyword for the card it is using as a source (eg. a card with 1 or more gold on it)
- Subtracts that with the current counts of each keyword being provided to that card by Shagwells effect. 
- The result is a list of …

Fix Shagwell and other fools with gold giving each-other keywords which have no source

---

server/game/GameActions/ThenAbilityAction.js
server/game/cards/17.1-R/AMissionInEssos.js
server/game/cards/20-HMW/Jinglebell.js

This should fix a bug with Jinglebell & A Mission in Essos for when Traits are added to that character (eg. The Many-Faced God).
**Jinglebell**: Previously was calculating triggerable traits when Jinglebell entered play (House Frey & Fool only). Now it is calculated when the ability actually triggers.
**A Mission in Essos**: Was checking traits for that character after they were returned to hand, rather than before. I have confirmed with the Design Team that it should take into account that characters card-state whilst in-play for the search condition, and this adjustment does that.

Fixing bug for "shares a Trait" abilities and added Traits

---

server/game/AttachmentValidityCheck.js
server/game/drawcard.js
test/server/cards/20-HMW/AMummersFarce.spec.js

fix the mummers farce attachments so they also check for attachment validity and get discarded when parent fool gains the no attachments keyword

fix the mummers farce attachments so they also check for attachment validity 

---

server/game/cards/04.5-GoH/ThePrincesPass.js

fixes #3263
i think refactoring the `ability.effects.removeIcon(icon)` part so that it now is a gameaction breaks this particular card. the check for 
`if(this.targetCharacter.getNumberOfIcons() === 0) {` returns false as the number of icons is still 1 at that point as the game action hasn´t resolved yet
seems more like a workaround to be honest, other ideas welcome

fix the princess pass after the refactoring of the loseIcon effect so that the then part of the card triggers in a queued simple step

---

server/game/cards/11.5-IDP/Glamor.js

The text for Glamor says "another character killed this phase", so you cannot
select the card killed as a cost to activate its ability.

Do not allow Glamor to resurrect killed parent

---

server/game/cards/20-HMW/AMummersFarce.js

Concerning A Mummer's Farce:
This is from the FAQ what @Odrl wrote:
If a Fool character has the no attachments keyword, the Forced Reaction will not trigger for that character. 
In fact theironthrone tries to resolve the forced reaction and then discards that card immediatly.

fix the reaction of the mummers farce so it only triggers on cards that can have weapon attachments

---

server/game/cards/22-BtB/SerRollyDuckfield.js

Allow Ser Rolly Duckfield to save himself if he has the correct trait

---

server/game/AbilityChoiceSelection.js
server/game/AbilityTarget.js
server/game/cards/09-HoT/NothingBurnsLikeTheCold.js
server/game/cards/22-BtB/TheMadKingsCommand.js

Mad King's Command & Nothing Burns like the cold both have each player select all cards before moving on to the next player to select. Currently with how `AbilityTarget` is coded, each individual selection will be made, message the chat then move onto the next player. This repeats until all selections are made. 
Realistically, we need these cards to have each player select all cards required (eg. for MKC, select up to 3 characters, 3 attachments, 3 locations and 3 hand/shadow cards), THEN announce those cards in chat & move onto the next player.
I have achieved this by allowing for `SubTarget`'s within an ability target (we can rename this if we think its appropriate). If an ability target has SubTargets configured, it will ask the choosing player for each of those selections, save them & …

Fixing Player Select order for simultaneous multi-target abilities

---

server/game/GameActions/MoveCardEventGenerator.js
server/game/GameActions/PutIntoPlay.js
test/server/cards/01-Core/ArianneMartell.spec.js

The `PutIntoPlay` game action now generates the onCardEntersPlay event
directly, rather than wrapping it in a placeholder event. By returning
it directly, the reaction for onCardEntersPlay when Ramsay Snow is put
into play by Arianne Martel now properly happens after Arianne has
returned to hand.
Fixes #3272

Fix interaction between Arianne and Ramsay Snow

---

server/game/EventTrackers/EventPlayedTracker.js
test/server/cards/13.1-AtG/WhiteSwordTower.spec.js

Event card abilities that are triggered from the discard pile do not count
as playing an event.
Fixes #3211

White Sword Tower + discard events interaction

---

server/game/cards/13.1-AtG/BaelorBlacktyde.js

If there's a single copy of an event in your discard pile, and you
have an ability that allows playing from the discard pile (e.g.
Annals of Castle Black), then you're allowed to play that card.
Fixes #3100

Fix Baelor Blacktyde vs play from discard

---

server/game/gamesteps/GameWonPrompt.js

This was simply missed in the PR from AHaH to Live; just removes the review button on game won.
Will find a more permanent solution to this within playtesting so we don't have to keep adding/removing it.

Removing the forgotten reviewer text

---

server/game/GameActions/PutIntoPlay.js
server/game/cards/11.6-DitD/GiftsForTheWidow.js
server/game/cards/13.2-CoS/BlackMarketMerchant.js
server/game/cards/17.1-R/GiftsForTheWidow.js
server/game/gamesteps/attachmentprompt.js
server/game/player.js

There is a bug for cards (namely "Black Markey Merchant" and "Gifts for the Widow") which allow the attachment to be put on any character, when the ability specified "character you control". These cards were updated as part of the search/reveal update within AHaH, and this must've been missed.
The resolution here is definitely not the cleanest, but it does the job quickly with what we currently have; I think we need to clean up `GameActions.putIntoPlay` in the future (eg. moving those methods out of `Player` and into GameActions), and this could be a part of that.

Fixing search abilities not filtering valid attachment targets

---

server/game/GameActions/RemoveFromChallenge.js

A bug I noticed during playtesting actually, but is relevant here (primarily for `A Wall of Roses`); It seems that a character removed using the new `GameActions.RemoveFromChallenge` currently still "contributes their STR" to the challenge after removed. This fixes that. I must've simply missed this in AHaH development, whoops!
Also, updating submodule!

Fixing RemoveFromChallenge GameAction

---

server/game/cards/11.4-MoD/SerMarkMullendore.js

Closes #3350 
Incorrect `GameAction` was initially used, primarily as `simultaneous` game action only requires one of any of those actions to change the game state to work. This was both giving the user the option to "put" an event into play, as well as actually "attempting" to put it into play, failing, but still putting Mark on top as it was simultaneous.
The fix was simply running the "put into play" game action first, **then** putting Mark on top (meaning if no card was put into play, Mark **doesn't** get put on top). Since this is all using game actions, the "can the revealed card enter play?" check is automatically made before giving the user the option to put it into play + put Mark on top.

Fixing Ser Mark Mullendore with events

---

server/game/cards/18-FH/TheTatteredPrince.js
server/game/gamesteps/AbilityChoicePrompt.js

Closes #3351 
Simply allowing The Tattered Prince to be saved by a duplicate, as well as updating his code to GameActions.
Also includes a quick adjustment to the `AbilityChoicePrompt` to ensure that the default `cancelMessage` is presented as a 'danger' message, not a regular message.

Properly allowing The Tattered Prince to be saved + update to GameAction

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js

This fix addresses a bug related to the defending player using participation effects (such as My Mind is My Weapon) **before** declaring defenders, and then that character incorrectly being knelt at the defender declaration step.
What should be happening is that *only* declared defenders should be knelt at this stage, and not "currently defending" characters. This fix corrects that by adding a `declaredDefenders` array to challenge, and referencing that instead to decide who to kneel.

Fixing non-declared defenders being knelt at defender declaration

---

server/game/cards/05-LoCR/OldWyk.js
server/game/cards/08.1-TAK/DreadfortMaester.js
server/game/cards/11.6-DitD/TheBastardsLetter.js
server/game/cards/14-FotS/LynCorbray.js

Certain cards were still incorrectly referencing current challenge type, rather than initiated challenge type, during the **onChallengeInitiated** check ~ therefore they would incorrectly react to when Storms End (BtB) would change challenge type.
Applying fixes to the following cards:
- Old Wyk
- Dreadfort Maester
- The Bastards Letter
- Lyn Corbray

Fixes to properly check initiated challenge type

---

server/lobby.js

When we implemented game links last year, we added a "join" flag to the newGame method. This wasn't being passed during rematch games, so the owner of the game was no longer joining the rematch.
Also adds the game name to the rematch game, so we don't get games list in the lobby as "undefined".
Fixes #3360

Ensure game owner joins rematch games

---

server/game/GameActions/ChooseGameAction.js
server/game/GameActions/DiscardPower.js
server/game/GameActions/GainPower.js
server/game/GameActions/MovePower.js
server/game/Message.js
server/game/effects.js
server/game/game.js
server/game/gamesteps/AbilityChoicePrompt.js
server/game/gamesteps/keywordwindow.js
test/helpers/integrationhelper.js
test/server/GameActions/DiscardPower.spec.js
test/server/GameActions/GainPower.spec.js
test/server/GameActions/MovePower.spec.js
test/server/GameActions/PlaceToken.spec.js
test/server/integration/WinningAndLosing.spec.js

* Ensures eliminated players aren't prompted
* First player chooses winner when multiple players would win simultaneously, or all remaining players would be eliminated simultaneously
* Fixes simultaneous resolution of choose game action (used in Jon Arryn, the best way to test simul-win)
Progress towards #1237

Implement player elimination + simultaneous win/loss for Melee

---

server/game/baseability.js
test/server/card/cardaction.spec.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js

Closes: #3374 
This is a minor engine tweak to the `canResolve` logic of `baseAbility`; there are scenarios, such as Ashemark, where an ability will need access to it's source's state before initialisation, and thus to ensure that GameActions are properly implemented, we need to include `cardStateWhenInitialised` in any `allowed` checks made against it.
This adjustment here tries to take a generalised approach, by pulling the `this.gameAction.allowed(context)` into the temporary context builder, and within that builder adding a temporary snapshot of the source, if the ability **has** a source.
@ystros, if you can think of any issues this may cause, let me know. Will leave this for you to merge as I like a second set of eyes for any engine changes.

Fixing Ashemark, and any other GameActions checking cardStateWhenInitialised

---

server/game/cards/03-WotN/TheBlackfish.js
test/server/effects/doesNotKneelAsAttacker.spec.js

Closes: #3383 
Title says it all.
Also includes an alteration to the `doesNotKneelAsAttacker.spec.js` as Blackfish now *correctly* does not trigger if the player has no cards in their deck (GameActions actually doing it's job!). Clicking "Pass" on his ability is no longer necessary.

Updating TheBlackfish to GameAction & added limit

---

server/game/ChallengeKeywordAbility.js
server/game/gamesteps/ChallengeKeywordsWindow.js
server/game/gamesteps/InitiatingKeywordsWindow.js
server/game/gamesteps/ResolutionKeywordsWindow.js

Primarily addressing an issue where players who have the `keywordSettings.chooseCards` option set would be receiving a prompt to trigger intimidate order when winning on defence. This fix correctly uses the `canResolve` of each keyword before determining which cards *can* trigger, as well as previously checking it in-between each application.

Fixing keywords to check canResolve before resolve

---

server/game/drawcard.js

close #3385 but review needed because it is an engine-level fix.
After investigation, I've found another way to reproduce the problem which doesn't use any trigger restriction.
If Player 1 has `Arya Stark (Core)` with a facedown event as dupe (for example: `Nightmares`) and gold less than the cost of the event (for example: 0 gold), then dupe cannot be used.
That's because during the duplicate ability setup (method `setupDuplicateAbility` of `drawcard`) a new `CardInterrupt` instance is constructed. This class inherits from `TriggeredAbility` which has, in the constructor, a logic for which if the `card.printedType` is `'event'` and the caller doesn't explicitly said to `ignoreEventCosts`, then all three `Costs.playEvent` are added to the cost. As a result, when duplicate ability is setup …

- fix proposal to Arya Stark duplicates not working sometimes

---

server/game/cards/24-TSoW/HarlawScout.js

Very simple fix here which was noticed on the Playtesting server; causing triggering issues for `cardStateWhenDiscarded` being undefined, which is caused by this incorrectly being an **Interrupt**, when the card is actually a **Reaction**.

Fixing Harlaw Scout to be a reaction, not interrupt

---

server/game/ChallengeMatcher.js
server/game/cards/10-SoD/ToTheSpears.js
server/game/cards/13.2-CoS/TheFowlerTwins.js
server/game/challenge.js
server/game/gamesteps/challengephase.js

Closes #3425 
The primary issue as to why this is being improved upon (eg. not just copying To The Spears logic) is outlined in the following comment: https://github.com/throneteki/throneteki/issues/3425#issuecomment-1728637728
This is resolved by tracking the "total number" of each challenge being initiated during the challenges phase (regardless of player), and checking that total number is incremented by 1; this should ensure TFT is active during `onChallengeInitiation`, as well as during the challenge itself, but never before or after those points.
Additionally, this also updates **To The Spears!** to use this new logic, even though that card is currently fine - consistency is key! :)

Fixing TheFowlerTwins to only apply on the next challenge initiated

---

server/game/cards/10-SoD/ToTheSpears.js

Ensures To The Spears only applies during the next challenge initiated by that player, rather than any player; granted, this would not have actually cause any issues, but should be correct regardless for consistency!

Minor fix to condition of To The Spear's effect

---

server/game/GameActions/AddToChallenge.js
server/game/GameActions/index.js
server/game/cards/11.4-MoD/BondsOfChivalry.js

It was noticed on the Playtesting server that this is a bit outdated in abilities which react to a card standing; reactions should trigger _after_ the full ability is resolved - in this case, after the new character has been chosen to participate. BoC has been updated to properly reflect this logic through the use of GameActions.
This is mostly an update I am looking to pull through to the playtesting server, but since it's only updating an already-released card, thought it best to instead push to live. :)

Updating Bonds of Chivalry to GameAction

---

server/game/GameActions/KneelCard.js
server/game/cards/11.4-MoD/BondsOfChivalry.js

This was a little mistake by me whilst testing the message format for `AddToChallenge`; corrected the message for the "Then" portion of BoC.
Additionally, added a message for `KneelCard`, just in case for the future (since it was super simple).

Fixing missed adjustments in Bonds of Chivalry

---

server/game/cards/14-FotS/ACaskOfAle.js

Changed the event so you first have to select the two cards from the same controller and then which card you are moving the power from. You are apparently also supposed to be able to select two cards without power if you for some reason want the event to not resolve, because it is a referential target, but you can't play the event if there is no power in play.

Fixing A Cask of Ale

---

server/game/cards/08.3-Km/ForgottenByHistory.js
server/game/cards/13.5-TB/TheBloodyCup.js

Closes: #3440
I added the condition when selecting targets, this way you also can't play the event if there is no valid target. I also added this condition in Bloody Cup, because it now let's you select invalid targets on Crone turn. Not sure if this is okay solution for this, but if it is I can add it on some other events that I know also work like that.

Crone Forgotten By History Interaction

---

server/game/GameActions/GainGold.js
server/game/GameActions/GainPower.js
server/game/cards/06.2-GtR/TheDornishmansWife.js
server/game/cards/17.1-R/TheDornishmansWife.js

Achieves the following:
- Updates both versions to `GameActions` (GtR version still needs handler due to opponent targetting)
- Fixes string interpolation for both by utilizing built-in gameaction messaging
Should replace & close #2988

Updating & fixing The Dornishmans Wife

---

eslint.config.js

Found a way to fix eslint on global "integration" function for jasmine tests; simply needed to add to globals list

Fixing eslint for jasmine files which use global "integration" function

---

deck-helper/DeckValidator.js

moment appears to take 50 times longer to parse + create + compare dates than simply using the native Date class. Given how frequently DeckValidator is being instantiated currently, this is significantly slowing down loading player decks.

Use date parsing for validator pack filtering

---

README.md

Updated the README file for running the throneteki server in a docker container.
Changes:
- Moved `git submodule update --init` into an **Installation** section so both Docker and Non-Docker setups run it
- Added server run commands under **Running** section since they're needed for Docker and non-Docker environments
- Updated server path to correct version `/` instead of `\`
- PORT 5000 is restricted by MacOS, so I propose we recommend 4050 to remove that roadbump for onboarding.

Updated README instructions for running lobby and game node

---

server/game/cards/07-WotW/Queenscrown.js
test/server/cards/07-WotW/Queenscrown.spec.js

Issue: #3526 
Added fix for issue with Queenscrown not sending cards to the bottom of the deck when no characters are revealed.
Added unit tests for Queenscrown

Queenscrown fix to send cards to bottom of deck if no character is revealed

---

server/game/GameActions/DiscardAtRandom.js
test/server/cards/25.3-FUtG/TheLaughingStorm.spec.js

Fixes #3520 
- Laughing Storm no longer allows discard from Heads on Spikes
- Updated effects and player classes to deny discard at random to GameAction (it was previously only card action)
- Added spec for Laughing Storm

Laughing storm heads on spikes

---

server/game/cards/02.1-TtB/TheWatchHasNeed.js
server/game/cards/04.3-FFH/NightGathers.js
server/game/cards/04.6-TC/FistOfTheFirstMen.js
server/game/cards/06.1-AMAF/EastwatchByTheSea.js
server/game/cards/07-WotW/CrowKillers.js
server/game/cards/08.6-SAT/Godswood.js
server/game/cards/09-HoT/SmallPaul.js
server/game/cards/11.5-IDP/ThreeFingerHobb.js
server/game/cards/14-FotS/ProtectorsOfTheRealm.js
server/game/cards/14-FotS/SiegePreparations.js
server/game/cards/17.1-R/ThreeFingerHobb.js
server/game/cards/20-HMW/OldTattersalt.js
server/game/cards/22-BtB/FleetFromTenTowers.js
server/game/cards/22-BtB/SamwellTarly.js
server/game/cards/23-AHaH/BannerOfTheFalcon.js
server/game/cards/23-AHaH/KnightsOfTheVale.js
server/game/cards/23-AHaH/Mord.js
server/game/cards/23-AHaH/Sweetrobin.js
server/game/cards/23-AHaH/TheEyrie.js
server/game/cards/23-AHaH/TorrhensSquare.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/revealplots.js
server/game/gamesteps/taxation/DiscardToReservePrompt.js
server/game/player.js
test/helpers/playerinteractionwrapper.js
test/server/cards/02.4-NMG/WraithsInTheirMidst.spec.js
test/server/cards/13.1-AtG/AtTheGates.spec.js
test/server/gamesteps/revealplots.spec.js

Primarily to fix a bug where the +/- for some of the plot stat values were simply not working as they were calling the wrong function name in `player` object. Then made me think of whether "Total" was appropriate for these functions, and ultimately it does not make sense as it's simply passing the same value being calculated by the plot - there is no "total" calculation being made.
Done a simple find & replace for these functions, as well as fixing `Godswood` to properly look at the players claim, rather than the plots claim.
+/- buttons now also work!

Fixing plot stat functions

---

client/Components/Games/NewGame.jsx
client/Components/Games/PasswordGame.jsx

This has been lightly tested locally, but best to confirm it actually works after pushing live.
NextUI Input expects `autoComplete` (with capital C) to then pass through to the inner `input` element it creates.

Attempting to disable password autocomplete on game passwords

---

deck-helper/AgendaRules.js

Plots should not be included in the max 3 check (outlined in ThronesDB FAQ).

Fixing plots being incorrectly included in max 3 check

---

server/game/gamesteps/AbilityChoicePrompt.js

This was incorrectly using the choose prompt as its `gameAction`, when it should be using the gameAction of the selected choice when writing the message.
Eg. if the GameAction chosen was "ReturnToHand", this will now set `{gameAction}` to "ReturnToHand" gameaction message, rather than "Choose" gameaction message.

Message logic fix for Choose prompt

---

client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/CardPileLink.scss
client/Components/GameBoard/MovablePanel.jsx
server/game/basecard.js

These are primarily noticeable within playtesting (specifically with [Armed to the Teeth](https://thronesdb.com/card/26618)), but are applicable to the site in general.
These changes:
- Moves the "Select Card" option to be a client side option, rather than something sent from the server. The intent here is that the "Select Card" option is not always appropriate for scenarios where that card is the top of a cardpile, and there is no simple way to alter or remove that option when it's coming from serverside.
- Adds better logic to when the "Open/Close Popup" menu item is available
- Adds better logic on when to show the menu on card click with a `hidable` menu item options (currently only for toggling the popup or select card)
- Adjusted the agenda popup to show some of the second row like …

Some adjustments to Card Piles

---

client/Components/Decks/DeckHelper.js
client/Components/Decks/DeckStatus.jsx
client/Components/Decks/DeckStatusSummary.jsx
deck-helper/DeckValidator.js
deck-helper/DeckWrapper.js
deck-helper/RestrictedList.js

Fixing deck counts for validation
Fixing pods being accidentally double listed
Cleaning up restricted list validation logic to simply be `valid` or not, rather than needing to check multiple flags for validity.

Fixing some counts and validation logic

---

client/Components/Games/GameOptions.jsx
client/Components/Games/GameTypes.jsx
client/Components/Games/NewGame.jsx

Reported that event game options are not being applied, even though they are set in events. Turns out there is nothing to actually set them.
This is to be treated as a hotfix, as I plan to refine/rework how events + restricted lists work in the mobile update. :)

Fixing event set game options for World Cup

---

server/game/cards/25.3-FUtG/TarleTheThriceDrowned.js

Issue https://github.com/throneteki/throneteki/issues/3592 - Tarle the Thrice Drowned's kill effect was able to target characters that could not be killed, due to the target matcher properties not specifying the 'kill' action as eg on Mag the Mighty, meaning the action didn't filter possible targets based on whether or not a kill action would affect game state.
Tested with Valyrian Steel Armor and The Eyrie, but not Long May He Reign

Fix for issue 3592: kill effect from Tarle

---

server/game/ChessClock.js
server/game/game.js
server/game/gamesteps/AcknowledgeRevealCardsPrompt.js
server/game/gamesteps/plot/ChooseTitlePrompt.js
server/game/gamesteps/uiprompt.js
server/game/player.js
server/gamenode/gameserver.js
test/server/gamesteps/uiprompt.spec.js

Attempts the following:
- Automatically completing prompts if its player has left or is eliminated
- Fixing Acknowledgement prompt to use `game.getPlayers()` so it naturally filters out inactive players
- Slight improvement to title prompt if one leaves on first selection
- Game server continues game after handling "leave game" code (similar to when a regular command is run)
- Added basic test for the above

Fixing hanging prompts when active player leaves or eliminated

---

server/game/GameOverConditions/GameOverHandler.js
server/game/game.js
server/game/gamesteps/GameOverPrompt.js
test/server/cards/17.1-R/ValyrianSteel.spec.js
test/server/integration/effects.spec.js
test/server/integration/gameover.spec.js
test/server/integration/takecontrol.spec.js

We can see the winner object is being passed through rather than just the name; could not replicate the game-holding locally, but this is *likely* the issue. Will monitor

Attempting to fix lobby game end bug

---

server/game/GameHandlers/GameOverHandler.js
server/game/TextHelper.js
server/gamenode/gameserver.js

Fixing the following bugs:
- Players leaving after the game is over was accidentally triggering another `gameOver` as a draw (since it was safe for them to leave). Fixed by just ensuring that `gameOver` doesn't trigger if the game is already over (seems like a better wide-range fix)
- Fixed a bug with clearing stale games, where I made an oopsie and was checking the game closing warning **before** the game close check, meaning it never could reach the game closing section.
- I have fixed this, and just slightly improved the wording on the warning as well so it actually tells you the remaining time, rather than the "waiting time"
Apologies! Message me on discord for any questions

Hotfix for leaving & clearing

---

client/Components/GameBoard/GameBoardLayouts/JoustGameBoardLayout.jsx
client/Components/GameBoard/GameBoardLayouts/MeleeGameBoardLayout.jsx
deck-helper/AgendaRules.js
server/game/cards/12-KotI/HeirToTheIronThrone.js
server/game/cards/25.5-TIC/GilbertOfTheVines.js
server/game/cards/26.2-WoW/BeneathThePetals.js
server/game/cards/26.2-WoW/JoffreysCrossbow.js
server/game/gamesteps/revealplots.js
test/server/gamesteps/revealplots.spec.js

All these fixes were reported on the GOT discord:
✅ Prompt height incorrectly affecting player row height. Player rows will now remain the same height always
✅ Joffrey's Crossbow not working, and erroring when discarded during a challenge
✅ Gilbert of the Vines fixed (was missed in the X update)
✅ Kingdom of Shadows now allows for `Shadow (X)` cards, like House Umber Berserkers
✅ Timing of Heir to the Iron Throne has been corrected so that shuffle happens _before_ the sacrifice. This mattered for Wyman, as it meant you would draw the first card (and see it) before shuffling your deck
✅ Fixed & improved the initiative logic so that it does not trigger twice
✅ Beneath the Petals Interrupt has been fixed
Also added unit test for player choosing ties for initiative.

Bulk of small fixes

---

server/game/ChallengeRestriction.js
server/game/basecard.js
server/game/immunityrestriction.js
server/game/restriction.js
test/server/card/basecard.spec.js
test/server/cards/26.1-WAID/MilkwaterCrossing.spec.js

Checking on restriction name now isn't accurate with how flags are used, and checking that the restriction name is a flag is not accurate to how those names should be used, or how the flags are represented.
Instead, I've added an `isActive` function for restrictions, which should realistically only be used for immunity checks thus far to explicitly check the card does not have that `losesAspect.immunity` flag. If there is somehow a loses aspect flag for "cannot" effects, that restriction type would also be updated.
Other checks like `allowGameAction('kill')` is handled properly in the `CannotRestriction` by checking the "type" of restriction actually matches.

Fixing recent bugs introduces to immunity clearing for Flags
