README.md

Slight typo in the README - was fetchcards.js, should be fetchdata.js

Fix instructions for populating card data.

---

server/game/cards/attachments.js
server/game/cards/characters.js
server/game/cards/locations.js
server/game/player.js
test/server/player.plotstats.spec.js

Allows an income modifier to be added to cards and introduces all the cards with such a modifier.

Implement income modifier cards

---

client/GameBoard.jsx
less/site.less

The card refactor implemented the ability for attachments to be knelt.
This adds the UI styling to indicate that it has been knelt.
Fixes #36.

Add UI styling for knelt attachments.

---

test/server/player/playcard.spec.js

playCard now calls the play method on the card rather than setting
inPlay directly.

Fix Player.playCard tests

---

server/game/basecard.js
server/game/drawcard.js
server/game/player.js
test/server/card/drawcard.ambush.spec.js

Parses the ambush cost from card text and uses that cost to calculate
the total cost of the card when played as an ambush.

Finish ambush implementation.

---

server/game/game.js
server/game/gamesteps/dominancephase.js
server/game/gamesteps/standingphase.js
test/server/gamesteps/dominancephase.spec.js

Converts dominance and stand phase to the new game flow.

Dominance and stand phase

---

server/game/game.js
server/game/gamepipeline.js
server/game/gamesteps/menuprompt.js
server/game/gamesteps/phase.js
server/index.js
test/server/gamepipeline/handleMenuCommand.spec.js
test/server/gamesteps/menuprompt.spec.js

Will be used in refactoring plot prompts in the big plot phase refactor.

Introduce general purpose menu prompt.

---

server/game/cards/characters/01/rattleshirtsraiders.js
server/game/cards/plots/01/confiscation.js
server/game/cards/plots/01/filthyaccusations.js
server/game/cards/plots/01/marchedtothewall.js
server/game/cards/plots/01/powerbehindthethrone.js
server/game/cards/plots/01/rebuilding.js
server/game/cards/plots/01/reinforcement.js
server/game/cards/plots/01/wildfireassault.js
server/game/cards/plots/03/thelongwinter.js
server/game/game.js
server/game/gamesteps/selectcardprompt.js
test/server/gamesteps/selectcardprompt.spec.js

Will be used in the big plot phase refactor.

Introduce general purpose card selection prompt

---

server/game/cards/plots/03/atimeforwolves.js

* ATfW searches the entire deck, not just the top 10 cards.
* The deck should always be shuffled, not just when a card is picked.
* Need to return true from menu prompt methods in order to complete the
prompt.
* Unnecessary to check the player in MenuPrompt callbacks - MenuPrompt
does this check already.
* Game.playerRevealDone method no longer exists.

Fix 'A Time for Wolves'

---

server/game/game.js
server/game/gamesteps/drawphase.js
server/game/gamesteps/marshaling/marshalcardsprompt.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/plotphase.js
server/game/player.js
server/index.js

Converts the draw and marshal phases to the new flow with no other real changes.

Draw and marshal phase

---

server/game/challenge.js
server/game/game.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/challenge/choosestealthtargets.js
server/game/gamesteps/challenge/fulfillmilitaryclaim.js
server/game/gamesteps/selectcardprompt.js
server/game/player.js
server/index.js
test/server/gamesteps/selectcardprompt.spec.js

Trying to break this up as much as possible.
* Implements choosing attackers as a card selection prompt.
* Implements stealth targeting as a card selection prompt.
Right now the `Challenge` class is a dumb data bucket, but I plan on refactoring to move challenge logic there once the entire challenge flow has been converted.

Convert selecting attackers + stealth to new flow

---

server/game/cards/characters/03/catelynstark.js

Catelyn Stark should not gain power when killed.

---

server/game/gamesteps/challenge/challengeflow.js

Upon winning a challenge with a participating character with the
Intimidate keyword, the player is prompted to select an opponents
character whose strength is less than or equal to the strength the
challenge was won.

Implement Intimidate keyword.

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js

This change should allow single player games to get through each
challenge type. There could be still problems in individual card
event handlers related to challenges.

Support single player challenges.

---

server/game/cards/agendas/thelordofthecrossing.js
server/game/cards/characters/01/rattleshirtsraiders.js
server/game/cards/characters/01/serjaimelannister.js
server/game/cards/characters/02/hodor.js
server/game/cards/characters/02/redcloaks.js
server/game/cards/characters/03/eddardstark.js
server/game/cards/characters/05/cerseilannister.js
server/game/cards/locations/01/greatkraken.js
server/game/cards/locations/01/lannisport.js
server/game/cards/locations/01/theredkeep.js
server/game/cards/plots/01/aclashofkings.js
server/game/cards/plots/02/riseofthekraken.js
server/game/gamesteps/challenge/challengeflow.js
test/server/cards/characters/01/01087 - serjaimelannister.spec.js
test/server/cards/characters/02/02070 - redcloaks.spec.js
test/server/cards/plots/01/01001-aclashofkings.spec.js

Updates all of the challenge-related events to just send the full challenge object.

Simplify challenge event params

---

server/game/gamesteps/challengephase.js
server/game/gamesteps/dominancephase.js
server/game/gamesteps/drawphase.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/phase.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/setupphase.js
server/game/gamesteps/standingphase.js
server/game/gamesteps/taxationphase.js
server/game/player.js

* Moves the setting of the phase to the Phase class.
* Fires events for the beginning of a phase, the ending of a phase ("Until end of phase" and "during phase" effects), and at the end of phase ("At the end of the phase" effects)

Implement basic phase events

---

client/DeckEditor.jsx
client/DeckSummary.jsx
client/StatusPopOver.jsx
client/deck-validator.js
karma.config.js
less/site.less
test/client/DeckSummary.spec.jsx

Also improve the error reporting of invalid decks slightly, and fix an issue where whitespace caused cards to  be considered invalid

Rains of castamere deck builder support

---

less/site.less

Ensure knelt cards appear selected / new

---

client/Application.jsx
client/GameBoard.jsx
client/Lobby.jsx
client/PendingGame.jsx
server/game/game.js
server/game/gamesteps/attachmentprompt.js
server/game/gamesteps/plot/firstplayerprompt.js
server/game/gamesteps/plot/plotrevealprompt.js
server/game/gamesteps/plot/resolveplots.js
server/game/player.js
server/game/spectator.js
server/index.js
test/client/GameBoard.spec.jsx
test/server/cards/plots/02/02039-pentoshi.spec.js
test/server/game/getplayers.spec.js
test/server/game/getsummary.spec.js
test/server/gamesteps/actionwindow.spec.js
test/server/gamesteps/attachmentprompt.spec.js
test/server/gamesteps/dominancephase.spec.js
test/server/gamesteps/killcharacterprompt.spec.js
test/server/gamesteps/menuprompt.spec.js
test/server/gamesteps/playerorderprompt.spec.js
test/server/gamesteps/plot/resolveplots.spec.js
test/server/gamesteps/taxation/discardtoreserveprompt.spec.js
test/server/gamesteps/uiprompt.spec.js
test/server/player/drop.spec.js

Move to using usernames instead of ids for keys everywhere
Update the Id when the client reconnects
Fixes #64

Add reconnect support

---

server/game/challenge.js
server/game/gamesteps/plotphase.js
server/game/player.js

* Fixes the display of the claim values for each player.
* Ensures that if claim is modified by the player through the UI, the updated value is used when claim is applied.

Fix claim UI

---

server/game/deck.js
server/game/player.js

Mild refactor that pulls deck preparation out of Player and updates the allCards collections to include faction, agenda, draw and plot cards instead of just draw cards.

Deck preparation refactor

---

server/game/cards/attachments/01/ice.js

Allow Ice's ability when winning defense.

---

less/cards.less
server/game/cards/characters/01/goldcloaks.js
server/game/cards/characters/02/redcloaks.js
server/game/cards/characters/04/shae.js
server/game/gamesteps/challengephase.js
server/game/gamesteps/dominancephase.js
server/game/gamesteps/drawphase.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/phase.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/standingphase.js
server/game/gamesteps/taxationphase.js
test/server/cards/characters/02/02070 - redcloaks.spec.js

* Reverts the commit that added event triggers in the derived phase classes. Rely on the base Phase class instead.
* Renames the phase events to onPhaseStarted and onPhaseEnded (past-tense for better naming consistency)
* Adds a background color to the gold token used by Red Cloaks (as well as future cards that use gold as tokens).

Fix phase related events.

---

server/game/gamesteps/challenge/challengeflow.js

Intimidate only applies for the attacker

---

server/game/cards/characters/01/margaerytyrell.js

Margaery Tyrell should boost until end of phase.

---

server/game/basecardreaction.js
server/game/cards/characters/01/aryastark.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js

* Fixes bug where reactions could be triggered for cards in the setup phase.
* Converts Arya Stark to the ability API, thus making her reaction optional.
Fixes #226

Convert Arya Stark to ability API.

---

client/Application.jsx
client/GameList.jsx
client/PendingGame.jsx
client/actions.js
client/reducers/games.js
server/game/game.js
server/index.js
test/server/game/getsummary.spec.js

Summary is:
remove the leavegame message and let the client figure out when the game is gone
Don't remove a player from the game when they disconnect, just mark them as disconnected

reworking reconnecting to be less stupid and more resilient

---

server/game/cards/attachments/03/greendreams.js
server/game/cards/characters/01/greenbloodtrader.js
server/game/cards/characters/04/lordsportfisherman.js
server/game/cards/events/01/thebearandthemaidenfair.js
server/game/cards/events/02/ineverbetagainstmyfamily.js
server/game/cards/events/05/aroseofgold.js
server/game/cards/locations/04/caswellskeep.js
server/game/cards/locations/05/oldwyk.js
server/game/challenge.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/player/movecard.spec.js

Implements "The Bear and the Maiden Fair", Lordsport Fisherman, Caswell's Keep, "A Rose of Gold", Green Dreams, Old Wyk, and I Never Bet Against My Family.

Implement all "bottom of deck" related cards.

---

server/game/cards/plots/05/unexpecteddelay.js

Force Unexpected Delay + allow selection of opponent characters

---

server/game/cards/characters/04/devotedbloodrider.js

Picked a pretty simple one for my first attempt.  Let me know if there are any issues

Implement Devoted Bloodrider

---

docs/implementing-cards.md

Also additional docs for effects + not needing to do anything for keywords.

Documentation for implementing plot modifiers, actions and ability limits.

---

server/game/cards/attachments/04/motherofdragons.js

This one was a little trickier but thanks to the clean, well organized codebase not too hard.  Props to Cryogen for the project and its excellent structure

Implement mother of dragons

---

server/game/cards/characters/04/xaroxhoandaxos.js
server/game/player.js

Playing attachments never raised "onCardEntersPlay".  I couldn't think of a good reason for that to be the case so I added it.  Let me know if that's an issue, thanks.

Implement xaro xhoan daxos

---

server/game/cards/plots/01/aclashofkings.js

Fix a clash of kings

---

server/game/cards/characters/02/serhobberredwyne.js

This is now the third or fourth place essentially the same summons/tutor code is which hurts my soul, especially since its a known avenue for continuing to get used.  But before I did a refactor I wanted to bring up the idea.  My initial idea was a SearchDeckPrompt class inheriting from MenuPrompt that would take a match criteria and number of cards,
Thoughts?

Implement Ser Hobber Redwyne

---

server/game/cards/characters/01/areohotah.js

I was working on implementing Quaithe in advance of the upcoming release and couldn't figure out why the event condition was never triggering when i copied it from Areo...

Fix areo hotah

---

server/game/cards/characters/01/serdavosseaworth.js

Fix Davos Seaworth's interrupt.

---

server/game/cards/characters/01/daenerystargaryen.js

Convert Daenerys Targaryen to effects API

---

server/game/cards/characters/01/fieryfollowers.js

Instead of when they're already standing.

Prompt Fiery Followers when actually kneeling

---

server/game/cards/locations/04/seabitch.js

hat tip to the guy in chat who helpfully pointed out the cards in the new pack that would be difficult/impossible to resolve manually!

Implement sea bitch

---

server/game/game.js
server/index.js
server/repositories/gameRepository.js
test/server/card/drawcard.hasKeyword.spec.js
test/server/cards/locations/01/01137 - thewall.spec.js
test/server/game/chat.spec.js
test/server/game/getplayers.spec.js
test/server/game/getsummary.spec.js
test/server/game/playermanagement.spec.js
test/server/game/power.spec.js
test/server/gamesteps/actionwindow.spec.js
test/server/gamesteps/dominancephase.spec.js
test/server/gamesteps/killcharacterprompt.spec.js
test/server/gamesteps/menuprompt.spec.js
test/server/gamesteps/playerorderprompt.spec.js
test/server/gamesteps/taxation/discardtoreserveprompt.spec.js
test/server/player/drop.spec.js

Previously, a lot of the work of adding players / spectators, managing
disconnecting, reconnecting and leaving games was being managed manually
through the socket handlers. This code has now been moved into the
`Game` class itself.

Manage players through the `Game` class

---

server/game/cards/locations/04/bearisland.js

Not a 100% perfect implementation, since I believe it would trigger when you would for example put a Grey Wind into play with Arianne during marshalling, but that's such a fringe case and I believe Stark Harrenhal has a similar limitation.

Implement Bear Island

---

server/game/cards/locations/02/tobhomottsarmory.js

How do I deal with the apostrophe in the title?

Implement Tobho Mott's Armory

---

server/game/cards/characters/02/greatjonsvanguard.js

Is there a way to implement 'no attachments' and the like? Didn't see it on other cards.

Implement Greatjon's Vanguard

---

server/game/cards/characters/02/serilynpayne.js

Not sure if card.getCost() is a thing.

Implement Ser Ilyn Payne

---

server/game/cards/characters/02/seralliserthorne.js

Implements Alliser Thorne's effect while you are the defending player.

Partial implementation of Alliser Thorne

---

server/game/chatcommands.js
server/game/game.js
test/server/game/chat.spec.js

Plus update the testing style for `Game.chat`.

Split chat commands into separate class.

---

server/game/cards/characters/02/gendry.js

1. Checking if dominance is lost in the forced reaction this way would not work in solo test games. Cryogen mentioned having the event pass the loser. If someone could do that for me or point out to me how to, gladly. :)
2. I guess it is possible to choose to discard a power when Gendry doesn't have any to prevent the sacrifice. Is this important (enough)?

Implement Gendry

---

server/game/cards/attachments/02/drownedgodsblessing.js
server/game/cards/locations/02/northernrookery.js

Also add a TODO comment on Drowned God's Blessing to make it clear it
isn't fully implemented.

Implement reaction for Northern Rookery.

---

server/game/cards/characters/05/serlancellannister.js
server/game/cards/locations/03/towerofthehand.js

Tower of the hand should return the selected controller character to his hand as well as kneel the location itself.

Adding ser lancer and fixing tower of the hand

---

server/game/cards/locations/04/seabitch.js

As per FAQ: https://thronesdb.com/find?q=sea+bitch

stop Sea Bitch from taking control of another Sea Bitch

---

server/game/cards/characters/05/serlancellannister.js

Fix Lancel Lannister

---

server/game/cards/characters/02/will.js
server/game/cards/locations/01/thewall.js

This is will:
http://thronesdb.com/card/02001

Adding the card effect for will.

---

server/game/cards/characters/02/ladyinwaiting.js

This works perfectly except that she can't be marshaled at all with less than 2 gold.

(partial) Implement lady in waiting as reaction

---

server/game/cards/challengeevent.js
server/game/cards/events/01/forthenorth.js
server/game/cards/events/01/oursisthefury.js
server/game/cards/events/01/winteriscoming.js
server/game/cards/events/02/inthenameofyourking.js
server/game/cards/events/02/thewatcheronthewalls.js
server/game/cards/events/04/blesshimwithsalt.js
server/game/cards/events/04/thereismyclaim.js
server/game/challengetracker.js
server/game/effects.js
server/game/player.js

The new class is called ChallengeEvent and by default checks whether we're
currently in a challenge or not. Additionally it can be passed arguments to
declaratively request checking that we're in a challenge of a given type and/or
participating in a given role (attacker/defender).

implement most of the missing challenge events

---

server/game/cards/characters/02/croneofvaesdothrak.js

it should only trigger when discarding from either hand or deck

stop Crone of Vaes Dothrak from triggering when discarding from play

---

server/game/cards/characters/02/hodor.js
server/game/cards/characters/05/edricstorm.js
server/game/drawcard.js
server/game/effects.js
server/game/player.js

as part of this, Hodor implementation has been reworked to use the new effect
as well

implement Edric Storm using a new effect for dominance exclusion

---

server/game/cards/characters/04/knightofsummer.js

A plot card can have both winter and summer traits!  ex: Old Nan

Knight of summer

---

server/game/cards/characters/04/stannisbaratheon.js

The effect of the reaction (character that cannot stand) is not enforced, but displaying the message still makes it clear you have triggered him and who was targeted.

Implement Stannis Baratheon [TIMC] (partial)

---

server/game/cards/characters/01/euroncrowseye.js
server/game/chatcommands.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/game/chat.spec.js

Also update /discard x phrasing, depending on number of cards discarded.

Update chat to log pillaged card for /pillage and onPillage.  

---

server/game/cards/characters/05/sweetdonnelhill.js
server/game/effects.js

Quite sure this should be able to be done more eloquently. :P

Implement Sweet Donnel Hill

---

server/game/cards/characters/04/captainsdaughter.js

Also updated Stark Harrenhal to use the cost framework.

Implement Captain's Daughter

---

server/game/cards/locations/02/raidinglongship.js
server/game/cards/locations/02/shadowblacklane.js
server/game/cards/locations/02/streetofsilk.js
server/game/cards/locations/02/streetofsteel.js
server/game/cards/locations/02/streetofthesisters.js
server/game/cards/locations/02/theboneway.js
server/game/cards/locations/02/tobhomottsarmory.js

Note: the implementation of Street of the Sisters has reduced a lot as part of
this pass, as it was doing lot of manual stuff for functionalities that were
available from the core game engine. Its code might deserve additional review
scrutiny.

port cycle 1 locations that kneel to the cost framework

---

server/game/cards/attachments/02/lady.js
server/game/cards/attachments/03/aryasgift.js
server/game/cards/attachments/03/nymeria.js
server/game/player.js

When attachments are moved from one character to another, they now keep their duplicates rather than discarding them.

Implemented Arya's Gift and fixed Nymeria 

---

server/game/cards/characters/04/serdavosseaworth.js
server/game/gamesteps/challenge/choosestealthtargets.js

Implement Ser Davos Seaworth [GoH]

---

server/game/cards/characters/01/maesterlomys.js

Fix Maester Lomys

---

server/game/costs.js
server/game/gamesteps/abilityresolver.js
test/server/costs/payreduceablegoldcost.spec.js

Moves the logic of paying for a card that can be reduced by any active
cost reduction effects into a Cost.

Implement cost for reduceable gold costs.

---

server/game/game.js

This should fix King Robb's Host

Fix anyPlotHasTrait() on game

---

server/game/cards/locations/03/towerofthehand.js
server/game/costs.js

Implements a cost that returns a card to its owners hands and converts
Tower of the Hand to use it.

Implement 'return to hand' cost

---

client/DeckEditor.jsx

Complete ThronesDB-like textual decks can now be pasted into the "Cards"
section of the deck builder. If a deck "header" --- made of deck title,
faction, agenda, possibly with multiple banners in the case of "Alliance" ---
is detected, it will be used to pre-populate the values of the various deck
builder dropdown selectors.
Fixes #633

add automatic parsing of deck title/faction/agenda to the deck builder

---

server/game/cards/characters/05/serjaimelannister.js

Don't override addIcon in LoCR Jaime.

---

server/game/cards/characters/05/moonbrothers.js
server/game/cards/characters/05/shaggasonofdolf.js
server/game/cards/characters/05/tyrionlannister.js

Implement Clansmen: Tyrion, Moon Bros & Shagga

---

server/game/cards/locations/07/thenewgift.js

The challenges action is working, but the marshalling action is not for some reason...

Implement The New Gift

---

server/game/cards/characters/05/timettsonoftimett.js

This should also close the kill prompt which previously allowed you to kill multiple characters

Port Timett to the target API

---

server/game/cards/characters/01/littlefinger.js

Restrict Littlefinger to marshalling phase

---

server/game/cards/attachments/01/bodyguard.js

Add save from discard to Bodyguard.

---

server/game/cards/characters/01/randylltarly.js
server/game/drawcard.js
server/game/effects.js
test/server/cards/characters/01/01183-randylltarly.spec.js
test/server/effects/dynamicstrength.spec.js

Implement Randyll Tarly

---

server/game/cards/characters/01/melisandre.js

make Melisdanre trigger on R'hllor events

---

server/game/cards/events/01/unbowedunbentunbroken.js
server/game/cards/events/02/inthenameofyourking.js
server/game/challengetracker.js
server/game/effects.js
server/game/player.js

Changes Unbowed, Unbent, Unbroken to use an effect and changes the
effect to properly reflect "cannot" in the card text.

Use effect for Unbowed Unbent Unbroken.

---

server/game/player.js

Do not display prompt title for spectators.

---

server/game/gamepipeline.js
server/game/gamesteps/basestep.js
server/game/gamesteps/simplestep.js

I've written something like this multiple times when I needed a semi-readable way of seeing what was in the pipeline. Might as well put it in for real...

Add method to inspect state of game pipeline.

---

server/game/cards/characters/07/maesteraemon.js
server/game/gamesteps/challenge/applyclaim.js
server/game/gamesteps/challenge/challengeflow.js
test/server/cards/characters/07/07005-maesteraemon.spec.js

Completes #628 by using the `ApplyClaim` step to apply claim.

Complete implementation of Maester Aemon (WotW)

---

server/game/ambushcardaction.js
server/game/cardaction.js
server/game/cards/characters/02/ladyinwaiting.js
server/game/cards/plots/06/theannalsofcastleblack.js
server/game/costs.js
server/game/effects.js
server/game/marshalcardaction.js
server/game/playablelocation.js
server/game/playcardaction.js
server/game/player.js
server/game/triggeredability.js
test/server/ambushcardaction.spec.js
test/server/cards/plots/06/06040-theannalsofcastleblack.spec.js
test/server/effects/canmarshalfrom.spec.js
test/server/marshalcardaction.spec.js
test/server/playcardaction.spec.js
test/server/player/drop.spec.js
test/server/player/movecard.spec.js
test/server/player/removeattachment.spec.js

* Generalizes the previous 'marshal location' mechanism used for Night Gathers to be used for playing events and ambushing cards.
* Implements The Annals of Castle Black.

Implement The Annals of Castle Black.

---

server/game/cards/locations/06/eastwatch-by-the-sea.js

Fix Eastwatch-by-the-Sea triggering condition.

---

server/game/cards/plots/01/calmoverwesteros.js
test/server/cards/plots/01/01008-calmoverwesteros.spec.js
test/server/cards/plots/04/04020-varyssriddle.spec.js

Fix Varys's Riddle vs Calm Over Westeros.

---

server/game/cards/attachments/06/marriagepact.js
server/game/cards/characters/02/winterfellkennelmaster.js
server/game/cards/plots/02/wardensofthenorth.js
server/game/drawcard.js
server/game/effects.js

The forced interrupt on Marriage Pact is not working currently which must be the same issue as Viserys Targaryen.

Implement Marriage Pact

---

server/game/cards/events/01/wakingthedragon.js

WARNING: this is untested because, for the reasons we're discussing on the dev
chat, I haven't yet restored a fully working local deployment environment...

Implement Waking the Dragon

---

server/game/cards/events/06/adragonisnoslave.js
server/game/cards/events/06/guardingtherealm.js
server/game/cards/events/06/lordrenlysride.js
server/game/cards/events/06/thedornishmanswife.js

Both the reactions from discard pile don't seem to be working currently...

Implement events from Guarding the Realm

---

server/game/cards/characters/05/tommenbaratheon.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js

I couldn't get the more efficient code ystros suggested for Tommen itself in the previous PR (https://github.com/cryogen/throneteki/pull/665) to work so I reverted to this less efficient one.

Implement Tommen Baratheon

---

client/Application.jsx
client/Avatar.jsx
client/FormComponents/Checkbox.jsx
client/FormComponents/Input.jsx
client/GameComponents/Messages.jsx
client/GameList.jsx
client/Lobby.jsx
client/Login.jsx
client/PendingGame.jsx
client/Profile.jsx
client/Register.jsx
client/actions.js
client/index.dev.jsx
client/index.prod.jsx
client/reducers/auth.js
server/api/account.js
server/game/gamechat.js
server/game/player.js
server/gamenode/gameserver.js
server/lobby.js
server/pendinggame.js
server/repositories/userRepository.js
server/server.js
test/client/Register.spec.jsx
test/server/game/chat.spec.js

Allow change of email address and password
Allow gravatar images to be disabled
Allow default action windows to be set
Fixes #765

Add User profiles

---

server/game/cards/attachments/06/marriagepact.js
server/game/cards/characters/01/viserystargaryen.js
server/game/cards/characters/04/jaqenhghar.js
server/game/challenge.js
server/game/effectengine.js
server/game/game.js
server/game/gamesteps/eventwindow.js
server/game/player.js
test/server/cards/characters/01/01167-viserystargaryen.spec.js
test/server/effectengine.spec.js
test/server/integration/takecontrol.spec.js
test/server/player/movecard.spec.js
test/server/player/removeattachment.spec.js

Make discarding cards async so cards that trigger on leaving play trigger again.  Fixes #727

Fix viserys

---

server/game/cards/characters/03/bearislandloyalist.js

Use the correct method name. Fixes THRONETEKI-S9.

Fix Bear Island Loyalist

---

client/GameList.jsx

display client toaster errors when trying to watch/join before login

---

server/game/cards/locations/04/thevalyrian.js

Fix The Valyrian's ability condition.

---

server/game/cards/characters/01/balongreyjoy.js
server/game/cards/characters/03/fishwhiskers.js
server/game/cards/events/01/thekrakensgrasp.js
server/game/cards/locations/02/raidinglongship.js
server/game/challenge.js
server/game/drawcard.js
server/game/effects.js
server/game/game.js

* Adds an effect that prevents strength from being added to a challenge.
* Converts Core Balon, The Kraken's Grasp, and Raiding Longship to use the effect.
* Implements Fishwhiskers.

Add a 'does not contribute strength to challenge' effect

---

server/game/cards/events/02/thewatchhasneed.js
server/game/gamesteps/decksearchprompt.js

To that end, extend the deck selector to allow selecting multiple cards among
the found ones (based on an idea by @cryogen).

implement The Watch Has Need

---

server/game/cards/events/01/theswordinthedarkness.js

Fix Sword in the Darkness

---

server/game/cards/events/02/ladysansasrose.js

This is a bit of a messy implementation. If I've missed any easy opportunities to simplify it, please let me know. :)

Implement Lady Sansas Rose

---

server/game/cards/attachments/04/motherofdragons.js
server/game/cards/events/01/oursisthefury.js

Restrict Ours is the Fury/Mother of Dragons to target characters that are allowed to participate in challenges

Fix Ours is the Fury/Mother of Dragons to target characters that are allowed to participate in challenges

---

server/game/basecard.js
server/game/effectengine.js
test/server/card/basecard.spec.js
test/server/integration/factionchange.spec.js

Recalculate effects when faction changes.

---

server/game/cards/attachments/02/crownofgold.js

make sure Crown of Gold can only be attached to characters

---

server/game/cards/characters/06/elinortyrell.js
server/game/effects.js

* Add a modifyMaxLimited() effect
* Implement Elinor Tyrell
* Port Taxation to use the new effect

Implement Elinor Tyrell/port Taxation

---

server/game/cards/plots/01/marchedtothewall.js

Only allow discarding from play for Marched

---

server/game/cards/locations/07/blackbetha.js

I think the strength calculation conditions could be a little cleaner, but otherwise a pretty straight-forward card to implement, nothing really new.

Implement Black Betha.

---

server/game/cards/events/04/tarredheads.js
server/game/cards/events/05/thecouncilconsents.js
server/game/cards/events/06/allmenarefools.js
server/game/cards/events/06/attackfromthemountains.js
server/game/cards/events/07/raidingthebayofice.js

With the exception of The Scorpions Sting and Burning on the Sand, all reactions to winning/losing from hand should now be implemented.

Implement most remaining reactions to winning/losing events

---

server/game/cards/characters/07/southronmessenger.js

Allow save vs Southron Messenger ability.

---

server/game/cards/locations/06/undergroundvault.js

is should just no-op when there is no opponent
Fixes THRONETEKI-VM

make Undeground Vault work in solo games

---

server/game/cards/characters/01/dornishparamour.js
server/game/cards/characters/04/viserystargaryen.js
server/game/cards/events/06/dornishrevenge.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/challenge/challengeflow.js

The implementation of the effect is a little longer than I'd like, though upside is that it should be future proof for any potential upcoming effects that create challenger limits of > 1.

Implement Viserys Targaryen (AtSK) and Dornish Revenge

---

server/game/cards/characters/03/stonesnake.js

Opted to only potentially prompt for keywords that do something.

Implement Stonesnake

---

server/game/cards/characters/01/jonsnow.js
server/game/cards/characters/06/walderfrey.js
server/game/challenge.js
server/game/effects.js

* Jon Snow is technically "considered to be participating", instead of "attacking", but it works out to the same in any case.
* Fixes #954

Implement Walder Frey/Convert Jon Snow (Core)

---

server/game/cards/plots/06/wheelswithinwheels.js

* Using player.removeCardFromPile allows to remove a card from the prompt without revealing yet (like moving to discard pile did before)
* Cleanup messaging

Update Wheels Within Wheels

---

server/game/cards/characters/02/rakharo.js
server/game/cards/characters/04/podrickpayne.js
server/game/costs.js
server/game/game.js
server/game/gamesteps/challenge/applyclaim.js

Similarly to Stark Harrenhal, I took the liberty to have Podrick trigger solely on characters you control.

Implement Podrick Payne & Rakharo

---

server/game/cards/attachments/06/breakerofchains.js
server/game/cards/attachments/06/improvedfortifications.js
server/game/cards/characters/06/daceymormont.js
server/game/cards/characters/06/othellyarwyck.js
server/game/cards/characters/06/silencescrew.js
server/game/cards/events/06/plunder.js
server/game/cards/locations/06/arborvineyard.js
server/game/cards/locations/06/winterfellarcheryrange.js

- Dacey Mormont ~~won't work currently as a result of strength X cards now being defined as 'null' instead of '0' in the JSON data (Beric Dondarrion has the same issue)~~ needs #1115.
- Improved Fortifications needs #1108 to function.
- Let me know if you want me to convert the trigger of Breaker of Chains to the upcoming onChallengeInitiated event.

Implement remaining cards from The Red Wedding

---

server/game/cards/characters/01/jonsnow.js

Fix Jon Snow

---

server/game/cards/events/07/scalingthewall.js

Fix Scaling the Wall

---

server/game/cards/events/04/thescorpionssting.js

Fixes THRONETEKI-WB
Fixes THRONETEKI-WC

Ensure array for selection of Scorpion's Sting.

---

server/game/cards/events/06/freyhospitality.js

Ensure Frey Hospitality selects array of cards.

---

server/game/cards/events/01/thethingsidoforlove.js

Fix return to hand typo in Things I Do For Love.

---

server/game/cards/characters/04/craster.js
test/server/cards/characters/04/04085-craster.spec.js

Implement Craster's resurrect ability.

---

server/game/cards/events/01/thehandsjudgment.js
server/game/drawcard.js
test/server/cards/events/01/01045-thehandsjudgment.spec.js

Use printed cost for Hand's Judgment to cancel.

---

server/game/cards/events/06/freyhospitality.js

* Kill characters simultaneously
* Fix prompt title
* Close prompt after selecting targets

Fix Frey Hospitality

---

server/game/chatcommands.js

* Also don't raise onCardPowerChanged event.
* Partially fixes #1104.

Don't check for winner when manually modifying power

---

server/game/cards/characters/07/maryaseaworth.js

Use correct target for Marya Seaworth.

---

server/game/cards/events/07/nowmywatchbegins.js
server/game/player.js

Limit Now My Watch Begins to opponent cards

---

client/Application.jsx
client/ReduxActions/socket.js
client/reducers/games.js

Don't show disconnect message when the game socket is closing on purpose, fix leave game issue when two players in a game

Fix leave game

---

server/game/cards/locations/04/seabitch.js
test/server/integration/takecontrol.spec.js

* Specifically check for locations not belonging to the player initiating the ability, instead of not belonging to the owner.
* Fixes #1199.

Convert and fix Sea Bitch

---

client/GameBoard.jsx
client/deck-validator.js
server/game/cards/agendas/theconclave.js
server/game/gamesteps/setup/keepormulliganprompt.js
test/server/cards/cancreatecards.spec.js
test/server/gamesteps/setup/keepormulliganprompt.spec.js

* After keep hand / mulligan is decided, the top 7 cards of the deck are placed under the agenda.
* The current player can click the agenda at any time to get a popup showing the cards under there.
* Opponents and spectators don't get this popup, but can see how many cards are under there (which for Conclave should always be 7)

Implement The Conclave

---

client/GameBoard.jsx

Disable agenda popup if there are no cards

---

server/game/cards/characters/01/edricdayne.js
server/game/cards/characters/01/maestercaleotte.js
server/game/cards/characters/02/nymeriasand.js
server/game/cards/characters/02/unswornapprentice.js
server/game/cards/characters/06/othellyarwyck.js
server/game/cards/events/06/theprincesplan.js
server/game/cards/locations/04/theprincespass.js
server/game/cards/locations/05/mountainsofthemoon.js
server/game/game.js
server/game/gamesteps/iconprompt.js

A slight issue: the waiting prompt whenever you're selecting an icon will say "Waiting on opponent to use undefined".

Convert remaining icon cards to cost/target/icon API

---

server/game/cards/characters/01/thequeenofthorns.js

* Convert to use target API and only allow printed cost 6 or lower characters to be put into play.
* Fixes #1224.

Convert and fix The Queen of Thorns (Core)

---

server/game/cards/events/07/therearenomenlikeme.js
server/game/cards/locations/02/northernrookery.js

... as requested by log message conventions

remove trailing dot from card log messages

---

server/game/cards/events/06/thenorthremembers.js
server/game/cards/locations/04/bitterbridgeencampment.js
server/game/cards/locations/07/queenscrown.js
server/game/cards/plots/01/marchedtothewall.js
server/game/cards/plots/03/thelongwinter.js
server/game/cards/plots/05/unexpecteddelay.js
server/game/cards/plots/06/duel.js
server/game/cards/plots/08/valardohaeris.js

as per log message conventions

card messages: switch to present tense

---

client/deck-validator.js
client/reducers/cards.js

* Allows Draft agendas to be selected.
* Adds validation rules for the Draft agendas
* Indicates whether a deck contains Draft cards if it is otherwise valid.

Add validation rules around draft cards

---

server/game/cards/characters/02/brothelmadame.js
server/game/cards/plots/01/wildfireassault.js
server/game/cards/plots/02/politicaldisaster.js

follow-up to commit baa87821d701ecd1ec266b936ebdd9eb0d59e993

card messages: switch to present tense, take 2

---

server/game/drawcard.js

Remove the "new this phase" highlight when character leaves play

---

server/game/cards/characters/04/captainsdaughter.js
server/game/cards/characters/04/eliasand.js
server/game/cards/characters/04/qhorinhalfhand.js
server/game/cards/characters/04/serarysoakheart.js
server/game/cards/characters/04/tandastokeworth.js
server/game/cards/characters/05/jeynewesterling.js
server/game/cards/locations/04/harrenhal.js

* Convert card implementations to cost/target API's.
* Simplify event property functions by fetching the card in question from the context object.
* Standardise chat messages and action titles.

Update card implementations

---

server/game/game.js
server/game/gamesteps/drawphase.js
server/game/gamesteps/marshalingphase.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/standingphase.js
server/game/player.js

Only one I wasn't really sure on was the onStatChanged. It isn't being used currently, but maybe it still has reason to exist?

Remove unused events

---

server/game/cards/events/02/loot.js
server/game/cards/events/04/ritualofrhllor.js
server/game/costs.js
server/game/costs/payxgoldprompt.js
test/server/cards/cancreatecards.spec.js

Implement Ritual of R'hllor and convert Loot

---

server/game/cards/attachments/02/lady.js
server/game/cards/attachments/03/nymeria.js
server/game/cards/attachments/07/summer.js

Previous implementations for Lady and Nymeria were quite needlessly convoluted. This PR ports them to use the target API and brings them in line with the more recently implement Summer.

Simplify implementations for Lady & Nymeria

---

server/game/cards/characters/03/jonsnow.js

* Has the additional benefit of not having identical prompt titles for the cost and target prompts.

Convert Jon Snow (WotN) to cost/target API

---

server/game/gamesteps/challengephase.js
server/game/plotcard.js

Remove unused onBeginChallengePhase method

---

server/game/cards/attachments/00/supportofsaltcliffe.js
server/game/cards/characters/00/blackcrownknights.js
server/game/cards/characters/00/tyrionlannister.js
server/game/cards/events/00/compelledbytheking.js
server/game/cards/events/00/deadlykhalasar.js
server/game/cards/events/00/thevipersrage.js
server/game/cards/locations/00/thenightfort.js

* Implements all in-faction Valyrian draft only cards with the exception of Raventree Elite.

Implement Valyrian draft only in-faction cards

---

server/game/cards/agendas/protectorsoftherealm.js
server/game/cards/agendas/thepowerofwealth.js
server/game/cards/agendas/treaty.js
server/game/cards/agendas/unitingthesevenkingdoms.js
server/game/player.js

* Deckbuilder validation for these agendas has already been implemented by ystros.

Implement Valyrian draft only agendas

---

server/game/basecard.js
server/game/cards/plots/00/commoncause.js
server/game/cards/plots/00/feastorfamine.js
server/game/cards/plots/00/holdingthetrident.js
server/game/cards/plots/00/summonedbytheconclave.js
server/game/cards/plots/00/thepalemare.js
server/game/effects.js
server/game/plotcard.js

* Needs player.getFaction() shorthand from #1292.

Implement Valyrian draft only plots

---

server/game/cards/characters/00/housebannerman.js
server/game/cards/characters/00/lyncorbray.js
server/game/cards/events/00/muster.js
server/game/cards/locations/00/hollowhill.js

* Needs #1292 for player.getFaction() shorthand.
* Needs #1293 for card.getFactions().

Implement Valyrian draft only draw deck neutrals

---

server/game/gamesteps/selectcardprompt.js

* Defaults the title to 'Select a character' or 'Select x characters' when x > 1.

Default card select prompt title

---

client/GameComponents/PlayerHand.jsx
client/GameComponents/PlayerRow.jsx

* Removes a bunch of dead code
* Extracts the hand rendering / functionality into its own component, `PlayerHand`.
I considered extracting the draw deck behavior into its own component as well, but it was pretty light after deleting the unused `getDrawDeck` method. Let me know if you think extracting it also would be worthwhile.

Cleanup PlayerRow component

---

server/game/cards/attachments/02/stinkingdrunk.js
server/game/cards/events/06/plunder.js

* Check play condition on the opponents to choose
* Get the card controller from the event object

Fix Plunder & Stinking Drunk

---

client/Profile.jsx
server/game/gamesteps/triggeredabilitywindow.js

Add options for limiting the timer to events or card abilities
Partially addresses #1266

Timer refinements

---

package.json

Adds scripts for when you just want to run one set of tests instead of everything.

Add individual npm scripts for Jasmine and Karma

---

server/game/player.js

Prompt bestow when attachments enter play

---

client/GameComponents/ActivePlayerPrompt.jsx
client/Profile.jsx
server/api/account.js
server/game/gamechat.js
server/game/gamesteps/triggeredabilitywindow.js
server/lobby.js
server/server.js
server/settings.js
server/util.js
test/server/card/drawcard.hasKeyword.spec.js
test/server/gamesteps/triggeredabilitywindow.spec.js

and we can guarantee they are set so don't have to check for them everywhere

Unify all of the user logic so that defaults are in one place 

---

server/game/cards/characters/04/roosebolton.js

And kill targets simultaneously.

Port Roose Bolton to cost/target API

---

server/game/cards/locations/06/ironvictory.js

Prevent Iron Victory crashing if no card

---

server/game/ambushcardaction.js
server/game/cards/characters/02/ladyinwaiting.js
server/game/cards/plots/01/marchingorders.js
server/game/cards/plots/06/barringthegates.js
server/game/costs.js
server/game/drawcard.js
server/game/effects.js
server/game/marshalcardaction.js
server/game/player.js
test/server/marshalcardaction.spec.js

* Reworks Marching Orders and Iron Bank Will Have Its Due to use the same mechanism to restrict playable cards.
* Implements Barring the Gates

Implement Barring the Gates

---

server/game/effects.js

Before pulling in with Walder Frey.

Check if a character is allowed to participate

---

server/game/cards/characters/04/joffreybaratheon.js
server/game/costs.js

Cost that makes sure the player does not get prompted to kneel a card when there is a specific card that should be kneeled.

Implement kneelSpecific cost function

---

server/game/cards/characters/01/ariannemartell.js

* Also port to target API, use proper method on player and standardise messaging.

Allow Arianne Martell to put a dupe of herself into play

---

server/game/costs.js
server/game/drawcard.js

Allow blanking of Limited keyword

---

server/game/cards/events/01/ameagercontribution.js
server/game/cards/events/01/confinement.js
server/game/cards/events/01/consolidationofpower.js
server/game/cards/events/01/doransgame.js
server/game/cards/events/01/dracarys.js
server/game/cards/events/01/fireandblood.js
server/game/cards/events/01/forthenorth.js
server/game/cards/events/01/growingstrong.js
server/game/cards/events/01/hearmeroar.js
server/game/cards/events/01/likewarmrain.js
server/game/cards/events/01/olennascunning.js
server/game/cards/events/01/oursisthefury.js
server/game/cards/events/01/puttothesword.js
server/game/cards/events/01/puttothetorch.js
server/game/cards/events/01/risenfromthesea.js
server/game/cards/events/01/seeninflames.js
server/game/cards/events/01/superiorclaim.js
server/game/cards/events/01/taketheblack.js
server/game/cards/events/01/tearsoflys.js
server/game/cards/events/01/thebearandthemaidenfair.js
server/game/cards/events/01/thekrakensgrasp.js
server/game/cards/events/01/theswordinthedarkness.js
server/game/cards/events/01/thethingsidoforlove.js
server/game/cards/events/01/unbowedunbentunbroken.js
server/game/cards/events/01/wakingthedragon.js
server/game/cards/events/01/wedonotsow.js
server/game/cards/events/01/winteriscoming.js
server/game/cards/events/06/thenorthremembers.js
test/server/cards/events/01/01045-thehandsjudgment.spec.js
test/server/cards/plots/06/06040-theannalsofcastleblack.spec.js

* Standardises messages.
* Converts implementations to use the cost and/or target API.
* Revert previous destructuring of event object.
* Removes redundant activePromptitle properties.
* Invokes game.transferGold() instead of two times invoking game.addGold().
* Changes var into let where possible.

Update Core Set event card implementations

---

client/GameComponents/ActivePlayerPrompt.jsx

Fixes THRONETEKI-19M
Fixes THRONETEKI-19P
Fixes THRONETEKI-19Q
Fixes THRONETEKI-19R
Fixes THRONETEKI-19S

Check that buttons exist before comparing length

---

server/game/cards/characters/06/nutethebarber.js

Have Nute the Barber target loser discard pile

---

server/game/cards/events/01/risenfromthesea.js
server/game/cards/plots/00/thepalemare.js
server/game/cards/plots/01/wildfireassault.js
server/game/cards/plots/06/duel.js
server/game/drawcard.js
server/game/effects.js
server/game/game.js
server/game/gamesteps/killcharacters.js
server/game/player.js
test/server/cards/events/01/01081-risenfromthesea.spec.js
test/server/effects/killbystrength.spec.js

Allow Risen from the Sea to save burn effects

---

server/game/cards/characters/02/wildlingscout.js

Also converts it to the cost / target API.
Fixes #1364

Remove incorrect limit from Wildling Scout

---

client/HowToPlay.jsx
less/application.less

Also add a topic list with bookmark links.

Explain Riddle vs Harvest interaction on How To Play page

---

server/game/cards/attachments/01/bodyguard.js
server/game/cards/attachments/06/improvedfortifications.js
server/game/cards/attachments/07/ghost.js
server/game/cards/characters/01/maesteraemon.js
server/game/cards/characters/02/serbarristanselmy.js
server/game/cards/characters/03/jorycassel.js
server/game/cards/characters/04/podrickpayne.js
server/game/cards/characters/04/renlybaratheon.js
server/game/cards/characters/05/victariongreyjoy.js
server/game/cards/characters/06/bericdondarrion.js
server/game/cards/characters/06/strongbelwas.js
server/game/cards/events/01/risenfromthesea.js
server/game/cards/events/02/bloodmagicritual.js
server/game/cards/events/03/healingexpertise.js
server/game/cards/locations/02/ironmines.js
server/game/drawcard.js
server/game/effects.js
server/game/game.js

Implement FFH Renly's cannot be saved effect

---

server/lobby.js

bubble non started games to the top of the list

---

server/game/player.js
server/game/setupcardaction.js
test/helpers/gameflowwrapper.js
test/server/setupcardaction.spec.js

Also, clear the cards in play if a mulligan is taken so all cards are shuffled
Fixes #826

Don't allow placing cards in setup before the game is started

---

server/game/cards/plots/06/wheelswithinwheels.js

Reinitialise the cards array when triggering the ability otherwise when triggered twice it can contain leftover cards
Fixes #1324

Fix wheels within wheels when triggered twice

---

client/DeckEditor.jsx
server/bannerfix.js

Fixes THRONETEKI-12M
Fixes THRONETEKI-12N
Fixes THRONETEKI-12K
Fixes THRONETEKI-12S

Don't try to add a banner card if there isn't one selected

---

server/game/cards/attachments/04/theboyking.js
server/game/cards/characters/01/joffreybaratheon.js
server/game/cards/characters/01/robbstark.js
server/game/cards/characters/03/aryastark.js
server/game/cards/characters/03/catelynstark.js
server/game/cards/characters/06/margaerytyrell.js
server/game/cards/events/02/funeralpyre.js
server/game/cards/events/03/ashardaswinter.js
server/game/cards/events/06/thenorthremembers.js
server/game/cards/locations/02/winterfellcrypt.js
server/game/cards/plots/07/thewhiteshadows.js
server/game/drawcard.js
server/game/gamesteps/killcharacters.js
server/game/player.js
test/server/integration/factionchange.spec.js

Take 2.
Fixes #837
Fixes #1222
Fixes #1386
Partial for #1351

Snapshot card state when killed or sacrificed

---

server/game/gamesteps/plot/selectplotprompt.js
server/game/gamesteps/uiprompt.js
server/game/plotcard.js

Allow buttons to be added to a waiting prompt
Fixes #1388

Allow the selected plot to be changed before plots are revealed

---

server/game/gamesteps/attachmentprompt.js
test/server/integration/setup.spec.js

Disallow attaching to opponent's characters during setup

---

server/game/game.js
server/game/player.js
test/server/cards/plots/06/06019-BarringTheGates.spec.js

Do not prevent take control with Barring the Gates

---

server/game/ChallengeRestriction.js
server/game/cards/01-Core/TheSwordInTheDarkness.js
server/game/cards/02.2-TRtW/BrothelMadame.js
server/game/challengetracker.js
server/game/effects.js
server/game/gamesteps/challengephase.js
server/game/player.js

Allow 'cannot initiate challenge' effects to stack

---

client/GameComponents/Messages.jsx
server/game/chatcommands.js
server/game/game.js
server/game/gamechat.js
server/game/gamesteps/taxationphase.js
test/server/game/chatcommands.spec.js

Add a prominent message at the end of a round as well as a general alerting method

---

server/game/cards/01-Core/BodyGuard.js
server/game/cards/06.6-TBWB/KingsBlood.js
server/game/cards/08.1-TAK/Ashemark.js
server/game/drawcard.js
server/game/gamesteps/abilityresolver.js
test/server/gamesteps/abilityresolver.spec.js

I'd love to use the snapshot functionality here, but it's not that straightforward. Ideas?

Implement King's Blood

---

server/game/chatcommands.js
server/game/game.js
server/game/gamesteps/abilityresolver.js
server/game/gamesteps/challenge/challengeflow.js
server/game/gamesteps/challengephase.js
server/game/gamesteps/plot/plotrevealprompt.js
test/server/cards/cancreatecards.spec.js
test/server/player/canattach.spec.js
test/server/player/costreduction.spec.js
test/server/player/drop.spec.js
test/server/player/find.spec.js
test/server/player/flipplotfaceup.spec.js
test/server/player/getduplicateinplay.spec.js
test/server/player/movecard.spec.js
test/server/player/playcard.spec.js
test/server/player/removeattachment.spec.js
test/server/player/searchDrawDeck.spec.js
test/server/player/setupdone.spec.js

Remove remaining usages of getOtherPlayer

---

server/game/cards/01-Core/AClashOfKings.js
server/game/cards/01-Core/ChamberOfThePaintedTable.js
server/game/cards/01-Core/Lightbringer.js
server/game/cards/02.3-TKP/TheKingsPeace.js
server/game/cards/03-WotN/KingRobbsHost.js
server/game/cards/04.1-AtSK/Riverrun.js
server/game/cards/04.3-FFH/SerEdmureTully.js
server/game/cards/04.4-TIMC/VaesTolorro.js
server/game/cards/06.1-AMAF/TheTumblestone.js
server/game/cards/07-WotW/Grenn.js
server/game/drawcard.js
server/game/game.js
server/game/gamesteps/challenge/applyclaim.js
server/game/gamesteps/triggeredabilitywindowtitles.js
test/server/card/drawcard.modifyPower.spec.js
test/server/game/power.spec.js

🙃 
Per #1474, Edmure will still trigger inappropriately for an immune character, but will no longer actually allow the player to gain power (since the immune character cannot lose the power).

Distinguish between gaining and moving power

---

server/game/cards/01-Core/ChamberOfThePaintedTable.js

Fix filtering and prompt for Painted Table

---

server/game/cards/06.5-OR/BeggingBrother.js

Allow Begging Brothers to cancel own abilities

---

.babelrc
package.json

Trying to get rid of deprecation warnings on node packages now.

Upgrade deprecated node packages

---

server/game/game.js
server/game/player.js
test/server/integration/takecontrol.spec.js
test/server/player/drop.spec.js
test/server/player/flipplotfaceup.spec.js
test/server/player/movecard.spec.js
test/server/player/putintoplay.spec.js

May fix other take control bugs as well, who knows at this point.
Likely progress toward #1351. (Might fix it but hard to tell the state of that issue since it's a bunch of disparate things)
Fixes #1490.

Fix improper discards of controlled cards

---

server/game/player.js
test/server/cards/06.6-TBWB/PayTheIronPrice.spec.js

Needs the change from #1500 that simplifies take control to fully work.
Fixes #1485.

Allow opponent-only attachments for Pay Iron Price

---

server/game/cards/07-WotW/Grenn.js

Fix triggering condition for Grenn

---

server/game/game.js
server/lobby.js
server/pendinggame.js
test/helpers/gameflowwrapper.js
test/server/PendingGame.spec.js
test/server/card/drawcard.hasKeyword.spec.js
test/server/game/applygameaction.spec.js
test/server/game/chat.spec.js
test/server/game/getplayers.spec.js
test/server/game/getsummary.spec.js
test/server/game/playermanagement.spec.js
test/server/game/power.spec.js
test/server/gamesteps/actionwindow.spec.js
test/server/gamesteps/dominancephase.spec.js

* Ensures that players that have been blocked by the game creator cannot join / watch the game.
* Hides games in the lobby from blocked users - previously it only hid games created by the blockee from the blocker.
Does not fix the issue of needing to refresh the page or log out / in after modifying the blocklist. (EDIT: #1509 fixed this)
Fixes #1505

Server-side fixes to block list

---

server/game/cards/04.2-CtA/DolorousEdd.js

Do not prompt to return D. Edd if not in play

---

docs/implementing-cards.md
server/game/AbilityTarget.js
server/game/AbilityTargetSelection.js
server/game/CardSelectors/BaseCardSelector.js
server/game/cards/01-Core/GhastonGrey.js
server/game/cards/01-Core/TearsOfLys.js
server/game/cards/02.1-TtB/Lady.js
server/game/cards/02.6-TS/TyeneSand.js
server/game/cards/03-WotN/Nymeria.js
server/game/cards/04.2-CtA/VenomousBlade.js
server/game/cards/05-LoCR/HighSepton.js
server/game/cards/07-WotW/Summer.js
server/game/cards/09-HoT/DrownedGodsApostle.js
server/game/gamesteps/ResolvedTargets.js
server/game/gamesteps/abilityresolver.js
test/server/AbilityTarget.spec.js
test/server/card/baseability.spec.js
test/server/cards/05-LoCR/HighSepton.spec.js
test/server/gamesteps/abilityresolver.spec.js

Implement High Septon

---

server/game/cards/09-HoT/SixMaidsInAPool.js
server/game/cards/09-HoT/WillasTyrell.js

Link to data PR: https://github.com/Alsciende/thronesdb-json-data/pull/200/commits/f83e5c16a4d67a2b6d0aeeea368c8b5cd00564d5

Implement Willas Tyrel & Six Maids in a Pool

---

server/game/chatcommands.js

Fix message serialization for /reveal-hand command

---

server/game/gamesteps/triggeredabilitywindow.js
test/server/cards/06.2-GtR/TheAnnalsOfCastleBlack.spec.js

Display aberrant ability source location in button prompt

---

server/gamerouter.js

allow for nodes to time out but stay connected (zmq is weird.)

---

server/game/effects.js

More progress toward figuring out #1506

Log stack trace when double unapplying setMinReserve

---

server/game/baseability.js
server/game/cardaction.js
server/game/forcedtriggeredability.js
server/game/gamesteps/abilityresolver.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/card/cardaction.spec.js
test/server/card/cardforcedreaction.spec.js
test/server/card/cardreaction.spec.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/AbilityLimits.spec.js

Increment ability limit even when cancelled

---

server/game/cards/09-HoT/BrienneOfTarth.js
server/game/cards/09-HoT/BrokenVows.js
server/game/cards/09-HoT/GarthTheGross.js
server/game/cards/09-HoT/GreenAppleKnight.js
server/game/cards/09-HoT/HighgardenCourtier.js
server/game/cards/09-HoT/HighgardenHonorGuard.js
server/game/cards/09-HoT/LastHearth.js
server/game/cards/09-HoT/LionsTooth.js
server/game/cards/09-HoT/SerDontosHollard.js
server/game/cards/09-HoT/SmallPaul.js
server/game/cards/09-HoT/TheBlueBard.js
server/game/cards/09-HoT/TheCitadel.js
server/game/cards/09-HoT/TheHound.js
server/game/cards/09-HoT/TheKnightOfFlowers.js

Implements remaining HoT cards except Emissary of Hightower

Implement House of Thorns draw cards

---

server/game/cards/09-HoT/EmissaryOfTheHightower.js
server/game/effect.js
server/game/effectengine.js
server/game/effects.js
server/game/playablelocation.js
server/game/player.js
test/server/cards/09-HoT/EmissaryOfTheHightower.spec.js
test/server/effectengine.spec.js
test/server/effects/canmarshalfrom.spec.js

Do not merge until #1552 has been merged.

Implement Emissary of the Hightower

---

server/game/costs/SpecificCardCost.js

Pass context into specific card costs

---

server/api/account.js

I haven't actually tried this, as i don't yet have locally deployed a recent enough node on my dev laptop, sorry about that.

sort the block list

---

client/GameBoard.jsx

Instead of checking that otherPlayer is null for each field passed into
a component, a placeholder object is used with the fields pre-blanked.

Default fields for other player on client

---

server/game/cards/04.2-CtA/BalonGreyjoy.js

Also standardise action label and message

Add limit to Balon Greyjoy (CtA)

---

client/GameBoard.jsx
client/GameComponents/PlayerPlots.jsx

This will probably conflict slightly with #1587, just let me know.

Extract plots to separate component

---

server/lobby.js

Check the list of games on the lobby every minute and automatically
close games that haven't started within 15 minutes of their creation
time.

Automatically close old pending games

---

server/game/cards/08.2-JtO/GatesOfTheMoon.js
server/game/cards/08.2-JtO/ThorosOfMyr.js

Implement Thoros of Myr & Gates of the Moon

---

server/game/cards/05-LoCR/OldWyk.js
server/game/cards/08.1-TAK/ValarDohaeris.js
server/game/game.js

Check immunity when placing on bottom of deck

---

server/game/cards/09-HoT/BrokenVows.js

Broken Vows: do not allow to take control of loyal characters

---

server/game/PaidGoldTracker.js
server/game/cards/02.2-TRtW/BrothelMadame.js
test/server/cards/02.2-TRtW/BrothelMadame.spec.js

Do not allow Brothel Madame to stack

---

server/game/cards/08.2-JtO/ConsumingFlames.js

Add condition to Consuming Flames

---

client/GameBoard.jsx
client/GameComponents/PlayerHand.jsx
client/GameComponents/PlayerRow.jsx
client/NewGame.jsx
server/game/game.js
server/game/player.js
server/pendinggame.js

Adds a New Game option to reveal both players' hand to any spectators, defaulted to off.

Add option to reveal players' hand to spectators

---

server/game/cards/02.2-TRtW/PoliticalDisaster.js
server/game/cards/02.3-TKP/NewlyMadeLord.js
server/game/cards/04.1-AtSK/Pyromancers.js
server/game/cards/09-HoT/NothingBurnsLikeTheCold.js

With the current prevalence of The House with the Red Door, this makes sure players will choose a legal target for any effects that discard locations.

Add gameAction property to location discard effects

---

client/HowToPlay.jsx

Also standardize description of Manual Commands.

Update link to unimplemented cards on HTP-page

---

server/game/cards/04.5-GoH/XaroXhoanDaxos.js

Only trigger XaroXD after marshalling own attachments

---

client/Application.jsx
client/Lobby.jsx
client/ReduxActions/account.js
client/ReduxActions/auth.js
client/pages/Activation.jsx
client/pages/Register.jsx
client/reducers/account.js
client/reducers/auth.js
server/api/account.js
server/server.js
server/services/UserService.js

Only allow accounts to be used when they have received an email and clicked the link in it

Email confirmation

---

server/game/cards/08.3-Km/Jhiqui.js
server/game/cards/08.3-Km/TheSkahazadhan.js

implement Targaryen cards from Kingsmoot

---

server/game/cards/08.4-FotOG/ObsidianArrows.js
server/game/cards/08.5-TFM/CerseisInformer.js
server/game/costs.js
server/game/costs/MoveTokenFromSelfCost.js

Obsidian Arrows: https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/27332697_1797655143600557_265714798727256064_n.jpg?oh=1503a93c58d3bab052b9c92167232db7&oe=5AF09A93
Cersei's Informer: https://thronesdb.com/card/08089

Implement Obsidian Arrows & Cersei's Informer

---

server/game/cards/02.6-TS/Ward.js
server/game/drawcard.js
server/game/effects.js
server/game/gamesteps/attachmentprompt.js
server/game/player.js
test/server/card/drawcard.canAttach.spec.js
test/server/cards/06.6-TBWB/PayTheIronPrice.spec.js

Fixes to Pay The Iron Price / attachment control

---

server/game/cards/06.5-OR/FleaBottom.js
server/game/effectengine.js
server/game/effects.js
test/server/cards/06.5-OR/FleaBottom.spec.js

Return dupes to bottom of deck for Flea Bottom

---

client/NewsAdmin.jsx
client/ReduxActions/news.js
client/SiteComponents/NewsItem.jsx
client/reducers/news.js
server/api/news.js
server/services/NewsService.js

Make the news display a bit more user friendly, allow editing and deleting of news entries

Improve news

---

server/game/cards/07-WotW/ScalingTheWall.js

Also bring message in line with current standards and revert object deconstruction.

Limit Scaling the Wall to loser locations

---

server/game/cards/08.4-FotOG/WiseMaster.js
server/game/cards/08.4-FotOG/Yunkai.js

Wise Master: https://scontent-ams3-1.xx.fbcdn.net/v/t31.0-8/27709846_2016917728531458_1642392789526987296_o.jpg?oh=4e5e0b5ba0794b1816c0a7208ab2ea20&oe=5B161E20
Yunkai: https://scontent-ams3-1.xx.fbcdn.net/v/t31.0-8/27709685_2016917698531461_7027436418164478280_o.jpg?oh=a3f95753f4c5cbfa250cb9d8258aed31&oe=5ADD5EB8

Implement Targaryen cards from FotOG

---

server/game/cardaction.js
server/game/cards/05-LoCR/TommenBaratheon.js
server/game/cards/08.4-FotOG/TheKingInTheNorth.js
server/game/effects.js
server/game/player.js
server/game/triggeredability.js
test/server/card/cardaction.spec.js
test/server/cards/01-Core/TheRedKeep.spec.js
test/server/cards/06.1-AMAF/ThePrincesPlan.spec.js
test/server/cards/08.4-FotOG/TheKingInTheNorth.spec.js
test/server/integration/effects.spec.js
test/server/integration/traitchange.spec.js

https://images-cdn.fantasyflightgames.com/filer_public/b4/35/b43521fa-7fa8-41a2-81c4-6ae591cf4d47/gt26_card_king-in-the-north.png

Implement The King in the North

---

server/game/basecard.js
server/game/cards/08.4-FotOG/WiseMaster.js
server/game/cards/agendas/UnitingTheSevenKingdoms.js

From the RRG: "Neutral cards are not considered to be in-faction or out-of-faction."

Clarify and enfore out-of-faction rules

---

client/ReduxActions/admin.js
client/UserAdmin.jsx
less/application.less
server/api/user.js
server/lobby.js
server/server.js
server/services/UserService.js
test/server/integration/lobby.spec.js

tidy up the admin page and add some stuff that makes the user removal process a little more automated and open to others

Admin improvements

---

server/game/cards/08.4-FotOG/SweetCersei.js

also, make it eslint clean and fix trailing whitespace error

move Sweet Cersei to the right pack directory

---

server/game/cards/08.1-TAK/TheIronBank.js

This is a partly implementation of  'The Iron Bank' (The Archmasters Key).
What this should do: Calculate the interest for the Iron bank.
What this does not do: Provide ways to use the gold

Partly implementation of The Iron Bank

---

server/game/cards/08.5-TFM/SerPounce.js

French spoiler image:
https://i.redditmedia.com/ld5rsmcojnrsO9VHnfmbz4L1jYzQK5FV7PZ1w6_QChs.jpg?w=493&s=ef319e2d45d8d2169be9fd0c1d21cce1
When ready this PR can be merged, as we are (reasonably) sure the english card
name will be the english character name from the books.

implement Ser Pounce (TFM)

---

server/game/cards/08.5-TFM/Mhysa.js

French spoiler image here: https://i.redd.it/cp5ydmxlchg01.jpg
When ready this PR can be merged, as we are (reasonably) sure the english card
name will be the same of the french one.

implement Mhysa (TFM)

---

server/game/cards/08.6-SAT/Qyburn.js

French spoiler image:
https://i.redditmedia.com/VrrAa5wBUeNL4RToajSnC99CgAJmLX8kE_IgfUyY8fw.jpg?w=515&s=9deb8e43aa158f83f36c8571f7bb7e50
It should be safe to merge this PR when ready, as we are reasonably sure that
the official english card name will be the same.

implement Qyburn (SAT)

---

server/game/cards/08.4-FotOG/CoastalReaver.js

Coastal Reaver: do not reveal the card put back on the deck

---

server/game/cards/08.6-SAT/SaltcliffeSailor.js

incomplete English spoiler:
https://images-cdn.fantasyflightgames.com/filer_public/07/b8/07b87d96-2edd-4869-b7f0-c87e0a9c49c0/gt28_a1_cardfan.png
full French spoiler: 
https://i.redditmedia.com/bpUBzsCefjoO3T9HwF51UImKcQIJNirxit4hBKF99LU.jpg?w=510&s=5953033e5154de82bc0231662b1af61f

implement Saltcliffe Sailor (SAT)

---

server/game/cards/10-SoD/BreakingTies.js

https://images-cdn.fantasyflightgames.com/filer_public/8c/a3/8ca3e0e9-1bf5-4289-ab7b-577d40099063/gt30_breaking-ties.png

Implement Breaking Ties

---

server/game/cards/08.5-TFM/KingsMen.js

not to be merged yet: we're waiting for the official english card name

implement King's Men (TFM)

---

server/game/cards/08.5-TFM/BayOfSeals.js

not to be merged yet: we're waiting for the official english card name

implement Bay of Seals (TFM)

---

server/game/cards/08.6-SAT/TheCrowIsATricksyBird.js
server/game/effects.js
server/game/gamesteps/plot/selectplotprompt.js
server/game/gamesteps/plotphase.js
server/game/gamesteps/uiprompt.js
server/game/player.js

https://i.redditmedia.com/3uyEYaQdp7tx9r-ekjvp2hnwcefmNxOHoTXxECTSOmo.jpg?w=508&s=2ad988b04de9e7ff0c6640c0858ca3e7
Plot action: kneel your faction card to choose an opponent and look at his plot deck. Choose one plot in that deck. This player must reveal that plot the next time he reveals a plot card, if possible.
Name seems pretty much confirmed, as there is an old CCG card with the same name: https://vignette.wikia.nocookie.net/cardguide/images/7/7a/Thecrowisatricksybird-ASoT.JPG/revision/latest/scale-to-width-down/350?cb=20170602061554

Implement The Crow is a Tricksy Bird

---

server/game/cards/04.3-FFH/NightGathers.js
server/game/effects.js
test/server/effects/canmarshalfrom.spec.js

should wait for #1780 to be merged as this requires the new canMarshal() effect

restrict Night Gathers to only marshal characters

---

server/game/cards/08.5-TFM/TheFaithMilitant.js

card spoiler: https://images-cdn.fantasyflightgames.com/filer_public/72/c3/72c3e0f0-5368-4f99-83c6-a79bf760aed4/gt27_the-faith-militant.png

implement The Faith Militant agenda (TFM)

---

server/game/player.js

Reset the number of limited cards played by each player at the start of each round (Plot phase) and not at the start of the marshal phase.

Reset the number of limited cards played by each player at the start of each round

---

server/game/cards/08.2-JtO/ArianneMartell.js

Restrict Arianne Martell's (JtO) action to the challenges phase

---

server/game/cards/10-SoD/Extortion.js
server/game/cards/10-SoD/MyrcellaBaratheon.js

Myrcella Baratheon: https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/28468308_2026623064227591_7881423779124668504_n.jpg?oh=02b7a290b6556ae942808cda610bb93e&oe=5B0EEA1B
Extortion: https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/28575659_2026623047560926_2788492622903714422_n.jpg?oh=cdd2f3b7c18c6ef24afc60204b8f32c6&oe=5B01F53F

Implement Lannister cards from Sands of Dorne

---

server/game/cards/08.6-SAT/Godswood.js
server/game/cards/08.6-SAT/HostOfTheRiverlands.js

Not to be merged yet, as we don't have neither the corresponding JSON data yet,
nor the proper english card names. For review purpose, I've kept at the
beginning of each card implementation a URL pointing to spoiler image; it
should be removed before merging too.

implement Stark cards from Someone Always Tells chapter pack

---

server/game/cards/08.5-TFM/Coldhands.js

https://images-cdn.fantasyflightgames.com/filer_public/bb/c9/bbc92b6b-349c-40b8-b736-16dcea81e746/gt27_a1_cardfan.png

Implement Coldhands

---

server/game/CardMatcher.js
server/game/cards/10-SoD/SpareBoot.js
server/game/cards/10-SoD/Turncloak.js
test/server/CardMatcher.spec.js

Spare Boot: https://www.wardensofthemidwest.com/wp-content/uploads/2018/03/GT30_Cards_COMPOSITE-32-211x300.png
Turncloak: https://www.wardensofthemidwest.com/wp-content/uploads/2018/03/GT30_Cards_COMPOSITE-33-211x300.png

Implement The Night's Watch cards from Sands of Dorne

---

server/game/cards/10-SoD/BeaconOfTheSouth.js
server/game/cards/10-SoD/LeytonHightower.js

Images: https://scontent-ams3-1.xx.fbcdn.net/v/t1.0-9/28783710_1917942861614435_1868086081418353449_n.jpg?oh=2f02237d0101a8614367456a3e138e91&oe=5B4E6204

Implement Tyrell cards from Sands of Dorne

---

server/game/basecard.js
server/game/cards/01-Core/AMeagerContribution.js
server/game/cards/01-Core/SupportingTheFaith.js
server/game/cards/02.2-TRtW/BrothelMadame.js
server/game/cards/02.2-TRtW/WardensOfTheWest.js
server/game/cards/02.4-NMG/PaidOff.js
server/game/cards/02.4-NMG/RedCloaks.js
server/game/cards/04.1-AtSK/LeviesAtTheRock.js
server/game/cards/04.1-AtSK/WhiteTree.js
server/game/cards/04.6-TC/PodrickPayne.js
server/game/cards/05-LoCR/Alayaya.js
server/game/cards/05-LoCR/LannisportTreasury.js
server/game/cards/06.2-GtR/Polliver.js
server/game/cards/06.2-GtR/WexPyke.js
server/game/cards/06.3-TFoA/CorsairsDirk.js
server/game/cards/06.5-OR/StannissCavalry.js
server/game/cards/08.2-JtO/Dareon.js
server/game/cards/08.2-JtO/TheHouseOfBlackAndWhite.js
server/game/cards/08.3-Km/LyseniPirate.js
server/game/cards/08.3-Km/MolesTown.js
server/game/cards/08.6-SAT/SaltcliffeSailor.js
server/game/cards/10-SoD/Extortion.js
server/game/chatcommands.js
server/game/costs.js
server/game/game.js
server/game/gamesteps/bestowprompt.js
server/game/gamesteps/taxationphase.js
server/game/player.js
test/server/costs/payreduceablegoldcost.spec.js

Introduces methods for spending gold and returning gold to treasury, as well as updates `transferGold` to have a less confusing interface and handle the following scenarios:
* player => player
* player => card
* card => player
* card => card

Better encapsulate gold usages

---

server/game/cards/04.2-CtA/BalonGreyjoy.js

Restrict Balon Greyjoy's (CtA) action ability to challenges

---

server/game/cards/08.5-TFM/HouseYronwoodKnight.js

french spoiler: https://www.instagram.com/p/BfQd_yCBTn0/

implement House Yronwood Knight (TFM)

---

client/NavBar.jsx
client/ReduxActions/game.js
client/ReduxActions/socket.js
client/reducers/lobby.js
less/site.less

replace toastrs with funky little icons to show lobby / game node socket connection status

---

server/game/cards/06.3-TFoA/FeverDreams.js

Fix method name typo in Fever Dreams

---

server/game/cards/04.5-GoH/BlessHimWithSalt.js

Check controller can draw for Bless Him With Salt

---

server/game/cards/10-SoD/Darkstar.js
server/game/cards/10-SoD/EllariaSand.js
server/game/cards/10-SoD/HouseDayneEscort.js
server/game/cards/10-SoD/LorezaSand.js
server/game/cards/10-SoD/MaesterKedry.js
server/game/cards/10-SoD/NymeriaSand.js
server/game/cards/10-SoD/NymeriasGuard.js
server/game/cards/10-SoD/QuentynMartell.js
server/game/cards/10-SoD/TheRedViper.js
server/game/challenge.js
server/game/costs.js

Implements all remaining Martell characters from Sands of Dorne, with the exception of Obella Sand.
https://imgur.com/a/pjdvw

Implement remaining Martell characters from Sands of Dorne

---

server/game/cards/10-SoD/Beguiled.js
server/game/cards/10-SoD/NoUseForGrief.js
server/game/cards/10-SoD/Starfall.js
server/game/cards/10-SoD/ToTheSpears.js

Implements all remaining Martell locations, attachments & events from Sands of Dorne, with the exception of False Plans.
https://imgur.com/a/pjdvw

Implement remaining Martell locations, attachments & events from Sands of Dorne

---

server/game/cards/10-SoD/GreatjonUmber.js
server/game/cards/10-SoD/Qarth.js
server/game/cards/10-SoD/TasteForFlesh.js

https://i.imgur.com/BWoVgA5.jpg

Implement Stark cards from Sands of Dorne & Qarth

---

server/game/cards/10-SoD/FleetFromPyke.js
server/game/cards/10-SoD/Plundered.js
server/game/cards/10-SoD/SeaDragonTower.js
server/game/cards/10-SoD/SerCortnayPenrose.js

https://i.imgur.com/M7VWP5k.jpg

Implement Baratheon & Greyjoy cards from Sands of Dorne

---

server/game/cards/10-SoD/ForcedMarch.js
server/game/drawcard.js

https://i.imgur.com/iCLXszW.jpg

Implement Forced March

---

server/game/cards/01-Core/ANobleCause.js
server/game/cards/10-SoD/GrandMelee.js
server/game/cards/10-SoD/PeaceAndProsperity.js

Fixes #1801.
https://i.imgur.com/iCLXszW.jpg

Implement remaining neutral plots from Sands of Dorne

---

server/game/cards/10-SoD/BrothersRobes.js
server/game/cards/10-SoD/JadeSeaDromond.js
server/game/cards/10-SoD/OffToGulltown.js
server/game/cards/10-SoD/OldtownScholar.js
server/game/cards/10-SoD/SeptonMeribald.js

https://i.imgur.com/cHi8d9Y.jpg
https://i.imgur.com/Y39sTsZ.jpg

Implement remaining neutral characters, locations & attachments from Sands of Dorne

---

server/game/cards/10-SoD/FalsePlans.js
server/game/cards/10-SoD/Missandei.js
server/game/cards/10-SoD/ObellaSand.js
server/game/deck.js
server/game/forcedtriggeredability.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/promptedtriggeredability.js
server/game/triggeredability.js
test/server/card/cardreaction.spec.js
test/server/cards/10-SoD/FalsePlans.spec.js
test/server/cards/10-SoD/Missandei.spec.js
test/server/cards/10-SoD/ObellaSand.spec.js
test/server/gamesteps/triggeredabilitywindow.spec.js

* Implements False Plans, Obella Sand, and Missandei
* Abilities can now be sent an array of locations from which they can be triggered.
https://imgur.com/a/pjdvw

Implement "when discarded" abilities from Sands of Dorne

---

server/game/cards/10-SoD/DoranMartell.js

Add condition to Doran Martell (SoD)

---

server/game/cards/08.6-SAT/YouWinOrYouDie.js

My first implemented card, please check whether it’s ok. I choosed the
easiest one for beginning :)

Implement You Win or You Die

---

client/Application.jsx
client/routes.js
less/site.less
package-lock.json
package.json

will add a gif that shows this in action later...

add transitions for navigating between pages

---

server/scripts/fetchdata/CardgameDbImageSource.js

Do not attempt to fetch images if missing CGDB ID

---

client/reducers/cards.js

Only load deck faction info if factions loaded

---

client/Components/GameBoard/Card.jsx
client/Components/GameBoard/CardPile.jsx
client/Components/GameBoard/Droppable.jsx
client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/Messages.jsx
client/Components/GameBoard/PlayerBoard.jsx
client/Components/GameBoard/PlayerHand.jsx
client/Components/GameBoard/PlayerPlots.jsx
client/Components/GameBoard/PlayerRow.jsx
client/constants.js
less/cards.less
less/gameboard.less
package-lock.json
package.json
webpack.config.vendor.js

to use react-dnd and generally tidy the whole thing up

refactor drag drop 

---

server/game/cards/01-Core/AryaStark.js

do not try to dupe core arya if the draw deck is empty

---

client/Components/Lobby/SideBar.jsx
less/application.less

https://giphy.com/gifs/7J86tesVI1KXwZwock

add transitions for the user sidebar

---

client/pages/Profile.jsx
client/reducers/account.js
client/reducers/auth.js
server/api/account.js
server/game/game.js
server/gamenode/gameserver.js
server/lobby.js
server/models/User.js
server/pendinggame.js
server/server.js
server/services/UserService.js
server/socket.js
test/server/integration/lobby.spec.js

Convert the user object to be a class, so that the intent is much clearer as the data is passed from place to place
Fix a bug where the user data was not sent across the wire from the game node on a sync, so settings/blocklist data were lost causing the block list not to work

Abstract user

---

server/game/cards/08.5-TFM/SacrificeToTheRedGod.js

French spoiler: https://i.redditmedia.com/0uqmMRzViESffdRtQi59pPVqXFJde4cd88eXUA_VObA.jpg?w=495&s=2bfddfedf849902ed3ec0fa4aea3cf8e

implement Sacrifice to the Red God (TFM)

---

server/game/cards/08.5-TFM/GivenToTheDrownedGod.js
server/game/cards/08.5-TFM/TarleTheThriceDrowned.js
server/game/costs.js

not to be merged yet, as official english card names are still unknown
French spoiler images:
- Tarle: https://i62.servimg.com/u/f62/17/07/69/48/27858510.jpg
- Offer: https://scontent-cdg2-1.xx.fbcdn.net/v/t1.0-9/27973413_10211210705523648_4881871956079145362_n.jpg?oh=085f4c4b18b6a31ac20789980888e48b&oe=5B17B03C

implement Greyjoy cards from The Faith Militant chapter pack

---

server/game/cards/01-Core/LordsportShipright.js

Fix Lordsport Shipright  so that only play area locations are available to choose from

Fix Lordsport Shipright 

---

server/game/cards/08.5-TFM/SecretPact.js

French spoiler image:
https://i.redditmedia.com/i5HUPDjKuemXv1Is077rHNtrnBJ4uXRwiapcqk85axs.jpg?w=495&s=c34a879d5d2b217e296a0adf8c199398
Not to be merged yet, as the english card name is guesswork on my part.

implement Secret Pact (TFM)

---

server/game/cards/08.5-TFM/ArborQueen.js
server/game/cards/08.5-TFM/HighgardenRefugee.js

French spoilers:
- https://www.instagram.com/p/BfMFx9qBZWT/
- https://www.instagram.com/p/BfMFqqABtLP/
not to be merged yet, as final card names and codes are not known yet

implement Tyrell cards from The Faith Militant chapter pack

---

server/game/cards/08.5-TFM/CompelledByTheFaith.js

french spoiler:
https://i.redditmedia.com/1UpI8ZdXeb1qpNVb7pBcRU3D46C1zg4-xZpDHvaQAAY.jpg?w=1024&s=8807fbff18075593f04001a584f54da6

implement Compelled by the Faith (TFM)

---

client/Components/Decks/AddDeck.jsx
client/Components/Decks/DeckEditor.jsx
client/Components/Decks/EditDeck.jsx
less/deckbuilder.less

Refactor the deck builder again

---

server/game/cards/01-Core/GreenbloodTrader.js
server/game/cards/05-LoCR/TywinLannister.js
server/game/cards/08.6-SAT/TheCrowIsATricksyBird.js
server/game/cards/10-SoD/Dorne.js
server/game/gamesteps/menuprompt.js

This allows the card that the button is representing to automatically be passed through to the handler
rework the (very few) places where this is used to take advantage of this
fix greenblood trader when there is <2 cards in deck

Add a 'mapCard' property to the menu button

---

client/Components/GameBoard/CardZoom.jsx
client/Components/GameBoard/GameBoard.jsx
client/Components/GameBoard/PlayerBoard.jsx
client/Components/Site/NavBar.jsx
less/application.less
less/cards.less
less/chat.less
less/gameboard.less
less/site.less
less/variables.less

shrink the nav bar
shrink the player stat rows
add horizontal scrollbar to play area
fix firefox to not grow the play area vertically beyond the screen with no way of scrolling
extend the chat window full height
make the card zoom overlay
fix card row spacing

Various styling fixes

---

client/Components/Games/GameLobby.jsx
client/ReduxActions/socket.js
client/reducers/games.js
client/reducers/lobby.js
less/site.less

1. Fix new game window sticking if the current game is closed
2. Fix being unable to join/rejoin a game if the connection is lost
3. Fix the styling of the leave game confirmation box

Minor client fixes

---

server/game/cards/05-LoCR/OldWyk.js

Fix Old Wyk for dupes and put into play restrictions

---

server/game/effects.js
server/game/player.js

Allow saving vs Coldhands ability

---

client/Components/GameBoard/ActivePlayerPrompt.jsx
client/Components/GameBoard/CardNameLookup.jsx
client/Components/GameBoard/GameBoard.jsx
server/game/cards/04.1-AtSK/RubyOfRhllor.js
server/game/gamesteps/menuprompt.js

Implement Ruby of R'hllor

---

server/game/CardSelectors/BaseCardSelector.js
server/game/CardSelectors/EachPlayerCardSelector.js
server/game/CardSelectors/MaxStatCardSelector.js
server/game/cards/02.6-TS/DrownedGodsBlessing.js
server/game/effects.js
server/game/gamesteps/selectcardprompt.js

This is a complicated effect with fairly obvious reasons as to why its been left until now.
Here's my attempt at it
Fixes #1903

Drowned gods blessing

---

server/game/cards/08.6-SAT/SeptonCellador.js

Character, Night's Watch, The Seven, Loyal
Cost: 4
STR: 2
Icons: Intrigue
Challenge action: kneel Septon Cellador to choose an opponent. This player must choose and discard a character from his hand unless he reveals a hand containing no character.

Implement Septon Cellador

---

client/Components/Decks/DeckEditor.jsx
client/Components/Decks/DeckSummary.jsx
client/Components/Form/Typeahead.jsx
client/ReduxActions/deck.js
client/deck-validator.js
client/reducers/cards.js
server/services/DeckService.js

This only adds support to the deck builder, it does not add server side support, or allow rookery games to be created

Add rookery support to the deck builder

---

server/game/cards/10-SoD/OffToGulltown.js

Restrict "Off to Gulltown" to challenge phase

---

server/game/cards/03-WotN/JoryCassel.js
server/game/drawcard.js

Also standardize message and remove underscore usage.

Convert Jory Cassel to costs API

---

server/game/cards/01-Core/GreenbloodTrader.js
server/game/cards/01-Core/HeadsOnSpikes.js
server/game/cards/02.2-TRtW/InDoransName.js
server/game/cards/02.3-TKP/INeverBetAgainstMyFamily.js
server/game/cards/02.3-TKP/TheKingsPeace.js
server/game/cards/02.6-TS/Jhogo.js
server/game/cards/03-WotN/KingRobbsHost.js
server/game/cards/04.2-CtA/BeggarKing.js
server/game/cards/04.2-CtA/KnightOfSummer.js
server/game/cards/04.2-CtA/StarfallCavalry.js
server/game/cards/04.6-TC/TyrionsChain.js
server/game/cards/05-LoCR/GoldenTooth.js
server/game/cards/05-LoCR/InsidiousScheme.js
server/game/cards/06.1-AMAF/EastwatchCarpenter.js
server/game/cards/06.1-AMAF/SlaversBayPort.js
server/game/cards/06.2-GtR/IronIslandsMarket.js
server/game/cards/06.2-GtR/LightOfTheLord.js
server/game/cards/06.3-TFoA/DornishFiefdom.js
server/game/cards/06.3-TFoA/UndergroundVault.js
server/game/cards/06.4-TRW/Plunder.js
server/game/cards/06.4-TRW/SecretSchemes.js
server/game/cards/06.5-OR/TheIronBankWillHaveItsDue.js
server/game/cards/06.6-TBWB/NorthernKeep.js
server/game/cards/07-WotW/CalledIntoService.js
server/game/cards/08.3-Km/TheSkahazadhan.js
server/game/cards/08.6-SAT/Godswood.js
server/game/cards/09-HoT/SixMaidsInAPool.js
server/game/cards/09-HoT/TradeRoutes.js

also apply minor style fixes here and there, for consistency

convert a bunch of unneeded var to let in card implementations

---

server/game/cards/08.6-SAT/SeptonCellador.js

Remove leftover underscore usage from Septon Cellador

---

server/game/cards/08.6-SAT/APlotAgainstTheQueen.js
server/game/cards/08.6-SAT/TheSevenPointedStar.js

Current card names are best guesses from translation, need to wait for official card names.
https://i.redditmedia.com/2ijjv5Eg8-B5rYOwJPv2d6sIbaIuW_8HxKUmLdLRVpo.jpg?w=507&s=c1444017cc4c66735a7e05a8bf5ee2ea
https://i62.servimg.com/u/f62/13/09/73/62/11910.jpg

Implement remaining Someone Always Tells cards

---

server/game/cards/02.1-TtB/VaesDothrak.js

Only triggers Vaes Dothrak when you reveal a plot, not when any player
reveals a plot. Also converts it to use the target API.

Fixes to Vaes Dothrak

---

server/game/cards/08.6-SAT/MaceTyrell.js
server/game/cards/08.6-SAT/ThisMustBeAnsweredFiercely.js

Not to be merged yet, as we don't have neither the corresponding JSON data yet,
nor the proper english card name for the event. For review purpose, I've kept
at the beginning of each card implementation a URL pointing to spoiler image;
it should be removed before merging too.

implement Tyrell cards from Someone Always Tells chapter pack

---

server/game/cards/08.6-SAT/SaltcliffeSailor.js
server/game/cards/08.6-SAT/TheSevenPointedStar.js

FIXES THRONETEKI-261
FIXES #1954

Fix Saltcliffe Sailor & The Seven-Pointed Star

---

client/ReduxActions/socket.js
client/menus.js
client/pages/NodesAdmin.jsx
client/pages/UserAdmin.jsx
client/reducers/admin.js
client/routes.js
server/api/user.js
server/gamenode/zmqsocket.js
server/gamerouter.js
server/lobby.js

can see the number of games on a node, disable/enable them and restart them
should provide node admin without needing to login to the box

Add a page to allow the game nodes to be administered

---

server/game/cards/08.6-SAT/TheBastardOfNightsong.js

Ensure The Bastard of Nightsong only triggers on power challenges

---

server/game/cards/08.6-SAT/TheGreatSeptOfBaelor.js

The Great Sept of Baelor: fix message about effect duration

---

server/game/cards/11.1-TSC/NefariousAcolyte.js

Implement Nefarious Acolyte

---

server/game/cards/11.1-TSC/SerGerrisDrinkwater.js
server/game/cards/11.1-TSC/TheShadowCity.js
server/game/costs.js
server/game/costs/CostBuilders.js
server/game/costs/DiscardFromShadowsCost.js

Implement Martell cards from The Shadow City

---

server/game/cards/11.1-TSC/NighttimeMarauders.js

Implement Nighttime Marauders

---

server/game/cards/11.1-TSC/SchemingSepton.js

Implement Scheming Septon

---

server/game/cards/11.1-TSC/MargaerysInfluence.js

Implement Margaery's Influence

---

server/game/cards/11.1-TSC/BoltonFlayer.js
server/game/cards/11.1-TSC/NorthernArmory.js

Implement Stark cards from The Shadow City

---

server/game/cards/11.1-TSC/BurningTheDead.js
server/game/cards/11.1-TSC/ExchangeOfInformation.js

Implement remaining neutral cards for The Shadow City

---

server/game/cards/11.1-TSC/AegonTargaryen.js
server/game/cards/11.1-TSC/UnexpectedReturn.js

Implement Targaryen cards from The Shadow City

---

server/game/cards/11.1-TSC/SeizeTheInitiative.js
server/game/cards/11.1-TSC/SerRobertStrong.js
server/game/game.js
server/game/gamesteps/plot/firstplayerprompt.js

Implement remaining Lannister and Greyjoy cards from The Shadow City

---

server/game/cards/06.3-TFoA/RecruiterForTheWatch.js
test/server/cards/06.3-TFoA/RecruiterForTheWatch.spec.js

Expire Recruiter for Watch when target leaves play

---

server/api/cards.js
server/services/CardService.js

Add more properties to the cards sent to the client so that the client can display them when there's no images

Export extra data for cards

---

server/game/cards/11.2-TMoW/MarchOnWinterfell.js
server/game/cards/11.2-TMoW/SerJustinMassey.js
server/game/cards/11.2-TMoW/TheQueenOfThorns.js
server/game/cards/11.2-TMoW/WymanManderly.js
server/game/gamesteps/killcharacters.js
server/game/player.js

Implement cards from The March on Winterfell first preview

---

server/game/cards/10-SoD/Val.js

Add canPutIntoPlay check to Val

---

server/game/cards/11.1-TSC/BoltonFlayer.js

Disallow saving vs Bolton Flayer

---

server/game/cards/11.3-SoKL/Catspaw.js
server/game/cards/11.3-SoKL/GlassCandle.js
server/game/cards/11.3-SoKL/PoorFellows.js
test/server/cards/01-Core/RandyllTarly.spec.js

Implement spoilers from Streets of King's Landing

---

server/game/cards/01-Core/RobbStark.js

Don't trigger Robb Stark (Core) if ability can't change game state

---

server/game/PropertyTypes/KeywordsProperty.js
server/game/cards/11.3-SoKL/GrowingAmbition.js

https://images-cdn.fantasyflightgames.com/filer_public/46/01/4601c97b-a4a4-4065-a69e-3e20cc774561/gt33_a1_growing-ambition.png

Implement Growing Ambition

---

server/game/Claim.js
server/game/cards/02.5-COW/TrialByCombat.js
server/game/cards/02.5-COW/VengeanceForElia.js
server/game/cards/07-WotW/MaesterAemon.js
server/game/cards/08.6-SAT/MyaStone.js
server/game/cards/09-HoT/NowItComesToWar.js
server/game/cards/titles/MasterOfWhispers.js
server/game/challenge.js
server/game/effects.js
server/game/gamesteps/challenge/ClaimPrompt.js
server/game/gamesteps/challenge/applyclaim.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/cards/01-Core/MasterOfWhispers.spec.js

Overhauls claim to allow it to be applied to multiple players at once.
Progress toward #1237

Implement Master of Whispers multi-claim ability

---

server/game/cards/01-Core/EddardStark.js
server/game/cards/02.3-TKP/TheKingsPeace.js
server/game/cards/02.4-NMG/ForTheWatch.js
server/game/cards/02.5-COW/TrialByCombat.js
server/game/cards/04.3-FFH/TheScorpionsSting.js
server/game/cards/04.6-TC/BattleOfTheBlackwater.js
server/game/cards/05-LoCR/BridgeOfSkulls.js

Card fixes for Melee

---

docs/implementing-cards.md
server/game/AllowedChallenge.js
server/game/cards/01-Core/AStormOfSwords.js
server/game/cards/01-Core/CasterlyRock.js
server/game/cards/01-Core/KhalDrogo.js
server/game/cards/01-Core/OlennasInformant.js
server/game/cards/02.3-TKP/TheSilverSteed.js
server/game/cards/04.6-TC/RelentlessAssault.js
server/game/cards/05-LoCR/ALannisterAlwaysPaysHisDebts.js
server/game/cards/06.5-OR/OlennasMachinations.js
server/game/cards/08.1-TAK/BloodyArakh.js
server/game/cards/08.2-JtO/SailingTheSummerSea.js
server/game/cards/09-HoT/TheSpidersWeb.js
server/game/cards/11.2-TMoW/MarchOnWinterfell.js
server/game/cards/titles/HandOfTheKing.js
server/game/challengetracker.js
server/game/effects.js
server/game/gamesteps/challengephase.js
server/game/gamesteps/chooseopponentprompt.js
server/game/player.js
test/server/cards/01-Core/HandOfTheKing.spec.js

Implement Hand of the King additional challenge

---

server/game/challenge.js
server/game/gamesteps/challenge/challengeflow.js
server/game/player.js
test/server/integration/MeleeTitles.spec.js

Implement rival bonuses for Melee

---

server/lobby.js
server/services/UserService.js

bring the clear sessions button/command up to date with the new(ish) user auth

fix clear sessions

---

server/game/AllowedChallenge.js
server/game/challengetracker.js
test/server/cards/01-Core/KhalDrogo.spec.js
test/server/integration/challengesphase.spec.js

* Don't mark an allowed challenge as being used when you're the defending player
* Don't remove allowed challenges at the start of the round when reseting the number of challenges

Fix how allowed challenges are tracked

---

server/game/cards/11.5-IDP/HeCallsItThinking.js
server/game/cards/11.5-IDP/RefurbishedHulk.js
server/game/cards/11.5-IDP/StormsEndMaester.js
server/game/cards/11.5-IDP/ThreeFingerHobb.js
server/game/gamesteps/taxation/discardtoreserveprompt.js
test/server/cards/01-Core/RisenFromTheSea.spec.js
test/server/cards/06.5-OR/FleaBottom.spec.js
test/server/integration/burneffects.spec.js
test/server/integration/leavingplay.spec.js

https://www.fantasyflightgames.com/en/news/2018/6/19/in-daznaks-pit/

Implement cards from In Daznak's Pit preview

---

server/api/account.js

validate that the id passed in is a valid mongo id before sending it on to mongo

Fix the activate api validation

---

server/game/cards/11.2-TMoW/BowelsOfCasterlyRock.js
server/game/cards/11.2-TMoW/CityGates.js
server/game/cards/11.2-TMoW/CunningSteward.js
server/game/cards/11.2-TMoW/HagensDaughter.js
server/game/cards/11.2-TMoW/HizdahrZoLoraq.js
server/game/cards/11.2-TMoW/HonorBound.js
server/game/cards/11.2-TMoW/MaidenOfPoisons.js
server/game/cards/11.2-TMoW/Penny.js
server/game/cards/11.2-TMoW/TheBloodyFlux.js
server/game/cards/11.2-TMoW/TradingWithQohor.js
server/game/cards/11.2-TMoW/TychoNestoris.js
server/game/costs.js
server/game/effects.js
server/game/game.js
server/game/player.js
test/server/cards/01-Core/TheWall.spec.js
test/server/integration/burneffects.spec.js
test/server/integration/factionchange.spec.js
test/server/integration/forcedreactionorder.spec.js
test/server/integration/leavingplay.spec.js
test/server/integration/setup.spec.js
test/server/integration/takecontrol.spec.js

http://www.cardgamedb.com/index.php/agameofthrones2ndedition/a-game-of-thrones-2nd-edition-cards/_/dance-of-shadows-cycle/the-march-on-winterfel/

Implement cards from The March on Winterfell

---

server/game/cards/11.2-TMoW/ServeObeyProtect.js

http://lcg-cdn.fantasyflightgames.com/got2nd/GT32_36.jpg

Implement Serve. Obey. Protect.

---

.eslintrc
server/game/cards/11.4-MoD/Rhaegal.js

Pass event object into Rhaegal ability listener

---

server/game/PlayActions/AmbushCardAction.js
server/game/PlayActions/MarshalCardAction.js
server/game/PlayActions/MarshalIntoShadowsAction.js
server/game/PlayActions/OutOfShadowsAction.js
server/game/gamechat.js
server/game/gamesteps/phase.js
server/game/gamesteps/taxationphase.js
server/game/player.js
test/server/game/gamechat.formatMessage.spec.js

Refactor game chat to not use underscore
send player name as an argument so that players can be highlighted
standardise some messages so they show better as icons
add start of round and end of phase markers

game chat improvements

---

server/game/cards/11.6-DitD/CerseiLannister.js
server/game/cards/11.6-DitD/DaggersInTheDark.js
server/game/cards/11.6-DitD/Moqorro.js
server/game/cards/11.6-DitD/RedRonnet.js
server/game/cards/11.6-DitD/UnderhandedMethods.js
server/game/cards/11.6-DitD/Varys.js
test/server/cards/01-Core/Bodyguard.spec.js
test/server/cards/09-HoT/EmissaryOfTheHightower.spec.js
test/server/cards/09-HoT/HiddenThorns.spec.js
test/server/integration/EndOfPhaseTimings.spec.js
test/server/integration/takecontrol.spec.js

https://www.fantasyflightgames.com/en/news/2018/7/9/daggers-in-the-dark/

Implement cards from Daggers in the Dark preview article

---

server/game/effects.js
test/server/cards/11.2-TMoW/Meereen.spec.js

http://www.cardgamedb.com/forums/index.php?/topic/39868-ruling-meereen/

Implement multiple Meereen trigger rulings

---

server/game/cards/11.2-TMoW/HagensDaughter.js

Ruling: http://www.cardgamedb.com/forums/index.php?/topic/39870-ruling-hagens-daughter-dracarys/

Allow Hagen's Daughter to save vs burn

---

package-lock.json
package.json

Ensures that decks with multiple Trading w/ Qohor's are marked as
invalid.
http://www.cardgamedb.com/forums/index.php?/topic/39873-ruling-alliance-trading-with-qohor/

Bump version for deck helper

---

server/game/cards/11.2-TMoW/WymanManderly.js

Trigger Wyman on sacrificing opponent owned characters

---

server/game/cards/11.1-TSC/JanosSlynt.js
server/game/cards/11.1-TSC/NighttimeMarauders.js
server/game/cards/11.1-TSC/SerGerrisDrinkwater.js
server/game/cards/11.1-TSC/SerRobertStrong.js
server/game/cards/11.1-TSC/ShadowPriestess.js
server/game/cards/11.2-TMoW/BowelsOfCasterlyRock.js
server/game/cards/11.2-TMoW/OldtownUndercity.js
server/game/cards/11.3-SoKL/Catspaw.js
server/game/cards/11.6-DitD/CerseiLannister.js
server/game/cards/11.6-DitD/Moqorro.js
server/game/cards/11.6-DitD/Varys.js
server/game/gamesteps/abilityresolver.js
server/game/player.js
test/server/gamesteps/abilityresolver.spec.js
test/server/integration/ShadowKeyword.spec.js
test/server/player/putintoplay.spec.js

Consider dupes and events as coming out of shadows

---

server/game/game.js
server/game/player.js
test/server/gamesteps/menuprompt.spec.js
test/server/player/canattach.spec.js
test/server/player/costreduction.spec.js
test/server/player/find.spec.js
test/server/player/flipplotfaceup.spec.js
test/server/player/getduplicateinplay.spec.js
test/server/player/movecard.spec.js
test/server/player/playcard.spec.js
test/server/player/putintoplay.spec.js
test/server/player/removeattachment.spec.js
test/server/player/searchDrawDeck.spec.js
test/server/player/setupdone.spec.js

Ruling: http://www.cardgamedb.com/forums/index.php?/topic/39872-ruling-tycho-nestoris-decking-going-to-time/

Games end in a draw if remaining player can't win

---

server/game/cards/10-SoD/AtPrinceDoransBehest.js

Limit targets for Doran's Behest to plot deck

---

server/game/basecard.js
server/game/cards/01-Core/TheTickler.js
server/game/cards/08.2-JtO/TrisBotley.js

Per the RRG, a "copy of" a card is determined solely by the card's
title.

Apply Tris Botley's ability by card title

---

server/game/cards/12-KotI/AshaGreyjoy.js
server/game/cards/12-KotI/BalonGreyjoy.js
server/game/cards/12-KotI/OrkmontReaver.js
server/game/cards/12-KotI/PriestOfOldWyk.js
server/game/drawcard.js
server/game/effects.js

https://www.fantasyflightgames.com/en/news/2018/7/30/king-of-the-isles/

Implement characters from Kings of the Isles announcement article

---

server/game/cards/11.3-SoKL/Dragonbinder.js
server/game/cards/11.3-SoKL/DrowneGodFanatic.js
server/game/costs.js
server/game/costs/CostBuilders.js
server/game/costs/PlaceInDeadPileFromHandCost.js

Implement Greyjoy cards from Streets of King's Landing

---

server/game/AttachmentValidityCheck.js
server/game/basecard.js
server/game/cardaction.js
server/game/cards/01-Core/MarchingOrders.js
server/game/cards/09-HoT/EmissaryOfTheHightower.js
server/game/cards/11.2-TMoW/TradingWithQohor.js
server/game/cards/11.3-SoKL/ValyriansCrew.js
server/game/drawcard.js
server/game/effects.js
server/game/game.js
server/game/player.js
server/game/triggeredability.js
test/helpers/DeckBuilder.js
test/helpers/playerinteractionwrapper.js
test/server/card/basecard.spec.js
test/server/card/cardaction.spec.js
test/server/card/cardreaction.spec.js
test/server/cards/11.3-SoKL/ValyriansCrew.spec.js
test/server/player/putintoplay.spec.js

Probably a lot of individual interaction bugs, and need to update the UI to display the facedown cards like a mini-hand, but the basics of the card works.

Basic implementation of Valyrian's Crew

---

server/game/cards/11.3-SoKL/BlackwaterBay.js
server/game/cards/11.3-SoKL/GoldMine.js
server/game/cards/11.3-SoKL/LazyLeo.js
server/game/cards/11.3-SoKL/MinersPick.js
server/game/cards/11.3-SoKL/NaiveScout.js
server/game/cards/11.3-SoKL/UmberLoyalist.js
server/game/cards/11.3-SoKL/WhiteHarbor.js

http://www.cardgamedb.com/index.php/agameofthrones2ndedition/a-game-of-thrones-2nd-edition-cards/_/dance-of-shadows-cycle/streets-of-king-s-landing/

Add card implementations for first half of Streets of King's Landing

---

server/game/cards/11.3-SoKL/SerArchibaldYronwood.js
server/game/cards/11.3-SoKL/SummerSeaPort.js

Implement Martell cards from Streets of King's Landing

---

server/game/cards/11.3-SoKL/LazyLeo.js

Shuffle targeted cards into the deck for Lazy Leo

---

server/pendinggame.js

Set the arg type for lobby players so that pending game chat works properly

Fix pending game chat

---

server/game/cards/11.3-SoKL/Catspaw.js

Fix crash for minimum cost on Catspaw

---

server/game/CardVisibility.js

Event cards being played should be visible

---

server/game/cards/04.6-TC/SeaBitch.js

Limit Sea Bitch targets to cards that can be taken control of

---

server/game/chatcommands.js
server/game/costs.js
server/game/costs/CostBuilders.js
server/game/costs/DiscardDuplicateCost.js
server/game/costs/SacrificeCost.js
server/game/drawcard.js
server/game/game.js
server/game/player.js
server/game/triggeredability.js
server/settings.js
test/server/player/movecard.spec.js

Make use of the player setting for whether or not dupes are prompted instead of being automatic
Fixes #992
Fixes #1774

Manual dupes

---

server/game/cards/11.4-MoD/GreyGhost.js
server/game/cards/11.4-MoD/VictarionGreyjoy.js
test/server/cards/01-Core/HandOfTheKing.spec.js
test/server/cards/02.3-TKP/SerGregorClegane.spec.js
test/server/cards/04.2-CtA/FearCutsDeeperThanSwords.spec.js
test/server/integration/EndOfPhaseTimings.spec.js

Also update card data submodule

Add greyjoy cards from MoD

---

server/game/cards/11.4-MoD/SerMarkMullendore.js

remove character restriction

---

server/game/cards/11.4-MoD/Rhaegal.js

Fix Rhaegal (MoD) card code + trigger condition

---

server/game/cards/08.5-TFM/Mhysa.js

Fix strength calculation for Mhysa

---

server/game/CardVisibility.js
server/game/basecard.js
server/game/cardaction.js
server/game/game.js
server/game/player.js
server/game/spectator.js
server/gamenode/gameserver.js
test/server/CardVisibility.spec.js
test/server/card/basecard.spec.js
test/server/card/cardaction.spec.js
test/server/card/drawcard.getsummary.spec.js
test/server/cards/02.5-COW/Bronn.spec.js
test/server/game/chat.spec.js
test/server/game/getplayers.spec.js

Fixes a crash related to spectators when Bronn is in play, as well as adds back the anyPlayer flag in menu items, which apparently was needed after all despite not being used directly.

Fix Bronn crash and ability trigger

---

server/game/cards/10-SoD/GreatjonUmber.js

Only trigger Greatjon Umber while kneeling

---

server/game/cards/11.1-TSC/ExchangeOfInformation.js

Add card names to Exchange of Information message

---

server/game/cards/11.5-IDP/APinchOfPowder.js
server/game/cards/11.5-IDP/BearIslandScout.js

Implement A Pinch of Powder and Bear Island Scout from IDP

---

server/game/AttachmentValidityCheck.js

Add message when discarding invalid attachments

---

server/game/cards/03-WotN/TheLongWinter.js

Don't stop resolution of Long Winter in case of no power

---

server/game/player.js
test/server/integration/ShadowKeyword.spec.js
test/server/player/removeattachment.spec.js

Trigger out-of-shadow events for attachments

---

server/game/cards/11.6-DitD/SerJasonMallister.js

Ser Jason Mallister; 4 cost; unique; non-loyal; House Tully, Knight,
Lord; Military, Power;
While there are no cards in shadows, Ser Jason Mallister gains renown.
Reaction: after you win challenge, in which was Ser Jason Mallister
attacking, choose card in shadows controlled by losing opponent and
discard it from play.

Implement Stark card from Daggers in the Dark 

---

server/game/cards/11.6-DitD/CunningDiplomat.js

Cunning Diplomat(my translation, may be different); 3 cost; non-unique; non-loyal; Ally, Spy; Power;
Ambush (5), Shadows(3)
Reaction: After Cunning Diplomat enters play during the challenge, choose participating character. Stand that character and remove it from challenge.

Implement Cunning Diplomat - Tyrell card from Daggers in the Dark 

---

server/game/cards/03-WotN/RickonStark.js

Rickon Stark: allow to cancel self searches

---

server/game/cards/11.6-DitD/ArborMarket.js

Arbor Market(my translation, may be different); 2 cost; non-unique; loyal; House Redwyne; 
Challenges phase action: Kneel Arbor Market to choose participating character. That character gains +1 STR until the end of challenge.

Implement Arbor Market - Tyrell card from Daggers in the Dark 

---

server/game/basecard.js
server/game/cards/11.6-DitD/AssaultFromTheShadows.js
server/game/cards/11.6-DitD/BanishedFromTheLight.js
server/game/cards/12-KotI/SeaOfBlood.js
server/game/chatcommands.js
server/game/costreducer.js
server/game/drawcard.js
server/game/player.js
test/server/card/drawcard.moveto.spec.js

* Implements Sea of Blood, Assault from the Shadows, and Banished from the Light
* Fixes handling of when tokens are discarded
* Updates the /token to be more flexible plus add support for the new token types.

Implement upcoming cards that use tokens

---

server/game/cards/11.6-DitD/BloodOfTheViper.js
server/game/cards/11.6-DitD/StarfallSpy.js
server/game/costs.js
server/game/costs/CostBuilders.js
server/game/costs/PutIntoShadowsCost.js

https://thronesdb.com/find?q=e%3ADitD+f%3Amartell&sort=set&view=card

Implement Martell cards for Daggers in the Dark

---

server/game/cards/11.6-DitD/BrazenBeast.js
server/game/cards/11.6-DitD/GiftsForTheWidow.js

Implement Targaryen cards for Daggers in the Dark

---

server/game/cards/12-KotI/HeirToTheIronThrone.js

Fix Heir to the Iron Throne sacrifice prompt

---

server/game/cards/12-KotI/SecretsOfTheConclave.js

Fix top placement for Secrets of Conclave

---

server/game/cards/12-KotI/VindictiveRanger.js

Fix improper match in vindictive ranger

---

server/game/cards/12-KotI/ScoutingVessel.js
test/server/cards/12-KotI/ScoutingVessel.spec.js

Allow Scouting Vessel to be chained

---

server/game/cards/13.2-CoS/SmalljonUmber.js

First time contribution. Hope this is correct like this.
Please let me know if I missed something.

Implement Smalljon Umber #2377

---

server/game/cards/12-KotI/RedRain.js

Red Rain reaction limited to once per Phase.

Fix Red Rain - Once per phase #2375

---

server/game/cards/13.1-AtG/AlysaneMormont.js
test/server/cards/13.1-AtG/AlysaneMormont.spec.js

Implement Alysane Mormont #2376
