server/game/cards/13.1-AtG/TheKnightOfFlowers.js
=> Implement TheKnightOfFlowers (AtG)  #2376

server/game/cards/01-Core/SerJaimeLannister.js, test/server/cards/06.6-TBWB/Patchface.spec.js
=> Fix the way Core Jaime gains renown

server/game/cards/13.1-AtG/KingsGate.js
=> Implement King's Gate #2376

server/game/cards/13.1-AtG/Littlefinger.js
=> Implement Littlefinger (AtG)  #2376

server/game/cards/13.1-AtG/AtTheGates.js
=> Implement At the Gates #2376

server/game/cards/13.2-CoS/NoSurprises.js
=> Implement No Surprises #2377

server/game/cards/13.2-CoS/ShadowOfTheWall.js
=> Implement Shadow of the Wall #2377

server/game/cards/13.2-CoS/ShadowOftheEast.js
=> Implement ShadowOfTheEast #2377

server/game/cards/13.2-CoS/ShadowOftheSouth.js
=> Implement Shadow Of The South #2377

server/game/cards/06.3-TFoA/Duel.js
Previously, Duel allowed you to choose an already knelt character to
kneel, or even a character that couldn't be knelt. Now you must
explicitly choose a standing, kneelable character.
Additionally, the prompt has been changed to a select prompt to be more
in line with the rest of the UI.
Fixes #2412
=> Do not allow Duel to kneel knelt targets

server/game/cards/01-Core/ConsolidationOfPower.js
=> Fix pre-then kneel for Consolidation of Power

server/game/GameActions/AbilityAdapter.js, server/game/GameActions/GameAction.js, server/game/GameActions/SacrificeCard.js, server/game/GameActions/SimultaneousAction.js, server/game/GameActions/index.js, server/game/NullEvent.js, server/game/cards/06.3-TFoA/TheNorthRemembers.js, server/game/cards/08.3-Km/RamsaySnow.js, server/game/cards/10-SoD/BeyondReproach.js, server/game/cards/11.6-DitD/DaggersInTheDark.js, server/game/cards/12-KotI/ReturnToTheFields.js, server/game/game.js, server/game/player.js, test/server/GameActions/AbilityAdapter.spec.js, test/server/GameActions/GameAction.spec.js, test/server/GameActions/SacrificeCard.spec.js
=> Support simultaneous sacrifices

server/game/cards/03-WotN/AryasGift.js, test/server/cards/03-WotN/AryasGift.spec.js
=> Fix Arya's Gift to move opponent-only attachments

server/game/cards/13.1-AtG/CityOfSecrets.js
=> Implement City of Secrets

server/game/AbilityMessage.js, server/game/cards/13.1-AtG/SouthronEscort.js, test/server/AbilityMessage.spec.js
=> Implement Southron Escort

server/game/cards/13.1-AtG/RiverGate.js
=> Implement River Gate

server/game/EventTrackers/EventPlayedTracker.js, server/game/cards/13.1-AtG/WhiteSwordTower.js, test/server/cards/13.1-AtG/WhiteSwordTower.spec.js
=> Implement White Sword Tower

server/game/cards/13.1-AtG/BaelorBlacktyde.js
=> Implement Baelor Blacktyde

server/game/cards/13.1-AtG/SerMandonMoore.js
=> Implement Ser Mandon Moore

server/game/cards/13.1-AtG/RhllorInfiltrator.js
=> Implement R'hllor Infiltrator

server/game/cards/03-WotN/RickonStark.js, test/server/cards/03-WotN/RickonStark.spec.js
=> Prevent Rickon from cancelling keyword abilities

server/Array.js, server/game/AbilityTargetSelection.js, server/game/GameActions/DiscardCard.js, server/game/GameActions/index.js, server/game/Messages/index.js, server/game/baseability.js, server/game/cards/01-Core/TheThingsIDoForLove.js, server/game/cards/04.4-TIMC/ValarMorghulis.js, server/game/cards/09-HoT/FacelessMan.js, server/game/cards/11.6-DitD/RavagesOfWar.js, server/game/effect.js, server/game/gamesteps/ResolvedTargets.js, server/game/gamesteps/standingphase.js, test/server/Array.spec.js, test/server/GameActions/DiscardCard.spec.js
=> Implement Ravages of War

server/game/cards/13.2-CoS/KnightsOfHollowHill.js, server/game/effects.js
=> Implement Knights of Hollow Hill

server/game/AbilityMessage.js, server/game/GameActions/LookAtHand.js, server/game/GameActions/RemoveFromGame.js, server/game/GameActions/index.js, server/game/cards/13.2-CoS/ShadowPolitics.js, server/game/player.js, test/server/AbilityMessage.spec.js, test/server/GameActions/LookAtHand.spec.js
=> Implement Shadow Politics

server/game/cards/13.2-CoS/Nightflyer.js
=> Implement Nightflyer

server/game/cards/13.2-CoS/ShowOfStrength.js
=> Implement Show of Strength

server/game/cards/13.2-CoS/TheFowlerTwins.js
=> Implement The Fowler Twins

server/game/cards/13.2-CoS/BlackMarketMerchant.js
=> Implement Black Market Merchant

server/game/cards/13.2-CoS/RedKeepGaoler.js, server/game/costs.js, server/game/costs/MovePowerFromFactionCost.js
=> Implement Red Keep Gaoler

server/game/cards/13.2-CoS/TheBlackCells.js, server/game/drawcard.js, test/server/cards/13.2-CoS/TheBlackCells.spec.js
=> Implement The Black Cells

server/game/cards/13.2-CoS/TheRegentsGuard.js
=> Implement The Regent's Guard

server/game/cards/13.2-CoS/OwenTheOaf.js
=> Implement Owen the Oaf

server/game/cards/13.2-CoS/PyromancersCache.js
Provides the proper blanking effect but does not do the "gain text"
effect.
Progress toward #2377
=> Partially implement Pyromancer's Cache

server/game/cards/13.2-CoS/ArrogantContender.js
=> Implement Arrogant Contender

server/game/cards/13.2-CoS/AlannysGreyjoy.js
=> Implement Alannys Greyjoy (CoS)

server/game/AbilityChoiceSelection.js, server/game/AbilityChoosePlayerDefinition.js, server/game/AbilityMessage.js, server/game/AbilityTarget.js, server/game/baseability.js, server/game/cardaction.js, server/game/cards/01-Core/TheBearAndTheMaidenFair.js, server/game/cards/04.4-TIMC/CaswellsKeep.js, server/game/game.js, server/game/gamesteps/ChoosePlayerPrompt.js, server/game/gamesteps/abilityresolver.js, server/game/triggeredability.js, test/server/AbilityMessage.spec.js, test/server/AbilityTarget.spec.js, test/server/gamesteps/abilityresolver.spec.js
Add `choosePlayer` to abilities and refactors `chooseOpponent` to use the same mechanisms.
=> Implement "choose player"

package-lock.json, server/game/game.js, server/game/gamepipeline.js, server/game/gamesteps/InterruptWindow.js, server/game/gamesteps/abilityresolver.js, server/game/gamesteps/basestep.js, server/game/gamesteps/challenge/challengeflow.js, server/game/gamesteps/eventwindow.js, server/game/gamesteps/phase.js, server/game/gamesteps/uiprompt.js, test/helpers/playerinteractionwrapper.js, test/server/gamepipeline/handleMenuCommand.spec.js, test/server/gamesteps/uiprompt.spec.js
To make sure button clicks aren't processed if the current step does not permit it (ie, when theyve been clicked more than once)
=> Add promptid to every button

server/lobby.js
Fixes an issue where lobby messages can't be deleted until the browser is refreshed
=> Wait for lobby messages to be added to the db before sending notice to the client

server/game/chatcommands.js, server/game/game.js, server/game/gamesteps/RematchPrompt.js, server/gamenode/gameserver.js, server/gamerouter.js, server/lobby.js, server/pendinggame.js
=> Add a /rematch command

server/game/effects.js
=> Fix unapply of trigger restriction effect

server/game/costs/choosecost.js
Botched translating the old underscore calls.
Fixes THRONETEKI-2F9
=> Fix ChooseCost#canPay

server/game/cards/14-FotS/Outwit.js
=> Implement Outwit

server/game/cards/14-FotS/ThePrinceThatWasPromised.js
=> Implement The Prince That Was Promised

server/game/cards/14-FotS/ParleyAtStormsEnd.js
=> Implement Parley at Storm's End

server/game/cards/14-FotS/RobertBaratheon.js
=> Implement Robert Baratheon (FotS)

server/game/cards/14-FotS/StannisBaratheon.js
=> Implement Stannis Baratheon (FotS)

server/game/cards/14-FotS/RenlyBaratheon.js
=> Implement Renly Baratheon (FotS)

server/game/cards/14-FotS/SalladhorSaan.js
=> Implement Salladhor Saan (FotS)

server/game/cards/14-FotS/SelyseBaratheon.js
=> Implement Selyse Baratheon (FotS)

server/game/cards/14-FotS/NightfireVision.js, test/helpers/playerinteractionwrapper.js, test/server/cards/14-FotS/NightfireVision.spec.js
=> Implement Nightfire Vision

server/game/cardaction.js, server/game/cards/08.4-FotOG/TheKingInTheNorth.js, server/game/cards/14-FotS/Rationing.js, server/game/triggeredability.js
=> Implement Rationing

server/game/GameActions/AbilityAdapter.js, server/game/GameActions/ThenAbilityAction.js, server/game/ThenClauseAbility.js, server/game/baseability.js, server/game/cards/14-FotS/RedPriest.js, server/game/effects.js, test/server/GameActions/ThenAbilityAction.spec.js, test/server/cards/14-FotS/RedPriest.spec.js
=> Implement Red Priest

server/game/GameActions/AbilityAdapter.js, server/game/GameActions/ThenAbilityAction.js, server/game/ThenClauseAbility.js, server/game/baseability.js, server/game/cards/13.2-CoS/GhostOfHighHeart.js, test/server/GameActions/ThenAbilityAction.spec.js
Fixes #2514 
Will either need to rebase #2546 or this when merged.
=>  Don't reveal hand early for Ghost of High Heart

server/game/cards/14-FotS/GriffinsRoostKnight.js
=> Implement Griffin's Roost Knight

server/game/cards/14-FotS/ShyraErrol.js
=> Implement Shyra Errol

server/game/cards/14-FotS/BastardOfRobert.js
=> Implement Bastard of Robert

server/game/cards/14-FotS/WilySmuggler.js
=> Implement Wily Smuggler

server/game/cards/14-FotS/TheStormlands.js
=> Implement The Stormlands

server/game/cards/14-FotS/CapeWrath.js
=> Implement Cape Wrath

server/game/cards/14-FotS/LyseniGalley.js
=> Implement Lyseni Galley

server/game/cards/14-FotS/AzorAhaiReborn.js
=> Implement Azor Ahai Reborn

server/game/cards/14-FotS/HuntingAccident.js
=> Implement Hunting Accident

server/game/cards/14-FotS/Warhammer.js
=> Implement Warhammer

server/game/GameActions/ReturnGoldToTreasury.js, server/game/GameActions/index.js, server/game/cards/14-FotS/BotleyCrew.js, test/server/GameActions/ReturnGoldToTreasury.spec.js
=> Implement Botley Crew

server/game/cards/14-FotS/EveryCaptainIsAKing.js
=> Implement Every Captain is a King

server/game/cards/14-FotS/SerGregorClegane.js
=> Implement Ser Gregor Clegane (FotS)

server/game/cards/14-FotS/Lionstar.js
=> Implement Lionstar

server/game/cards/14-FotS/PrincesAttendant.js
=> Implement Prince's Attendant

server/game/ChallengeMatcher.js, server/game/cards/14-FotS/Kingsgrave.js
=> Implement Kingsgrave

server/game/cards/14-FotS/ProtectorsOfTheRealm.js
=> Implement Protectors of the Realm

server/game/cards/14-FotS/TheHornThatWakesTheSleepers.js
=> Implement The Horn That Wakes the Sleepers

server/game/cards/14-FotS/SheBear.js
=> Implement She-Bear

server/game/cards/14-FotS/BearskinCloak.js
=> Implement Bearskin Cloak

server/game/cards/14-FotS/Haggo.js
=> Implement Haggo

server/game/cards/14-FotS/DothrakiSteed.js
=> Implement Dothraki Steed

server/game/cards/14-FotS/HightowerKnight.js
=> Implement Hightower Knight

server/game/cards/14-FotS/FieldsOfTheReach.js
=> Implement Fields of the Reach

server/game/cards/14-FotS/LynCorbray.js
=> Implement Lyn Corbray

server/game/cards/14-FotS/UnlikelyChampion.js
=> Implement Unlikely Champion

server/game/cards/14-FotS/AnguyTheArcher.js
=> Implement Anguy the Archer

server/game/cards/14-FotS/TheHollowHill.js
=> Implement The Hollow Hill

server/game/cards/14-FotS/LadyForlorn.js
=> Implement Lady Forlorn

server/game/EventTrackers/ParticipationTracker.js, server/game/cards/14-FotS/Defiance.js
=> Implement Defiance

server/game/cards/14-FotS/SiegePreparations.js
=> Implement Siege Preparations

server/game/cards/14-FotS/DesperateAttack.js
=> Implement Desperate Attack

server/game/cards/14-FotS/TheHandsTourney.js
=> Implement The Hand's Tourney

server/game/cards/14-FotS/TheNewGods.js
=> Implement The New Gods

server/game/cards/14-FotS/Melisandre.js
=> Implement Melisandre (FotS)

server/game/cards/14-FotS/AlesterFlorent.js
=> Implement Alester Florent

server/game/GameActions/SimultaneousAction.js, server/game/ThenClauseAbility.js, server/game/cards/14-FotS/SerImryFlorent.js, test/server/cards/14-FotS/NightfireVision.spec.js
=> Implement Ser Imry Florent

server/game/cards/14-FotS/SerDavosSeaworth.js
=> Implement Ser Davos Seaworth (FotS)

server/game/GameActions/DiscardPower.js, server/game/GameActions/GainPower.js, server/game/GameActions/MovePower.js, server/game/basecard.js, server/game/cards/14-FotS/ACaskOfAle.js, server/game/drawcard.js, server/game/player.js, test/server/GameActions/DiscardPower.spec.js, test/server/GameActions/GainPower.spec.js, test/server/GameActions/MovePower.spec.js
=> Implement "A Cask of Ale"

server/game/cards/14-FotS/BastardOfRobert.js
=> Fix typo on Bastard of Robert

server/game/cards/01-Core/SerJaimeLannister.js, server/game/cards/01-Core/VanguardOfTheNorth.js, server/game/cards/04.2-CtA/BalonGreyjoy.js, server/game/cards/04.4-TIMC/TheWolfKing.js, server/game/cards/04.5-GoH/MyrcellaBaratheon.js, server/game/cards/05-LoCR/CerseiLannister.js, server/game/cards/06.2-GtR/BearIslandHost.js, server/game/cards/07-WotW/ThereAreNoMenLikeMe.js, server/game/cards/08.5-TFM/SerPounce.js, server/game/cards/14-FotS/AnguyTheArcher.js, server/game/cards/14-FotS/EveryCaptainIsAKing.js, server/game/drawcard.js, server/game/effects.js, server/game/gamesteps/challenge/ChooseParticipantsPrompt.js, server/game/gamesteps/challenge/challengeflow.js, test/server/cards/14-FotS/EveryCaptainIsAKing.spec.js
=> Fix "does not kneel" lasting effects

server/game/ThenClauseAbility.js, server/game/cards/13.2-CoS/GhostOfHighHeart.js
=> Don't accidentally reveal for Ghost of High Heart

server/game/cards/14-FotS/SerImryFlorent.js
=> Only kneel opponent-controlled cards for Ser Imry

server/game/cards/14-FotS/SerDavosSeaworth.js
=> Only allow in-play Kings for Ser Davos (FotS)

server/game/AllowedChallenges.js, server/game/EventTrackers/ChallengeTracker.js, server/game/EventTrackers/index.js, server/game/cards/01-Core/AGameOfThrones.js, server/game/cards/01-Core/DrogosArakh.js, server/game/cards/01-Core/OldBearMormont.js, server/game/cards/01-Core/TheRedKeep.js, server/game/cards/02.4-NMG/ForTheWatch.js, server/game/cards/05-LoCR/ALannisterAlwaysPaysHisDebts.js, server/game/cards/05-LoCR/BridgeOfSkulls.js, server/game/cards/05-LoCR/GossipAndLies.js, server/game/cards/07-WotW/MaesterAemon.js, server/game/cards/08.5-TFM/Mhysa.js, server/game/cards/10-SoD/ToTheSpears.js, server/game/cards/11.2-TMoW/ServeObeyProtect.js, server/game/cards/11.4-MoD/PrivilegedPosition.js, server/game/cards/13.1-AtG/RiverGate.js, server/game/cards/14-FotS/GriffinsRoostKnight.js, server/game/cards/14-FotS/TheNewGods.js, server/game/cards/titles/HandOfTheKing.js, server/game/challengetracker.js, server/game/gamesteps/challengephase.js, server/game/player.js, test/server/cards/08.5-TFM/Mhysa.spec.js, test/server/cards/11.4-MoD/PrivilegedPosition.spec.js
Moves challenge tracking off of Player and allows both per phase and per round.
Fixes #2239 
Fixes #2413 
Fixes #2616
=> Fix Mhysa and Privileged Position

server/game/EventTrackers/GenericTracker.js, server/game/PlayActions/MarshalIntoShadowsAction.js, server/game/cards/11.3-SoKL/KingsLanding.js, server/game/cards/13.3-PoS/MaesterGormon.js, server/game/costs.js, server/game/effects.js, server/game/gamesteps/abilityresolver.js, server/game/gamesteps/eventwindow.js, server/game/player.js, test/server/cards/11.3-SoKL/KingsLanding.spec.js
=> Implement Maester Gormon + KL ruling

server/game/cards/13.3-PoS/TheFaithsDecree.js, server/game/player.js
=> Implement The Faith's Decree

server/game/cards/13.3-PoS/Chiswyck.js, server/game/costs.js, server/game/costs/DiscardFromDeckCost.js
=> Implement Chiswyck

server/game/cards/13.3-PoS/ManningTheCityWalls.js
=> Implement Manning the City Walls

server/game/GameActions/LookAtHand.js, server/game/cards/13.3-PoS/MelleonsTome.js
=> Implement malleons tome

server/game/cards/13.3-PoS/ShadowOfTheThrone.js
=> Implement Shadow of the Throne

server/game/cards/13.3-PoS/EddardStark.js
Implementation of Eddard Stark (PoS)
Hey there another try to implement a card, tried myself at the Ghost of High Heart before, this one is an easier one. I'd appreciate feedback if this was the correct way to do things.
Greetings.
=> Implement Eddard Stark (PoS)

server/game/GameActions/RevealCard.js, server/game/GameActions/index.js, server/game/cards/13.3-PoS/JonConnington.js, test/server/GameActions/RevealCard.spec.js
=> Implement Jon Connington

server/game/CardMatcher.js, server/game/cards/13.3-PoS/UnexpectedGuile.js
=> implement unexpected guile

server/game/cards/13.3-PoS/ArianneMartell.js
=> Implement Arianne Martell (PoS)

server/game/cards/13.3-PoS/APitOfSnakes.js
=> Implement A Pit of Snakes

server/game/cards/13.3-PoS/OutfittedForWar.js
=> Implement Outfitted for War

server/game/cards/13.3-PoS/KingsLandingProselyte.js
=> Implement King's Landing Proselyte

server/game/cards/13.3-PoS/TheDragonpit.js
=> Implement The Dragonpit

server/game/cards/13.3-PoS/StatueOfBaelor.js
=> Implement Statue of Baelor

server/game/cards/13.3-PoS/SerEldonEstermont.js
=> Implement Ser Eldon Estermont

server/game/cards/13.3-PoS/HandsOfGold.js
=> Implement "Hands of Gold"

server/game/cards/13.4-BtRK/TowerOfTheHand.js
First contribution to the project. I implemented Tower Of The Hand by copying & pasting the relevant parts from Oldtown Undercity, Maidens Bane and Jory Cassel. I would appreciate any feedback!
=> implemented Tower Of The Hand (BtRK)

server/game/cards/13.4-BtRK/TunnelsOfTheRedKeep.js
=> implement tunnels of the red keep

server/game/cards/13.4-BtRK/TheMaidenvault.js
=> implement the maidenvault

server/game/cards/13.4-BtRK/ShadowOfTheIsles.js
as inspiration i used "shadow of the Throne" and "nothing burns like the cold"
=> implement shadow of the isles

server/game/cards/13.5-TB/WhiteCloak.js
=> implement White Cloak

server/game/cards/13.5-TB/TheMountainsSkull.js
=> implement The Mountain´s Skull

server/game/cards/13.5-TB/Yoren.js
=> Implement Yoren #2655

server/game/cards/13.4-BtRK/PublicExecution.js
do not merge yet, i don´t know the card code yet
=> implement public execution

server/game/cards/13.4-BtRK/WhiteHarborWatchman.js
do not merge yet, card code needs to be fixed
=> implement White Harbor Watchman

server/game/cards/13.4-BtRK/Blackbird.js
do not merge yet, card code needs to be fixed
=> implement Blackbird

server/game/cards/13.4-BtRK/ForestPatrol.js
=> implement forest patrol

server/game/cards/13.4-BtRK/DragonSkull.js
=> implement dragon skull

server/game/cards/13.4-BtRK/ShadowblackAssassin.js
=> implement shadowblack assassin

server/game/cards/04.1-AtSK/RubyOfRhllor.js, server/game/cards/13.4-BtRK/AlyceGraceford.js
do not merge yet, card code needs to be fixed
=> implement Alyce Graceford

server/game/cards/13.4-BtRK/GoroldGoodbrother.js
i´m not sure about the event triggering the reaction. Is onCardDiscarded enough to capture all instances of a card entering the discard pile?
=> implement gorold goodbrother

server/game/cards/13.5-TB/ShadowOfTheNorth.js
=> Implement Shadow Of the North #2655

server/game/cards/13.4-BtRK/CityOfSpiders.js
I copied the card body from Pulling The Strings.
In comparison to Pulling the Strings, i think that you are not allowed to choose a City plot card without a when revealed ability, so i added that part to the cardCondition helper function. Furthermore, i think the taking control part of Pulling the Strings is not necessary as the chosen card has to be one of your own.
Appreciate any feedback!
Also, the card code needs to be fixed.
=> implement city of spiders

server/game/cards/13.4-BtRK/KnightsOfTheMind.js
i would love feedback on the handler implementation as i am not sure if i did that correctly when there is no "choose" part in the card text
=> implement knights of the mind

server/game/cards/13.4-BtRK/AdvisorToTheCrown.js
copied the card body from the FactionCharacterCostReducer implementation
=> implement advisor to the crown

server/game/cards/13.4-BtRK/CastleGuard.js
=> Implement Castle Guard

package-lock.json, package.json, server/services/UserService.js
New default eslint rules caution against declaring Promise executor
functions as async.
=> Upgrade packages

server/game/cards/13.5-TB/AVeryLargeShadow.js, server/game/effects.js
=> implement a very large shadow

server/game/cards/13.5-TB/TyrionLannister.js, test/server/cards/13.5-TB/TyrionLannister.spec.js
=> Implement tyrion lannister tb

server/lobby.js
Doens't fix the issue but should make it crash a lot less
=> Add defensive coding around rematch

server/game/cards/13.2-CoS/Nightflyer.js
While playing i noticed that the chosen xValue for Nightflyer is not written in the game log so i decided to add it
=> add the chosen xValue of Nightflyer to the message

server/game/basecard.js, server/game/cards/13.5-TB/SmallfolkMob.js
=> Implement Smallfolk Mob

server/game/cards/13.5-TB/KingsLandingRiot.js
=> Implement King's Landing Riot

server/game/cards/13.5-TB/MusicOfDragons.js
=> Implement Music of Dragons

server/game/GameActions/MovePower.js, server/game/cards/13.5-TB/SerPrestonGreenfield.js
=> Implement Ser Preston Greenfield

server/game/cards/13.5-TB/MaesterKerwin.js
=> implement maester kerwin

server/game/cards/13.5-TB/Sparrows.js
=> implement Sparrows

server/game/cards/13.5-TB/HighgardenJester.js
=> Implement Highgarden Jester

server/game/cards/13.5-TB/BoundForTheWall.js
=> Implement Bound for the Wall

server/game/CardMatcher.js, server/game/cards/13.5-TB/TheWhiteBook.js, server/game/player.js, test/server/CardMatcher.spec.js, test/server/cards/13.5-TB/TheWhiteBook.spec.js
=> Implement The White Book

server/game/cards/13.5-TB/DagosManwoody.js
=> Implement Dagos Manwoody

server/game/CardMatcher.js, server/game/cards/13.5-TB/CovertLoyalist.js, server/game/costs/CostBuilder.js
=> Implement Covert Loyalist

server/game/cards/13.5-TB/TheBloodyCup.js
=> Implement The Bloody Cup

server/game/cards/13.5-TB/Yoren.js
=> [bugfix] Allow Yoren to target characters independent of ownership

.gitignore, package-lock.json, package.json, server/api/account.js, server/api/cards.js, server/api/decks.js, server/api/index.js, server/api/messages.js, server/api/news.js, server/api/user.js, server/config.js, server/gamerouter.js, server/index.js, server/lobby.js, server/models/User.js, server/server.js, server/services/ConfigService.js, server/services/PatreonService.js, server/services/ServiceFactory.js, server/services/UserService.js, server/socket.js
abstract configuration to use a service
Add integration for patreon to automatically set supporter status for linked accounts
=> Add patreon api support

server/game/cards/13.6-LMHR/MercenaryContract.js
progress towards #2641 
Fixes #2706
=> implement mercernary contract

server/game/cards/01-Core/TakeTheBlack.js, server/game/cards/04.6-TC/SeaBitch.js, server/game/cards/06.3-TFoA/RecruiterForTheWatch.js, server/game/cards/08.1-TAK/DaarioNaharis.js, server/game/cards/10-SoD/Turncloak.js, server/game/cards/11.3-SoKL/Dragonbinder.js
Following up on Yoren in #2727, I went through all control-changing effects and changed them. Admittedly, some of these are purely academic, but I do not see why the software should not accept these.
=> Adapt all control changing effects to also target cards you control

server/game/cards/13.6-LMHR/SerJorahMormont.js
=> implement ser jorah mormont

server/game/cards/13.6-LMHR/RobertBaratheon.js
=> implement robert baratheon

server/game/cards/13.6-LMHR/LongMayHeReign.js
=> implement long may he reign

server/game/cards/13.6-LMHR/Rimegate.js
=> implement rimegate

server/game/cards/13.6-LMHR/BloodOfTheFirstMen.js
=> implement blood of the first men

server/game/cards/13.6-LMHR/ExposeDuplicity.js
=> implement expose duplicity

server/game/cards/13.6-LMHR/AlchemistsGuildhall.js
progress towards #2641 
copied the body from begging brothers and added !event.source.isShadow() to the onCardAbilityInitiated statement. Unfortunately, i couldn´t write a test for it yet.
=> Implement alchemists guildhall

server/game/cards/13.6-LMHR/Huntress.js
=> implement huntress

server/game/cards/13.6-LMHR/TheQueensRetinue.js
=> implement the queens retinue

server/game/cards/13.6-LMHR/PoisonedDagger.js
progress towards #2641 
copied and adjusted the handler body from stone crows
=> Implement poisoned dagger

server/game/cards/13.6-LMHR/TheBastardOfDriftmark.js
=> implement the bastard of driftmark

server/game/cards/13.6-LMHR/FishmongersSquare.js
=> implement fishmongers square

server/game/cards/13.6-LMHR/RecruitFromTheDungeons.js
progress towards #2641 
not 100% sure on the afterChallenge method and how i bound it with this.game.once as i do not fully understand what is happening. would appreciate feedback on it!
=> implement recruit from the dungeons

server/game/cards/00-VDS/CommonCause.js, server/game/cards/10-SoD/SerCletusYronwood.js, server/game/cards/13.6-LMHR/CityOfWealth.js, server/game/effects.js, test/server/cards/04.2-CtA/KingsOfSummer.spec.js, test/server/cards/04.2-CtA/KingsOfWinter.spec.js
=> Implement City of Wealth

server/game/cards/13.6-LMHR/TheIronThrone.js
=> Implement The Iron Throne (LMHR)

README.md, config/default.json5, package-lock.json, package.json, server/config.js, server/services/ConfigService.js
Remove config.js and add default.json5 which contains the config defaults
=> Update lobby/gamenode to use the 'config' module.

server/game/game.js, server/game/gamesteps/setupphase.js, server/game/timeLimit.js, server/lobby.js, server/pendinggame.js
This is the first draft for a optional time limit for games.
A uses is able to configure if a new game should use a time limit and how many minutes this time limit should be.
The time limit starts when a configurable event is raised (currently, the only event listened to is when the setup phase is finished)
Each time state is transferred to the clients, the timeLimit object will check if the time limit is reached. In case the limit is reached, a log message is added and a event listener will be added to the endOfRound event to handle determining the winner in case the game is not finished by then (currently, the functionality to check who is closer to 15 power and all the tie breakers are not implemented, instead a log message is added to inform the players on how to determine the winner) …
=> Implement time limit for games

.gitignore, config/default.json5, server/game/game.js, server/game/gamesteps/taxationphase.js, server/game/timeLimit.js, server/gamenode/gameserver.js
Fix some issues left over from the config changes
=> Few small changes to the timer so it counts down and is more responsive

config/default.json5, server/api/account.js, server/api/banlist.js, server/api/index.js, server/api/user.js, server/lobby.js, server/models/User.js, server/services/BanlistService.js, server/services/ServiceFactory.js, server/services/UserService.js
fix several bugs that caused users not to be banned properly
Add ban list functionality
Add linked accounts and session info to user admin
=> backport admin enhancement from throneteki

server/game/cards/13.1-AtG/SouthronEscort.js, server/game/cards/13.2-CoS/RedKeepGaoler.js, server/game/cards/13.2-CoS/TheRegentsGuard.js, server/game/cards/13.3-PoS/KingsLandingProselyte.js, server/game/cards/13.4-BtRK/ForestPatrol.js, server/game/cards/13.5-TB/CovertLoyalist.js, server/game/cards/13.6-LMHR/TheQueensRetinue.js
=> Fix The Queens Retinue interacting with Barring the Gates

server/game/cards/14-FotS/AzorAhaiReborn.js, server/game/challenge.js, server/game/effects.js, server/game/gamesteps/challenge/challengeflow.js, test/server/cards/14-FotS/AzorAhaiReborn.spec.js
that stannis is still participating in a challenge even though the last rhllor character was removed
fixes #2731
=> fix the azor ahai reborn bug

server/game/cards/15-DotE/DaenerysTargaryen.js
=> implement daenerys targaryen

server/game/cards/15-DotE/Drogon.js
=> Implement drogon

server/game/cards/15-DotE/TheTitansBastard.js
=> implement the titans bastard

server/game/cards/15-DotE/CaptainGroleo.js
=> implement-captain-groleo

server/game/cards/15-DotE/KhalDrogo.js
=> Implement khal drogo

server/game/cards/15-DotE/Rakharo.js
=> implement rakharo

server/game/cards/15-DotE/Jhogo.js
=> implement jhogo

server/game/cards/15-DotE/Horselord.js
=> implement horselord

server/game/cards/15-DotE/DragonstoneConvert.js
=> implement dragonstone convert

server/game/cards/15-DotE/PitFightersBlade.js
=> implement pit fighters blade

server/game/cards/15-DotE/Khaleesi.js
=> implement khaleesi

server/game/cards/15-DotE/BarsenaBlackhair.js
=> implement barsena blackhair

server/game/cards/15-DotE/BrownBenPlumm.js
=> implement brown ben plumm

server/game/cards/15-DotE/AtThePalaceOfSorrows.js
=> Implement At The Palace of Sorrows

server/game/cards/15-DotE/LoanFromTheIronBank.js
=> Implement Loan from the Iron Bank

server/game/cards/15-DotE/ChampionsChallenge.js
=> Implement Champion's Challenge

server/game/cards/15-DotE/TheWhiteSwords.js
=> Implement The White Swords

server/game/cards/15-DotE/ArchmaesterMarwyn.js
=> Implement Archmaester Marwyn

server/game/CardMatcher.js, server/game/cards/15-DotE/FuryOfTheKhalasar.js
=> Implement Fury of the Khalasar

server/game/basecard.js, server/game/cards/03-WotN/Stonesnake.js
=> Allow Stonesnake to gain all types of keywords

server/game/cards/15-DotE/TheRedKeep.js
=> implement the red keep

server/game/cards/15-DotE/TenTowersGalley.js
=> implement ten towers galley

server/game/cards/15-DotE/SerMerynTrant.js
=> implement ser meryn trant

server/game/cards/15-DotE/SpottedSylva.js
=> implement spotted sylva

server/game/cards/15-DotE/BlueGraces.js
=> implement blue graces

server/game/cards/15-DotE/Rhaegal.js
=> implement rhaegal

server/game/cards/15-DotE/Viserion.js
=> implement viserion

server/game/cards/15-DotE/CageOfRavens.js
=> implement cage of ravens

server/game/cards/15-DotE/Clydas.js
=> implement clydas

server/game/cards/15-DotE/WyllaManderly.js
=> implement wylla manderly

server/game/cards/15-DotE/FightToTheLast.js
=> Implement fight to the last

server/game/Constants/Tokens.js, server/game/cards/15-DotE/TormundGiantsbane.js
needs the matching [client PR](https://github.com/throneteki/throneteki-client/pull/85) to fully work
=> implement tormund giantsbane and tale token

server/game/cards/15-DotE/ChampionsFavor.js
=> implement champions favor

server/game/cards/15-DotE/Braavos.js
=> implement braavos

server/game/cards/15-DotE/LysaArryn.js
=> implement lysa arryn

server/game/cards/15-DotE/ThePrinceWhoCameTooLate.js
=> Implement The Prince Who Came Too Late

server/game/cards/15-DotE/WaterDancersSword.js
=> implement water dancers sword

server/game/cards/15-DotE/DragonEgg.js
=> implement dragon egg without search effect

server/game/CardMatcher.js, server/game/GameActions/Search.js, server/game/GameActions/index.js, server/game/cards/15-DotE/GalazzaGalare.js
=> Implement Galazza Galare

server/game/GameActions/TakeControl.js, server/game/GameActions/index.js, server/game/cards/15-DotE/MathisRowan.js, server/game/game.js
not 100% sure if `chooseOpponent: () => true` and `target: {...}` work together like intended. Might be i have to rework the choosing of the character/attachment/location to be in the handler part. Feedback is welcome!
=> implement mathis rowan

server/game/GameActions/DrawCards.js, server/game/GameActions/PutIntoPlay.js, server/game/cards/15-DotE/Pentos.js, test/server/GameActions/DrawCards.spec.js
=> implement pentos

server/game/cards/15-DotE/ChoosingTheSpear.js, server/game/gamesteps/challenge/challengeflow.js
copied the parts from [Recruit from the Dungeons](https://github.com/throneteki/throneteki/blob/master/server/game/cards/13.6-LMHR/RecruitFromTheDungeons.js) and [The Queens Assassin](https://github.com/throneteki/throneteki/blob/master/server/game/cards/01-Core/TheQueensAssassin.js).
=> implement choosing the spear

server/game/cards/15-DotE/TheLostMessage.js, test/server/cards/02.5-TS/Jhogo.spec.js, test/server/cards/13.1-AtG/Viserion.spec.js, test/server/cards/15-DotE/TheLostMessage.spec.js, test/server/integration/effects.spec.js, test/server/integration/marshalphase.spec.js
=> Implement The Lost Message

server/game/cards/15-DotE/TheShavepate.js
=> implement the shavepate

server/game/cards/15-DotE/LayWaste.js, test/server/cards/15-DotE/LayWaste.spec.js
i am not 100% sure if the `then(...)` part works like i want it to. I have tried writing a test but i only get to the discarding part although i can observe it entering the `handler` function of the `then ` part.
Test is not included as it is based on a different throneteki-json-data revision than what master is currently on.
=> implement lay waste

server/game/GameActions/CheckReserve.js, server/game/GameActions/index.js, server/game/cards/15-DotE/HothoHumpback.js, server/game/gamesteps/taxation/DiscardToReservePrompt.js
not 100% sure about the reserve part, but i thought it might work that way
=> implement hotho humpback

server/game/cards/15-DotE/FireMadeFlesh.js
=> Implement Fire Made Flesh

server/game/CardMatcher.js, server/game/cards/15-DotE/DothrakiHandmaiden.js, server/game/effects.js, server/game/player.js
=> Implement Dothraki Handmaiden

server/game/cards/15-DotE/DelenaFlorent.js
=> Implement Delena Florent

server/game/cards/15-DotE/Incinerate.js
=> Implement Incinerate

server/game/basecard.js, server/game/cards/15-DotE/OverwhelmingNumbers.js, server/game/effectengine.js, server/game/effects.js, server/game/gamesteps/challenge/challengeflow.js, server/game/player.js
=> Implement Overwhelming Numbers

server/game/cards/15-DotE/WombOfTheWorld.js
=> implement womb of the world

server/game/cards/15-DotE/Bribery.js
=> implement bribery

server/game/cards/15-DotE/CageOfRavens.js, server/game/cards/15-DotE/CaptainGroleo.js, server/game/cards/15-DotE/ChampionsFavor.js, server/game/cards/15-DotE/KhalDrogo.js, server/game/cards/15-DotE/SpottedSylva.js, server/game/cards/15-DotE/TheWhiteSwords.js, server/game/cards/15-DotE/TormundGiantsbane.js
=> Improve messages and use game actions

server/api/account.js, server/game/game.js, server/game/player.js, server/gamenode/gameserver.js, server/lobby.js, test/server/game/playermanagement.spec.js
Don't consider a client disconnected until theyve been gone for 30 seconds
=> Reduce the amount of data flowing to the client

server/game/cards/15-DotE/OverwhelmingNumbers.js
=> Allow Overwhelming Numbers to choose from discard

server/game/CardMatcher.js, server/game/cards/15-DotE/WaterDancersSword.js, server/game/drawcard.js
=> fix water dancers sword´s attachmentRestriction

server/game/cards/15-DotE/Bribery.js
=> Allow Bribery to take control of kneeling char

server/game/cards/15-DotE/Horselord.js
=> Fix STR amount for Horselord effect

server/game/cards/01-Core/RisenFromTheSea.js, server/game/cards/02.5-COW/BloodMagicRitual.js
=> Apply blanking from BMR regardless of controller

server/game/cards/15-DotE/DragonstoneConvert.js
=> Fix cannot play condition for Dragonstone Convert

server/game/cards/15-DotE/TormundGiantsbane.js
=> fix duration of tormunds action

server/game/cards/15-DotE/TheRedKeep.js
=> Only allow Red Keep to cancel opponent abilities

server/game/cards/16-TTWDFL/CatelynStark.js
=> Implement Catelyn Stark (TTWDFL)

server/game/cards/16-TTWDFL/WintertimeMarauders.js
=> Implement Wintertime Marauders

server/game/CardMatcher.js, server/game/cards/16-TTWDFL/TheHatchlingsFeast.js
=> Implement The Hatchlings' Feast

server/game/cards/16-TTWDFL/Littlefinger.js
=> Implement Littlefinger (TTWDFL)

server/game/cards/16-TTWDFL/DarkWingsDarkWords.js
=> Implement Dark Wings, Dark Words

server/game/cards/16-TTWDFL/MadKingAerys.js
=> Implement Mad King Aerys

server/game/cards/16-TTWDFL/AloofAndApart.js
=> Implement Aloof and Apart

server/game/cards/16-TTWDFL/SerDavosSeaworth.js
=> Implement Ser Davos Seaworth (TTWDFL)

server/game/cards/16-TTWDFL/Conquer.js
=> Implement Conquer

server/game/GameActions/ChooseGameAction.js, server/game/GameActions/HandlerGameActionWrapper.js, server/game/GameActions/SimultaneousAction.js, server/game/GameActions/ThenAbilityAction.js, server/game/GameActions/index.js, server/game/ThenClauseAbility.js, server/game/baseability.js, server/game/cardaction.js, server/game/cards/15-DotE/HothoHumpback.js, server/game/cards/15-DotE/TheLostMessage.js, server/game/cards/15-DotE/ThePrinceWhoCameTooLate.js, server/game/cards/16-TTWDFL/DarkWingsDarkWords.js, server/game/forcedtriggeredability.js, server/game/gamesteps/BaseAbilityWindow.js, server/game/promptedtriggeredability.js, test/server/GameActions/ThenAbilityAction.spec.js, test/server/card/cardaction.spec.js, test/server/card/cardforcedreaction.spec.js, test/server/card/cardreaction.spec.js, test/server/gamesteps/BaseAbilityWindow.spec.js, test/server/gamesteps/ForcedTriggeredAbilityWindow.spec.js, test/server/gamesteps/TriggeredAbilityWindow.spec.js
Allows abilities to be defined using game actions instead of handlers. More work needed to integrate targeting.
=> Simple game action integration

server/game/Constants/Tokens.js, server/game/GameActions/CancelEffects.js, server/game/GameActions/index.js, server/game/baseability.js, server/game/cards/16-TTWDFL/Harrenhal.js
=> Implement Harrenhal (TTWDFL)

server/game/cards/16-TTWDFL/OlennasStudy.js
=> Implement Olenna's Study

server/game/cards/16-TTWDFL/TheQueenOfThorns.js
=> Implement Queen of Thorns (TTWDFL)

server/game/cards/16-TTWDFL/KnightsOfTheRealm.js
=> Implement Knights of the Realm

server/game/GameActions/Search.js, server/game/cards/16-TTWDFL/BenjensCache.js, server/game/plotcard.js
=> Implement Benjen's Cache

server/game/cards/16-TTWDFL/Rioting.js
=> Implement Rioting

server/game/cards/16-TTWDFL/WesterosBleeds.js
=> Implement Westeros Bleeds

server/game/GameActions/DiscardTopCards.js, server/game/GameActions/index.js, server/game/cards/16-TTWDFL/HeadsOnPikes.js
=> Implement Heads on Pikes

server/game/cards/16-TTWDFL/WheelsWithinWheels.js
=> Implement Wheels Within Wheels (TTWDFL)

server/game/cards/16-TTWDFL/MelisandresFavor.js
=> Implement Melisandre's Favor

server/game/cards/16-TTWDFL/SnowCastle.js
=> Implement Snow Castle

server/game/cards/16-TTWDFL/KingsLanding.js
=> Implement King's Landing (TTWDFL)

server/game/cards/16-TTWDFL/TheLongVoyage.js, server/game/gamesteps/drawphase.js
=> Implement The Long Voyage

server/game/GameActions/Search.js, server/game/cards/16-TTWDFL/YouMurderedHerChildren.js
=> Implement You Murdered Her Children (TTWDFL)

server/game/cards/16-TTWDFL/PrincesLoyalist.js
=> Implement Prince's Loyalist

server/game/cards/16-TTWDFL/SpidersWhisperer.js
=> Implement Spider's Whisperer

server/game/cards/16-TTWDFL/SeductivePromise.js
=> Implement Seductive Promise

server/game/cards/16-TTWDFL/OldBearMormont.js
=> Implement Old Bear Mormont (TTWDFL)

server/game/cards/16-TTWDFL/SearchAndDetain.js
=> Implement Search and Detain

server/game/cards/16-TTWDFL/TheArtOfSeduction.js, server/game/effects.js, server/game/gamesteps/plot/selectplotprompt.js, server/game/gamesteps/plotphase.js, server/game/player.js
=> Implement The Art of Seduction

server/game/cards/16-TTWDFL/HighGround.js
=> Implement High Ground

server/game/cards/16-TTWDFL/ValeRefugee.js
=> Implement Vale Refugee

server/game/CardTextDefinition.js, server/game/basecard.js, server/game/cards/13.2-CoS/PyromancersCache.js, server/game/cards/16-TTWDFL/SkyCell.js, server/game/effects.js
=> Implement Sky Cell

server/game/AbilityTarget.js, server/game/cards/16-TTWDFL/RuleByDecree.js
=> Implement Rule By Decree

server/game/cards/16-TTWDFL/NarrowEscape.js
=> Implement Narrow Escape

server/game/cards/16-TTWDFL/TheGatheringStorm.js
=> Implement The Gathering Storm

server/game/GameActions/LookAtDeck.js, server/game/cards/16-TTWDFL/SamwellTarly.js, test/server/GameActions/LookAtDeck.spec.js
=> Implement Samwell Tarly (TTWFDL)

package-lock.json, package.json
=> Update deck helper and data for TTWDFL and RL 3.0

server/game/cards/12-KotI/SeaOfBlood.js
=> Fix the message when triggering Sea of Blood

server/game/cards/16-TTWDFL/TheArtOfSeduction.js, server/game/effects.js, server/game/gamesteps/phase.js, test/server/cards/16-TTWDFL/TheArtOfSeduction.spec.js
=> Ensure Art of Seduction effect wears off

server/game/cards/14-FotS/SerImryFlorent.js
=> Use initiating player for Imry Florent

server/game/cards/16-TTWDFL/TheGatheringStorm.js
=> Move active plot to plot deck for Gathering Storm

server/game/player.js, test/server/integration/MeleeTitles.spec.js
=> Prevent Melee supporters from initiating challenges

server/game/cards/14-FotS/SerImryFlorent.js
=> Check for opponents with kneelable cards for Imry

server/game/GameActions/PutIntoPlay.js, server/game/cards/16-TTWDFL/CatelynStark.js
=> Ensure Catelyn (TTWDFL) enters knelt and returns to hand

server/game/game.js, server/game/gamesteps/GameWonPrompt.js, server/lobby.js, test/helpers/gameflowwrapper.js
Also ensures that the event and restricted list from the previous game is copied over to the rematch game.
=> Port end of game / rematch prompt from Keyteki

server/game/Conditions.js, server/game/cards/08.4-FotOG/FavorOfTheOldGods.js, server/game/cards/11.5-IDP/BearIslandScout.js, server/game/cards/13.1-AtG/AlysaneMormont.js, server/game/cards/13.1-AtG/OldGate.js, server/game/cards/13.3-PoS/EddardStark.js, test/helpers/playerinteractionwrapper.js, test/server/cards/13.1-AtG/OldGate.spec.js
Fixes bugs across several cards that would allow an ability to
be triggered when the player controlled no characters / cards.
Fixes #2978
=> Make "each card is Stark" abilities consistent

server/game/chatcommands.js, server/game/game.js, server/pendinggame.js
also have a look at the client side PR
=> port mute spectators feature from keyteki

server/game/cards/13.2-CoS/ACityBesieged.js
fix the call to hasUsedCityPlots so context.player is passed
=> fix a city besieged

server/game/cards/00-VDS/FeastOrFamine.js, server/game/cards/00-VDS/SummonedByTheConclave.js, server/game/cards/01-Core/CalmOverWesteros.js, server/game/cards/01-Core/PowerBehindTheThrone.js, server/game/cards/02.6-TS/CloseCall.js, server/game/cards/03-WotN/ATimeForWolves.js, server/game/cards/03-WotN/FallenFromFavor.js, server/game/cards/04.1-AtSK/VaryssRiddle.js, server/game/cards/04.5-GoH/GhostsOfHarrenhal.js, server/game/cards/04.6-TC/BattleOfTheBlackwater.js, server/game/cards/04.6-TC/TyrionsChain.js, server/game/cards/06.3-TFoA/Duel.js, server/game/cards/08.5-TFM/CompelledByTheFaith.js, server/game/cards/09-HoT/TradeRoutes.js, server/game/cards/10-SoD/BeyondReproach.js, server/game/cards/10-SoD/FalseSpring.js, server/game/cards/12-KotI/WeTakeWesteros.js, server/game/cards/14-FotS/ParleyAtStormsEnd.js, server/game/cards/16-TTWDFL/BenjensCache.js, server/game/plotcard.js, server/game/triggeredability.js, test/server/card/cardforcedreaction.spec.js, test/server/card/cardreaction.spec.js
* Should fix any lingering issues with Pulling the Strings
* Stops using fake take control for Varys's Riddle and Tyrion's Chain.
=> Remove `this.controller` from remaining plots

server/game/cards/01-Core/Dracarys.js
=> Only allow Dragon chars for Dracarys!

server/game/cards/12-KotI/DesertRaider.js
=> quick fix for desert raider + barring the gates interaction

server/api/events.js, server/lobby.js
Adds an option to events so that events can use the default restricted list instead of specifying their own
=> add option to use the default RL for an event

server/game/GameActions/EndPhase.js, server/game/cards/01-Core/PalaceSpearman.js, server/game/cards/03-WotN/RangersCache.js, server/game/cards/05-LoCR/LastHearthScouts.js, server/game/drawcard.js, server/game/gamesteps/phase.js, server/game/player.js, test/server/integration/EndOfPhaseTimings.spec.js, test/server/player/movecard.spec.js, test/server/player/removeattachment.spec.js
=> Fix interaction between Delena Florent and In Daznak's Pit

server/game/cards/15-DotE/FightToTheLast.js
=> fix fight to the last so it saves against burn

server/game/cards/13.5-TB/TyrionLannister.js
=> fix tyrion lannister card target

server/game/cards/08.5-TFM/Mhysa.js, test/server/cards/08.5-TFM/Mhysa.spec.js
fix the condition of Mhysa´s STR buff  to only apply during the first power challenge
currently, it applies to every challenge including and after the first power challenge
=> fix the condition of Mhysa´s STR buff 

server/game/GameActions/DiscardPlot.js, server/game/GameActions/LeavePlay.js, server/game/GameActions/PlaceCard.js, server/game/GameActions/RevealPlot.js, server/game/cards/05-LoCR/TheRainsOfCastamere.js, server/game/cards/10-SoD/AtPrinceDoransBehest.js, server/game/cards/16-TTWDFL/TheGatheringStorm.js, server/game/cards/16-TTWDFL/WheelsWithinWheels.js, server/game/gamesteps/plotphase.js, server/game/gamesteps/revealplots.js, server/game/player.js, test/server/GameActions/LeavePlay.spec.js, test/server/GameActions/PlaceCard.spec.js, test/server/cards/05-LoCR/TheRainsOfCastamere.spec.js, test/server/cards/08.3-Km/SandSteed.spec.js, test/server/player/flipplotfaceup.spec.js
=> Fix timing of discarding plot to used pile

server/game/cards/03-WotN/WinterfellHeartTree.js
=> Only allow play area for Winterfell Heart Tree

server/game/cards/15-DotE/HothoHumpback.js, test/server/cards/15-DotE/HothoHumpback.spec.js
so the draw happens first, then the checking for reserve
resolves #2878
=> fix Hotho Humpback 

server/game/cards/15-DotE/ArchmaesterMarwyn.js, test/server/cards/15-DotE/ArchmaesterMarwyn.spec.js
=> Count marshalling dupes and shadows for Marwyn

test/server/cards/15-DotE/ArchmaesterMarwyn.spec.js
currently archmaesterMarwyn.spec.js blocks the complete execution of npm test. Changing describe to fdescribe fixes this
=> change fdescribe to describe in ArchmaesterMarwyn.spec.js

server/game/cards/19-JS/Wraith.js
=> fix wraith so the target gets knelt

package-lock.json, package.json
TODO: Update throneteki-json-data reference when https://github.com/throneteki/throneteki-json-data/pull/102 is merged
=> Update for new RL Redesigns 2.2

server/services/GameService.js, server/stats.js
save the startedAt and finishedAt properties as a Date when saving to the database
cast the input parameters of getAllGames to a date so the comparison works
update stats.js so the local db is used as config.js got removed some time ago
add number of unique players to the stats result
=>  save the startedAt and finishedAt properties as a Date when saving to the database

package.json
TODO: release deckhelper 2.4.0
=> update deck-helper to 2.4.0 for new pack HMW

server/game/game.js, server/game/timeLimit.js
also take a look at the client PR here https://github.com/throneteki/throneteki-client/pull/139
=> implement pause functionality for general timelimit

server/game/cards/18-FH/HaldonHalfmaester.js
fix haldon halfmaester not revealing the topcard if there is no card in play with the same type
=> fix haldon halfmaester not revealing the topcard 

server/game/player.js
=> log the target of an attachment in the game log

server/stats.js
use configservice in stats.js
add number of unique players to the result of the stats script
=> improve stats.js

server/game/cards/20-HMW/WeGuardtheWay.js
we guard the way couldn´t be triggered before correctly
=> fix costs of we guard the way

server/game/cards/20-HMW/OurBladesAreSharp.js
drive-by pull request to fix #3158 
untested.
=> removes stipulation that sacrificed cards is a character.

server/game/GameActions/DiscardToken.js, server/game/GameActions/index.js, server/game/cards/20-HMW/KindlyMan.js
Introduces a new game action explicitly about discarding tokens from
cards. The existing place card action explicitly does not allow to
"place" negative tokens.
Fixes #3154
=> Fix Kindly Man discarding tokens

server/game/Message.js, server/game/gamesteps/setupphase.js, server/game/player.js
side effect of https://github.com/throneteki/throneteki/commit/97c2e4bb94ee6c4490e2dc131a4c6e0414913ec9
=> do not log the target and name of an attachment when the attachment is attached facedown

server/game/cards/12-KotI/GoldenStorm.js
noticed this when spectating a game with Goldenstorm in play
=> golden storm´s game messages used an invalid placeholder

server/game/GameActions/DiscardCard.js, server/game/GameActions/Kill.js, server/game/GameActions/LeavePlay.js, server/game/GameActions/MoveCardEventGenerator.js, server/game/GameActions/PlaceCard.js, server/game/GameActions/ReturnCardToDeck.js, server/game/GameActions/ReturnCardToHand.js, test/server/GameActions/DiscardCard.spec.js, test/server/GameActions/Kill.spec.js, test/server/cards/08.1-TAK/ValarDohaeris.spec.js
* Leave play event is now simultaneous to the discard card event
* Reactions to placing a card in discard are now simultaneous to reactions to discarding the card
Fixes #3166 
Fixes #3102
=> Make discard + leave play + placement simultaneous

server/game/cards/20-HMW/CornCornCorn.js
Also implement the Melee clause about which opponents can be selected,
and fix the message.
Fixes #3148
=> Fix cost of Corn, Corn, Corn

server/game/cards/19-JS/TheWinterMaid.js, server/game/game.js, test/server/cards/19-JS/TheWinterMaid.spec.js
fixing the way the plot phase works was too much of a hassle so i figured i "just" fix winter maid in regards to the interrupt window timing by creating a workaround.
fixes #3176
=> fix winter maid interrupt so it checks the previous plots traits

server/game/cards/11.1-TSC/FreshRecruits.js
=> fix fresh recruits so it searches the whole deck

server/game/triggeredability.js
=> fix triggeredAbility.meetsRequirement so that a facedown duplicate can be manually triggered

server/game/cards/17.1-R/WombOfTheWorld.js
only revealing dead dothrakis with womb of the world crashes the game as a .reduce call will be made on an empty array
=> fix womb of the world only revealing dead dothrakis

server/game/cards/18-FH/HaldonHalfmaester.js
Currently, Haldon Halfmaester says "and have {object object} gain 1 gold" or "and put {object object} into play". This simply fixes these messages.
=> Fix Haldons message from showing {object object}

server/game/player.js, test/server/integration/DeadCharacters.spec.js
=> Prevent attachments from entering play when dead

server/game/cards/15-DotE/FightToTheLast.js
fix fight to the last so that the set strength part happens before the save, otherwise terminal burn would kill the character again after the save
=> fix fight to the last

server/game/cards/22-BtB/BranTheBuilder.js, server/game/cards/22-BtB/BrienneTheBlue.js, server/game/cards/22-BtB/FlorianAndJonquil.js, server/game/cards/22-BtB/TrystaneMartell.js
=> Fixing a few BtB prompt titles

server/game/cards/22-BtB/TheGreatPyramid.js
=> fix the great pyramid so cards are removed from play instead of discarded when the pyramid leaves play

server/api/events.js, server/services/DeckService.js, server/services/EventService.js
=> Add locked deck feature for events

server/game/cards/01-Core/TakeTheBlack.js
=> Only allow in-play targets for Take the Black

server/game/cards/15-DotE/Incinerate.js
=> Move discard selection to effect for Incinerate

server/game/GameActions/DiscardToken.js, server/game/GameActions/DiscardTopCards.js, server/game/GameActions/DrawCards.js, server/game/GameActions/GainGold.js, server/game/GameActions/LookAtDeck.js, server/game/GameActions/MoveCardEventGenerator.js, server/game/GameActions/PutIntoPlay.js, server/game/GameActions/ReturnGoldToTreasury.js, server/game/cards/01-Core/ArianneMartell.js, server/game/cards/12-KotI/HeirToTheIronThrone.js, server/game/cards/12-KotI/Silence.js, server/game/cards/13.1-AtG/FleaBottomAlley.js, server/game/cards/20-HMW/AsHighAsHonor.js, server/game/cards/20-HMW/IPledgeMyLifeAndHonor.js, server/game/event.js, test/server/Event.spec.js
Fixes #2874 
Fixes #2435
Progress toward #2428
=> Fix "Then" interactions with put into play 

server/game/gamesteps/challenge/ChooseParticipantsPrompt.js, server/game/gamesteps/challenge/challengeflow.js, test/server/cards/22-BtB/StormsEnd.spec.js
Fixes: https://github.com/throneteki-playtesting/throneteki/issues/276 (Need to manually close)
=> Applying fix to Storms End (BtB) from AHaH changes

server/game/cards/02.3-TKP/SerHobberRedwyne.js
No issue yet, but noticed by a DT member; simple fix.
=> Fixing Ser Hobber Redwyne's GameAction

server/game/cards/11.1-TSC/ExchangeOfInformation.js
=> Fixing Varys's Riddle vs Exchange of Information

server/game/cards/20-HMW/OurWordIsGoodAsGold.js
=> Fixing top 10 cards for OWiGaG

server/game/cards/04.6-TC/RelentlessAssault.js
=> Fixing 'then' format for relentless assault

server/game/cards/04.4-TIMC/PyatPree.js
=> Fixing Pyat's search from numToSelect to topCards

server/game/cards/21-FtR/Goldengrove.js
=> Fixing Goldengrove to prevent kneel cost as target

server/game/cards/19-JS/SerBorosBlount.js
Not sure if this is the way to use CardMatcher, just proposing in case it can save some time in order to fix Boros.
=> Boros to be able to pick lanni kingsguard

server/Array.js, server/game/DynamicKeywordsEffect.js, server/game/basecard.js, server/game/cards/06.6-TBWB/Patchface.js, server/game/cards/20-HMW/Shagwell.js, server/game/effects.js, server/game/game.js, test/server/cards/20-HMW/Shagwell.spec.js, test/server/effects/DynamicKeywordSources.spec.js
=> Fix Shagwell / Patchface loop

server/game/game.js
also take a look at the client PR here https://github.com/throneteki/throneteki-client/pull/187
=> do not log game messages when a spectator joins/leaves/disconnects from a game to reduce spam in the game log

server/game/cards/08.6-SAT/ToGoForwardYouMustGoBack.js
Noticed that the draw from To Go Forward You Must Go Back was not being handled correctly with effects which react to card's being drawn, such as Oldtown Scholar; decided it was a good opportunity to fix that & update the card to a gameaction in the process.
=> Fixing TGFYMGB to be simultaneous Gameactions

server/game/cards/24-TSoW/DefendingTheWall.js
Straightforward fix here; simply missed it on initial implementation.
=> Fixing DtW resolveGameAction

server/game/ChessClock.js, server/game/game.js, server/lobby.js, server/pendinggame.js
also take a look at the client PR here: https://github.com/throneteki/throneteki-client/pull/189
fixes #3368
fixes #3038 (client PR)
fixes #2952
=> change the delay to start the chess clock so that it is a game option instead of fixed 5 seconds

server/game/cards/24-TSoW/TheBastardsBoys.js
Close #3387
Very simple fix here
=> fix The Bastard's Boys action, now restricted to characters

server/game/cards/24-TSoW/IronEmmett.js
=> fix Iron Emmet ability not working

server/game/cards/23-AHaH/WingedKnight.js
=> fix winged knight so it can trigger on non-saveable kill events

server/game/cards/24-TSoW/HarlawScout.js
=> fix harlaw scout so it only triggers on opponents reserve check

server/game/cards/22-BtB/Pyke.js
=> Fix pyke draw effect

server/game/cards/23-AHaH/TheSeedIsStrong.js
=> fix the seed is strong so it actually discards the chosen card

server/game/timeLimit.js
=> fix the timelimit so that the timelimit does not end when you pause the game after half the time has expired.

server/game/cards/15-DotE/Drogon.js
=> Fixing Drogon (DotE) from killing printed STR 1

server/game/cards/11.6-DitD/GiftsForTheWidow.js, server/game/cards/17.1-R/GiftsForTheWidow.js
=> Fixing messages on both Gifts for the Widow

server/game/cards/08.1-TAK/DaarioNaharis.js
Close #3419 
Additionally, updated Daario's format to GameActions.
=> Fixing Daario Naharis to target only characters

server/game/cards/15-DotE/OverwhelmingNumbers.js
=> Fixing Overwhelming Numbers

server/game/cards/12-KotI/Silence.js
=> Fixing Silence (Kotl)

server/game/AbilityTarget.js, server/game/GameActions/ReturnCardToDeck.js, server/game/GameActions/ShuffleIntoDeck.js, server/game/cards/04.1-AtSK/CaptainsDaughter.js, server/game/cards/06.1-AMAF/GhiscariElite.js, server/game/cards/07-WotW/RaidingTheBayOfIce.js, server/game/cards/08.1-TAK/MaesterAtTheRock.js, server/game/cards/08.1-TAK/ValarDohaeris.js, server/game/cards/08.2-JtO/ChangeOfPlans.js, server/game/cards/08.3-Km/ForgottenByHistory.js, server/game/cards/08.4-FotOG/CoastalReaver.js, server/game/cards/08.6-SAT/MaceTyrell.js, server/game/cards/11.1-TSC/SchemingSepton.js, server/game/cards/11.2-TMoW/OldtownUndercity.js, server/game/cards/11.4-MoD/SerMarkMullendore.js, server/game/cards/11.6-DitD/Moqorro.js, server/game/cards/12-KotI/SecretsOfTheConclave.js, server/game/cards/12-KotI/WhenIWoke.js, server/game/cards/13.5-TB/TheBloodyCup.js, server/game/cards/14-FotS/WilySmuggler.js, server/game/cards/15-DotE/WyllaManderly.js, server/game/cards/21-FtR/FairIsle.js, server/game/cards/22-BtB/Pyke.js, server/game/cards/22-BtB/TheMadKingsCommand.js, server/game/chatcommands.js, server/game/costs/ShuffleCardIntoDeckCost.js, server/game/effects.js, server/game/gamesteps/InterruptWindowOrder.js, server/game/player.js, test/server/cards/15-DotE/LayWaste.spec.js
Continuation of #3461 
Also makes card messages more consistent with their card text ("place on the bottom" / "place on top" instead of "move to"), and converts several things to use game actions directly.
=> Add more checks for leave play to shuffle into / return to deck

server/game/cards/15-DotE/Bribery.js, server/game/cards/17.1-R/Bribery.js
Was resolving an issue I saw somewhere, although cannot pinpoint where 😅.
=> Updating Bribery to use GameActions

eslint.config.js
Attempts to fix new flat-file eslint breaking on jasmine test files.
=> Adding jasmine to global language options

server/game/CardVisibility.js, server/game/PlayActions/AmbushCardAction.js, server/game/PlayActions/MarshalDuplicateAction.js, server/game/PlayActions/MarshalIntoShadowsAction.js, server/game/PlayActions/OutOfShadowsAction.js, server/game/ServerCommands/DropCommand.js, server/game/gamesteps/abilityresolver.js
Just fixing & standardising some messages as someone mentioned it looked wrong when ambushing with The Watch Needs Good Men.
=> Fixing ambush & marshal messages for all locations

server/game/cards/25.4-TTS/Varys.js
Just some silly goose putting `this.reaction` in the wrong method!! (The silly goose is me).
Closes #3507
=> Fixing reaction being set in wrong method

server/game/GameActions/MayGameAction.js
Noticed that Little Bird was crashing, and is entirely because I did not add some critical updates to the "choose player" logic of `MayGameAction`. Re-adding that in now (from playtesting repo).
=> Fixing Little Bird (TIC)

client/Components/Decks/DeckEditor.jsx, client/Components/Table/ReactTable.jsx
Branch name was originally for one issue, but will just bundle them all into this one request rather than making many
Fixes:
- No decks message preventing users from creating or importing decks
- Borders and positioning of button groups within editor (cleaned it up)
=> Some NextUI Deck Editor improvements

client/Components/GameBoard/CardPile.jsx, client/Components/GameBoard/PlayerPlots.jsx
Simple update here; adds the selected highlight to the plot pile when a user has selected their plot (as it were before, but implemented slightly differently)
=> Re-adding plotpile highlight when selected

client/Components/Decks/DraftDeckEditor.jsx, client/Components/Drafting/DraftingTable.jsx, client/Components/GameBoard/ActivePlayerPrompt.jsx, client/Components/GameBoard/GameBoard.jsx, client/Components/Lobby/LobbyChat.jsx, client/Components/Site/LoadingSpinner.jsx, client/Components/Table/ReactTable.jsx, client/Components/Table/TableGroupFilter.jsx, client/pages/EventsAdmin/EventEditor.jsx, client/pages/Lobby.jsx
Just adding more loading spinners where previously missed, and improving some small visuals
=> Fixing/Improving Loadspinners & UI messages

server/game/cards/26.3-MaV/SerGulianQorgyle.js, server/game/cards/26.3-MaV/TakingTheShieldIslands.js
- Ser Gulian Qorgyle not triggering
- Taking the Shield Islands crashing when played from hand (ie. to choose & place a single card)
=> Small patch fix for some MaV cards
